### ISSUE TITLE
Build fails: switch_apr.c:854:12: error: use of undeclared identifier 'APR_INET6'

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1003]
Starting with master 20201217 and later (1224 tested), make fails with message below. Version 20201216 built fine. Config and make attached.

Making all in xml/expat
make[4]: Nothing to be done for `all'.
make[3]: Nothing to be done for `local-all'.
  CC       src/libfreeswitch_la-switch_apr.lo
src/switch_apr.c:854:12: error: use of undeclared identifier 'APR_INET6'
                family = APR_INET6;
                         ^
1 error generated.
make[1]: *** [src/libfreeswitch_la-switch_apr.lo] Error 1

Env: macOS 10.15 Catalina and Big Sur 11.1, both clang v12
[06 FreeSWITCH configure.txt](https://github.com/signalwire/freeswitch/files/5720220/06.FreeSWITCH.configure.txt)
[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/5720221/07.FreeSWITCH.make.txt)

**Comment by clementbmn** [comment]
+1

**Comment by mjerris** [comment]
commit 56478e024884e50fa17d4b35aee77776cc483a84 (origin/osx-fixes)
Author: Mike Jerris <mike@signalwire.com>
Date:   Mon Nov 16 17:08:19 2020 -0700

    [core] fix build when undefined APR_INET6
