### ISSUE TITLE
«class menE» "Edit" of «class mbar» 1 of «class prcs» "Terminal" of application "System Events"”

### ISSUE THREAD

**Issue by yangchongduo** [signalwire/freeswitch#1004]
**Describe the bug**

**To Reproduce**
1. Using this example configuration...
2. Dial into conference using verto
3. Play my_problem_file.mp4 into conference
4. FreeSWITCH crashes

**Expected behavior**

**Package version or git hash**
 - Version [e.g. 1.10.4]

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
(gdb) set pagination off
(gdb) set logging file /tmp/backtrace.log
(gdb) set logging on
Copying output to /tmp/backtrace.log.
(gdb) bt
(gdb) bt full
(gdb) info threads
(gdb) thread apply all bt
(gdb) thread apply all bt full
(gdb) set logging off
Done logging to /tmp/backtrace.log.
(gdb) quit
```
![image](https://user-images.githubusercontent.com/19145102/102751174-2afe3d80-43a2-11eb-9221-bf45a207b19f.png)

**Comment by yangchongduo** [comment]
FreeSWITCH v1.10.5 Release  还有这个问题

**Comment by crienzo** [comment]
Please provide us a backtrace and the .mp4 file that crashes the conference.
