### ISSUE TITLE
Make in expat: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1006]
Make for expat has what looks like 4 potentially serious warnings from clang, and thought someone should be aware of them. I don't know if they are related to #1003 also for expat, which is why I noticed them and opened this issue.

-I/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib  -o xlate/xlate.lo -c xlate/xlate.c && touch xlate/xlate.lo

xlate/xlate.c:120:38: warning: passing 'const char \*\*' to parameter of type 'char \*\*' discards qualifiers in nested pointer types
      [-Wincompatible-pointer-types-discards-qualifiers]
    translated = iconv(convset->ich, (ICONV_INBUF_TYPE)&inbufptr,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/iconv.h:75:79: note: passing argument to parameter '__inbuf' here
extern __LIBICONV_DLL_EXPORTED size_t iconv (iconv_t __cd, char* * __restrict __inbuf, size_t * __restrict __inbytesleft, char* * __...
                                                                              ^
xlate/xlate.c:343:42: warning: passing 'const char \*\*' to parameter of type 'char \*\*' discards qualifiers in nested pointer types
      [-Wincompatible-pointer-types-discards-qualifiers]
        translated = iconv(convset->ich, (ICONV_INBUF_TYPE)&inbufptr,
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/iconv.h:75:79: note: passing argument to parameter '__inbuf' here
extern __LIBICONV_DLL_EXPORTED size_t iconv (iconv_t __cd, char* * __restrict __inbuf, size_t * __restrict __inbytesleft, char* * __...
                                                                              ^

**Comment by mjerris** [comment]
we dont actually use this code at all so I'm not concerned about this.  It only builds to not have to hack more our hacked apr
