### ISSUE TITLE
freeswitch assert failed in outgoing_answer_a 

### ISSUE THREAD

**Issue by chenchuanyin** [signalwire/freeswitch#1008]
**Describe the bug**
freeswitch assert failed in outgoing_answer_a when dns server send SERVFAIL content. 

**Expected behavior**
no assert fail and crash 

**Package version or git hash**
 - Version 1.4.26

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
(gdb) bt
#0  0x00007ff5660ba387 in raise () from /lib64/libc.so.6
#1  0x00007ff5660bba78 in abort () from /lib64/libc.so.6
#2  0x00007ff5660b31a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ff5660b3252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ff554d3e8e9 in outgoing_answer_a (orq=0x7ff526e5c8f0, q=<optimized out>, answers=<optimized out>)
    at nta.c:10829
#5  0x00007ff554d91105 in sres_query_report_error (q=q@entry=0x7ff527fb0690,
    answers=answers@entry=0x7ff524040520) at sres.c:2990
#6  0x00007ff554d9473d in sres_resolver_receive (res=0x7ff524002960, socket=<optimized out>) at sres.c:3533
#7  0x00007ff554d9ef3f in su_epoll_port_wait_events (self=0x7ff5240008c0, tout=<optimized out>)
    at su_epoll_port.c:510
#8  0x00007ff554d9e3b6 in su_base_port_run (self=0x7ff5240008c0) at su_base_port.c:349
#9  0x00007ff554da31b0 in su_pthread_port_clone_main (varg=0x7ff554bce660) at su_pthread_port.c:343
#10 0x00007ff566b2eea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ff56618296d in ?? () from /lib64/libc.so.6
#12 0x0000000000000000 in ?? ()
```

**Comment by andywolk** [comment]
You should upgrade you installation to a newer version of FreeSWITCH.

This version of FreeSWITCH is very old and unsupported. You should try reproducing this issue using the latest master.
Also this backtrace is from sofia-sip library which is not a part of FreeSWITCH anymore, see https://github.com/freeswitch/sofia-sip
On the other hand I have just given a try to reproduce this and my codeflow passes the assert successfully so I can not reproduce.
