### ISSUE TITLE
Slow motion audio in recording after Hold/UnHold	

### ISSUE THREAD

**Issue by melekoktay** [signalwire/freeswitch#1010]
Hi,

We have a interesting issue. After **Hold**/**UnHold** current call, we face **slow motion** audio in recording sound. 
When taking the call HOLD state, codec is changed with incoming Re-Invite packet.  And I think this is the foundation of the issue, but we could not disable to updating codec for Hold.

-->Tested FreeSwitch version **1.10.3**, Debian 8

**Comment by mjerris** [comment]
please at least confirm if this is an issue in latest release and latest master and re-open if its still an issue.  also debian 8 is no longer a supported platform and may be related to this issue, please try on debian 10
