### ISSUE TITLE
FreeSWITCH conference AGC doesn't work

### ISSUE THREAD

**Issue by figaro2015** [signalwire/freeswitch#1011]
I wrote this bug against the conference AGC handling, but I think it's applicable to all other audio media processing applications. If I play a constant 'loud' tone (in my it's 440hz tone) into the conference I am getting an initial reduction in volume based on the AGC level setting and then constant tone in the output. 
Instead, if I am running my test with conference default values (whatever those values are), meaning before issuing any AGC setting API, I see the initial reduction in volume (which looks correct to me), followed by constant 8-second cycles of another reduction in volume (approximately -8db) and then going back to the previous level. 
If I am running the same test after I assume conference AGC setting API - I do get constant output, which level is EXACTLY the same as the input tone. In fact, they are identical. This means no AGC processing takes place at all.
Just in case my explanation seems confusing, I have recorded .wav files and screenshots of Audacity plots.

My setup is the following:
1. I have Windows PC configured to use 'Stereo Mix' as audio input.
2. I am dialing into conference with the Linphone. Linphone is set up to have Stereo Mix as input and I am using Windows Media Player to play the constant tone into the conference. Important to note that 'Enable echo cancellation' on Linphone has to be unchecked. Otherwise, Linphone does it's own AGC processing.
3. I am recording the conference into an audio .wav file for further analysis.

The expected behavior would be an initial reduction in volume based on the AGC setting followed by the constant tone.

The version of the FreeSWITCH I have been testing this with is the top of the master branch:
FreeSWITCH Version 1.10.6-dev+git~20201223T174526Z~62970aa998~64bit (git 62970aa 2020-12-23 17:45:26Z 64bit)

I built FreeSWICH from sourse:
commit 62970aa9987683a802a413393b93b2f687499272 (HEAD -> master, origin/master, origin/HEAD)

I am going to attach recorded .wav files and screenshots of Audacity plots:
1. The initial settings of the conference are: 
energy_level = 50
AGC = 500

2 API has been used to set AGC level to 1100.

![50_550](https://user-images.githubusercontent.com/11821347/103142258-25ac3600-46b5-11eb-8b0d-b8822ad0f071.png)

![50_1100_api](https://user-images.githubusercontent.com/11821347/103142261-2e047100-46b5-11eb-9c0d-fbe0b6ede5ae.png)

Please let me know if there are any other artifacts I can provide. Github won't allow upload of .WAV files, therefore I had to convert them to .MP4

https://user-images.githubusercontent.com/11821347/103142589-6a869b80-46ba-11eb-86ca-2c927e328f4e.mp4

https://user-images.githubusercontent.com/11821347/103142591-71151300-46ba-11eb-8a23-9d14d9efe47f.mp4

**Comment by mjerris** [comment]
if you have a proposed fix, please submit a pull request.

**Comment by figaro2015** [comment]
Unfortunately, I don't have a fix for this issue.
