### ISSUE TITLE
segfault: sofia invite with replaces

### ISSUE THREAD

**Issue by wmasilva** [signalwire/freeswitch#102]
got a segfault in fs 1.8 from the bt i think is when the invite contains the header replaces (still truing to get a sip trace).

Attach a possible patch to solve this issue, because i think this is also in current master version. 
[sofia_try_to_fix_segfault_with_sip_replaces_params_v1.10.txt](https://github.com/signalwire/freeswitch/files/3803981/sofia_try_to_fix_segfault_with_sip_replaces_params_v1.10.txt)

the line number 11176, corresponds to the code:

if (rp_common && rp_common->h_class->hc_params) {
			int i, n;
			msg_param_t const *params = * (msg_param_t const **) ((char *)rp_common + rp_common->h_class->hc_params);
     		       **for (i = 0; params[i]; i++) {**

BT:

[New LWP 14183]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/freeswitch -ncwait -nonat -scripts /scripts/fs'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sofia_handle_sip_i_invite (session=0x0, nua=0x0, profile=0x338aa100, nh=0x1, sofia_private=0x0, sip=0xfe864b8, de=0x2a776620, tags=0x31474730) at sofia.c:11176
11176	sofia.c: No such file or directory.
(gdb) bt
#0  sofia_handle_sip_i_invite (session=0x0, nua=0x0, profile=0x338aa100, nh=0x1, sofia_private=0x0, sip=0xfe864b8, de=0x2a776620, tags=0x31474730) at sofia.c:11176
#1  0x00007f87d63707de in our_sofia_event_callback (event=nua_i_error, status=0, phrase=0x52616960 "", nua=0x1, profile=0x0, nh=0x0, sofia_private=0x1538b800, sip=0xfe864b8, de=0x2a776620, tags=0x31474730) at sofia.c:1797
#2  0x00007f87d6375626 in sofia_process_dispatch_event (dep=0x7f87bf3bede0) at sofia.c:2249
#3  0x00007f87d633e1c0 in sofia_receive_message (session=0x3d7c8028, msg=0x7f87bf3bfb50) at mod_sofia.c:1323
#4  0x00007f87e0611435 in switch_core_session_perform_receive_message (session=0x3d7c8028, message=0x7f87bf3bfb50, file=0x7f87bf3bfb48 " fw*", func=0x1 <error: Cannot access memory at address 0x1>, line=0) at src/switch_core_session.c:844
#5  0x00007f87e06c061c in switch_ivr_parse_signal_data (session=session@entry=0x3d7c8028, all=all@entry=SWITCH_TRUE, only_session_thread=only_session_thread@entry=SWITCH_FALSE) at src/switch_ivr.c:887
#6  0x00007f87e06c066c in switch_ivr_parse_all_signal_data (session=session@entry=0x3d7c8028) at src/switch_ivr.c:900
#7  0x00007f87e06c0687 in switch_ivr_parse_all_messages (session=0x3d7c8028) at src/switch_ivr.c:846
#8  0x00007f87e06188d4 in switch_core_session_run (session=0x3d7c8028) at src/switch_core_state_machine.c:587
#9  0x00007f87e061307e in switch_core_session_thread (thread=<optimized out>, obj=0x3d7c8028) at src/switch_core_session.c:1709
#10 0x00007f87e060ea6d in switch_core_session_thread_pool_worker (thread=0x1673a280, obj=0x0) at src/switch_core_session.c:1772
#11 0x00007f87e0911100 in dummy_worker (opaque=0x1673a280) at threadproc/unix/thread.c:151
#12 0x00007f87dfb2a064 in start_thread (arg=0x7f87bf3c0700) at pthread_create.c:309
#13 0x00007f87deecb62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

BT full:
[bt_full.txt](https://github.com/signalwire/freeswitch/files/3803992/bt_full.txt)

**Comment by crienzo** [comment]
fixed in commit 00113c480de5777984f2301ca9bdb0d619b1149b
