### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [signalwire/freeswitch#1021]
freeswitch-master/build/standalone_module/mod_skel.c line 175
Code:

	return SWITCH_STATUS_SUCCESS;

	do_config(SWITCH_TRUE); // <-- unreachable

	if (switch_event_create(&event, SWITCH_EVENT_TRAP) == SWITCH_STATUS_SUCCESS) {
		switch_size_t len = 0;
		int x = 0;

**Comment by dragos-oancea** [comment]
that's sample code for FreeSWITCH jira ticket FS-7653
"Sample build system for a stand alone(out of tree) FreeSWITCH module"
