### ISSUE TITLE
freeSWITCH 1.8.7 at centos7.4   Program terminated with signal 6,

### ISSUE THREAD

**Issue by yaoshenshen** [signalwire/freeswitch#1037]
**Describe the bug**
run command "freeswitch -nc" at centos7.4 ,after few min  The fressswitch process is missing and create   core.5587

gdb freeswitch core.5587 

[New LWP 7086]
[New LWP 6312]
[New LWP 7141]
[New LWP 7328]
[New LWP 7406]
[New LWP 7133]
[New LWP 5744]
[New LWP 7304]
[New LWP 7293]
[New LWP 6412]
[New LWP 7004]
[New LWP 7144]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `freeswitch -nc'.
Program terminated with signal 6, Aborted.
#0  0x00007f8ea0eb0387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-21.el7.x86_64 flac-libs-1.3.0-5.el7_1.x86_64 glibc-2.17-317.el7.x86_64 gsm-1.0.13-11.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 ldns-1.6.16-10.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libselinux-2.5-15.el7.x86_64 libsndfile-1.0.25-12.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtiff-4.0.3-35.el7.x86_64 libuuid-2.23.2-65.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 lua-5.1.4-15.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-3.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.44-5.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 opus-1.1-1.el7.centos.x86_64 pcre-8.32-17.el7.x86_64 speex-1.2-0.19.rc1.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) 

(gdb) bt
#0  0x00007f8ea0eb0387 in raise () from /lib64/libc.so.6
#1  0x00007f8ea0eb1a78 in abort () from /lib64/libc.so.6
#2  0x00007f8ea0ef2ed7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f8ea0f92607 in __fortify_fail () from /lib64/libc.so.6
#4  0x00007f8ea0f90782 in __chk_fail () from /lib64/libc.so.6
#5  0x00007f8ea0f92567 in __fdelt_warn () from /lib64/libc.so.6
#6  0x00007f8e8f3cf095 in ldns_sock_wait () from /lib64/libldns.so.1
#7  0x00007f8e8f3cf57f in ldns_udp_send () from /lib64/libldns.so.1
#8  0x00007f8e8f3cfd1a in ldns_send_buffer () from /lib64/libldns.so.1
#9  0x00007f8e8f3d0029 in ldns_send () from /lib64/libldns.so.1
#10 0x00007f8e8f3d4e9d in ldns_resolver_send_pkt () from /lib64/libldns.so.1
#11 0x00007f8e8f3d52c2 in ldns_resolver_send () from /lib64/libldns.so.1
#12 0x00007f8e8f3d5400 in ldns_resolver_query () from /lib64/libldns.so.1
#13 0x00007f8e8f5fc300 in ldns_lookup (number=number@entry=0x7f8d6c0035a0 "+1362800441519470058", root=root@entry=0x1432f00 "e164.org", server_name=server_name@entry=0x7f8b89b1aa10, 
    results=results@entry=0x7f8b89b1ab08) at mod_enum.c:511
#14 0x00007f8e8f5fc52a in enum_lookup (root=0x1432f00 "e164.org", in=<optimized out>, results=results@entry=0x7f8b89b1ab08, channel=channel@entry=0x7f8b788ace40, 
    session=session@entry=0x7f8b788aed68) at mod_enum.c:624
#15 0x00007f8e8f5fc6f7 in enum_dialplan_hunt (session=0x7f8b788aed68, arg=<optimized out>, caller_profile=0x7f8b87cf8220) at mod_enum.c:645
#16 0x00007f8ea363c937 in switch_core_standard_on_routing (session=0x7f8b788aed68) at src/switch_core_state_machine.c:281
#17 switch_core_session_run (session=0x7f8b788aed68) at src/switch_core_state_machine.c:643
#18 0x00007f8ea3634d6e in switch_core_session_thread (thread=<optimized out>, obj=0x7f8b788aed68) at src/switch_core_session.c:1709
#19 0x00007f8ea36307d3 in switch_core_session_thread_pool_worker (thread=0x7f8d5c0e9060, obj=<optimized out>) at src/switch_core_session.c:1772
#20 0x00007f8ea3902680 in dummy_worker (opaque=0x7f8d5c0e9060) at threadproc/unix/thread.c:151
#21 0x00007f8ea1924ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f8ea0f7896d in clone () from /lib64/libc.so.6
(gdb)

**Comment by mjerris** [comment]
freeswitch 1.8 isnt supported and hundreds of crashes are fixed, suggest upgrade

**Comment by mjerris** [comment]
also known issues with older ldns on older os, please use install instructions for a modern platform

**Comment by yaoshenshen** [comment]
> suggest upgrade


> freeswitch 1.8 isnt supported and hundreds of crashes are fixed, suggest upgrade

which version freeswitch and centos version I need

**Comment by mjerris** [comment]
we recommend latest freeswitch release on debian 10

**Comment by yaoshenshen** [comment]
> we recommend latest freeswitch release on debian 10

Thanks，I will try it
