### ISSUE TITLE
fs load mod_unimrcp error:  mod_unimrcp.so: undefined symbol: soatag_user_sdp_str**

### ISSUE THREAD

**Issue by wangduanduan** [signalwire/freeswitch#1039]
**Expected behavior**
can load unimrcp without error

**Package version or git hash**
 - Version 1.10.5

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

```
freeswitch@dd> load mod_unimrcp 
+OK Reloading XML
-ERR [module load file routine returned an error]
2021-01-22 20:38:13.891132 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/local/freeswitch/mod/mod_unimrcp.so
**/usr/local/freeswitch/mod/mod_unimrcp.so: undefined symbol: soatag_user_sdp_str**
```

**Comment by andywolk** [comment]
Try updating libsofia
`apt-get install libsofia-sip-ua0`

**Comment by wangduanduan** [comment]
thanks, but it not work

**Comment by wangduanduan** [comment]
sofia commands work ok.

freeswitch@dd> sofia profile internal rescan
Reload XML [Success]
+OK scan complete

**Comment by dragos-oancea** [comment]
do a "make clean" in the FS source tree and then rebuild FS.

**Comment by wangduanduan** [comment]
when build sofia-sip, use `/configure`, don't use `./configure.gun`
