### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by vogt31337** [signalwire/freeswitch#1040]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. 
I'm always frustrated when the list of dependencies isn't maintained. At the moment I'm trying to install freeswitch under buster on a raspberry pi. The repo's provided don't provide any packages, they just seem to be empty.

So I tried a source compilation. Your configure script needs some serious work. There's a handful of libs needed but not checked for. Maybe you should test it with a clean environment on a virtual machine or maybe set up some jenkins / travis build servers to check for these kind of things.
I haven't tracked all libs, but:
- I needed to install FFMPEG dev, I think for some video conferencing stuff.
- I needed to track down your version of spandsp, since your confluence link points to the original version (=0.0.6) and freeswitch needs >3.0.0 which is in your github repo and not provided with debian buster
- I needed to find libks and signalwire-c which aren't listed anywhere in your dep doc on confluence.
- I am forced to install sqlite3 even if I don't want to use it (will use postgresql)

**Describe the solution you'd like**
Well the examples says it already, I'd like to have a better compile / installation guide. Also I'd appreciate if you could explain in detail possible configure parameter. For example I'm not going to do anything related to video, so how do I disable the resp. module?

**Describe alternatives you've considered**
Retrying a lot, which takes enormous amounts of time...

**Additional context**
Tried to install FusionPBX and had to learn, that the fusionpbx installer didn't install freeswitch...

**Package version or git hash**
- FreeSWITCH branch v1.10
- Newest Version of debian buster on rpi 2

**Comment by andywolk** [comment]
If you go to the main page of the freeswitch repo https://github.com/signalwire/freeswitch
you can find that that page describes (via README.md) a lot of usefull information.
There are installation instructions like that https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster (this link does have a notice about Sofia-sip and SpanDSP)
and more.
