### ISSUE TITLE
use lua mysql instead of callcenter.conf.xml

### ISSUE THREAD

**Issue by ChuanjiaCai** [signalwire/freeswitch#1047]
hi guys,
     i hava a question about module callcenter queue, can i use lua and mysql instead of callcenter.conf.xml.  which one give some advice for me , thank you.

freeswitch.consoleLog("NOTICE","lua take the queues...\n");
local req_name   = params:getHeader("name")
local req_strategy   =params:getHeader("strategy")
freeswitch.consoleLog("NOTICE","start connect DB...\r\n");
local dbh = freeswitch.Dbh("freeswitch","root","root01");
assert(dbh:connected());
dbh:query("select strategy from queue where name="..req_name,function(row)
        freeswitch.consoleLog("NOTICE","DB select strategy="..string.format("%s\n",row.strategy))
        req_strategy=string.format("%s",row.strategy)
end);

dbh:release();
--freeswitch.consoleLog("NOTICE","info:"..req_name.."--"..req_strategy.."\n"); 
 freeswitch.consoleLog("NOTICE","info:"..req_name.."--"..req_strategy.."\n");
if req_name ~= nil then
    XML_STRING =
    [[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <document type="freeswitch/xml">
      <section name="autoload_configs">
<configuration name="callcenter.conf" description="CallCenter">
 <settings>
    
        <param name="odbc-dsn" value="freeswitch:root:root01"/>
    
    
  </settings>

<queues>
     <queue name="]]..req_name..[[">
      <param name="strategy" value="]]..req_strategy..[["/>
      <param name="moh-sound" value="$${hold_music}"/>
      
      <param name="time-base-score" value="system"/>
      <param name="max-wait-time" value="0"/>
      <param name="max-wait-time-with-no-agent" value="0"/>
      <param name="max-wait-time-with-no-agent-time-reached" value="5"/>
      <param name="tier-rules-apply" value="false"/>
      <param name="tier-rule-wait-second" value="300"/>
      <param name="tier-rule-wait-multiply-level" value="true"/>
      <param name="tier-rule-no-agent-no-wait" value="false"/>
      <param name="discard-abandoned-after" value="60"/>
      <param name="abandoned-resume-allowed" value="false"/>
    </queue>
</queues>

   <agents>
   
  </agents>

  <tiers>
    
    
  </tiers>
</configuration>
      </section>
    </document>]]
else
    XML_STRING =
    [[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <document type="freeswitch/xml">
      <section name="autoload_configs">
      </section>
    </document>]]
end
 
freeswitch.consoleLog("NOTICE", "debug from call_center.lua, generated XML:\n" .. XML_STRING .. "\n");

**Comment by andywolk** [comment]
You need to enable mod_mariadb and use a proper connection string.
https://freeswitch.org/jira/browse/FS-11727

```
local dbh = freeswitch.Dbh("freeswitch","root","root01");
```
does not look right. See out Docs:
https://freeswitch.org/confluence/display/FREESWITCH/Lua+FreeSWITCH+Dbh
especially the ODBC example:
```
local dbh = freeswitch.Dbh("odbc://datasourcename:username:password")
```
see `odbc://` prefix.

Take a look at the example of mysql prefix: https://github.com/signalwire/freeswitch/blob/master/conf/vanilla/autoload_configs/switch.conf.xml#L185
