### ISSUE TITLE
Recording immediately not starting  with originate command

### ISSUE THREAD

**Issue by surya4** [signalwire/freeswitch#1052]
**Describe the bug**
Case 1 - the call goes to the external number and then after the answer comes to the internal user. 

**Problem**: the initial audio in recording (ringing/waiting until answered by external number) is silent and needs to manually fill up with ringback - `'set:ringback=$${us-ring}'`

**To Reproduce**
Originate command - 
```
originate{
  ignore_early_media=false,
  hangup_after_bridge=true,
  leg_timeout=60
}[]sofia/gateway/mor/+971xxxxxxxx|
[]sofia/gateway/default-external-gateway/971xxxxxxxx
'
set:ringback=$${us-ring},
set:full_record_filename=$${base_dir}/recordings/${uuid}-full.mp3,
set:RECORD_STEREO=true,
set:RECORD_STEREO_SWAP=true,
record_session:$${base_dir}/recordings/${uuid}-full.mp3,
set:RECORD_STEREO_SWAP=false,
set:RECORD_STEREO=false,
wait_for_answer,
set:RECORD_BRIDGE_REQ=true,
set:cc_record_filename=$${base_dir}/recordings/${uuid}-main.mp3,
record_session:${cc_record_filename},
set:RECORD_BRIDGE_REQ=false,
set:hangup_after_bridge=true,
set:leg_timeout=15,
socket:$${ESL_HOST}:$${ESL_PORT} full
'
inline
```

Case 2 - the call goes to the internal user and then after it's answered by the internal user it goes to the external number. (Flow: Call Starts -> Rings Agent -> Agent Answered -> Call rings to external number -> External number answers -> Bridge happens -> They talk -> call is cut)

**Problem**: the call recording only starts after the call is answered by the internal user. It does not capture the initial ring audio to the internal user/audio from the moment the call is started.
I tried 
1. `return_ring_ready`/ but got an error - **Cannot execute app 'record_session' media required on an outbound channel that does not have media established**
2. Also tried -  'export=execute_on_originate::pre_answer,' 
/ export=execute_on_preoriginate full_record_filename::${RECORDING_PATH}`
/ export=execute_on_originate full_record_filename::${RECORDING_PATH}`
/ export=execute_on_pre_answer full_record_filename::${RECORDING_PATH}`
/ export=execute_on_answer full_record_filename::${RECORDING_PATH}`
/export=execute_on_ring full_record_filename::${RECORDING_PATH}`
but - no error , no recording

**To Reproduce**
Originate command - 
```
originate{
  ignore_early_media=false,
  hangup_after_bridge=true,
  effective_caller_id_name=+97155xxxxxx,
  origination_channel_name=verto.rtc/agent-0001@127.0.0.1
}user/agent-0001+97155xxxxxx XML default +97155xxxxxx +97155xxxxxx```
```

**Expected behavior**
 - I want the recording to start in both the cases from the very beginning of the call to the end of the call while capturing every step of the flow of call - (Call Starts -> Rings Agent -> Agent Answered -> Call rings to external number -> External number answers -> Bridge happens -> They talk -> call is cut)

**Package version or git hash**
 - Version [e.g. 1.10.5]

Sometimes while trying I got an error - `Can not record session. Media not enabled on channel.` Is it expected behavior that call recording can not be answered until it is answered by the source caller?

**Comment by crienzo** [comment]
Try `execute_on_media` variable in your originate dialstring.  Media must be established before attempting to record.

**Comment by surya4** [comment]
`execute_on_media` @crienzo didn't work with me I tried `execute_on_ring` but the same result.

Tried the execute_on_media -
`originate{
  presence_id=agent-0001@127.0.0.1,
  ignore_early_media=false,
  hangup_after_bridge=true,
  effective_caller_id_name=+971xxxxxx,
  origination_channel_name=verto.rtc/agent-0001@127.0.0.1,
  execute_on_media=record_session:: url.mp3,
}user/agent-0001 +971xxxxxx XML default +971xxxxxx +971xxxxxx`

When I added return_ring_ready=true within execute_on_media i get error **Can not record session.  Media not enabled on channel**
`originate{
return_ring_ready=true,
  presence_id=agent-0001@127.0.0.1,
  ignore_early_media=false,
  hangup_after_bridge=true,
  effective_caller_id_name=+971xxxxxx,
  origination_channel_name=verto.rtc/agent-0001@127.0.0.1,
  execute_on_media=record_session:: url.mp3,
}user/agent-0001 +971xxxxxx XML default +971xxxxxx +971xxxxxx`

Just would like to re-highlight that I am trying to get the audio before the source call answer it.

**Comment by crienzo** [comment]
You can't force the outbound side to establish media.  Best you can do is wait until media is established then record.
