### ISSUE TITLE
[mod_http_cache] Authorization header support in HTTP GET

### ISSUE THREAD

**Issue by tmnsur** [signalwire/freeswitch#1055]
Problem:
I want to use mod_http_cache to consume an internal REST API which requires a custom HTTP header (API_KEY) for authorization.

Solution:
I would like to add a new functionality that will allow defining a new HTTP header name and value pair in http_cache.conf.xml, and it would append this new header into each HTTP GET request.

Pull Request:
I already developed a patch and I am actively using it on my local setup. Here is the pull request link:

https://github.com/signalwire/freeswitch/pull/1048

Version:
HEAD

**Comment by crienzo** [comment]
Fixed in #1048
