### ISSUE TITLE
Can we add loop to Playback?

### ISSUE THREAD

**Issue by yasingok** [signalwire/freeswitch#1058]
HI GUYS;
I wanna use "(action application="loop_playback" data="+2 path.wav")". But there is no play terminator. is it possible to add?
Instead of this, I tried to use "(action application="playback" data="sounds/soundfile.wav")" there is playTerminator. But there is no "loop". Is it possible to add loop?

**Comment by mjerris** [comment]
you can add {loops=2} on the front of the data for playback
