### ISSUE TITLE
Remove use of effective_xxx variables from example config

### ISSUE THREAD

**Issue by MartinJPaterson** [signalwire/freeswitch#1059]
**Describe the bug**
The variables "effective_xxx" should not be used. Use origination_ vars instead. Therefore they should be replaced in the default config with the origination_ variables, because everyone's config will start out from the default and be modified.

**Justification**
Comments in the FreeSWITCH slack channel when someone asked about these variables:
Michael Jerris: 

> You should NEVER use effective in any case, if it is documented at all is should have no details other than you should never be using this. It is only there from legacy use. Setting in caller profile or via origination_ vars is really what should be done. The origination_ values are used to set in caller profile on the originate.

>  origination should be used as part of the dial string vars. Effective should NEVER be used, it’s entire design is problematic.

> If you export effective then transfer calls you’ll see how messed up things get… you’ll have a mess of wrong caller profiles.

Christopher Rienzo:
> origination_xx is used anywhere you have a dialstring- originate or bridge, etc. It is a reliable and predictable replacement for effective_xx. Effective_xx vars mostly work, but are more complex and could have edge cases where the behaviour is not what you expect. Origination_xx is the safe bet and all I use in FreeSWITCH. The main difference is effective_ is applied to the a-leg of a two legged call which then gets magically applied to the b-leg(s) when you dial. The origination_ variants only apply to the b-leg an must be in dialstring. No magic.

**Comment by mjerris** [comment]
we would be happy to review a pull request for this
