### ISSUE TITLE
Freeswitch not start

### ISSUE THREAD

**Issue by BaTa8059** [signalwire/freeswitch#1060]
**Dear Friends** 

I'm newbie in freeswitch, I have a freeswitch on cents 7 and on a vm and works fine, I made a copy of my freeswitch with rsync on another vm server, I copied all files on new server except these directories "/boot/, /lib/modules/, /etc/modules/, /etc/lilo.conf, /etc/fstab, /etc/hostname, /etc/hosts, /etc/mtab, /etc/shadow, /etc/shadow-, /etc/ssh/, /proc/, /dev/lost+found/, /etc/sysconfig/network-script/, /root/, /sys/, /run/, temp/, tmp/, log/"

now all services are runing except freeswitch, 
can anyone help me how resolve this issue...?

**journalctl -u freeswitch.service**
-- Logs begin at Tue 2021-02-02 10:33:08 UTC, end at Tue 2021-02-02 10:36:02 UTC. --
srv.wold.voip systemd[1]: Starting FreeSWITCH...
srv.wold.voip freeswitch[2306]: 2308 Backgrounding.
srv.wold.voip freeswitch[2306]: FreeSWITCH[2306] Error starting system! pid:2308
srv.wold.voip systemd[1]: freeswitch.service: control process exited, code=exited status=1
srv.wold.voip systemd[1]: Failed to start FreeSWITCH.
srv.wold.voip systemd[1]: Unit freeswitch.service entered failed state.
srv.wold.voip systemd[1]: freeswitch.service failed.

**Thanks,**

**Comment by crienzo** [comment]
Hello.  Please ask this question in our mailing list or our community slack channel.  Github issue tracker is intended for bug reports.
