### ISSUE TITLE
Is there a way to use http_remove_cache command with multiple file

### ISSUE THREAD

**Issue by ykalay** [signalwire/freeswitch#1061]
Hi everyone,
I want to delete multiple http caches from freeswitch in one command instead of one command for each file. Is there any way to do that? I tried a separate the files with '&' or ' ', but it does not work. Like below: @mjerris

->http_remove_cache http://example.com/media/hello_world.wav&http_remove_cache http://example.com/media/hello_world_2.wav 
Or
->http_remove_cache http://example.com/media/hello_world.wav&http://example.com/media/hello_world_2.wav

**Comment by crienzo** [comment]
Hello.  Please ask questions like this in our mailing list or our community slack forums.  Github issues are intended for bug reports.  Thank you.
