### ISSUE TITLE
Break of Playback of Multiple Files

### ISSUE THREAD

**Issue by yasingok** [signalwire/freeswitch#1066]
**Hi**
I used 
**1-uuid_break all**
Observe that 'file1' stops and the queued 'file2' starts playing.
The expected behavior is for the 'file1' to stop and 'file2' removed from the queue and never played.

**Comment by trdenton** [comment]
@yasingok can you provide version information and relevant dialplan section?

I am able to reproduce on `1.10.6-dev+git~20210205T103645Z~bc8e3da74c~64bit`

using the following xml dialplan:
`
[...]
<action application="playback" data="/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav" />
<action application="playback" data="/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav" />
<action application="playback" data="/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav" />
<action application="playback" data="/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav" />
<action application="voicemail" data="check default $${domain} 1000" />
`

If I understand correctly, running `uuid_break <uuid> all ` should bypass all of the playbacks and execute the voicemail check.  However, I have to run `uuid_break` once per playback item.

**Comment by trdenton** [comment]
note - on my previous comment, I now believe that what I observed is the correct behaviour for that dialplan.  

When I use [file_string](https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools%3A+file_string) the behaviour is as expected - calling `uuid_break all` bypasses all subsequent playbacks:

`<action application="set" data="playback_delimiter=!"/>
				<action application="playback" data="/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav!/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav!/usr/share/freeswitch/sounds/music/8000/ponce-preludio-in-e-major.wav" />`

**Comment by briankwest** [comment]
No, because uuid_break all will break all queued events, those events aren't queued till you hit them in the DP as it runs thru this instruction list.

**Comment by yasingok** [comment]
**@briankwest @trdenton  hi**;
Im sending 
**`(action application="playback" data="file_string://https://file1.wav!https://file2.wav!https://file3.wav")`** then
when I use 
**`(action application="break" data="all")`**  all playing file stop and other action 
 **`(action application="playback" data="file_string://https://file3.wav!https://file4.wav!https://file5.wav")`**  was sended
then I use  **`(action application="break" data="all")`** not stopped this time all file
why did not stop? Shouldn't he have stopped/

**Comment by trdenton** [comment]
@yasingok i have followed the directions you listed and i cannot reproduce your issue.  Perhaps I have not understood correctly. I am using this dialplan:

`<action application="set" data="playback_delimiter=!"/>`
`<action application="playback" data="file_string:///tmp/test.wav!/tmp/test.wav" />`
`<action application="playback" data="file_string:///tmp/test.wav!/tmp/test.wav" />`

in fs_cli i send the `uuid_break ... all` - each time it cancels one `playback` line in the dialplan, which is expected.  As a result i only have to run it twice instead of four times.  This is the intended behaviour as briankwest described above.


Could you provide your exact dialplan/script and logs?

**Comment by yasingok** [comment]
@trdenton  @briankwest  thanks. It is working now.
I have question about **mod_dptools: play_and_get_digits**
max=5 min=2
When I determine terminator as **=#**, if I hit digits the less than 5 , No problem I can see digits.
e.g.  I press   **1234#** ===> I see  **1234** or   I press **12#** ===> I see **12**    no problem 
but I hit max digits , I cant see any digit.
e.g. I prees **12345#** ===> No digit 

 THANKS

**Comment by briankwest** [comment]
uuid_break is not to stop playback of the items you collect up from dialplan, never has been, this is behaving exactly how its intended.

its designed to stop files queued via ESL:

sendmsg
call-command: execute
execute-app-name: playback
execute-app-arg: /tmp/swimp.raw\n\n

sendmsg
call-command: execute
execute-app-name: playback
execute-app-arg: /tmp/swimp.raw\n\n

sendmsg
call-command: execute
execute-app-name: playback
execute-app-arg: /tmp/swimp.raw\n\n

sendmsg
call-command: execute
execute-app-name: playback
execute-app-arg: /tmp/swimp.raw\n\n

uuid_break all would stop all those that are queued, in your dialplan case its not queued yet.

**Comment by briankwest** [comment]
See also https://freeswitch.org/confluence/display/FREESWITCH/Event+Socket+Outbound
