### ISSUE TITLE
Debian repository not signed

### ISSUE THREAD

**Issue by rhopportunist** [signalwire/freeswitch#1068]
**Describe the bug**
Attempted to Build From Source and Compile Release Branch (production) IAW instructions at https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster

Received the following error after "apt-get update" step:
Get:4 http://files.freeswitch.org/repo/deb/debian-release buster InRelease [3,936 B]
Err:4 http://files.freeswitch.org/repo/deb/debian-release buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BD3189F5A2B57698
Reading package lists... Done
W: GPG error: http://files.freeswitch.org/repo/deb/debian-release buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BD3189F5A2B57698
E: The repository 'http://files.freeswitch.org/repo/deb/debian-release buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**To Reproduce**
1. Start with a fresh install of Debian 10.8.  
2. apt-get update
3. apt-get update && apt-get install -yq gnupg2 wget lsb-release
4. wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -
5. echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list
6. echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list
7. apt-get update

**Expected behavior**
I expected the apt-get update to complete without error so that I could execute: apt-get build-dep freeswitch

**Package version or git hash**
 Debian 10.8

**Trace logs**
Didn't get this far!

**backtrace from core file**
Didn't get this far!

**Comment by rhopportunist** [comment]
mb

**Comment by rhopportunist** [comment]
For those wondering, this did not complete successfully.  Rerunning the command got me past this issue:
wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -

**Comment by abe-dci** [comment]
Perfect. Thanks @rhopportunist That wget worked for me!
