### ISSUE TITLE
Freeswitch-1.10.1 will crash when the playback file does not exist that the tts_commandline module needs to read

### ISSUE THREAD

**Issue by githubkimizhou** [signalwire/freeswitch#107]
freeswitch version: 1.10.1-release
os: debian 9.11

Freeswitch will crash when the playback file does not exist that the tts_commandline module needs to read. This problem happens every time.

Here is the coredump content：
#0  0x00007fef697ba5d8 in sndfile_file_close (handle=0x7fef80014710) at mod_sndfile.c:272
#1  0x00007fefa7711b0c in switch_core_file_close (fh=0x7fef80014710) at src/switch_core_file.c:934
#2  0x00007fef6844a889 in tts_commandline_speech_read_tts (sh=<optimized out>, data=<optimized out>, datalen=0x7fef7c0cc558, flags=<optimized out>) at mod_tts_commandline.c:189
#3  0x00007fefa770c245 in switch_core_speech_read_tts (sh=sh@entry=0x7fef7c0d0800, data=data@entry=0x7fef7c0cc620, datalen=datalen@entry=0x7fef7c0cc558, 
    flags=flags@entry=0x7fef7c0cc554) at src/switch_core_speech.c:226
#4  0x00007fefa77c641f in switch_ivr_speak_text_handle (session=session@entry=0x7fef90026408, sh=sh@entry=0x7fef7c0d0800, codec=codec@entry=0x7fef7c0d0710, timer=0x0, text=0x0, 
    text@entry=0x7fef80048228 "This is an example of using tts_commandline", args=args@entry=0x7fef7c0d0940) at src/switch_ivr_play_say.c:2854
#5  0x00007fefa77c6d49 in switch_ivr_speak_text (session=session@entry=0x7fef90026408, tts_name=tts_name@entry=0x7fef800481e0 "tts_commandline", 
    voice_name=voice_name@entry=0x7fef800481f0 "pico", text=text@entry=0x7fef80048228 "This is an example of using tts_commandline", args=args@entry=0x7fef7c0d0940)
    at src/switch_ivr_play_say.c:3070
#6  0x00007fef7d789473 in speak_function (session=0x7fef90026408, data=<optimized out>) at mod_dptools.c:2482
#7  0x00007fefa7723257 in switch_core_session_exec (session=session@entry=0x7fef90026408, application_interface=application_interface@entry=0x55f90fc67230, 
    arg=arg@entry=0x7fef900366d8 "tts_commandline|pico|This is an example of using tts_commandline") at src/switch_core_session.c:2891
#8  0x00007fefa772383f in switch_core_session_execute_application_get_flags (session=session@entry=0x7fef90026408, app=0x7fef900366d0 "speak", 
    arg=0x7fef900366d8 "tts_commandline|pico|This is an example of using tts_commandline", flags=flags@entry=0x0) at src/switch_core_session.c:2756
#9  0x00007fefa7727ada in switch_core_standard_on_execute (session=0x7fef90026408) at src/switch_core_state_machine.c:354
#10 switch_core_session_run (session=0x7fef90026408) at src/switch_core_state_machine.c:651
#11 0x00007fefa7720a0e in switch_core_session_thread (thread=<optimized out>, obj=0x7fef90026408) at src/switch_core_session.c:1709
#12 0x00007fefa771c493 in switch_core_session_thread_pool_worker (thread=0x7fef9004b6c0, obj=<optimized out>) at src/switch_core_session.c:1772
#13 0x00007fefa7853057 in dummy_worker (opaque=0x7fef9004b6c0) at threadproc/unix/thread.c:151
#14 0x00007fefa6c3d4a4 in start_thread (arg=0x7fef7c0d1700) at pthread_create.c:456
#15 0x00007fefa6279d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by yine** [comment]
I also have the same problem!

**Comment by dragos-oancea** [comment]
try current master, should be fixed

**Comment by githubkimizhou** [comment]
> try current master, should be fixed

ok! thank you very much! I saw that the bug has been fixed in the master branch!
