### ISSUE TITLE
Freeswitch crash on bridging conference (mod_conference) between SIP endpoints when destination hangsup (after initial answer).

### ISSUE THREAD

**Issue by andmar** [signalwire/freeswitch#1085]
** Description **

On a bridging conference (mod_conference) initiated by a SIP endpoint through the dialplan, if the destination SIP endpoint hangsup, after initially answering, Freeswitch crashes.

** Reproduce **

1. Get/Install Freeswitch from Github source (git clone https://github.com/signalwire/freeswitch.git -bv1.10 freeswitch)
2. Register two SIP devices (1000, 1001)
3. Replace line 287 (bridge app for "Local Extention") with "\<action application="conference" data="bridge:conferencename:user/1001" /\>"
4. Call from 1000 to any destination
5. Answer in 1001
6. Hangup 1001 (Freeswitch crashes imediately)
7. 1000 is left in a limbo until RTP timeout on the device side?

** Expected behavior **

Expected the channel for the calling endpoint to be hangup also and conference to finish.

** Affected Versions (tested) **

 - FreeSWITCH Version 20.20.3-dev-920-a142219d66~64bit (-dev-920-a142219d66 64bit)
 - FreeSWITCH Version 1.10.5-release+git~20200818T185121Z~25569c1631~64bit (git 25569c1 2020-08-18 18:51:21Z 64bit) (reproduce steps and logs taken from an installation of this version on a Debian 10/Buster)

** Logs **

[fs_bridgeconfcrash_freeswitch.log](https://github.com/signalwire/freeswitch/files/6051262/fs_bridgeconfcrash_freeswitch.log)
[fs_bridgeconfcrash_core_backtrace_20210226T170330Z-bt.txt](https://github.com/signalwire/freeswitch/files/6051263/fs_bridgeconfcrash_core_backtrace_20210226T170330Z-bt.txt)

**Comment by crienzo** [comment]
looking

**Comment by crienzo** [comment]
@andywolk this looks like conference->variables got destroyed and then mod_conference tried to send a conference event w/ those variables.

**Comment by andmar** [comment]
Hi @crienzo , @andywolk.

I think I may have found another crash which seems related, will leave it here just FYI.

If we have a conference and we do a bgdial command on it, if everyone leaves the conference before this new channel is either answered or rejected, when one of these happen Freeswitch crashes.
