### ISSUE TITLE
mod_av, missing the av_packet_unref() for AVPacket

### ISSUE THREAD

**Issue by 63isOK** [signalwire/freeswitch#1088]
**Describe the bug**
there is no relase for AVPacket after write_frame() send the AVPacket in "write audio data process"

**Comment by andywolk** [comment]
@63isOK Do you have any other details?

**Comment by 63isOK** [comment]
do the same thing as "video process"

**Comment by andywolk** [comment]
@63isOK  What is your scenario hitting that bug?

**Comment by 63isOK** [comment]
no a bug.
