### ISSUE TITLE
bgapi?originate {origination_uuid=12345678,hangup_after_bridge=true,ignore_early_media=true,originate_timeout=30,origination_caller_id_number=7777777}sofia/gateway/gw/15200000000  &playback(file_string://silence_stream://6000!https://****test.wav!silence_stream://6000!https://@@@@test1.wav)

### ISSUE THREAD

**Issue by ChuanjiaCai** [signalwire/freeswitch#1093]
Before and after the two voices are silent 6 s then play, sometimes normal silence time, and then normal play. Sometimes the value of setting the silent time is exceeded, and then played. Excuse me, do you have any questions about my writing, thanks for you attention，

**Comment by crienzo** [comment]
Sometimes https:// is slow to fetch.
