### ISSUE TITLE
Cannot recover transactions execution after broken odbc connection

### ISSUE THREAD

**Issue by razvancrainea** [signalwire/freeswitch#1095]
**Describe the bug**
When using MySQL Percona database configured over a ODBC connection, if the Percona cluster gets disconnected, FreeSWITCH cannot recover properly when it gets back online. Instead it goes into an infinite loop printing an error message (`switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqlfsdsn";...`).

**To Reproduce**
1. Configure MySQL (Percona) ODBC connector in the SIP profile `odbc-dsn` parameter
2. Stop MySQL for a while, then start it
3. Check the logs - lots of `switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqlfsdsn";...` appear, one every 200ms
4. Restart FreeSWITCH - this restarts the connection and everything is back fine.

**Expected behavior**
Properly recover the connection, or terminate it and start a new working one, without the need to restart FreeSWITCH.

**Package version or git hash**
 - Version 1.10.5-release-17-25569c1631

**Trace logs**
```
...
2021-03-03 04:28:02.489792 [CRIT] switch_odbc.c:291 The connection could not be re-established
2021-03-03 04:28:03.529778 [CRIT] switch_odbc.c:283 The sql server is not responding for DSN mysqldsn [STATE: 08003 CODE 0 ERROR: [unixODBC][Driver Manager]Connection not open
][233]
2021-03-03 04:28:03.529778 [INFO] switch_odbc.c:288 The connection has been re-established
2021-03-03 04:28:15.909782 [CRIT] switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqldsn";type="odbc"user="***";pass="***"]
2021-03-03 04:28:16.109782 [CRIT] switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqldsn";type="odbc"user="***";pass="***"]
2021-03-03 04:28:16.309779 [CRIT] switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqldsn";type="odbc"user="***";pass="***"]
2021-03-03 04:28:16.509779 [CRIT] switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqldsn";type="odbc"user="***";pass="***"]
2021-03-03 04:28:16.709774 [CRIT] switch_core_sqldb.c:2171 ERROR [Unable to Set AutoCommit Off--1], [db="mysqldsn";type="odbc"user="***";pass="***"]
...
```

**Extra**
I tried to investigate this myself and after the connection recovers, when FreeSWITCH wants to execute a transaction, it looks like it is unable to set the AutoCommit feature [OFF](https://github.com/signalwire/freeswitch/blob/v1.10.5/src/switch_core_sqldb.c#L2151) in the `do_trans` function, printing an [ERROR](https://github.com/signalwire/freeswitch/blob/v1.10.5/src/switch_core_sqldb.c#L2171). Most likely setting the AutoCommit feature [ON](https://github.com/signalwire/freeswitch/blob/v1.10.5/src/switch_core_sqldb.c#L2230) fails as well, leaving the connection in a "failed" state. The function continues and returns a `0` [ttl](https://github.com/signalwire/freeswitch/blob/v1.10.5/src/switch_core_sqldb.c#L2265), which doesn't change the stop condition and leads to an [infinite loop](https://github.com/signalwire/freeswitch/blob/v1.10.5/src/switch_core_sqldb.c#L2324).

**Comment by razvancrainea** [comment]
It looks like after FreeSWITCH recovers, when it tries to change the `AutoCommit`, the connection gets immediately lost: my MariaDB ODBC connector returns `Lost connection to MySQL server during query`, which is not handled anywhere, so from FreeSWITCH's perspective the connection is up (and sequentially used), but from the ODBC connector's point of view, it is not usable. Re-connecting the handler solves this issue.

I've tested this with a small patch:
```
                        if ((result = switch_odbc_SQLSetAutoCommitAttr(qm->event_db->native_handle.odbc_dbh, 0)) != SWITCH_ODBC_SUCCESS) {
-                               char tmp[100];
-                               switch_snprintfv(tmp, sizeof(tmp), "%q-%i", "Unable to Set AutoCommit Off", result);
-                               errmsg = strdup(tmp);
+                               errmsg = switch_odbc_handle_get_error(qm->event_db->native_handle.odbc_dbh, 0);
+                               if (strstr(errmsg, "Lost connection")) { 
+                                       errmsg = strdup(errmsg);
+                                       switch_odbc_handle_connect(qm->event_db->native_handle.odbc_dbh);
+                               } else {
+                                       char tmp[100];
+                                       switch_snprintfv(tmp, sizeof(tmp), "%q-%i", "Unable to Set AutoCommit Off", result);
+                                       errmsg = strdup(tmp);
+                               }
                        }
```

Now the connection recovers fine, but I feel like I've just fixed this isolated the issue (in a non generic manner, as it's probably just occurring for my particular Maria ODBC connector), whereas the problem might has a broader effect. However I'm not sure how to deal with this in a more generic fashion. Any ideas/feedback would be helpful and much appreciated.

**Comment by andywolk** [comment]
See if that helps https://github.com/signalwire/freeswitch/pull/1773
