### ISSUE TITLE
Coding error in switch_dso_open()

### ISSUE THREAD

**Issue by Paul-Mateer** [signalwire/freeswitch#1097]
if the first call to LoadLibraryEx fails in switch_dso_open, it makes a second call with amended parameters but does not capture the return code. As a result this second call may succeed but the code will still report an error and return a  NULL value to the caller.

**Comment by andywolk** [comment]
Patches are always welcome :-) @Paul-Mateer

**Comment by Paul-Mateer** [comment]
Happy to oblige @andywolk . Bit of a git/github novice so do I need to clone the active branch (apr-osx-configure-ipv6) and submit the change there?

**Comment by andywolk** [comment]
Press fork, create a branch in your fork, make a change, commit with a message, click to make a PR.

**Comment by Paul-Mateer** [comment]
Thanks @andywolk. So I think that I have successfully forked, branched, modified the file and committed it using GitHub for Desktop. Not sure what I am supposed to click to make a PR however. Getting my head around Git after years of working with TFS is giving me a headache.

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/1100
