### ISSUE TITLE
AMR codec problem - very bad sound quality

### ISSUE THREAD

**Issue by alpercoskun** [signalwire/freeswitch#1101]
**Describe the bug**
We are trying AMR codec with Freeswitch 1.10.5. When we try to play a voice file, sound is very choppy, and has some distortion.

We tried to enable volte parameters in amr.conf.xml, but it doesn't help.

**To Reproduce**
- Enable AMR
- Start the call
- Play a voice file

**Expected behavior**
Clear sound

**Package version or git hash**
 - Version 1.10.5

**Trace logs**
[log_tcpdump.zip](https://github.com/signalwire/freeswitch/files/6110395/log_tcpdump.zip)

**Comment by dragos-oancea** [comment]
A common issue is OA is negotiated and the device wants BE. Or BE negotiated and device wants OA. Are you sure you don't fall into this scenario ?

**Comment by dragos-oancea** [comment]
so it plays okay and without issues in wireshark ?

**Comment by alpercoskun** [comment]
wireshark doesn't support amr, but i extracted it as raw file, and it could be played well in a good quality.

**Comment by dragos-oancea** [comment]
is the device confirmed that it works in in other scenarios ? eg: proxy media ? 
From the log I see the spacing between packets is not always 20 ms and that you're not using a timer. 
"switch_rtp.c:4472 Not using a timer" 
Make sure you have these lines in the sip profile:
```
  <param name="use-rtp-timer" value="true"/>
  <param name="rtp-timer-name" value="soft"/>
```

**Comment by alpercoskun** [comment]
@dragos-oancea thanks for your support. problems are solved when enabled timer. 

also, we are playing .vox (dialogic adpcm) files, it seems libsndfile has a sound quality problem to play such files. i am adding a blog post for this .vox problem for just reference here:

http://lhari.hu/transcoding-in-freeswitch-from-dialogic-adpcm-to-g711/

**Comment by sanju-rgithub** [comment]
@alpercoskun Hi,
Am also trying to play amr files in freeswitch,but am getting disorted sounds only.

Can you guide me through how its done please.
It will be very helpfull.

**Comment by alpercoskun** [comment]
- make sure you use latest freeswitch version. 
- you should check your freeswitch.log. maybe there are some warnings or errors. 
- check your files if they play clearly on a media player. 
- check dragos-oancea comments here, especially about timer. 
- take a tcpdump, and apply "RTP analysis" from Telephony menu of Wireshark.

**Comment by sanju-rgithub** [comment]
Ok sure,thanks

**Comment by dragos-oancea** [comment]
we don't have support to play AMR or AMRWB files. And libsndfile does not implement it either.
