### ISSUE TITLE
Bug in switch_xml_parse_str_dynamic() 

### ISSUE THREAD

**Issue by pregalla** [signalwire/freeswitch#1107]
**Issue**: **Double free Situation**

In switch_xml_parse_str_dynamic(_In_z_ char *s, _In_ switch_bool_t dup), 

when dup is SWITCH_TRUE, data is duped. data = dup ? switch_must_strdup(s) : s;

But irrespective of the value of 'dup', **root->dynamic = 1;**

if ((root = (switch_xml_root_t) switch_xml_parse_str(data, strlen(data)))) {
		**root->dynamic = 1;**		/* Make sure we free the memory is switch_xml_free() */
		return &root->xml;
	}

In switch_xml_parse_str(char *s, switch_size_t len)
     **root->m = s;**

And in switch_xml_free():
		if (root->dynamic == 1)
			**free(root->m)**;		/* malloced xml data */

All will be good when called as: switch_xml_parse_str_dynamic(str, SWITCH_TRUE); switch_xml_free()

But when we do: switch_xml_parse_str_dynamic(str, SWITCH_FALSE); switch_xml_free()
Here str will be free'd as root->dynamic was set to 1, even though it was called with **SWITCH_FALSE**

As the user did not ask 'str' to be duplicated, they will then call free(str), which will be a double free situation.

Please check once if I missed something here in understanding the current code. Once confirmed I can open a PR for fixing this.

**Comment by pregalla** [comment]
Yes, below code crashes with double free.

SWITCH_STANDARD_STREAM(api_stream);
switch_api_execute("sofia", "xmlstatus", NULL, &api_stream);

char *line = (char *) api_stream.data;

xmlroot = switch_xml_parse_str_dynamic(line, SWITCH_FALSE);

switch_xml_free(xmlroot);
switch_safe_free(api_stream.data);  **//double free here**

**Comment by andywolk** [comment]
You should call `switch_xml_parse_str_dynamic` with `SWITCH_TRUE` in that case. So that's not a bug.
