### ISSUE TITLE
mod_av: audio/video failed when ffmpeg libraries compiled with libaom and SVT-AV1

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#1111]
**Describe the bug**
if ffmpeg is compiled with --enable-libaom --enable-svtav1
mod_av is compiled ok but not working when freeswitch is running.
reload mod_av gives this error:
**/usr/local/lib/libavcodec.so.58: undefined symbol: aom_codec_set_option**

**Expected behavior**
fix the undefined symbol in libavcodec link

**Package version or git hash**
 FreeSWITCH Version 1.10.6-dev+git~20210310T203436Z~2c2f2f9606~64bit (git 2c2f2f9 2021-03-10 20:34:36Z 64bit)

**Comment by seven1240** [comment]
you need to install the libaom libs tool. it's not a FreeSWITCH problem.
