### ISSUE TITLE
Wrong sample rate with record_session

### ISSUE THREAD

**Issue by Alienmaster** [signalwire/freeswitch#1112]
**Describe the bug**
When using record_session in my dialplan (or with mod_audio_fork its the same) and set the record_sample_rate to 16khz it works perfect with Chrome 89. When using Firefox 86 (bot x64 on Windows 10) the rate doubles to 32khz. When changing the sample rate to 8khz it works fine with Firefox.

Update: After some testing i can narrow the problem down to the opus codec. When i comment out the mod_opus module the audio data from both browser is fine.

**To Reproduce**
1. add the following lines to the dialplan:
```
<action application="set" data="RECORD_READ_ONLY=true"/>
   <action application="set" data="record_sample_rate=16000"/>
   <action application="record_session" data="/var/freeswitch/meetings/${strftime(%Y-%m-%d-%H-%M-%S)}_${call_uuid}.wav"/>
```

2. Join a call with Chrome and record a file. Join a call with Firefox also record a file.
3. Compare the frequency with eg audacity.

**Expected behavior**
A record with everytime 16khz sample rate

**Package version or git hash**
 - Version 1.10.4 in BigBlueButton

I use FreeSwitch in BigBlueButton 2.2.

**Comment by dragos-oancea** [comment]
check the SDP . Firefox vs Chrome . The difference may be coming from Opus's fmtp.

**Comment by Alienmaster** [comment]
After some testing i was able to narrow it down to the opus codec. I check the SDP.

**Comment by Alienmaster** [comment]
When I compare the two Local SDP messages, I notice the following: 
Chrome:
```
a=msid-semantic: WMS m9OqCRQDOOyCEa6V4fgvRx4k6eGByD1L
m=audio 21218 UDP/TLS/RTP/SAVPF 111 110
a=rtpmap:111 opus/48000/2
a=fmtp:111 useinbandfec=1; minptime=10
**a=rtpmap:110 telephone-event/48000**
a=ptime:20
a=sendrecv
a=setup:active
a=rtcp-mux
a=rtcp:21218 IN IP4 127.0.0.1
a=ice-ufrag:xHcf56p1bWtAplbR
a=ice-pwd:R2M5AaXNWitIzVpWtr1oohgp
a=candidate:2040621985 1 udp 659136 127.0.0.1 21218 typ host generation 0
a=end-of-candidates
a=ssrc:3025414273 cname:CG14nHx2mWuQWrBQ
a=ssrc:3025414273 msid:m9OqCRQDOOyCEa6V4fgvRx4k6eGByD1L a0
a=ssrc:3025414273 mslabel:m9OqCRQDOOyCEa6V4fgvRx4k6eGByD1L
a=ssrc:3025414273 label:m9OqCRQDOOyCEa6V4fgvRx4k6eGByD1La0
```
and Firefox:
```
a=msid-semantic: WMS YqkRRTV7YRQMZMbYIbkdLG17xie2lFw9
m=audio 17042 UDP/TLS/RTP/SAVPF 109 101
a=rtpmap:109 opus/48000/2
a=fmtp:109 useinbandfec=1; stereo=1
**a=rtpmap:101 telephone-event/8000**
a=ptime:20
a=sendrecv
a=setup:active
a=rtcp-mux
a=rtcp:17042 IN IP4 127.0.0.1
a=ice-ufrag:T9xuGos4wwWI2iIN
a=ice-pwd:Ppg5SHa3OR4zzTSiSfDpuWjQ
a=candidate:6736693537 1 udp 659136 127.0.0.1 17042 typ host generation 0
a=end-of-candidates
a=ssrc:3025414188 cname:VGRCpDAekhQaUSYt
a=ssrc:3025414188 msid:YqkRRTV7YRQMZMbYIbkdLG17xie2lFw9 a0
a=ssrc:3025414188 mslabel:YqkRRTV7YRQMZMbYIbkdLG17xie2lFw9
a=ssrc:3025414188 label:YqkRRTV7YRQMZMbYIbkdLG17xie2lFw9a0
```

**Comment by dragos-oancea** [comment]
The telephone-event is unrelated. Maybe it has something to do with Firefox setting "stereo=1" .

**Comment by Alienmaster** [comment]
Is there a way to force this as "mono"?

**Comment by dragos-oancea** [comment]
try this patch https://github.com/signalwire/freeswitch/pull/1115 . put this in opus cfg: ```	<param name="mono" value="1"/>```

**Comment by dragos-oancea** [comment]
the patch will enforce mono. however, I tried to reproduce what you say about the sample rate with Firefox, but I didn't get the same as you, I get a stereo file at 16 khz with the above settings in dialplan, which is expected.

**Comment by Alienmaster** [comment]
The whole snippet is this: (due to my fault with the code formatting github didn't show the first line)
```
<action application="set" data="RECORD_READ_ONLY=true"/>
   <action application="set" data="record_sample_rate=16000"/>
   <action application="record_session" data="/var/freeswitch/meetings/${strftime(%Y-%m-%d-%H-%M-%S)}_${call_uuid}.wav"/>
```
I made the changes to mod_opus and got the same results: Chrome is fine and Firefox isn't.

**Comment by dragos-oancea** [comment]
please show FS debug logs (both browsers)

**Comment by Alienmaster** [comment]
[freeswitch.log](https://github.com/signalwire/freeswitch/files/6151131/freeswitch.log)
The first connection is Firefox the second is Chrome

**Comment by dragos-oancea** [comment]
Needs fix in core media:
```
if (!zstr((char *) mmap->rm_fmtp) && switch_stristr("stereo=1", (char *) mmap->rm_fmtp)) {
pmap->channels = 2;
} else {
pmap->channels = 1;
}```

**Comment by Alienmaster** [comment]
I guess you mean this file: https://github.com/signalwire/freeswitch/blob/master/src/switch_core_media.c#L5776
What do i need to change?

**Comment by dragos-oancea** [comment]
I pushed a commit that does a change in the code I've shown. You will need to add a param to autoload_configs/switch.conf.xml . ``` <param name="max-audio-channels" value="1"/>``` . Both params (the one in opus cfg too) must be used.

**Comment by Alienmaster** [comment]
Could you please link me the commit? I didn't find it, sorry.

**Comment by dragos-oancea** [comment]
This branch with the 2 commits: https://github.com/signalwire/freeswitch/pull/1115

**Comment by dragos-oancea** [comment]
the branch was merged.
