### ISSUE TITLE
How can I use say when using play_and_detect_speech?

### ISSUE THREAD

**Issue by vvstormhao** [signalwire/freeswitch#1116]
when I am using play_and_detect_speech, i want to use mod_dptool:say api instead of a file. I want to set some custom param in say api, such as "engine=AWS",  which could transfer to SPEAK as a vendor param. how can i do this?

**Package version or git hash**
- Version of FreeSWITCH [e.g. 1.10.4]

**Comment by crienzo** [comment]
Use mod_ssml tts:// file format.  https://freeswitch.org/confluence/display/FREESWITCH/mod_ssml  Please check our confluence docs (confluence.freeswitch.org), the mailing list or our slack channel next time.  Thanks!
