### ISSUE TITLE
mod_callcenter

### ISSUE THREAD

**Issue by CraftedCat** [signalwire/freeswitch#113]
FreeSWITCH Version 1.10.2-dev+git~20191031T165005Z~aa2df4f3f8~64bit (git aa2df4f 2019-10-31 16:50:05Z 64bit)

2019-11-08 03:00:03.071578 [ERR] mod_callcenter.c:4213 Couldn't register subclass callcenter::info!
2019-11-08 03:00:03.071578 [CRIT] switch_loadable_module.c:1786 Error Loading module /usr/local/freeswitch/mod/mod_callcenter.so
**Module load routine returned an error**

callcenter.conf.xml exist...

**Comment by cdosoftei** [comment]
Can you provide the entire FreeSWITCH log? There could be a few different reasons, including a prior load attempt, which may have failed but didn't clean up after itself.

**Comment by cdosoftei** [comment]
#40 just got merged to master, please rebuild and test. The PR should resolve the reported issue.

**Comment by mochouinard** [comment]
@CraftedCat have you tested recent fs which include PR #40 ?

**Comment by crienzo** [comment]
Reopen issue if this is still a problem.
