### ISSUE TITLE
Make fails: libapr-1 error undeclared identifier 'NSIG' extern __const char *__const sys_signame[NSIG]; missing define in apr_general.h

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1145]
Master apr modules build fails starting April 2 due to undeclared identifier. Was good March 27, only one commit between those dates but doesn't look related.

On Apr 11 I found [this issue](https://gitlab.com/DavidGriffith/frotz/-/issues/98) so I added "**#define NSIG  __DARWIN_NSIG**" to  **apr_general.h** then build was fine.

The 3 line patch I copied the from the link fixed it. I found identical patches on other URLs, but I also tested using only:
+#if defined(_DARWIN_C_SOURCE) and it worked as well but I am no expert so change it as required.

diff --git a/libs/apr/include/apr_general.h b/libs/apr/include/apr_general.h
index 42eec83ce4..f98193cf4a 100644
--- a/libs/apr/include/apr_general.h
+++ b/libs/apr/include/apr_general.h
@@ -29,6 +29,10 @@
 #include "apr_pools.h"
 #include "apr_errno.h"
 
+#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
+#define NSIG   __DARWIN_NSIG
+#endif
+
 #if APR_HAVE_SIGNAL_H
 #include <signal.h>
 #endif

Make errors before patch:
In file included from ./include/apr_general.h:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:69:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_signame[NSIG];
                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:70:42: error: use of undeclared identifier 'NSIG'
extern __const char *__const sys_siglist[NSIG];
                                         ^
2 errors generated.
make[2]: *** [locks/unix/thread_mutex.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [libs/apr/libapr-1.la] Error 2

Tested April 2 and 28 on Big Sur/Clang V12.5, Catalina/Clang V12.4, and Mojave 10.14/Clang V11, all same results.

Make attached.
[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/6255019/07.FreeSWITCH.make.txt)

**Comment by MarioG-X** [comment]
Does anyone know if it should be:
#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
   or just
#if defined(_DARWIN_C_SOURCE)

Everything I found on the web that mentions this problem shows the first one, but I am wondering if the second one is simpler for just macOS.

**Comment by mjerris** [comment]
@MarioG-X most likely the first one

**Comment by MarioG-X** [comment]
Any idea when a fix will go into master? Have not done weekly builds since early April.

**Comment by andywolk** [comment]
@MarioG-X 
Try `nsig` branch please: https://github.com/signalwire/freeswitch/pull/1213/files

**Comment by MarioG-X** [comment]
Wow that works! Can't wait for master! I tested like this:
Downloaded latest master
applied the nsig patch by hand
make completed, started FreeSWITCH.

FYI make had several "warning:" messages for apr and other models you may want to check out. Search for "warning:"
[make.txt](https://github.com/signalwire/freeswitch/files/6563010/make.txt)
. I attached make.

**Comment by MarioG-X** [comment]
Figured download out, make and startup tested good from:
git clone –b nsig https://github.com/signalwire/freeswitch.git

1.10.7-dev+git~20210528T182656Z~749e5ca6a2~64bit (git 749e5ca 2021-05-28 18:26:56Z 64bit)

FYI make had several "warning:" messages for apr and other models you may want to check out. Search for "warning:". Make attached.
[make.txt](https://github.com/signalwire/freeswitch/files/6563398/make.txt)

**Comment by andywolk** [comment]
@MarioG-X I made some changes to the fix. Please give that another try, Same branch nsig.

**Comment by MarioG-X** [comment]
That fails, make attached. I already tried the define later than on in code and it did not work.
[Make2.txt](https://github.com/signalwire/freeswitch/files/6580216/Make2.txt)

**Comment by andywolk** [comment]
@MarioG-X Give that another try please

**Comment by MarioG-X** [comment]
349b4ea AOK now! Make and started up.

**Comment by andywolk** [comment]
@MarioG-X Give that another try please.

**Comment by MarioG-X** [comment]
189f6f8 AOK again. Make and startup good.

**Comment by MarioG-X** [comment]
Anything else needed from me?

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/1213
