### ISSUE TITLE
compiling without mod_pgsql

### ISSUE THREAD

**Issue by john9393** [signalwire/freeswitch#1149]
I have been using freeswitch for years in Slackware  (freeswitch 1.8..2),
postgres is NOT installed in my system (I am using mysql / mariadb) 
Moving to freeswitch-1.10.x, I have to compile the source but during this process I have this error :

Makefile:946: *** You must install libpq-dev to build mod_pgsql.  Stop.
make[4]: Leaving directory '/usr/src/freeswitch-1.10.6.-release/src/mod/databases/mod_pgsql'
make[3]: *** [Makefile:709: mod_pgsql-all] Error 1
How I can disable mod_pgsql ?
I have seen not option in ./configure.
Thank you for the answer.

**Comment by mjerris** [comment]
modules.conf selects which modules to build.  you can comment that module

**Comment by john9393** [comment]
thank you, solved!

________________________________
De : Michael Jerris ***@***.***>
Envoyé : mardi 6 avril 2021 17:48
À : signalwire/freeswitch ***@***.***>
Cc : john9393 ***@***.***>; Author ***@***.***>
Objet : Re: [signalwire/freeswitch] compiling without mod_pgsql (#1149)


modules.conf selects which modules to build. you can comment that module
