### ISSUE TITLE
mod_pgsql

### ISSUE THREAD

**Issue by joebarrero** [signalwire/freeswitch#115]
Freeswitch becomes unresponsive to SIP requests when mod_pgsql is used for core data.  Although the SQL statement can vary, it is always a SQL request to data that's stored within the Freeswitch core database.  

[CRIT] mod_pgsql.c:694 Query (select call_id,expires,sub_to_user,sub_to_host,event,version, 'full',full_to,full_from,contact,network_ip,network_port from sip_subscriptions where hostname='vfx2-test' and profile_name='external' and sub_to_user='1100' and sub_to_host='hostb.mydomain.com' and call_id='1924199135-40361-5460@BA.A.A.BAG') took too long to complete or database not responding.

The server does not crash with a core.  A core had to be generated using gcore.

I am currently using mod_pgsql via freeswitch.dbh API within my LUA scripts and the mod_pgsql error is not being triggered.  However, the number of calls via freeswitch.dbh may also be far less than core calls to the freeswitch database.

The database is connecting via the network interface, however, I've observed that there were no connection issues or other database anomalies when the mod_pgsql error would trigger. 

This error has occurred on multiple servers including a bare metal server.  The platform used for this test was:

- FreeSWITCH Version 1.10.1-release+git\~20190820T165404Z\~f9990221e6\~64bit (git f999022 2019-08-20 16:54:04Z 64bit)
- Debian 10 (Buster) Linux vfx2-test 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
- 2 virtual CPUs
- RAM: 4 GIGS

Please see the following backtrace. 
[gdb-backtrace.txt](https://github.com/signalwire/freeswitch/files/3828980/gdb-backtrace.txt)

**Comment by joebarrero** [comment]
Has there been any progress on this issue?

**Comment by andywolk** [comment]
Please try latest master

**Comment by crienzo** [comment]
Reopen if this is still an issue.
