### ISSUE TITLE
Memory leak found in mod_spandsp fs-1.2

### ISSUE THREAD

**Issue by rohanbendale** [signalwire/freeswitch#1152]
Valgrind shows leak in this block.

==9583== 3,088 (1,608 direct, 1,480 indirect) bytes in 3 blocks are definitely lost in loss record 1,569 of 1,685
==9583==    at 0x483D444: malloc (vg_replace_malloc.c:296)
==9583==    by 0x4A7014B: span_alloc (alloc.c:114)
==9583==    by 0x126DD4A3: super_tone_rx_make_descriptor (super_tone_rx.c:203)
==9583==    by 0x126AB25B: tone_descriptor_create (mod_spandsp_dsp.c:629)
==9583==    by 0x1269C66F: load_configuration (mod_spandsp.c:688)
==9583==    by 0x1269D8D7: mod_spandsp_init (mod_spandsp.c:839)
==9583==    by 0x49BEBDB: switch_loadable_module_load_file (switch_loadable_module.c:1356)
==9583==    by 0x49BF1D7: switch_loadable_module_load_module_ex (switch_loadable_module.c:1464)
==9583==    by 0x49C0223: switch_loadable_module_init (switch_loadable_module.c:1767)
==9583==    by 0x49B30A7: switch_core_init_and_modload (switch_core.c:2089)
==9583==    by 0xD9B3: main (switch.c:1198)
==9583==

**Comment by andywolk** [comment]
Please attach freeswitch log.
What freeswitch version is this?

**Comment by rohanbendale** [comment]
> Please attach freeswitch log.
> What freeswitch version is this?

Freeswitch version is old v1.2
freeswitch.log cannot be attached.

**Comment by andywolk** [comment]
We do not support FreeSWITCH v1.2 anymore. Please update and try reproducing the issue on the latest.
