### ISSUE TITLE
Huge delay between RTP packets in the IVR

### ISSUE THREAD

**Issue by muaddib91** [signalwire/freeswitch#1179]
**Describe the bug**
We have a simple IVR, which just answer the call and play the audio file. But in some circumstance it starts to work worse, the voice quality becomes really bad. From the logs perspective everything is fine, but I have looked at the network dumps and discovered that Freeswitch sends RTP packets with a huge delay between some of them.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/717750/116696001-00646700-a9ca-11eb-8db5-e04ba534f08c.png">

our freeswitch is connected to a public number via Twilio Elastic SIP trunk. 

What I have discovered that it happens when I am reaching the freeswitch via Web version of the  Skype the issue reproduces every time. Some of our customers experiences this issue by calling us (via public number) with their own Skype For Business solution.

**To Reproduce**
1. Try to call using Web version of Skype

**Expected behavior**
Good call quality

**Package version or git hash**
 2.2

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled
[freeswitch.log.zip](https://github.com/signalwire/freeswitch/files/6405377/freeswitch.log.zip)

Bad call ID example (the call affected by this issue):
be33dfd42e3894341b867e4cc166cae2

Good call
32b07c2e5b7f6b230d62a86656a5660d

**Comment by dragos-oancea** [comment]
do you have this in the SIP profiles ? ``` <param name="rtp-timer-name" value="soft"/>```

**Comment by dragos-oancea** [comment]
From your log:
```bffeefb5-e77c-4f71-a4bc-db41e4b6fa9f 2021-04-30 10:46:56.269392 [DEBUG] switch_rtp.c:4472 Not using a timer```

**Comment by muaddib91** [comment]
Hi @dragos-oancea, yes it has not been set in the external which was handling the calls, and it helps!! Thank you a lot :) We can close this thread
