### ISSUE TITLE
"Illegal instruction" on Raspberry Pi Zero W - armv6

### ISSUE THREAD

**Issue by bronkoo** [signalwire/freeswitch#1184]
freeswitch doesn't starts due to "Illegal instruction" output.

1. Prepare installation from [official](https://freeswitch.org/confluence/display/FREESWITCH/Raspberry+Pi)
2. `apt install hylafax-server freeswitch freeswitch-mod-commands freeswitch-mod-dptools freeswitch-mod-event-socket freeswitch-mod-sofia freeswitch-mod-spandsp freeswitch-mod-tone-stream freeswitch-mod-db freeswitch-mod-syslog freeswitch-mod-logfile`
3. `$ freeswitch`
`Illegal instruction`
5. `$ fs_cli`
`Segmentation fault`

`$ lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

`$ uname -a`
`Linux hub 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux`

`$ apt policy freeswitch`
```
freeswitch:
  Installed: 1.10.6~release~7~1ff9d0a60e~buster-1~buster+1
  Candidate: 1.10.6~release~7~1ff9d0a60e~buster-1~buster+1
  Version table:
 *** 1.10.6~release~7~1ff9d0a60e~buster-1~buster+1 500
        500 http://files.freeswitch.org/repo/deb/rpi/debian-release buster/main armhf Packages
        100 /var/lib/dpkg/status
     1.10.5~release~6~25569c1631~buster-1~buster+1 500
        500 http://files.freeswitch.org/repo/deb/rpi/debian-release buster/main armhf Packages
```

**Comment by andywolk** [comment]
That repo is not for Raspberry Pi Zero W - armv6

**Comment by bronkoo** [comment]
Ah, ok. **armv7** only?
Any option for me to run on armv6?
Building from sources by standard procedure?

**Comment by andywolk** [comment]
Yeah..but you will have to build sofia-sip and spandsp manually too

**Comment by bronkoo** [comment]
Yes, mentioned [here](https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster).
Mmmh, [GOfax.IP](https://gofaxip-project.org/documentation/#building) have to wait... ;-)

**Comment by andywolk** [comment]
I am closing the issue.

**Comment by bronkoo** [comment]
**Thanks!**
