### ISSUE TITLE
Play an image in place of a participant in the video conference when he goes on hold.

### ISSUE THREAD

**Issue by ramelcom** [signalwire/freeswitch#12]
Looks like when a participant in a video conference goes on hold, other participants see frozen video (last frame) of the participant on hold. It would be good to have an image or video-no-video-avatar functionality for this.

**Comment by mjerris** [comment]
This is a feature for a very specific use case that i added and did not need the behavior you are talking about.  I am going to close this but feel free to create a pull request if you would like to add this behavior yourself.
