### ISSUE TITLE
Resource locking issue

### ISSUE THREAD

**Issue by freeswitch1** [signalwire/freeswitch#120]
Hello,  I have run into a problem that happens every once in a while when maybe timing is right.  It seems to be a race condition on maybe locking?

What I see is that when using AVMD on a call and the  callee leg gets a hangup just before the Bug is being attached.  Freeswitch prints out the error that it was unable to put the bug on the channel, but from this point forward all calls do not release File handles held by the thread I am assuming.   While call stats do not show they are locked inside of freeswitch monitoring /proc/PRCOESSID/fd/ this just grows until freeswitch either crashes or hangs no longer able to process anything.   I have tried to look through the code, I did not really see anything obvious.  Though I am not a C programmer so chances are I would miss it.

Below is the calls log output when the issue starts.

This is FreeSWITCH version: 1.10.1-release~64bit (-release 64bit)
running on Debian GNU/Linux 10

Thanks 

6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.211768 [DEBUG] sofia.c:7290 Channel sofia/external/DESTNUMBER@sbc entering state [ready][200]
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.211768 [NOTICE] sofia.c:8409 Channel [sofia/external/DESTNUMBER@sbc] has been answered
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.211768 [DEBUG] switch_channel.c:3865 (sofia/external/DESTNUMBER@sbc) Callstate Change EARLY -> ACTIVE
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [INFO] switch_channel.c:3213 sofia/external/DESTNUMBER@sbc Flipping CID from "Test" <1002003000> to "Outbound Call" <DESTNUMBER>
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] mod_commands.c:5088 (sofia/external/DESTNUMBER@sbc) State Change CS_CONSUME_MEDIA -> CS_EXECUTE
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:585 (sofia/external/DESTNUMBER@sbc) Running State Change CS_EXECUTE (Cur 71 Tot 207953)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:651 (sofia/external/DESTNUMBER@sbc) State EXECUTE
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] mod_sofia.c:209 sofia/external/DESTNUMBER@sbc SOFIA EXECUTE
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:329 sofia/external/DESTNUMBER@sbc Standard EXECUTE
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 EXECUTE [depth=0] sofia/external/DESTNUMBER@sbc lua(checkVM.lua)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 EXECUTE [depth=0] sofia/external/DESTNUMBER@sbc tone_detect(vmdbeep 440,738,845,1000 r)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [NOTICE] mod_dptools.c:2308 Enabling tone detection vmdbeep 440,738,845,1000
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_ivr_async.c:4056 Adding tone spec 440,738,845,1000 index 0 hits 1
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_media_bug.c:970 Attaching BUG to sofia/external/DESTNUMBER@sbc
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 EXECUTE [depth=0] sofia/external/DESTNUMBER@sbc avmd(start)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [INFO] mod_avmd.c:1224 Avmd dynamic configuration: debug [0], report_status [1], fast_math [0], require_continuous_streak [1], sample_n_continuous_streak [15], sample_n_to_skip [6], require_continuous_streak_amp [1], sample_n_continuous_streak_amp [3], simplified_estimation [1], inbound_channel [0], outbound_channel [1], detection_mode [2], detectors_n [36], detectors_lagged_n [1]
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [NOTICE] sofia.c:1084 Hangup sofia/external/DESTNUMBER@sbc [CS_EXECUTE] [NORMAL_CLEARING]
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [ERR] switch_core_media_bug.c:832 Cannot establish media. Media bug add failed.
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [ERR] mod_avmd.c:1510 Failed to add media bug!
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [ERR] mod_avmd.c:1530 Avmd on channel [sofia/external/DESTNUMBER@sbc] NOT started
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_session.c:2905 sofia/external/DESTNUMBER@sbc skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_session.c:2685 sofia/external/DESTNUMBER@sbc Channel is hungup and application wait_for_silence does not have the zombie_exec flag.
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_cpp.cpp:731 CoreSession::hangup
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_cpp.cpp:1187 sofia/external/DESTNUMBER@sbc destroy/unlink session from object
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_session.c:2905 sofia/external/DESTNUMBER@sbc skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:651 (sofia/external/DESTNUMBER@sbc) State EXECUTE going to sleep
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:585 (sofia/external/DESTNUMBER@sbc) Running State Change CS_HANGUP (Cur 71 Tot 207953)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_media_bug.c:1289 Removing BUG from sofia/external/DESTNUMBER@sbc
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_media_bug.c:1289 Removing BUG from sofia/external/DESTNUMBER@sbc
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:848 (sofia/external/DESTNUMBER@sbc) Callstate Change ACTIVE -> HANGUP
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:850 (sofia/external/DESTNUMBER@sbc) State HANGUP
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] mod_sofia.c:460 Channel sofia/external/DESTNUMBER@sbc hanging up, cause: NORMAL_CLEARING
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:60 sofia/external/DESTNUMBER@sbc Standard HANGUP, cause: NORMAL_CLEARING
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:850 (sofia/external/DESTNUMBER@sbc) State HANGUP going to sleep
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:620 (sofia/external/DESTNUMBER@sbc) State Change CS_HANGUP -> CS_REPORTING
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:585 (sofia/external/DESTNUMBER@sbc) Running State Change CS_REPORTING (Cur 71 Tot 207953)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:936 (sofia/external/DESTNUMBER@sbc) State REPORTING
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:174 sofia/external/DESTNUMBER@sbc Standard REPORTING, cause: NORMAL_CLEARING
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:936 (sofia/external/DESTNUMBER@sbc) State REPORTING going to sleep
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:611 (sofia/external/DESTNUMBER@sbc) State Change CS_REPORTING -> CS_DESTROY
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_session.c:1726 Session 207852 (sofia/external/DESTNUMBER@sbc) Locked, Waiting on external entities
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [NOTICE] switch_core_session.c:1744 Session 207852 (sofia/external/DESTNUMBER@sbc) Ended
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [NOTICE] switch_core_session.c:1748 Close Channel sofia/external/DESTNUMBER@sbc [CS_DESTROY]
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:739 (sofia/external/DESTNUMBER@sbc) Running State Change CS_DESTROY (Cur 70 Tot 207953)
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:749 (sofia/external/DESTNUMBER@sbc) State DESTROY
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] mod_sofia.c:365 sofia/external/DESTNUMBER@sbc SOFIA DESTROY
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:181 sofia/external/DESTNUMBER@sbc Standard DESTROY
6e01a2b0-031c-11ea-8dcf-891db9fa24a1 2019-11-09 10:13:34.231771 [DEBUG] switch_core_state_machine.c:749 (sofia/external/DESTNUMBER@sbc) State DESTROY going to sleep

**Comment by andywolk** [comment]
Fixed by #122
