### ISSUE TITLE
CentOS 7 / RHEL 7 Yum repository (https://files.freeswitch.org) serving expired TLS certificate

### ISSUE THREAD

**Issue by jameswmcnab** [signalwire/freeswitch#1203]
**Describe the bug**
When trying to install FreeSWITCH on CentOS 7 using [the yum instructions provided](https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7), the https://files.freeswitch.org server **sometimes** serves an expired TLS certificate when yum attempts to download the `freeswitch-release-repo` package, or packages from the repo once configured. This causes installation to fail.

**To Reproduce**
1. CentOS 7 system (or RHEL 7 but I haven't tried it myself).
2. Attempt to follow the instructions here to install the repo and then install freeswitch from the repo: https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7
3. Yum will fail with a `Cannot open: https://files.freeswitch.org/repo/yum/centos-release/freeswitch-release-repo-0-1.noarch.rpm. Skipping.` error if served the expired TLS certificate.

Because this sometimes is fine (if you are served a valid certificate) and sometimes not, here is a more easily reproducable command to connect using OpenSSL and see the expired certificate being returned. You need to run this command multiple times to see the expired certificate returned.

```
echo "Q" | openssl s_client -showcerts -connect files.freeswitch.org:443 2>/dev/null | openssl x509 -noout -dates
```

Example output showing valid cert (first ) and invalid cert (last two)

```shell
$ echo "Q" | openssl s_client -showcerts -connect files.freeswitch.org:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Apr 18 04:58:09 2021 GMT
notAfter=Jul 17 04:58:09 2021 GMT

$ echo "Q" | openssl s_client -showcerts -connect files.freeswitch.org:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb 17 05:58:09 2021 GMT
notAfter=May 18 05:58:09 2021 GMT

$ echo "Q" | openssl s_client -showcerts -connect files.freeswitch.org:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb 17 05:58:09 2021 GMT
notAfter=May 18 05:58:09 2021 GMT
```

**Expected behavior**
The server to provide a valid TLS certificate on each connection.

**Package version or git hash**
 - `freeswitch-release-repo-0-1`

**Trace logs**
N/A

**backtrace from core file**
N/A

**Comment by andywolk** [comment]
Should be fine now. Let me know if there is a problem still.
