### ISSUE TITLE
Build RPM on CentOS7 fails with missing function

### ISSUE THREAD

**Issue by rippiedoos** [signalwire/freeswitch#121]
Building the RPM for FreeSWITCH 1.10.1 fails on CentOS Linux release 7.7.1908 (Core)

I've used 2 methodes, witch fail both on the same module, mod_kazoo:

```
making all mod_kazoo
make[4]: Entering directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src/mod/event_handlers/mod_kazoo'
/usr/bin/make  all-am
make[5]: Entering directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src/mod/event_handlers/mod_kazoo'
  CC       mod_kazoo_la-mod_kazoo.lo
  CC       mod_kazoo_la-kazoo_utils.lo
  CC       mod_kazoo_la-kazoo_dptools.lo
  CC       mod_kazoo_la-kazoo_tweaks.lo
  CC       mod_kazoo_la-kazoo_api.lo
  CC       mod_kazoo_la-kazoo_commands.lo
  CC       mod_kazoo_la-kazoo_config.lo
  CC       mod_kazoo_la-kazoo_message.lo
  CC       mod_kazoo_la-kazoo_ei_config.lo
  CC       mod_kazoo_la-kazoo_ei_utils.lo
kazoo_ei_utils.c: In function ‘ei_encode_json’:
kazoo_ei_utils.c:221:3: error: implicit declaration of function ‘ei_x_encode_map_header’ [-Werror=implicit-function-declaration]
   ei_x_encode_map_header(ebuf, count);
   ^
cc1: all warnings being treated as errors
make[5]: *** [mod_kazoo_la-kazoo_ei_utils.lo] Error 1
make[5]: Leaving directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src/mod/event_handlers/mod_kazoo'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src/mod/event_handlers/mod_kazoo'
make[3]: *** [mod_kazoo-all] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src/mod'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/freeswitch-1.10.1.-dev.14'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.StDSzX (%build)
```

It fails on the missing function ei_x_encode_map_header, which is introduced in erl_interface 3.8. On CentOS 7 the EPEL-erlang-erl_interface is 3.7.15, where this function isn't provided. 

I've managed to rebuild it with the erlang-release from puias-unsupported but this means that the mod_kazoo-module isn't usable on CentOS 7. The function isn't available from the erlang-release from EPEL.

**Comment by danielfinke** [comment]
You can solve this by installing `esl-erlang` (I used 19.3) from https://www.erlang-solutions.com/resources/download.html as well as the corresponding `esl-erlang-compat` (which provides the `erlang` package) from https://github.com/jasonmcintosh/esl-erlang-compat.

Or at least that should have been enough, but I had to also modify `freeswitch.spec` replacing `Requires: erlang` and `BuildRequires: erlang` with `Requires: esl-erlang` and `BuildRequires: esl-erlang` in all locations.

**Comment by mjerris** [comment]
@lazedo
