### ISSUE TITLE
mod_event_socket: cannot connect via fs_cli

### ISSUE THREAD

**Issue by wmasilva** [signalwire/freeswitch#124]
Current master is impossible to  connect using fs_cli, got the error in console:

    2019-11-12 15:52:18.902065 [ERR] mod_event_socket.c:2639 Listener session is null!

Solved by reverting the commit: 7f6348313826bb989cc0ad1d18d63451869f4f6b 
Patch: 
[FIX_mod_event_socket_connect_via_fscli.txt](https://github.com/signalwire/freeswitch/files/3840911/FIX_mod_event_socket_connect_via_fscli.txt)

**Comment by andywolk** [comment]
Reverting is not a solution. That commit does fix another problem. Need to make one more commit to fix that new issue. Please stand by. A fix is comming.

**Comment by wmasilva** [comment]
Thanks.
