### ISSUE TITLE
how to get RTCP voice quality？

### ISSUE THREAD

**Issue by freeeyes** [signalwire/freeswitch#1247]
In some cases, I want to get the call quality under a specified channel. It is used to judge the call quality of users on the current line. When the call quality is not good, I will record and report to the designated interface.
Excuse me, can you provide an API for judging voice quality?

thanks.

**Comment by dragos-oancea** [comment]
try  "mediaStats" 
```SWITCH_ADD_JSON_API(json_api_interface, "mediaStats", "JSON Media Stats", json_stats_function, "");```

**Comment by freeeyes** [comment]
thanks, it's work.
