### ISSUE TITLE
Freeswitch master on Debian 10.10 segfaults on libcrypto

### ISSUE THREAD

**Issue by keesvandenbos** [signalwire/freeswitch#1250]
Freeswitch master on Debian 10.10 segfaults on libcrypto

On a Debian 10.10 installation Freeswitch master crashes on average once every two days on libcrypto. The server has a low load around 150 concurrent calls doing SIP to WebRTC for locally registered WebRTC endpoints. This issue is present on multiple servers.

This issue was also present on the stable release version of Freeswitch, see my previsions issue  (https://github.com/signalwire/freeswitch/issues/1238)

FreeSWITCH Version: 1.10.7 -dev-2555-33040f2a43 64bit
Debian version: Linux webrtc 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21)

From syslog:

Jun 30 18:43:12 webrtc kernel: [163208.305993] freeswitch[23602]: segfault at 8 ip 00007f00e1158147 sp 00007f0060c2d6a0 error 4 in libcrypto.so.1.1[7f00e106d000+19e000]
Jun 30 18:43:12 webrtc kernel: [163208.306062] Code: 00 00 90 48 85 d2 74 0b ff 67 28 0f 1f 84 00 00 00 00 00 b8 01 00 00 00 c3 66 2e 0f 1f 84 00 00 00 00 00 41 54 55 53 48 8b 07 <83> 78 08 40 7f 4d 48 89 fb 48 89 d5 ff 50 28 41 89 c4 48 8b 03 48
Jun 30 18:43:14 webrtc systemd[1]: freeswitch.service: Main process exited, code=killed, status=11/SEGV

I am not sure if it is a generic problem or related to my specific configuration.

If you can provide me some hints or direction to resolve or better troubleshoot this, it will be helpful.

Thanks in advance for your attention.

[backtrace_681_webrtc_20210630.log](https://github.com/signalwire/freeswitch/files/6747412/backtrace_681_webrtc_20210630.log)

**Comment by andywolk** [comment]
Please install freeswitch debugging symbols anbd redo backtrace

**Comment by keesvandenbos** [comment]
Attached a new backtrace with debugging symbols. 

Same error. [backtrace.log](https://github.com/signalwire/freeswitch/files/6768542/backtrace.log)

**Comment by skainzwnt** [comment]
I may be wrong, but it sounds a little like a problem i reported some time ago. 
We also dont have a solution yet. 
#1180

**Comment by andywolk** [comment]
@keesvandenbos See if that fixes the issue: https://github.com/signalwire/freeswitch/pull/1283

**Comment by andywolk** [comment]
> I may be wrong, but it sounds a little like a problem i reported some time ago.
> We also dont have a solution yet.
> #1180

No, this is unrelated.

**Comment by andywolk** [comment]
@keesvandenbos Any updates?

**Comment by keesvandenbos** [comment]
@andywolk  We have been running with the patched server for the last 4 days and have not had a crash since. I will keep watching this server and report back next week. So far it seems the patch works!

**Comment by keesvandenbos** [comment]
@andywolk We had not have a crash for 2 weeks. This issue seems to be solved, I will close it.

Thanks for your time!
