### ISSUE TITLE
How to handle the Closed Outbound event socket?

### ISSUE THREAD

**Issue by LeeMaster** [signalwire/freeswitch#1258]
I'm a newbee learning FreeSwitch 
Here is a phenomenon which makes me puzzled 

Firstly I set the dialplan of a specific number `66666` and the only action in the extension is that 

```xml
<action application="socket" data="localhost:8040 async full"/>
```

when I call the specific number `66666` then the freeswitch routes this call channel to my socket server 
After receiving the event the call inbound , I do this 

```plain
call-command: execute
exectute-app-name: echo
```

After this operation I could hear my voice from my headset, at this time I killed my socket server.

But the call is not hungup or anything.

So how can I recover the connection to control this call again, or if anyone have more effective method to deal with this situation I met? 

:(

**Comment by hnimminh** [comment]
@LeeMaster 
Call will not hangup even your socket server killed. The  socket server should keep always running. 
You can interactive back to call by "api uuid_<command>" to control then call

The more safe and effective method is use inbound esl instead of outbound. Ideally:
1 - listen event. 
2 - control the call via uuid by state machine.

**Comment by LeeMaster** [comment]
> @LeeMaster
> Call will not hangup even your socket server killed. The socket server should keep always running.
> You can interactive back to call by "api uuid_" to control then call
> 
> The more safe and effective method is use inbound esl instead of outbound. Ideally:
> 1 - listen event.
> 2 - control the call via uuid by state machine.

but in my test case with `nc` the call will be hangup when I kill with ctrl-C, so if there some application or api to let the call keep alive when i close my server ?

**Comment by LeeMaster** [comment]
Could use this pattern, that when outbound scoket receive a new connection then store the information in redis or other storage and then call the dispatcher to start a new inbound socket with uuid_ application to control this call. But in my opnion if i implement the IVR using this pattern if the inbound scoket disconnected which state could cause the call hangup ? It's right ?
