### ISSUE TITLE
Compile ESL sample code "clang: error: linker command failed with exit code 1"

### ISSUE THREAD

**Issue by mengalong** [signalwire/freeswitch#1266]
Hello,

I try to manually compile ESL sample code on MacX， while compiling  "ld" complains that ” linker command failed with exit code 1“

```c
gcc -I/usr/local/src/freeswitch/libs/esl/src/include -o myesl myesl.c
Undefined symbols for architecture x86_64:
  "_esl_connect_timeout", referenced from:
      _main in myesl-bf1be3.o
  "_esl_disconnect", referenced from:
      _main in myesl-bf1be3.o
  "_esl_send_recv_timed", referenced from:
      _main in myesl-bf1be3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

I am sure I missed out something while compiling Can anyone please point out, what am I missing. Thank you.

The sample code（myesl.c):
```c
#include <stdio.h>
#include <stdlib.h>
#include <esl.h>


int main(void)
{
	esl_handle_t handle = {{0}};

	esl_connect(&handle, "localhost", 8021, NULL, "ClueCon");

	esl_send_recv(&handle, "api status\n\n");

	if (handle.last_sr_event && handle.last_sr_event->body) {
		printf("%s\n", handle.last_sr_event->body);
	} else {
		// this is unlikely to happen with api or bgapi (which is hardcoded above) but prefix but may be true for other commands
		printf("%s\n", handle.last_sr_reply);
	}

	esl_disconnect(&handle);

	return 0;
}
```

**Comment by LeeMaster** [comment]
I think you need link the libesl

**Comment by mengalong** [comment]
> I think you need link the libesl

Thanks, I have fix it.

 gcc -o myesl myesl.c /usr/local/src/freeswitch/libs/esl/.libs/libesl.a   -I/usr/local/src/freeswitch/libs/esl/src/include/

**Comment by LeeMaster** [comment]
but you should care about the dialplan and dynmaic dispatching with event socket, the event scoket protocol have a big global lock to keep the request SC, which could let all the application running ineffectively and not soundly
