### ISSUE TITLE
Make fails: test_mod_commands.so can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file for architecture x86_64

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1271]
**Describe the bug**
make fails with:
*** Warning: Linking the executable test/test_mod_commands against the loadable module
*** mod_commands.so is not portable!
*** Warning: lib mod_commands.so is a module, not a shared library

*** And there doesn't seem to be a static archive available
*** The link will probably fail, sorry
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file './.libs/mod_commands.so' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Make did not have this issue on July 12, this was introduced since then.
Tested on all supported macOS with same results, 11.4, 15.6, 14.6.

**To Reproduce**
1. Download master
2. ./bootstrap.sh
3. ./configure
4. make

**Expected behavior**
make should build to final steps.

**Package version or git hash**
 - Master downloaded July 17. Git log shows 311e932df5ac30f7fdb8b31f3579f6a012b964cf at top

configure and make attached
[06 FreeSWITCH configure.txt](https://github.com/signalwire/freeswitch/files/6836692/06.FreeSWITCH.configure.txt)
[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/6836693/07.FreeSWITCH.make.txt)

**Comment by andywolk** [comment]
Does this work for you? https://github.com/signalwire/freeswitch/pull/1270

**Comment by MarioG-X** [comment]
After many hours of trying to figure out if there is a way to "patch from online" I wound up editing the file by hand. The result: IT WORKS! I also started FreeSWITCH to make sure startup works. Thank you!

PS: The FreeSWITCH [macOS](https://freeswitch.org/confluence/display/FREESWITCH/macOS+Installation) wiki status will stay as **Bad** until after I test it in master.

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/1270
