### ISSUE TITLE
mod_http_cache not including query string for HTTP PUT requests to s3

### ISSUE THREAD

**Issue by aukeman** [signalwire/freeswitch#1280]
**Describe the bug**
For a 12 hour period, from 2021-07-19 12:00:00 UTC to 2021-07-20 00:00:00 UTC, it was observed in our production environment that HTTP PUT requests generated by `mod_http_cache` to upload audio recordings to an s3 bucket did not include any query string parameters.  Because the query string for these requests is used to transmit authentication & authorization information to AWS, the upload operations failed.

The missing query strings were confirmed by inspecting s3 access logs which show HTTP PUT requests made outside the 12 hour window (both before and after) include query string parameters but requests made during the window do not.

This behavior was observed from 50 different instances of freeswitch each running on its own ec2 instance.   That this behavior was observed across multiple hosts only during the same 12 hour window strongly suggest there is a time-based component involved.

However, other similarly configured freeswitch instances running in a separate QA environment did not exhibit this behavior during the same time window.

**To Reproduce**
We have so far been unable to reproduce.  Using a development system, we have set the system time to be within the time window in question and ran the same call flow but did not observe the bug.  We have run various scenarios in [test_aws.c](https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_http_cache/test/test_aws.c) again with system time set to the time window in question and all tests pass.

The recording processing was initiated by `mod_rayo` which includes the following relevant configuration in `conf/autoload_configs/rayo.conf.xml`:
```xml
	<!-- record component params -->
	<record>
	  <param name="record-file-prefix" value="{profile=s3}https://$${s3_audio_bucket}.s3.amazonaws.com/recordings/"/>
	</record>
```
The s3 profile is configured as follows in `conf/autoload_configs/http_cache.conf.xml`: 
```xml
  <profiles>
    <profile name="s3">
      <aws-s3>
        <access-key-id><![CDATA[$${aws_access_key_id}]]></access-key-id>
        <secret-access-key><![CDATA[$${aws_secret_access_key}]]></secret-access-key>
        <base-domain><![CDATA[s3.amazonaws.com]]></base-domain>
        <region><![CDATA[us-east-1]]></region>
      </aws-s3>
      <domains>
        <domain name="$${s3_audio_bucket}.s3.amazonaws.com" />
      </domains>
    </profile>
  </profiles>
```
All relevant variables (aws_access_key_id, aws_secret_access_key, s3_audio_bucket) have been checked and double-checked to have contained the expected and correct values.  This configuration did not change before or after the outage window noted above.  Freeswitch was not restarted before, during or after the outage window.

**Expected behavior**
a correctly configured mod_http_cache should always include query parameters in the HTTP PUT request to AWS S3

**Package version or git hash**
 - Version 1.10.6

**Trace logs**
only NOTIFY logs and above were logged during the incident, and those don't appear to show anything relevant

Looking through the source, our best guess is:
1. the `get_time` operation [here](https://github.com/signalwire/freeswitch/blob/1ff9d0a60e00c887d653805b3c6c7aa93443a05b/src/mod/applications/mod_http_cache/aws.c#L302) populated `aws_s3_profile.date_stamp` with a zero length string during the time in question, which 
2. due to [this check](https://github.com/signalwire/freeswitch/blob/1ff9d0a60e00c887d653805b3c6c7aa93443a05b/src/mod/applications/mod_http_cache/aws.c#L50) causes 
3. [this if statement to evaluate to true](https://github.com/signalwire/freeswitch/blob/1ff9d0a60e00c887d653805b3c6c7aa93443a05b/src/mod/applications/mod_http_cache/aws.c#L147) so `aws_s3_signature_key()` returns `NULL`
4. [As a result](https://github.com/signalwire/freeswitch/blob/1ff9d0a60e00c887d653805b3c6c7aa93443a05b/src/mod/applications/mod_http_cache/aws.c#L248), the query string generated by the call to `aws_s3_authentication_create()` is NULL

This fits the observed behavior and is time-dependent, but is speculative and we are not sure under what (if any) conditions the time formatting routine would output a zero-length string, so the problem could be elsewhere.

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/1282
