### ISSUE TITLE
Freeswitch Version 1.10.1 Crashes with Segfault errors, running on CentOS 7

### ISSUE THREAD

**Issue by Brendahnyaringita** [signalwire/freeswitch#1281]
FreeSWITCH  crashes from time to time  with a spike in Memory. The memory increases gradually and at around 85% FreeSWITCH crashes with the error below:

freeswitch[17986]: segfault at 8 ip 00007fad53d2736b sp 00007fabb2211638 error 6 in libpthread-2.17.so[7fad53d1c000+17000]

Other past crashes have show errors:

fs_cli[13798]: segfault at 0 ip 00007fb0b1ad5ed0 sp 00007fb0b2406ba8 error 4 in libedit.so.0.0.42[7fb0b1ac0000+35000]
 fs_cli[6847]: segfault at 3336126320 ip 00007feafc40ef64 sp 00007ffcf55a2350 error 4 in libc-2.17.so[7feafc38d000+1c3000]
freeswitch[1561]: segfault at 18 ip 00007f3974e21d00 sp 00007f3892e99608 error 4 in libpthread-2.17.so[7f3974e18000+17000]
 freeswitch[25457]: segfault at 18 ip 00007f9035610d00 sp 00007f8f64ef6638 error 4 in libpthread-2.17.so[7f9035607000+17000]
 freeswitch[25459]: segfault at 18 ip 00007f9035610d00 sp 00007f8e9244f638 error 4 in libpthread-2.17.so[7f9035607000+17000]
 sip csf_ng.DN04[14891]: segfault at 384 ip 00005582e0a38f23 sp 00007f300e7fb000 error 6 in janus[5582e09e5000+9a000]

**Comment by mjerris** [comment]
please collect backtraces from the core files generated from these crashes.  reopen issue once those are attached (please make sure debug symbols are installed)

**Comment by mjerris** [comment]
does the current release also crash in the same scenario or is this already fixed ?
