### ISSUE TITLE
Erroneous libvpx make warnings starting with macOS 11.5.1

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1286]
**Describe the bug**
_ld: warning: object file (libs/libvpx/libvpx.a(vpx_codec.c.o)) was built for newer macOS version (11.5) than being linked (11.0)_

macOS libvpx make warnings started due to Apple adding a modification level for the first time since 2001. Versions were "10.version.release" until Big Sur 11 which used "version.release": 11.r, 12.r, etc. On July 26 2021 Apple issued the first numbered security update adding .1 to 11.5 creating 11.5.1.

Libvpx configure passes a minimum version flag to make. PR #1253 eliminated annual libvpx maintenance by dropping the last .# leaving only the version. "10.version.release" became 10.version, 11.release became 11. Two days after the commit to master, the Apple change caused libvpx to pass "11.5" instead of "11".

**Changes**
libvpx configure.sh: If version starts with “10.” the last .# (Release) is dropped, 10.15.7 (10.v.r) becomes 10.15. Else the first period and everything after is truncated leaving only version: 11.5 and 11.5.1 become 11, 12.# and 12.#.# becomes 12, etc.

**Testing**
Tested on 10.14.6 Mojave, 10.15.7 Catalina, messages eliminated on 11.5.1 Big Sur.

Learning GitHub: I renamed the pull title from 10.5.1 to 11.5.1 but it deleted the pull request so added a second pull.

**Comment by MarioG-X** [comment]
Is there a way someone can modify libs/libvpx/build/make/configure.sh (same as #1288) so this issue can be closed, thank you:

replace this line:
      mvmin="-mmacosx-version-min="${mvmin%.*}

with these:
       if [[ $mvmin == 10.* ]]; then
         mvmin="-mmacosx-version-min=""${mvmin%.*}"
       else
         mvmin="-mmacosx-version-min=""${mvmin%%.*}"
       fi

**Comment by andywolk** [comment]
We already have 1288. Will that be enough?

**Comment by MarioG-X** [comment]
If 1288 is in master then this issue is resolved. Last known show stopper is #1474.
