### ISSUE TITLE
"Timer" for recurring scheduled events

### ISSUE THREAD

**Issue by ObakeFilter** [signalwire/freeswitch#1292]
Hi, I would like to know if there's a built in way to implement a scheduled event that should repeat itself for every given time, in a similar manner to the 'execute_on...' or "sched_api" commands, but instead of firing out once - I would like the command repeat itself as long as the call is alive. Right now I am using a recursive LUA script that schedules itself to acheive that.

Edward

**Comment by mjerris** [comment]
the scheduler timers core allows repeated timers at the c level

**Comment by ObakeFilter** [comment]
> the scheduler timers core allows repeated timers at the c level

Care to share a code example I can use, for instance, if I want to use 'uuid_broadcast' every 2 minutes?

**Comment by mjerris** [comment]
https://freeswitch.org/confluence/plugins/servlet/mobile?contentId=6587042#content/view/6587042

**Comment by ObakeFilter** [comment]
> https://freeswitch.org/confluence/plugins/servlet/mobile?contentId=6587042#content/view/6587042

Thank you so much.
