### ISSUE TITLE
Freeswitch V1.10.1 and v1.10.7  Crashes with Segfault and out of memory errors.

### ISSUE THREAD

**Issue by Brendahnyaringita** [signalwire/freeswitch#1295]
**Describe the bug**
Freeswitch memory increases rapidly when calls increase to nearly 1000. When traffic drops, the memory continously increases and eventually Freeswitch crashes due to Out of Memory error.
I was initially at version1.10.1 but upgraded to latest version. The issues however persist.

**To Reproduce**
1. Push a batch of between 1000 calls, with a majority not picked.
2. Memory spikes and keeps increasing even when calls clear. Eventually it runs Out of Memory 
3. FreeSWITCH crashes

**Expected behavior**
Memory to stabilize after a while. 
**Package version or git hash**
 - Version [ 1.10.7]

**Trace logs**
I constantly get such segfault errors, and below is the link to the core damp.

[Tue Aug  3 13:36:39 2021] fs_cli[3495]: segfault at 0 ip 00007f6fd8db6ed0 sp 00007f6fd96e7ba8 error 4 in libedit.so.0.0.42[7f6fd8da1000+35000]
[Wed Aug  4 15:53:31 2021] fs_cli[8491]: segfault at 31381470 ip 00007f089fea9f64 sp 00007ffc7dea9cb0 error 4 in libc-2.17.so[7f089fe28000+1c3000]

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
https://pastebin.freeswitch.org/view/327fbd22

**Comment by andywolk** [comment]
What's your sofia-sip version? Have up updated it too?

**Comment by Brendahnyaringita** [comment]
Yes, I'm at master 
sofia-sip-1.13

**Comment by andywolk** [comment]
backtrace is useless as you don't have debugging symbols installed.
