### ISSUE TITLE
Crash caused by lua

### ISSUE THREAD

**Issue by 2954456878** [signalwire/freeswitch#1304]
**Describe the bug**
When I use lua scripts, freeswitch sometimes crashes

E.g：
luarun a.lua 1000 1000 a123456*

**To Reproduce**
Unable to reproduce

**Expected behavior**

**Package version or git hash**
FreeSWITCH Version 1.8.6~64bit ( 64bit)

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
[crash.txt](https://github.com/signalwire/freeswitch/files/6985733/crash.txt)

This is my Lua script
[lua.txt](https://github.com/signalwire/freeswitch/files/6985726/lua.txt)
```
(gdb) set pagination off
(gdb) set logging file /tmp/backtrace.log
(gdb) set logging on
Copying output to /tmp/backtrace.log.
(gdb) bt
(gdb) bt full
(gdb) info threads
(gdb) thread apply all bt
(gdb) thread apply all bt full
(gdb) set logging off
Done logging to /tmp/backtrace.log.
(gdb) quit
```

**Comment by seven1240** [comment]
please reproduce in master or 1.10.6. old versions not supported any more.
