### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#1314]
src/switch_core_media.c:2225:111: error: argument 2 of type ‘switch_core_media_flag_t[15]’ with mismatched bound [-Werror=array-parameter=]
 2225 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[SCMF_MAX])
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:143,
                 from src/switch_core_media.c:33:
./src/include/switch_core_media.h:200:111: note: previously declared as ‘switch_core_media_flag_t[]’
  200 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[]);
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2471: src/libfreeswitch_la-switch_core_media.lo] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1432: all] Error 2

GCC 11.2

**Comment by micmac1** [comment]
Try #1261

**Comment by ROBERT-MCDOWELL** [comment]
Thanks! but why it's not already on the master branch?
