### ISSUE TITLE
mod_sofia: gateway wont register using register-proxy with ip address if the realm does not have a valid dns entry. 

### ISSUE THREAD

**Issue by wmasilva** [signalwire/freeswitch#1315]
In current master version is not possible to register a gateway directly to a proxy with a realm that doesn't have a valid dns entry.  It doesn't reply to the the SIP/401 Unauthorized request.

In log i see:
```

2021-08-24 16:41:54.890282 [ERR] sofia_reg.c:2512 verify 1
2021-08-24 16:41:54.890282 [ERR] sofia_reg.c:2516 verify 2
2021-08-24 16:41:54.890282 [WARNING] sofia_reg.c:2823 Cannot locate any authentication credentials to complete an authentication request for realm '"lab.local"'

```

If the realm resolves to an address the register result is ok. 

I did a bisec between 8a40ba20bd77a612c29e2f152367ddc73b0c03aa (OK) -> Master (KO), the result: 

c41aa83b17e49f7bff44750fa815ec59a299fb12 is the first bad commit
commit c41aa83b17e49f7bff44750fa815ec59a299fb12
Author: Dragos Oancea <dragos@signalwire.com>
Date:   Thu May 13 13:49:09 2021 +0000

    [mod_sofia] fix md5 digest infoleak
    
    [mod_sofia] refactor IP checks with sip-dig
    
    [mod_sofia] add sipp-based unit-tests (use spawn_instead_of_system)

:040000 040000 1c0ac86c63e437b76e5f20ed90cfda513f32fde2 9cf14c72dc78855af7f1236331813c8696fd2d36 M	src

Configuration used to replicate the issue:
```

<gateway name="sol">
	<params>
		<param name="context" value="local"/>
		<param name="realm" value="lab.local"/>
		<param name="outbound-proxy" value="192.168.1.10:5060"/>
		<param name="register-proxy" value="192.168.1.10:5060"/>
		<param name="username" value="1002"/>
		<param name="password" value="10234"/>
		<param name="expire-seconds" value="300"/>
		<param name="register" value="true"/>
		<param name="ping" value="120"/>
		<param name="contact-in-ping" value="false"/>
	</params>
	<variables>
		<variable name="rtp_codec_negotiation" value="generous"/>
		<variable name="absolute_codec_string" value="PCMU,PCMA"/>
		<variable name="codec_string" value="PCMU,PCMA"/>
	</variables>
</gateway>
```
I've setup a DNS server with bind so i can stop it from resolving lab.local. 

Log with sip trace enable and the output of command sofia_dig:

[debug_registerKO.txt](https://github.com/signalwire/freeswitch/files/7040069/debug_registerKO.txt)
[debug_registerOK.txt](https://github.com/signalwire/freeswitch/files/7040070/debug_registerOK.txt)
[debug_registerOK_GIT8a40ba2.txt](https://github.com/signalwire/freeswitch/files/7040432/debug_registerOK_GIT8a40ba2.txt)

**Comment by crienzo** [comment]
This is to verify challenges are coming from an IP that is authorized to request it.

**Comment by wmasilva** [comment]
sure, but in this case should it verify against the IP in register and/or outbound proxy fields?  

This is new from this commit, is there a new parameter i miss out?

**Comment by wmasilva** [comment]
found it:  
if i set the gw-auth-acl i can set the static ip address. 

`<param name="gw-auth-acl" value="gwsol"/>`

and in acl:
```
<list name="gwsol" default="deny">
	<node type="allow" cidr="192.168.1.10/32"/>
</list>
```

Is this now the only way to have this setup?

Thanks.

**Comment by crienzo** [comment]
We are discussing if we should do this automatically.

**Comment by crienzo** [comment]
OK- we'll do something to allow this automatically.

**Comment by wmasilva** [comment]
perfect, thanks.

**Comment by dragos-oancea** [comment]
try commit 69cdaac60b89d1f71649efba6ba404bf2ce31775.

**Comment by wmasilva** [comment]
it's ok. Thanks.
