### ISSUE TITLE
Debian 11 (bullseye) release

### ISSUE THREAD

**Issue by keith24** [signalwire/freeswitch#1318]
**Is your feature request related to a problem? Please describe.**
Yeah, I'm running debian stable and I don't want to mess up my apt with packages from a different release.  

**Describe the solution you'd like**
A release for debian bullseye. 

**Describe alternatives you've considered**
Could install the buster version but don't want to fudge anything up. 

**Additional context**
```
# apt update
Hit:1 https://atl.mirrors.clouvider.net/debian bullseye InRelease
Hit:2 https://atl.mirrors.clouvider.net/debian bullseye-updates InRelease       
Hit:3 https://security.debian.org/debian-security bullseye-security InRelease   
Ign:4 http://files.freeswitch.org/repo/deb/debian-release bullseye InRelease    
Err:5 http://files.freeswitch.org/repo/deb/debian-release bullseye Release
  404  Not Found [IP: 2803:d000:fffe::174 80]
Reading package lists... Done
E: The repository 'http://files.freeswitch.org/repo/deb/debian-release bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Package version or git hash**
N/A

**Comment by andywolk** [comment]
There are no Debian 11 packages yet. But you can try building from source manually.

**Comment by TelephonyMan** [comment]
Hi keith24,

Did you try building from source on Debian 11? Please let us know what happened.

**Comment by keith24** [comment]
I didn't but I might later.

**Comment by lexxua** [comment]
Hi @andywolk , do Freeswitch team has some plans to update repositories to bullseye?
Thanks!

**Comment by crienzo** [comment]
Debian 11 support is in the works for cluecon.
