### ISSUE TITLE
suspect source code issue in sofia.c

### ISSUE THREAD

**Issue by VincentShia** [signalwire/freeswitch#1327]
hi there,
i found that in sofia.c, to launch addtional sofia message process threads requires msg_queue size be greater than msg_queue_threads size as stated below:
`void sofia_queue_message(sofia_dispatch_event_t *de)
{
...
	if ((switch_queue_size(mod_sofia_globals.msg_queue) > (SOFIA_MSG_QUEUE_SIZE * msg_queue_threads))) {
		launch++;
	}
...
}`

but since msg_queue_threads is timed by SOFIA_MSG_QUEUE_SIZE(1000), it seems almost impossible to happen(launch addtional threads) as 
switch_queue_size returns the number of queues rather than bytes.

check the definition of switch_queue_size and apr_queue_size:
`SWITCH_DECLARE(unsigned int) switch_queue_size(switch_queue_t *queue)
{
	return apr_queue_size(queue);
}`
...
`APU_DECLARE(unsigned int) apr_queue_size(apr_queue_t *queue) {
    return queue->nelts;	// +1 every time a new queue is being pushed, thus, measured in number of queues, not bytes
}`

so is this an issue or i just misunderstood the code?

**Comment by mjerris** [comment]
queue size is the number of elements in the queue
