### ISSUE TITLE
Config Fails - FS Sofia-Sip updated to 1.13.5 but Homebrew still has 1.13.4

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1329]
**Describe the bug**
Sofia-Sip was updated on FS to 1.13.5 but Homebrew still has 1.13.4. I get:
checking for sofia-sip-ua >= 1.13.5... configure: error: no usable sofia-sip; please install sofia-sip-ua devel package or equivalent. configure attached.

**To Reproduce**
run ./configure

**Comment by andywolk** [comment]
Take a look one more time. Should be fine now.

**Comment by MarioG-X** [comment]
Works now. Thanks!
