### ISSUE TITLE
Typo while reading the parameters for vad_test

### ISSUE THREAD

**Issue by TelephonyMan** [signalwire/freeswitch#1332]
This is a simple typo in the code.

https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_dptools/mod_dptools.c#L6288

"silence_ms" is misspelled as "sicence_ms". So this value will never take effect.

**Comment by seven1240** [comment]
can you submit a pr?

**Comment by TelephonyMan** [comment]
No, please go ahead and do it yourself. 
Last time I tried, I couldn't push any code.

**Comment by andywolk** [comment]
@TelephonyMan You need to create a fork, make a branch from master, make a change, commit to your fork and then make  a contribution creating a Pull Request to upstream repo master.
This is an example article: https://opensource.com/article/19/7/create-pull-request-github

**Comment by TelephonyMan** [comment]
Alright, let me try it again.

**Comment by TelephonyMan** [comment]
Ok, I have created the PR. 

https://github.com/signalwire/freeswitch/pull/1333

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/1333
