### ISSUE TITLE
Make fails in SRTP - implicit declaration of function 'asm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1335]
**Describe the bug**
Make fails in SRTP, make attached. Last commit is ee9214c6fb6bc01a2798dea3ca0153e3c85e8f97. Make completed good 7 days ago.

Messages:
In file included from src/switch_rtp.c:48:
In file included from /usr/local/src/freeswitch/libs/srtp/include/srtp_priv.h:52:
In file included from /usr/local/src/freeswitch/libs/srtp/crypto/include/rdbx.h:50:
/usr/local/src/freeswitch/libs/srtp/crypto/include/datatypes.h:176:5: error: implicit declaration of function 'asm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    asm("bswap %0" : "=r"(v) : "0"(v));
    ^
/usr/local/src/freeswitch/libs/srtp/crypto/include/datatypes.h:176:20: error: expected ')'
    asm("bswap %0" : "=r"(v) : "0"(v));
                   ^
/usr/local/src/freeswitch/libs/srtp/crypto/include/datatypes.h:176:8: note: to match this '('
    asm("bswap %0" : "=r"(v) : "0"(v));
       ^
2 errors generated.
make[1]: *** [src/libfreeswitch_la-switch_rtp.lo] Error 1
make: *** [all] Error 2

After research I added CFLAGS="-Wno-implicit-function-declaration" to configure which is not recommended and it only eliminated the C99 warning, other errors the same:

In file included from src/switch_rtp.c:48:
In file included from /usr/local/src/freeswitch/libs/srtp/include/srtp_priv.h:52:
In file included from /usr/local/src/freeswitch/libs/srtp/crypto/include/rdbx.h:50:
/usr/local/src/freeswitch/libs/srtp/crypto/include/datatypes.h:176:20: error: expected ')'
    asm("bswap %0" : "=r"(v) : "0"(v));
                   ^
/usr/local/src/freeswitch/libs/srtp/crypto/include/datatypes.h:176:8: note: to match this '('
    asm("bswap %0" : "=r"(v) : "0"(v));
       ^
1 error generated.
make[1]: *** [src/libfreeswitch_la-switch_rtp.lo] Error 1
make: *** [all] Error 2
 

**To Reproduce**
Steps to reproduce the behavior on macOS 11.5.2 Big Sur:
1. Download FS master.
2. ./bootstrap.sh
3. ./configure
4. make

**Expected behavior**
Make completes normally

**Package version or git hash**
 - Version 1.10.7 ee9214c6fb6bc01a2798dea3ca0153e3c85e8f97.

[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/7110117/07.FreeSWITCH.make.txt)

**Comment by zmmDinAc** [comment]
I have the same problem. Have you solved it?

**Comment by seven1240** [comment]
looks like macOS missing `byteswap.h`, ref: https://github.com/sgan81/apfs-fuse/issues/6

and `asm` is a gnu extension https://stackoverflow.com/questions/35090479/why-does-gcc-std-c99-treat-the-keyword-asm-as-a-function

**Comment by seven1240** [comment]
maybe related to this change when update the lib

```
- #if defined(__GNUC__) && defined(HAVE_X86)
+ #if defined(__GNUC__) && (defined(HAVE_X86) || defined(__x86_64__))
```

**Comment by seven1240** [comment]
I reverted the above line (datatypes.h:171) and seems it's working, @MarioG-X @zmmDinAc  can you confirm?

**Comment by MarioG-X** [comment]
Yes removing the test for x86_64 allows make to complete, but it is actually x86_64 so I don't know if that's the correct fix.

**Comment by MarioG-X** [comment]
Just tested on Big Sur and new Command Line Tools 13. Same problem, but at least nothing else wrong. Aside from this error it built and came up after my edit.

**Comment by andywolk** [comment]
Please take a look https://github.com/signalwire/freeswitch/pull/1361
