### ISSUE TITLE
[mod_av] invalid  record video call .mp4 file cannot be reproduced

### ISSUE THREAD

**Issue by wmasilva** [signalwire/freeswitch#135]
Hi,

in current master on debian buster recording video call with extension .mp4 is not working. 
The record is done and the file looks ok (size 3MB) but it cannot be open.

In debian jessie with same master revision it's ok.
I i think the caus of the issue is in the difference between versions of lib libx264.

debian buster: libx264-155
profile Constrained Baseline, level 4.1
264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0x1:0x111 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=10 qpmax=31 qpstep=4 ip_ratio=1.41 aq=1:1.00
2019-11-22 16:23:57.832389 [INFO] avformat.c:2574 use video codec implementation Video: h264 (libx264), yuv420p(pc, bt709/unknown/unknown), 640x480, q=10-31

debian jessie: libx264-142

profile Constrained Baseline, level 4.1
264 - core 142 r2431 a5831aa - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0x1:0x111 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=10 qpmax=31 qpstep=4 ip_ratio=1.41 aq=1:1.00
2019-11-22 18:39:03.058685 [INFO] avformat.c:2574 use video codec implementation Video: libx264, yuv420p, 1280x720, q=10-31

Attach full log on debian buster with current master
[debian_buster_record_mp4_issue.log](https://github.com/signalwire/freeswitch/files/3880749/debian_buster_record_mp4_issue.log)
 Version 1.10.2-dev git a4f0b2f 2019-11-21 20:09:14Z 64bit, using vanilla config with smal change in dialplan:

<extension name="test">
        <condition field="destination_number" expression="^123$">
                <action application="set" data="enable_file_write_buffering=false"/>
                <action application="record_session" data="/home/testrecord.mp4"/>
                <action application="bridge" data="user/1001@${domain_name}"/>
        </condition>
 </extension>

**Comment by wirelessmundi** [comment]
it records with version Version 1.10.1-release git f999022 2019-08-20 16:54:04Z 64bit.
I'm doing a git bisec to find out the problem.

**Comment by briankwest** [comment]
This is already fixed as I do it often in testing.  Update to the latest release, if the problem returns please reopen or file a new issue.
