### ISSUE TITLE
Freeswitch unstable Dockerfile cannot build as based on Debian Jessie

### ISSUE THREAD

**Issue by mitchcapper** [signalwire/freeswitch#1364]
**Describe the bug**
Building the master dockerfile fails as it is based on too old of a debian build.    It is possible (likely) it hasn't worked since Jul 23, 2019 when the mariadb 3 check was added.   The fail dep path is:

freeswitch-all -> freeswitch-meta-all -> freeswitch-mod-mariadb ->  libmariadb3

Jessie only goes up to mariadb2.

Will submit a PR to fix (switching to buster as that seems the preferred version anyway). 

Not sure if this was the cause in #154 as well but likely given the description.

**To Reproduce**
Try to build the master (unstable) dockerfile, will fail as package dependencies cannot be met.

**Expected behavior**
Succeed:)

**Comment by soroshsabz** [comment]
ITNOA

I have same issue
