### ISSUE TITLE
Make fails switch_core_cert.c:284:2: error: implicit declaration of function 'CRYPTO_mem_ctrl' is invalid with OpenSSL 3.0

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1367]
Update Dec 5: I created a PR for this.
**Describe the bug**
Make gets the error below. This did not occur 10 days ago on master when I wast testing something else.

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
  CC       src/libfreeswitch_la-switch_core_cert.lo
src/switch_core_cert.c:284:2: error: implicit declaration of function 'CRYPTO_mem_ctrl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
        ^
src/switch_core_cert.c:284:2: note: did you mean 'CRYPTO_memcmp'?
/usr/local/opt/openssl/include/openssl/crypto.h:443:5: note: 'CRYPTO_memcmp' declared here
int CRYPTO_memcmp(const void * in_a, const void * in_b, size_t len);
    ^
src/switch_core_cert.c:284:18: error: use of undeclared identifier 'CRYPTO_MEM_CHECK_ON'
        CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
                        ^
2 errors generated.
make[1]: *** [src/libfreeswitch_la-switch_core_cert.lo] Error 1

**To Reproduce**
normal build steps, bootstrap, config, make

**Expected behavior**
Make should complete
 successfully

**Package version or git hash**
 - master 1.10.7 601960eb44556e2a5faeba2bf5ba3520ec4b2cbb

Testing
Tested on 10.14.6 Mojave, 10.15.7 Catalina, and 11.6 Big Sur with Command Line Tools 13. FS had built fine 10 days ago (if I applied a temp fix for another issue).

**Comment by MasonLuo918** [comment]
Do you fix this？same problem

**Comment by MarioG-X** [comment]
This is now occurring in building links from feeswitch. It apparently has to do with openssl 3. The FreeSWITCH prerequisites now require openssl 1.1 AND 3.0 and 3.0 seems to now cause this. See this for solutions:
https://github.com/mumble-voip/mumble/issues/4266

**Comment by MarioG-X** [comment]
Builds OK now.
