### ISSUE TITLE
Freeswitch Debian Bullseye support

### ISSUE THREAD

**Issue by mneirynck** [signalwire/freeswitch#1383]
**Describe the bug**
I noticed in the latest commits that with Python3 you also added support for Bullseye, but that's where it fails.

When building FreeSWITCH either from source or from packages on Debian Bullseye it fails as the packages aren't found.
This is both in the debian-release and the debian-unstable repo
"Unable to find a source package for freeswitch"

**To Reproduce**
1. Add the GPG key and the repo lists:
deb http://files.freeswitch.org/repo/deb/debian-unstable/ bullseye main
deb-src http://files.freeswitch.org/repo/deb/debian-unstable/ bullseye main
2. Apt update
3. apt build-dep freeswitch
4. "Unable to find a source package for freeswitch" comes up

**Expected behavior**
The above should have installed the FreeSWITCH dependencies for building FreeSWITCH

**Package version or git hash**
 - Not applicable

**Comment by andywolk** [comment]
`apt build-dep freeswitch` does not work as there are no freeswitch packages pushed to the repos. Therefore apt can not figure out what dependencies to install. You will have to specify them manually until then.
