### ISSUE TITLE
configure fails - sofia-sip-ua >= 1.13.6... configure: error: no usable sofia-sip; even though Sofi-sip is installed

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1400]
**Describe the bug**
Release 1.10.7 during configure:
checking for sofia-sip-ua >= 1.13.6... configure: error: no usable sofia-sip; please install sofia-sip-ua devel package or equivalent.

This had been fine during weekly macOS test builds until now. Looks like homebrew still has 1.13.5.

**To Reproduce**
1. Download 1.10.17 onto macOS Big Sur.
2. run ./configure

**Expected behavior**
configure should complete successfully. Then expected make to fail on #1367 outstanding.

**Package version or git hash**
 - Version 1.10.7 release

**Comment by ObakeFilter** [comment]
Experiencing the same on Debian 10.

**Comment by andywolk** [comment]
@ObakeFilter update sofia to the latest

**Comment by ObakeFilter** [comment]
> @ObakeFilter update sofia to the latest

Getting the following error:
```
2021-11-08T14:37:18.619221070Z 2021-11-08 14:37:18.578801 0.00% [CRIT] switch_loadable_module.c:1750 Error Loading module /usr/local/freeswitch/mod/mod_sofia.so
2021-11-08T14:37:18.619226401Z **/usr/local/freeswitch/mod/mod_sofia.so: undefined symbol: ntatag_max_recv_requests_per_second**

```

**Comment by andywolk** [comment]
You need  Sofia-sip 1.13.6

**Comment by MarioG-X** [comment]
Can I use the 1.13.6 that is on Homebrew (NOT the freeswitch version which is out of date) for macOS? Better than having to add instructions to wiki to build Sofia from scratch.

**Comment by MarioG-X** [comment]
For anyone interested this issue: I looked at the formula for "brew install sofia-sip" which is not the documented signalwire/homebrew-signalwire/sofia-sip for macOS and it looks like it's downloaded from FreeSWITCH so I had to assume that is now the correct one. It now gets past configure but make dies due to #1367 that is still keeping macOS FreeSWITCH from building for months.

**Comment by MarioG-X** [comment]
Reopening since never got an answer as to use the homebrew Sofia-sip or the signalwire softs-sip which I thought had modifications.

**Comment by mjerris** [comment]
homebrew… if it’s not the right one please comment here

**Comment by MarioG-X** [comment]
Is it still "brew install signalwire/homebrew-signalwire/sofia-sip" or now "brew install sofia-sip" which is different?

**Comment by MarioG-X** [comment]
Pardon me for being confused but I still need to know which to use on macOS based on responses here:

1. Stop using homebrew and download from https://github.com/freeswitch/sofia-sip
2. "brew install signalwire/homebrew-signalwire/sofia-sip" which is out of date and causes this issue. Needs updating?
3. "brew install sofia-sip" which is 1.13.6 but is not from signalwire and may not have modifications.

Thanks for any help, this is one of multiple holdups on macOS.

**Comment by andywolk** [comment]
https://github.com/signalwire/homebrew-signalwire/pull/5

**Comment by andywolk** [comment]
Please test again.

**Comment by MarioG-X** [comment]
Sofia-sip from signalwire/homebrew now installs but can't fully build and test due to #1474.

**Comment by iamtalhaasghar** [comment]
> clone sofia lib, build, install: https://github.com/freeswitch/sofia-sip . if you have sofia installed from packages uninstall it.

This worked for me on Debian 11.
