### ISSUE TITLE
ks.h: No such file or directory

### ISSUE THREAD

**Issue by voztovoice** [signalwire/freeswitch#1406]
I can't compile FreeSWITCH 1.10.7 on CentOS 7

The problem is with mod_verto:

making all mod_verto
make[4]: Entering directory `/usr/src/freeswitch/src/mod/endpoints/mod_verto'
  CC       mod_verto_la-mod_verto.lo
**mod_verto.c:46:16: fatal error: ks.h: No such file or directory**
 #include "ks.h"
                ^
compilation terminated.
make[4]: *** [mod_verto_la-mod_verto.lo] Error 1
make[4]: Leaving directory `/usr/src/freeswitch/src/mod/endpoints/mod_verto'
make[3]: *** [mod_verto-all] Error 1
make[3]: Leaving directory `/usr/src/freeswitch/src/mod'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/freeswitch/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/freeswitch'
make: *** [all] Error 2
**Describe the bug**

**To Reproduce**
1. Using this example configuration...
2. Dial into conference using verto
3. Play my_problem_file.mp4 into conference
4. FreeSWITCH crashes

**Expected behavior**

**Package version or git hash**
 - Version [e.g. 1.10.4]

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
(gdb) set pagination off
(gdb) set logging file /tmp/backtrace.log
(gdb) set logging on
Copying output to /tmp/backtrace.log.
(gdb) bt
(gdb) bt full
(gdb) info threads
(gdb) thread apply all bt
(gdb) thread apply all bt full
(gdb) set logging off
Done logging to /tmp/backtrace.log.
(gdb) quit
```
is it a Kernel relate problem?

Any Hint?

**Comment by mougua** [comment]
I solved this problem by following 

```bash
git clone https://github.com/signalwire/libks
cd libks
cmake .  #cmake version 3.22.0
make && make install
export CPLUS_INCLUDE_PATH=/usr/include/libks
export C_INCLUDE_PATH=/usr/include/libks

#then make mod_verto
```
