### ISSUE TITLE
Handling RTCP SR resulting in gaps (and lateron internally dropped) egress RTP

### ISSUE THREAD

**Issue by ldr** [signalwire/freeswitch#1408]
Hi,

I experience issues in RTP streams emitted by FreeSWITCH gateways when they have looped several times through (the same) machine. I noticed that this occurs whenever an RTCP SR is received.

I created the following simple dialplan to reproduce the issue:

```
<include>
  <context name="test">
    <extension>
      <condition field="${sip_h_X-COUNTDOWN}" expression="^0$" break="on-true">
        <action application="answer"/>
        <action application="playback" data="tone_stream://%(251,0,1004);loops=-1"/>
      </condition>
      <condition field="${sip_h_X-COUNTDOWN}" expression="^(\d+)$" break="never">
        <action application="export" data="_nolocal_sip_h_X-COUNTDOWN=${expr($1 - 1)}"/>
        <anti-action application="export" data="_nolocal_sip_h_X-COUNTDOWN=10"/>
      </condition>
      <condition>
        <action application="bridge" data="sofia/test/1234@172.18.2.142"/>
      </condition>
    </extension>
  </context>
</include>
```

Using mostly vanilla sofia profile params and switch conf, soft timer, etc. All tests are done on bare metal.

As can be seen, it loops the call 10 times through itself and finally ends up in playing a tone_stream.

Attached PCAP shows a test of this loop: [vsd-150-vw654-lo-only-2.zip](https://github.com/signalwire/freeswitch/files/7428285/vsd-150-vw654-lo-only-2.zip)

When looking at the PCAP, these are the UDP ports in SDP offers of the INVITEs:

- 16026
- 19318
- 19994
- 18004
- 11232
- 12708
- 17654
- 16710 (etc going up)
- 18950 (so rtp is 2x relayed)
- 15348 (so rtp is 1x relayed)
- 15680 (so is dstport of original stream coming from tone_stream)

Then taking a look at the RTP stream analysis graph in Wireshark in reverse order, I see the following:

* udp.dstport == 15680 (original stream from tone_stream)
![vsd-150-iter-0](https://user-images.githubusercontent.com/77184/139120798-5b29e254-ebc6-4e4f-b37b-6f56eb130f73.png)
* udp.dstport == 15348 (1x relayed)
![vsd-150-iter-1](https://user-images.githubusercontent.com/77184/139120855-79ea21a0-c788-4d2f-932a-df9992b80c8c.png)
* udp.dstport == 18950 (2x relayed)
![vsd-150-iter-2](https://user-images.githubusercontent.com/77184/139120875-693129d2-8f20-4857-aa6c-3a871ac100e8.png)
* udp.dstport == 16710 (3x relayed)
![vsd-150-iter-3](https://user-images.githubusercontent.com/77184/139120894-608055a1-32eb-4d85-9353-5b84717f7aee.png)
* udp.dstport == 17654 (4x relayed)
![vsd-150-iter-4](https://user-images.githubusercontent.com/77184/139120912-1c9e638b-0848-4a98-b67b-48d6cc708ec6.png)
* udp.dstport == 12708 (5x relayed)
![vsd-150-iter-5](https://user-images.githubusercontent.com/77184/139120938-ceda99be-4a08-4694-b21b-fa46792d220f.png)
..etc

It starts as a little spike in forward delta, but that offset becomes larger and larger (dstport 15680, 15348, 18950) until FS decides to drop a frame (dstport 16710 and further).

Looking in Wireshark with filter `udp.dstport == 18950 or udp.dstport == 16710` you'll see at egress frame 3870 that it has marker bit set, it has time jump of 320 instead of regular 160 and also before it 2 frames came in. So one was internally dropped.

The spikes happen every five seconds, coinciding with receiving an RTCP SR. I see the RTCP handling in FS cli. I notice that the issue is gone when I disable the RTCP SR sending (and therefore receiving).

I found that if I change the following line in switch_rtp.c:

https://github.com/signalwire/freeswitch/blob/master/src/switch_rtp.c#L7812

from `goto recvfrom;` into `continue;`, that the issue goes away.

Not entirely sure, but it seems to me that the `goto recvfrom` instructs to handle the frame as RTP, while at line 7812 the RTCP handling is done and the next frame should be dealt with ?

I have tested this on several versions and also on latest master from this repo.

Looking forward to your reply.

Thanks & best regards,

Leon

**Comment by Len-PGH** [comment]
@dragos-oancea  Not sure if they are but I did meet with a potential FSE customer with Ryan for this one back in November https://signalwire.slack.com/archives/GC69W07K6/p1636384220202300

**Comment by dragos-oancea** [comment]
does it still manifest with RTCP mux off and doing RTCP the classic way ?

**Comment by dragos-oancea** [comment]
are you using a timer ?
https://github.com/signalwire/freeswitch/blob/master/src/switch_rtp.c#L7808 - does changing "!rtp_session->flags[SWITCH_RTP_FLAG_USE_TIMER]"  to "rtp_session->flags[SWITCH_RTP_FLAG_USE_TIMER]" (removing the logical negation) fix it too ?
