### ISSUE TITLE
Bug after compiling PHP-ESL

### ISSUE THREAD

**Issue by neoscopio** [signalwire/freeswitch#1411]
After compiling PHP-ESL and using the test script provided, I get an error:

```
root@pbx:/usr/src/freeswitch/libs/esl/php# ./single_command.php status
Command to run is: status
/usr/bin/php: symbol lookup error: /usr/lib/php/20190902/ESL.so: undefined symbol: _ZN13ESLconnectionC1EPKcS1_S1_

```
Only reference I could find online is a bug report from 2014:

https://lists.freeswitch.org/pipermail/freeswitch-users/2014-June/105706.html

But it's a JIRA bug report not available to me.

Running on an ubuntu 20.04 

PHP 7.4.3 (cli) (built: Oct 25 2021 18:20:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

Switch Version | 1.10.3 (64bit)

**Comment by nyash** [comment]
Debian 11.4.
PHP 7.4.30
 
Initially I tried compiling the extension by following the freeswitch confluence wiki and had the same error with the undefined symbol, but then I followed the steps from [#32](https://github.com/signalwire/freeswitch/pull/32) in order (appears to matter):

cd /usr/src/freeswitch/libs/esl
make phpmod
cd /usr/src/freeswitch/libs/esl/php
make install
sed -i -e 's/enable_dl = Off/enable_dl = On/g' /etc/php/7.4/cli/php.ini

After that the ESL lib works. 

I think this issue can be closed.
