### ISSUE TITLE
No hangup after txfax

### ISSUE THREAD

**Issue by denzs** [signalwire/freeswitch#143]
From: https://freeswitch.org/jira/browse/FS-10824 (contains sip-trace and some comments)

When txfax() is triggered via originate, the channel is not hungup after the fax transmission is completed.

After the t38-transmission a re-invite to g711a is received.

Freeswitch 1.6.13 replied with SIP/488 to the re-invite but in 1.6.19 Freeswitch sends 200 OK and the channel hangs....

freeswitch@fax-test> version 
FreeSWITCH Version 1.6.19-36-7a77e0b~64bit (-36-7a77e0b 64bit)

It is the same problem with the current git master.

See the attachment for a cli trace.

**Comment by briankwest** [comment]
Try 1.10.2 and reopen if the issue persists.

**Comment by Brettk80** [comment]
This still occurs on FreeSWITCH Version 1.10.11-release~64bit (-release 64bit)
