### ISSUE TITLE
crash freeswitch 1.10.2 at _nta_outgoing_timer(), why assert?

### ISSUE THREAD

**Issue by freeeyes** [signalwire/freeswitch#1435]
**Describe the bug**
freeswitch 1.10.2 core dump

#0  0x00007fb831261337 in raise () from /usr/lib64/libc.so.6
#1  0x00007fb831262a28 in abort () from /usr/lib64/libc.so.6
#2  0x00007fb83125a156 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fb83125a202 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x00007fb7d2757457 in _nta_outgoing_timer (sa=0x7fb7b0001e40) at nta.c:8897
#5  agent_timer (rm=<optimized out>, timer=timer@entry=0x7fb7b00028f0, agent=agent@entry=0x7fb7b0001e40) at nta.c:1250
#6  0x00007fb7d27bb27b in su_timer_expire (timers=timers@entry=0x7fb7b0000908, timeout=timeout@entry=0x7fb7abffed60, now=...) at su_timer.c:585
#7  0x00007fb7d27ad674 in su_base_port_run (self=0x7fb7b00008c0) at su_base_port.c:339
#8  0x00007fb7d27b24a0 in su_pthread_port_clone_main (varg=0x7fb7d25a5690) at su_pthread_port.c:343
#9  0x00007fb831cd5e65 in start_thread () from /usr/lib64/libpthread.so.0
#10 0x00007fb83132988d in clone () from /usr/lib64/libc.so.6

code at here:
static void
_nta_outgoing_timer(nta_agent_t *sa)
...
assert(!orq->orq_reliable && orq->orq_interval != 0);
...

**To Reproduce**
FreeSWITCH crashes

**Expected behavior**
invite

**Package version or git hash**
 - Version [e.g. 1.10.2]

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
#0  0x00007fb831261337 in raise () from /usr/lib64/libc.so.6
#1  0x00007fb831262a28 in abort () from /usr/lib64/libc.so.6
#2  0x00007fb83125a156 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fb83125a202 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x00007fb7d2757457 in _nta_outgoing_timer (sa=0x7fb7b0001e40) at nta.c:8897
#5  agent_timer (rm=<optimized out>, timer=timer@entry=0x7fb7b00028f0, agent=agent@entry=0x7fb7b0001e40) at nta.c:1250
#6  0x00007fb7d27bb27b in su_timer_expire (timers=timers@entry=0x7fb7b0000908, timeout=timeout@entry=0x7fb7abffed60, now=...) at su_timer.c:585
#7  0x00007fb7d27ad674 in su_base_port_run (self=0x7fb7b00008c0) at su_base_port.c:339
#8  0x00007fb7d27b24a0 in su_pthread_port_clone_main (varg=0x7fb7d25a5690) at su_pthread_port.c:343
#9  0x00007fb831cd5e65 in start_thread () from /usr/lib64/libpthread.so.0
#10 0x00007fb83132988d in clone () from /usr/lib64/libc.so.6
#0  0x00007fb831261337 in raise () from /usr/lib64/libc.so.6
No symbol table info available.
#1  0x00007fb831262a28 in abort () from /usr/lib64/libc.so.6
No symbol table info available.
#2  0x00007fb83125a156 in __assert_fail_base () from /usr/lib64/libc.so.6
No symbol table info available.
#3  0x00007fb83125a202 in __assert_fail () from /usr/lib64/libc.so.6
No symbol table info available.
#4  0x00007fb7d2757457 in _nta_outgoing_timer (sa=0x7fb7b0001e40) at nta.c:8897
        orq = 0x7fb7b00f3e50
        trying = 4
        completed = 7
        rq = {{q_tail = 0x7fb7abffec88, q_head = 0x0, q_length = 0, q_timeout = 0}}
        terminated = 0
        total = 18
        now = <optimized out>
        retransmitted = 1
        timeout = 0
        destroyed = 2361183241434822607
        pending = 10
#5  agent_timer (rm=<optimized out>, timer=timer@entry=0x7fb7b00028f0, agent=agent@entry=0x7fb7b0001e40) at nta.c:1250
        now = <optimized out>
        next = <optimized out>
        latest = <optimized out>
        __func__ = "agent_timer"
#6  0x00007fb7d27bb27b in su_timer_expire (timers=timers@entry=0x7fb7b0000908, timeout=timeout@entry=0x7fb7abffed60, now=...) at su_timer.c:585
        f = 0x7fb7d2756600 <agent_timer>
        n = 0
        __PRETTY_FUNCTION__ = "su_timer_expire"
#7  0x00007fb7d27ad674 in su_base_port_run (self=0x7fb7b00008c0) at su_base_port.c:339
        now = <optimized out>
        tout = 15000
        tout2 = 0
        __PRETTY_FUNCTION__ = "su_base_port_run"
#8  0x00007fb7d27b24a0 in su_pthread_port_clone_main (varg=0x7fb7d25a5690) at su_pthread_port.c:343
        arg = 0x0
        task = {{sut_port = 0x7fb7b00008c0, sut_root = 0x7fb7b0001130}}
        zap = 1
#9  0x00007fb831cd5e65 in start_thread () from /usr/lib64/libpthread.so.0
No symbol table info available.
#10 0x00007fb83132988d in clone () from /usr/lib64/libc.so.6

**Comment by crienzo** [comment]
Try in FreeSWITCH 1.10.7. We've moved sofia-sip outside of the FreeSWITCH repository. If this issue still occurs, open the bug in https://github.com/freeswitch/sofia-sip
