### ISSUE TITLE
mod_conference no audio output when smode is SWITCH_MEDIA_FLOW_SENDONLY

### ISSUE THREAD

**Issue by LarryHemenway** [signalwire/freeswitch#1437]
**Describe the bug**
conference_loop_output is not invoked when smode is SWITCH_MEDIA_FLOW_SENDONLY. I believe this logic in mod_conference is the problem.

		switch_media_flow_t audio_flow = switch_core_session_media_flow(session, SWITCH_MEDIA_TYPE_AUDIO);

		if (switch_channel_test_flag(channel, CF_AUDIO) && (audio_flow == SWITCH_MEDIA_FLOW_SENDRECV || audio_flow == SWITCH_MEDIA_FLOW_RECVONLY)) {
			conference_loop_output(&member);
		} else {

Originally, I believed that SWITCH_MEDIA_FLOW_RECVONLY should be SWITCH_MEDIA_FLOW_SENDONLY switch_core_session_media_flow reads the smode (send mode). 

I now believe we should ignore the audio_flow direction and invoke conference_loop_output regardless because it both starts the input thread and handles the output processing. For SENDONLY, we need output processing. For RECVONLY we need the input thread. For SENDRECV we need both. Alternatively someone could break up starting of input from output and be more intelligent about what to start.

**To Reproduce**
When setting up a call, pass in an sdp offer with recvonly. FreeSWITCH responds with an answer of sendonly, but never sends audio. 

**Expected behavior**
When FreeSWITCH responds with an answer of sendonly it should originate audio to the client.

**Package version or git hash**
FreeSWITCH Version 1.10.8-dev~64bit ( 64bit)

**Trace logs**
Problem seems to have been introduced with [this commit](https://github.com/signalwire/freeswitch/commit/badd59d609b5d5583c01d543e0d6b3a9cb365df1?diff=split
). Line 2481.

**backtrace from core file**
N/A

**Comment by LarryHemenway** [comment]
I think there is more to this issue. With the original code, this situation fails:



    Client1 ---offer=recvonly--> FS
    Client1 <--answer=sendonly-- FS
                                 FS <--offer=sendrecv-- Client2
                                 FS --anser=sendrecv--> Client2
                                 FS <---audio---------- Client2
                     (FS does not pass audio to client1)

If I update, the above scenario works, but this one fails:

    Client1 ---offer=sendonly--> FS
    Client1 <--answer=recvonly-- FS
                                 FS <--offer=sendrecv-- Client2
                                 FS --anser=sendrecv--> Client2
    Client1 ----------audio----> FS
                     (FS does not pass audio to client2)

It should not have any effect, but client2 is using webrtc and client 1 is sending a plain sdp.

**Comment by LarryHemenway** [comment]
I think the issue is that the conference_loop_output invokes conference_loop_launch_input.  

In other words, conference_loop_output must be invoked regardless of the audio direction because it is responsible for both starting the input thread and being the output thread.

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/pull/1568
