### ISSUE TITLE
Compilation with GCC 11.2.1

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#1440]
Hi,

had a compile error on Fedora 35 (CentOS equivalent) Gcc 11.2.1

  CC       libs/libnatpmp/libfreeswitch_la-getgateway.lo
  CXX      src/switch_cpp.lo
  CXXLD    libfreeswitch.la

*** Warning: Linking the shared library libfreeswitch.la against the
*** static library libs/libvpx/libvpx.a is not portable!
Making all in .
make[2]: Entering directory '/home/src/freeswitch'
  CC       src/freeswitch-switch.o
  CCLD     freeswitch
/usr/bin/ld: ./.libs/libfreeswitch.so: undefined reference to `pthread_mutexattr_setrobust                                                                                                                                                    _np'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1994: freeswitch] Error 1
make[2]: Leaving directory '/home/src/freeswitch'
make[1]: *** [Makefile:3716: all-recursive] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1448: all] Error 2

Any idea?

thanks

**Comment by ROBERT-MCDOWELL** [comment]
apparently it comes from libvpx

**Comment by andywolk** [comment]
What's your linux kernel version?

**Comment by ROBERT-MCDOWELL** [comment]
kernel 5.15.2-rt

**Comment by ROBERT-MCDOWELL** [comment]
I just recompiled the kernel but still gets the same error not with libvpx but with others

/usr/bin/ld: ./.libs/libfreeswitch.so: undefined reference to `pthread_mutexattr_setrobust                                                                                                                                                    _np'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2077: tone2wav] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: ./.libs/libfreeswitch.so: undefined reference to `pthread_mutexattr_setrobust                                                                                                                                                    _np'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2038: fs_encode] Error 1
/usr/bin/ld: ./.libs/libfreeswitch.so: undefined reference to `pthread_mutexattr_setrobust                                                                                                                                                    _np'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2071: fs_tts] Error 1
make[2]: Leaving directory '/home/src/freeswitch'
make[1]: *** [Makefile:3716: all-recursive] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1448: all] Error 2

**Comment by ROBERT-MCDOWELL** [comment]
@andywolk
ok I think the problem comes from freeswitch builtin apr and apr-util folder which are too old (1.2.6 for apr). I tried to replace these folder with the new one and it seems that the issue went away.

**Comment by ROBERT-MCDOWELL** [comment]
@andywolk 
I just reset my clone repo to get the apr and apr-util again and now it compiles fine (with all the other PR I sent)
closing this issue.

**Comment by mjerris** [comment]
upgrading apr will lead to memory corruption and crashing.  apr memory pools are not threadsafe in the apr tree.
