### ISSUE TITLE
Bug/Question: No early media (video) on ring groups

### ISSUE THREAD

**Issue by pergolafabio** [signalwire/freeswitch#1445]
Hi,

I have an door entry (intercom), registered as SIP end point, for testing i registered some linphone clients as sip users

When i call from my door entry intercom to a single extension, i can see early media (video) this is inluced on the 183 session... so far so good... so i can see who actually  pressed the door button on my intercom, before i answer/pickup the call

I now created a ring group, added some sip extensions... when i call the group , i dont see any video anymore?

what am i missing? is this a bug? Or does some script needs to be changed?

help is appreciated!!

thnx in advance

**Comment by leasual** [comment]
> Hi,
> 
> I have an door entry (intercom), registered as SIP end point, for testing i registered some linphone clients as sip users
> 
> When i call from my door entry intercom to a single extension, i can see early media (video) this is inluced on the 183 session... so far so good... so i can see who actually pressed the door button on my intercom, before i answer/pickup the call
> 
> I now created a ring group, added some sip extensions... when i call the group , i dont see any video anymore?
> 
> what am i missing? is this a bug? Or does some script needs to be changed?
> 
> help is appreciated!!
> 
> thnx in advance



> 

Hi @pergolafabio Have you solve this problem? Can you share your solution?

**Comment by pergolafabio** [comment]
Hi, no, still no solution, you any idea?
