### ISSUE TITLE
Freeswitch High CPU consumption in conference

### ISSUE THREAD

**Issue by Badareenadh** [signalwire/freeswitch#1455]
Freeswitch process is taking around 4-5% for each participant when adding the participant to a conference with OPUS codec(48000 rate and 20ms).

Upon debugging the issue we noticed FreeSwitch is consuming the CPU while doing the codec translation. For a conference member it is converting the inbound RTP frame from OPUS to PCMU and while sending it is converting from PCMU to OPUS.

Is there any way we can stop the codec translation in this case?

OS:
CentOS Linux release 8.4.2105

**Package version or git hash**
FreeSwitch version: 1.10.3-release~64bit ( 64bit)

**Comment by crienzo** [comment]
Conferences require transcoding no matter what.

**Comment by Badareenadh** [comment]
Hi crienzo, 

Could you please let us know , How can we better scale the conference module with more number of participants? 

Right now, it is taking 60-70% of CPU for 10 participants in a single session. when initiated multiple sessions it is consuming more CPU in the box.

**Comment by crienzo** [comment]
Please consult the mailing list or the community slack. This is not a bug.
