### ISSUE TITLE
Freeswitch is taking around 60-70% of CPU for 10 participants in a single conference session with OPUS codec(48000 rate and 20ms)

### ISSUE THREAD

**Issue by ramuk448** [signalwire/freeswitch#1456]
We noticed FreeSwitch is consuming more CPU while doing the codec translation from OPUS TO PCMU for conference session. Could you please let us know , How can we better scale the conference module with more number of participants ? 

OS:
CentOS Linux release 8.4.2105

Package version or git hash
FreeSwitch version: 1.10.3-release~64bit ( 64bit)

**Comment by crienzo** [comment]
Please consult the mailing list or our community slack. This is not a bug.
