### ISSUE TITLE
macOS make for libks fails error: use of undeclared identifier 'CRYPTO_MEM_CHECK_ON' CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON) W/OpenSSL 3.0

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1461]
Update Dec 5: I modified libks from homebrew/freeswitch with the patch from crienzo from March below and it allowed libks to be built. So it's good.

Update Nov 28: This appears to have been addressed Feb 23 in libks ks_ssl.c by crienzo: https://github.com/signalwire/libks/commit/3493e9c952964c80e402aa0497891d57dc5f8d40 but was never synced with signalwire/homebrew-signalwire/libks which references libks 1.1 in files.freeswitch.org, I also looked at _libks 1.3 there and it also does not have the fix_. This appears to be the same problem affecting #1367.

Describe the bug
brew install signalwire/homebrew-signalwire/libks gets the error below. This appears identical to #1367.  It apparently has to do with openssl 3. The FreeSWITCH prerequisites now require openssl 1.1 AND 3.0 and 3.0 seems to now cause this. See this for possible solutions: mumble-voip/mumble#4266. This also causes brew install signalwire/homebrew-signalwire/signalwire-c to fail with libks messages.

See attachment for complete message:
[libks.txt](https://github.com/signalwire/freeswitch/files/7605039/libks.txt)

/tmp/libks-20211125-29993-1tbmwrb/libks/src/ks_ssl.c:134:18: error: use of undeclared identifier 'CRYPTO_MEM_CHECK_ON'
        CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
                        ^
1 error generated.
make[2]: *** [CMakeFiles/ks.dir/src/ks_ssl.c.o] Error 1

To Reproduce
brew install signalwire/homebrew-signalwire/libks IMPORTANT NOTE: If libks was already installed you must "brew remove libks" first to force it to rebuild.

Expected behavior
Make should complete successfully

Release 1.10.7 and master
Testing
Tested on 10.15.7 Catalina, 11.6 Big Sur and 12.0 Monterey with Command Line Tools 13.

**NOTE:** I did a grep and only found it in one file, not the ones with the error:
mario@FS-Big-Sur freeswitch 20211125-104521 % grep -r CRYPTO_MEM_CHECK_ON *
src/switch_core_cert.c:	CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);

**Comment by MarioG-X** [comment]
Update Dec 5: I modified libks from homebrew/freeswitch with the patch from crienzo from March below and it allowed libks to be built. So it's good.

**Comment by Egbert8527** [comment]
I has same problem

**Comment by MarioG-X** [comment]
More reports: https://github.com/signalwire/homebrew-signalwire/issues/1

**Comment by andywolk** [comment]
See https://github.com/signalwire/freeswitch/pull/1498
https://github.com/signalwire/homebrew-signalwire/pull/2

**Comment by andywolk** [comment]
Should be fine now.

**Comment by MarioG-X** [comment]
libks from signalwire/homebrew now installs but can't fully build and test due to #1474.
