### ISSUE TITLE
Formulas out of date in /signalwire/homebrew-signalwire/tree/master/Formula

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1464]
**Describe the bug**
Some formulas are out of date and some are obsolete causing build issues. These are required to build from source to add functionality like flite or work on run-time issues which can't be done with the homebrew version of Freeswitch. 
https://github.com/signalwire/homebrew-signalwire/tree/master/Formula

Referencing previous versions of libs:
libks
signalwire-c
sofia-sip. <- possible removal since it's now installed via "brew install sofia-sip"

Possible removal:
ilbc
libvpx <- now part of standard homebrew
libyuv

**Comment by seven1240** [comment]
the intree libvpx has custom patches not yet accepted by upstream.

**Comment by MarioG-X** [comment]
Thanks for responding, unfortunately I don't know what intree is. It's been 4 months with no successful build on macOS due to libks missing https://github.com/signalwire/libks/commit/3493e9c952964c80e402aa0497891d57dc5f8d40, #1367 and #1461. I did my first PR then made a small change in #1288 which is only a warning.

**Comment by MarioG-X** [comment]
signalwire/homebrew libks Sofia-sip and signalwire-c have been updated today to download correct versions.
