### ISSUE TITLE
Keep parsing commented 'x-pre-process' settings

### ISSUE THREAD

**Issue by wasphin** [signalwire/freeswitch#1465]
**Describe the bug**
The `freeswitch` keep parsing commented `x-pre-process` settings.

**To Reproduce**
1. Use configuration under `conf/vanilla`, edit the `vars.xml`, comment the `stun-set` related settings:
    ```xml
    <!-- <X-PRE-PROCESS cmd="stun-set" data="external_rtp_ip=stun:stun.freeswitch.org"/> -->
    <!-- <X-PRE-PROCESS cmd="stun-set" data="external_sip_ip=stun:stun.freeswitch.org"/> -->
    ```
2. Set `external_rtp_ip` and `external_sip_ip` to `local_ip_v4`:
    ```xml
    <X-PRE-PROCESS cmd="set" data="external_rtp_ip=$${local_ip_v4}"/>
    <X-PRE-PROCESS cmd="set" data="external_sip_ip=$${local_ip_v4}"/>
    ```
3. Start `freeswitch` with `-nonat`.

**Expected behavior**
`freeswitch` does not check the `stun-set` part.

**Package version or git hash**
 - Version 1.10.7

**Trace logs**
```
2021-11-30 03:40:09.756872 0.00% [INFO] switch_event.c:713 Activate Eventing Engine.
2021-11-30 03:40:09.767519 0.00% [WARNING] switch_event.c:683 Create additional event dispatch thread 0
2021-11-30 03:40:19.797041 0.00% [ERR] switch_stun.c:900 STUN Failed! [Timeout]
2021-11-30 03:40:19.797105 0.00% [ERR] switch_xml.c:175 stun-set failed.
```

**Comment by seven1240** [comment]
X-PRE-PROCESS is Pre process, it runs before the real XML parser works. you can comment that by renaming it to any string  FreeSWITCH doesn't understand so it can be ignored. e.g.

`xX-PRE-PROCESS`
`no-X-PRE-PROCESS`

**Comment by wasphin** [comment]
Thanks @seven1240, also find this:
> Standard XML comments have no effect on Pre-Process commands. If you want to comment out a Pre-Process Command you can replace X-PRE-PROCESS with X-NO-PRE-PROCESS

https://freeswitch.org/confluence/display/FREESWITCH/Understanding+the+Configuration+Files#UnderstandingtheConfigurationFiles-Pre-ProcessDirectives
