### ISSUE TITLE
ReINVITE break transcoding

### ISSUE THREAD

**Issue by fulhade** [signalwire/freeswitch#1484]
**Describe the bug**

I'm doing transcoding from Opus to PCMA. "A" side offer Opus, "B" side accept PCMA only. When B do reinvite (hold or toggle camera), FreeSWITCH reinvite "A" side with PCMA. Things break even if "B" side support Opus (Opus-Opus, no transcoding). FreeSWITCH reinvite "A" with Opus and payload type number for Opus not negotiated on "A" side, and call fail after awhile.

**To Reproduce**

I'm doing this on same sip_profile (external) with minimum config template. Same thing happens with internal/external or vice versa. 

UAC A=Opus - UAC B=PCMA
1. vars.xml `<X-PRE-PROCESS cmd="set" data="global_codec_prefs=OPUS,PCMU,PCMA,VP8,VP9"/>`
2. vars.xml `<X-PRE-PROCESS cmd="set" data="rtp_pass_codecs_on_stream_change=true"/>`
3. external.xml: `<param name="inbound-late-negotiation" value="false"/> `//same thing happens with "true"
4. dialplan `<action application="export" data="nolocal:absolute_codec_string=PCMA"/> `& bridge
5. On reinvite from "B", FS do reinvite toward A with PCMA and "A" reject with "415 Unsupported Media Type", as it did invite with Opus only.

I experimented with many different options, early, late, inbound/outbound codec pref, absolute... In one case, inbound pref Opus, outbound pref PCMA, late off and only bridge, FS send reinvite to "B" without m= line!

Even if I fake replay from "B", to support Opus as 2nd codec, but accept PCMA. Or connect "A" & "B" with Opus only. On reinvite from FS to "A", FS change payload type number to his own, disregarding previously negotiated PT. Some end points, like Zoiper5 on reinvite with new PT number, replay with old PT number and call drop after some timer.

**Expected behavior**
FreeSWITCH should create reinvite based on already negotiated codec (and their parameters) and only add diff, like media direction change, new codec, or new m= line.

**Package version or git hash**
 - Version 1.10.8 / master

**Trace logs**
https://pastebin.freeswitch.org/view/07be8257

**Comment by anthmFS** [comment]
Can you reproduce this again on the default configs but enable sip trace "sofia global siptrace on"
When you set absolute_codec_string don't do this deprecated method, instead add it to your target dial string.
{absolute_codec_string=PCMA}sofia/internal/user@domain.com

**Comment by fulhade** [comment]
I have registered two UAC. 1000 (Zoiper5) and 1001 (Linphone)

1st test:
1000 offer only Opus. 1001 accept only PCMA.
vars.xml `<X-PRE-PROCESS cmd="set" data="rtp_pass_codecs_on_stream_change=true"/>` Without this, reinvite will not be propagated on other side. I need this because of video on/off
dialplan/default.xm, under "Local_Extensions": `<action application="bridge" data="{absolute_codec_string=PCMA}user/${dialed_extension}@${domain_name}"/>`

"sofia global siptrace on" https://pastebin.freeswitch.org/view/d2d5d980 
Zoiper5 replay with 415 Unsupported Media Type. https://ibb.co/Pxw6JGj

2nd test: 1000 and 1001 offer/accept only opus. I just replace PCMA with Opus in absolute codec string. FreeSWITCH reinvite 1000 with Opus payload type number 102 and Zoiper replay with PT number 106 (because that was negotiated on first invite).
https://pastebin.freeswitch.org/view/8a913011
FreeSWITCH reinvite with PT 102: https://ibb.co/gZRQtsV
Zoiper 200 OK with PT 106: https://ibb.co/tD0fRTc

**Comment by fulhade** [comment]
I will try to explain a little better what the problem is. According to RFC3264 which defines SOA, after a session is established, any session change should respect the previously agreed parameters. The problem I am experiencing manifests itself like this. Inbound INVITE offer SDP with: m = audio 8000 RTP / AVP 106 102. 106 for Opus and 102 for G726-32. [L32](https://pastebin.freeswitch.org/view/062922aa#L23) After that, FS accepts with 200 OK and m = audio 28152 RTP / AVP 106 101. 106 for Opus and 101 for DTMF. [L562](https://pastebin.freeswitch.org/view/062922aa#L562)

The problem arises with reINVITE (which can happen either due to hold or changing the codec on the other side). FS reINVITE UA on inbound channel with m = audio 28152 RTP / AVP 102 101. Where 102 Opus and 101 DTMF. [L702](https://pastebin.freeswitch.org/view/062922aa#L702)

This is not by RFC and it often break UA. https://datatracker.ietf.org/doc/html/rfc3264#section-8.3.2 

   The list of media formats used in the session MAY be changed.  To do
   this, the offerer creates a new media description, with the list of
   media formats in the "m=" line different from the corresponding media
   stream in the previous SDP.  This list MAY include new formats, and
   MAY remove formats present from the previous SDP.  However, in the
   case of RTP, **the mapping from a particular dynamic payload type
   number to a particular codec within that media stream MUST NOT change
   for the duration of a session**.  For example, if A generates an offer
   with G.711 assigned to dynamic payload type number 46, payload type
   number 46 MUST refer to G.711 from that point forward in any offers
   or answers for that media stream within the session.  However, it is
   acceptable for multiple payload type numbers to be mapped to the same
   codec, so that an updated offer could also use payload type number 72
   for G.711.
      **The mappings need to remain fixed for the duration of the session**
      because of the loose synchronization between signaling exchanges
      of SDP and the media stream.
	  
	  
As I suspected, the problem is only with codecs assigned to dynamic payload type number.

FreeSWITCH should not use PT number offered or accepted by UA for any other codec except already offered/accepted.
FreeSWITCH should not change the session by changing the PT number of an already agreed codec that uses the PT number from the dynamic range. Or if it does, to work in a way to keep the previous list and add a new PT number (if the number has not already been used).

Also, there is no reason to use different PT number for the same codec in inbound and outbound channel that are bridged. Because of this, we force FS to do unnecessary rewriting of RTP headers from one PT to another.

https://pastebin.freeswitch.org/view/062922aa

Given trace is just convenient example I made with Zoiper and Linphone. I have experienced this issue with others UA. Things are getting worse as more users start using video. Just hold could be resolved by blocking reinvite. But need to turn on camera and propagate that to other side... I believe we will see more and more of this same issue.

In the end, it doesn't matter who is right. I'm looking for a way to overcome this problem. As I can only influence FS and adapt to end users...

**Comment by anthmFS** [comment]
Try this patch 

[payload.diff.txt](https://github.com/signalwire/freeswitch/files/7730820/payload.diff.txt)

**Comment by dragos-oancea** [comment]
@fulhade  can you test with the last master branch ? 
https://github.com/signalwire/freeswitch/commit/6c87ed491597fb5e30935d8309aa7e0c3aa9e18f

**Comment by dragos-oancea** [comment]
@anthmFS .

thx @fulhade .

**Comment by hpuzz** [comment]
@fulhade How to mkae freeswitch transfer an re-invite message?I send an re-invite message to freeswitch,but it does not transfer the message to the other leg.Thanks.
