### ISSUE TITLE
Messages "check_subs: internal is passive, skipping"

### ISSUE THREAD

**Issue by ot-i-to** [signalwire/freeswitch#1486]
Please clarify what this message means?
2021-12-16 23:54:16.631735 99.40% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping
2021-12-16 23:54:46.671727 99.57% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping
2021-12-16 23:55:16.731733 99.60% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping
2021-12-16 23:55:46.771809 99.63% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping
2021-12-16 23:56:16.811736 99.53% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping
2021-12-16 23:56:46.851737 99.60% [WARNING] sofia_presence.c:5076 check_subs: internal is passive, skipping

<profile name="internal">
  <gateways>
    <X-PRE-PROCESS cmd="include" data="gateways/*.xml"/>
  </gateways>
  <aliases>
  </aliases>
  <domains>
    <domain name="all" alias="false" parse="false"/>
  </domains>
  <settings>
    <param name="debug" value="7"/>
    <param name="sip-trace" value="no"/>
    <param name="sip-capture" value="no"/>
    <param name="rfc2833-pt" value="101"/>
    <param name="pass-rfc2833" value="true"/>
    <param name="dtmf-type" value="rfc2833"/>
    <param name="liberal-dtmf" value="true"/>
    <param name="dtmf-duration" value="2000"/>
    <param name="dialplan" value="XML"/>
    <param name="context" value="public"/>
    <param name="inbound-codec-prefs" value="$${global_codec_prefs}"/>
    <param name="outbound-codec-prefs" value="$${outbound_codec_prefs}"/>
    <param name="hold-music" value="$${hold_music}"/>
    <param name="auto-jitterbuffer-msec" value="120"/>
    <param name="rtp-timer-name" value="soft"/>
    <param name="enable-100rel" value="true"/>
    <param name="send-display-update" value="false"/>
    <param name="user-agent-string" value="fs36"/>
    <param name="username" value="fs36"/>
    <param name="t38-passthru" value="true"/>
    <param name="inbound-codec-negotiation" value="generous"/>
    <param name="nonce-ttl" value="60"/>
    <param name="auth-calls" value="false"/>
    <param name="inbound-late-negotiation" value="true"/>
    <param name="inbound-zrtp-passthru" value="true"/>
    <param name="rtp-ip" value="10.10.10.10"/>
    <param name="sip-ip" value="10.10.10.10"/>
    <param name="sip-port" value="1234"/>
    <param name="bind-params" value="transport=udp"/>
    <param name="stun-enabled" value="false"/>
    <param name="media_timeout" value="45"/>
    <param name="media_hold_timeout" value="1800"/>
    <param name="rtp-autoflush-during-bridge" value="true"/>
    <param name="rtp-rewrite-timestamps" value="true"/>
    <param name="suppress-cng" value="false"/>
    <param name="disable-transfer" value="true"/>
    <param name="enable-3pcc" value="false"/>
    
    <param name="max-recv-requests-per-second" value="100000"/>
  </settings>
</profile>

- Version of FreeSWITCH 1.10.7

**Comment by dragos-oancea** [comment]
It refers to the profile named "internal". It's inferred that is passive because the presence type is not PRES_TYPE_FULL.

```                                        } else if (!strcasecmp(var, "manage-presence")) {
                                                if (val && !strcasecmp(val, "passive")) {
                                                        profile->pres_type = PRES_TYPE_PASSIVE;

                                                } else if (val && !strcasecmp(val, "pnp")) {
                                                        profile->pres_type = PRES_TYPE_PNP;
                                                } else if (switch_true(val)) {
                                                        profile->pres_type = PRES_TYPE_FULL;
                                                } else {
                                                        profile->pres_type = 0;
                                                }

[]

```                if (profile->pres_type != PRES_TYPE_FULL) {
                        if (mod_sofia_globals.debug_presence > 0) {
                                switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_WARNING, "check_subs: %s is passive, skipping\n", (char *) profile->name);
                        }
                        return;
                ```
```
https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Configuration+Files

**Comment by dragos-oancea** [comment]
```   <param name="debug-presence" value="0"/>``` - use this to turn off Presence debug logging.
