### ISSUE TITLE
AUDIO RTP REPORTS ERROR: [Socket Error!]

### ISSUE THREAD

**Issue by burne-muz** [signalwire/freeswitch#1487]
[ERR] switch_rtp.c:4627 Error Starting timer [soft] 160 bytes per 20ms, async RTP disabled
[ERR] switch_core_media.c:9785 AUDIO RTP REPORTS ERROR: [Socket Error!]

This error often occurs when I stress test FreeSWITCH-1.10.7 using SIPP, but not when I do the same with FreeSWITCH-1.6.20
Does anybody know what's going on here?

The operating parameters of SIPP is：
./sipp -r 5 -l 200 -m 10000 -d 40s -s r60720113 -rtp_echo 11.8.75.147:16066

The dialplan for FreeSWITCH is:
<context name="public">
  <extension name="sipp_test">
    <condition field="caller_id_name" expression="^sipp$">
      <action application="sleep" data="${expr(randomize(&x);ceil(random(2000,10000,&x)))}"/>
      <action application="sched_hangup" data="+${expr(randomize(&x);ceil(random(4,35,&x))) NORMAL_CLEAR}"/>
      <action application="answer"/>
      <action application="record" data="$${recordings_dir}/${uuid}.wav"/>
    </condition>
  </extension>
</context>

freeswitch.log
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [NOTICE] switch_channel.c:1123 New Channel sofia/external/sipp@11.8.75.89:5060 [27595300-6dbe-4fb8-8589-cd958b201309]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_NEW (Cur 100 Tot 4913)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [INFO] sofia.c:10467 sofia/external/sipp@11.8.75.89:5060 receiving invite from 11.8.75.89:5060 version: 1.10.7-release  64bit call-id: 4913-36936@11.8.75.89
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] sofia.c:7499 Channel sofia/external/sipp@11.8.75.89:5060 entering state [received][100]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] sofia.c:7509 Remote SDP:
27595300-6dbe-4fb8-8589-cd958b201309 v=0
27595300-6dbe-4fb8-8589-cd958b201309 o=user1 53655765 2353687637 IN IP4 11.8.75.89
27595300-6dbe-4fb8-8589-cd958b201309 s=-
27595300-6dbe-4fb8-8589-cd958b201309 c=IN IP4 11.8.75.89
27595300-6dbe-4fb8-8589-cd958b201309 t=0 0
27595300-6dbe-4fb8-8589-cd958b201309 m=audio 6000 RTP/AVP 0
27595300-6dbe-4fb8-8589-cd958b201309 a=rtpmap:0 PCMU/8000
27595300-6dbe-4fb8-8589-cd958b201309 
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] sofia.c:7917 (sofia/external/sipp@11.8.75.89:5060) State Change CS_NEW -> CS_INIT
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:600 (sofia/external/sipp@11.8.75.89:5060) State NEW
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_INIT (Cur 100 Tot 4913)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:624 (sofia/external/sipp@11.8.75.89:5060) State INIT
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] mod_sofia.c:97 sofia/external/sipp@11.8.75.89:5060 SOFIA INIT
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:40 sofia/external/sipp@11.8.75.89:5060 Standard INIT
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:48 (sofia/external/sipp@11.8.75.89:5060) State Change CS_INIT -> CS_ROUTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:624 (sofia/external/sipp@11.8.75.89:5060) State INIT going to sleep
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_ROUTING (Cur 100 Tot 4913)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_channel.c:2380 (sofia/external/sipp@11.8.75.89:5060) Callstate Change DOWN -> RINGING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:640 (sofia/external/sipp@11.8.75.89:5060) State ROUTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] mod_sofia.c:158 sofia/external/sipp@11.8.75.89:5060 SOFIA ROUTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:230 sofia/external/sipp@11.8.75.89:5060 Standard ROUTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [INFO] mod_dialplan_xml.c:639 Processing sipp <sipp>->r60720113 in context public
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 parsing [public->unloop] continue=false
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Regex (PASS) [unloop] ${unroll_loops}(true) =~ /^true$/ break=on-false
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Regex (FAIL) [unloop] ${sip_looped_call}() =~ /^true$/ break=on-false
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 parsing [public->record_test] continue=false
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Regex (PASS) [record_test] destination_number(r60720113) =~ /^(r|0).*$/ break=on-false
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Action sleep(${expr(randomize(&x);ceil(random(500,2000,&x)))})
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Action pre_answer()
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Action sleep(${expr(randomize(&x);ceil(random(5000,20000,&x)))})
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Action answer()
27595300-6dbe-4fb8-8589-cd958b201309 Dialplan: sofia/external/sipp@11.8.75.89:5060 Action record(/usr/local/freeswitch/recordings/${uuid}.wav)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:281 (sofia/external/sipp@11.8.75.89:5060) State Change CS_ROUTING -> CS_EXECUTE
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:640 (sofia/external/sipp@11.8.75.89:5060) State ROUTING going to sleep
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_EXECUTE (Cur 100 Tot 4913)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:647 (sofia/external/sipp@11.8.75.89:5060) State EXECUTE
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] mod_sofia.c:213 sofia/external/sipp@11.8.75.89:5060 SOFIA EXECUTE
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:15.437923 95.30% [DEBUG] switch_core_state_machine.c:323 sofia/external/sipp@11.8.75.89:5060 Standard EXECUTE
27595300-6dbe-4fb8-8589-cd958b201309 EXECUTE [depth=0] sofia/external/sipp@11.8.75.89:5060 sleep(748)
27595300-6dbe-4fb8-8589-cd958b201309 EXECUTE [depth=0] sofia/external/sipp@11.8.75.89:5060 pre_answer()
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [INFO] mod_dptools.c:1490 Sending early media
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5650 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[opus:116:48000:20:0:1]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5650 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[G722:9:8000:20:64000:1]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5650 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[PCMU:0:8000:20:64000:1]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5705 Audio Codec Compare [PCMU:0:8000:20:64000:1] ++++ is saved as a match
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5650 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[PCMA:8:8000:20:64000:1]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:3870 Set Codec sofia/external/sipp@11.8.75.89:5060 PCMU/8000 20 ms 160 samples 64000 bits 1 channels
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_codec.c:111 sofia/external/sipp@11.8.75.89:5060 Original read codec set to PCMU:0
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5944 No 2833 in SDP. Liberal DTMF mode adding 101 as telephone-event.
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:5973 sofia/external/sipp@11.8.75.89:5060 Set 2833 dtmf send payload to 101 recv payload to 101
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_media.c:8777 AUDIO RTP [sofia/external/sipp@11.8.75.89:5060] 11.8.75.147 port 23998 -> 11.8.75.89 port 6000 codec: 0 ms: 20
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [ERR] switch_rtp.c:4627 Error Starting timer [soft] 160 bytes per 20ms, async RTP disabled
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [ERR] switch_core_media.c:9785 AUDIO RTP REPORTS ERROR: [Socket Error!]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [NOTICE] switch_core_media.c:9786 Hangup sofia/external/sipp@11.8.75.89:5060 [CS_EXECUTE] [INCOMPATIBLE_DESTINATION]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [WARNING] mod_sofia.c:2589 CODEC NEGOTIATION ERROR.  SDP:
27595300-6dbe-4fb8-8589-cd958b201309 v=0
27595300-6dbe-4fb8-8589-cd958b201309 o=user1 53655765 2353687637 IN IP4 11.8.75.89
27595300-6dbe-4fb8-8589-cd958b201309 s=-
27595300-6dbe-4fb8-8589-cd958b201309 c=IN IP4 11.8.75.89
27595300-6dbe-4fb8-8589-cd958b201309 t=0 0
27595300-6dbe-4fb8-8589-cd958b201309 m=audio 6000 RTP/AVP 0
27595300-6dbe-4fb8-8589-cd958b201309 a=rtpmap:0 PCMU/8000
27595300-6dbe-4fb8-8589-cd958b201309 
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_session.c:2983 sofia/external/sipp@11.8.75.89:5060 skip receive message [PHONE_EVENT] (channel is hungup already)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:647 (sofia/external/sipp@11.8.75.89:5060) State EXECUTE going to sleep
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_HANGUP (Cur 100 Tot 4918)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:844 (sofia/external/sipp@11.8.75.89:5060) Callstate Change RINGING -> HANGUP
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:846 (sofia/external/sipp@11.8.75.89:5060) State HANGUP
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] mod_sofia.c:468 Channel sofia/external/sipp@11.8.75.89:5060 hanging up, cause: INCOMPATIBLE_DESTINATION
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] mod_sofia.c:613 Responding to INVITE with: 488
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:59 sofia/external/sipp@11.8.75.89:5060 Standard HANGUP, cause: INCOMPATIBLE_DESTINATION
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:846 (sofia/external/sipp@11.8.75.89:5060) State HANGUP going to sleep
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:616 (sofia/external/sipp@11.8.75.89:5060) State Change CS_HANGUP -> CS_REPORTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:581 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_REPORTING (Cur 100 Tot 4918)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:932 (sofia/external/sipp@11.8.75.89:5060) State REPORTING
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:168 sofia/external/sipp@11.8.75.89:5060 Standard REPORTING, cause: INCOMPATIBLE_DESTINATION
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:932 (sofia/external/sipp@11.8.75.89:5060) State REPORTING going to sleep
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:607 (sofia/external/sipp@11.8.75.89:5060) State Change CS_REPORTING -> CS_DESTROY
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_session.c:1753 Session 4913 (sofia/external/sipp@11.8.75.89:5060) Locked, Waiting on external entities
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [NOTICE] switch_core_session.c:1771 Session 4913 (sofia/external/sipp@11.8.75.89:5060) Ended
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [NOTICE] switch_core_session.c:1775 Close Channel sofia/external/sipp@11.8.75.89:5060 [CS_DESTROY]
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:735 (sofia/external/sipp@11.8.75.89:5060) Running State Change CS_DESTROY (Cur 100 Tot 4919)
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:745 (sofia/external/sipp@11.8.75.89:5060) State DESTROY
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] mod_sofia.c:379 sofia/external/sipp@11.8.75.89:5060 SOFIA DESTROY
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:175 sofia/external/sipp@11.8.75.89:5060 Standard DESTROY
27595300-6dbe-4fb8-8589-cd958b201309 2021-12-16 15:10:16.178060 95.07% [DEBUG] switch_core_state_machine.c:745 (sofia/external/sipp@11.8.75.89:5060) State DESTROY going to sleep

**Comment by burne-muz** [comment]
The dialplan for FreeSWITCH is:
context name="public"
  extension name="sipp_test"
    condition field="caller_id_name" expression="^sipp$"
      action application="sleep" data="${expr(randomize(&x);ceil(random(2000,10000,&x)))}"
      action application="sched_hangup" data="+${expr(randomize(&x);ceil(random(4,35,&x))) NORMAL_CLEAR}"
      action application="answer"
      action application="record" data="$${recordings_dir}/${uuid}.wav"
    condition
  extension
context

**Comment by dragos-oancea** [comment]
Some hints:

```autoload_configs/verto.conf.xml:27:      <param name="ext-rtp-ip" value="$${external_rtp_ip}"/>
sip_profiles/external.xml:66:    <param name="ext-rtp-ip" value="$${external_rtp_ip}"/>
sip_profiles/internal.xml:296:    <param name="ext-rtp-ip" value="$${external_rtp_ip}"/>
sip_profiles/internal-ipv6.xml:102:    <!-- <param name="ext-rtp-ip" value="$${external_rtp_ip}"/> -->

vars.xml:301:  <X-PRE-PROCESS cmd="stun-set" data="external_rtp_ip=stun:stun.freeswitch.org"/>
```
Make sure you have a valid IP in ${external_rtp_ip} - FS must be able to bind to it.

**Comment by dragos-oancea** [comment]
also, you should have PCMU in the codec lists, in vars.xml.

**Comment by burne-muz** [comment]
Yes, I am sure, my SIPP and FreeSWITCH are on the same LAN, So I wrote the IP directly in the configuration file
`<param name="ext-rtp-ip" value="11.8.75.147"/>`

**Comment by burne-muz** [comment]
sofia status profile external
`CODECS IN         OPUS,G722,PCMU,PCMA,H264,VP8`
`CODECS OUT     OPUS,G722,PCMU,PCMA,H264,VP8`

**Comment by dragos-oancea** [comment]
check the RTP port range too. "Socket Error" comes from either switch_rtp_set_local_address() or switch_rtp_set_remote_address() . It's when switch_socket_create() fails.

**Comment by mjerris** [comment]
sounds like running out of configured ports for rtp…

**Comment by burne-muz** [comment]
I used the default RTP port Settings and tried to specify the free port range, but the problem still occurred
conf/autoload_configs/switch.conf.xml
`<param name="rtp-start-port" value="20000"/>`
`<param name="rtp-end-port" value="29998"/>`

**Comment by burne-muz** [comment]
I set up 10,000 ports, but sometimes FS crashes after only a few hundred calls

**Comment by dragos-oancea** [comment]
if it crashes open an issue about the crash, with description, FS logs, pcaps and gdb backtrace.

**Comment by limdlh** [comment]
Hello burne-muz, did you fixed this issue?
I met the same problem with you.
Could you share your solution?

**Comment by trisight** [comment]
We found that outbound rtp ports will not be released when bridge_early_media is setted, finally leads to that problem. I'm not sure that is a bug for FS.

**Comment by trisight** [comment]
We found that outbound rtp ports will not be released when bridge_early_media is setted, finally leads to that problem.
 I'm not sure if that is a bug for FS.
