### ISSUE TITLE
U+202C POP DIRECTIONAL FORMATTING being added to call.

### ISSUE THREAD

**Issue by mrjoli021** [signalwire/freeswitch#1488]
**To Reproduce**
I am running the latest version of FusionPBX on a Debian 10 VM.  
[Archive 3.zip](https://github.com/signalwire/freeswitch/files/7738142/Archive.3.zip)
When I make an outbound call the following characters get added to the sip invite "%E2%80%AC".  This is happening only on certain numbers.  I have made sure that these characters are not present throughout the call before sending it to the GW.  Once it hits the last part of the freeswitch process which is sending the call to the GW.  During this process these characters get added and get sent as an invite to the caracter in the form of "<sip:122233331024%E2%80%AC@12.12.12.12".  If I change the last digits from 1024 to 1023 the call successfully completes without these characters being added.

**Expected behavior**
I would like for the call to be sent to the carrier without any extra characters

**Package version or git hash**
Freeswitch [1.10.3]

Attached are the Freeswitch logs for the calls.  One is for a good call and the other from a bad call.  Both are from the same extension.  The only thing different is that the last digit changed from a 4 to a 3.  And with that change the call went through.

**Comment by mjerris** [comment]
That value is coming from your config or from fusion and is getting passed in it appears here

Dialplan: sofia/internal/46152@34.199.27.163 Action set(effective_caller_id_number=${emergency_caller_id_number}) 

as a side note you should never use effective_ vars as they will cause issues on transfer.  we have advised against using them for years now.
