### ISSUE TITLE
mod_conference maybe block ever in conference_member_del because of switch_thread_rwlock_wrlock

### ISSUE THREAD

**Issue by boss-li** [signalwire/freeswitch#1489]
在使用relate命令对会议中的成员进行视频切换时发现，如果sip客户端反复进出会议，那么有可能会出现会议中同一个号码出现两次的异常问题，通过gdb调试发现，是因为 conference_member_del在调用switch_thread_rwlock_wrlock时阻塞了。再深入分析发现是因为其它线程调用了switch_thread_rwlock_tryrdlock但可能会没有解锁，这导致switch_thread_rwlock_wrlock加锁一直阻塞。

保证switch_thread_rwlock_tryrdlock后进行解锁即可解决此问题。
done it!!!

**Comment by andywolk** [comment]
We speak english.

**Comment by seven1240** [comment]
I can help translate into English if you submit a pr help me understand the problem.
