### ISSUE TITLE
[FS crashes]AUDIO RTP REPORTS ERROR: [Socket Error!]

### ISSUE THREAD

**Issue by burne-muz** [signalwire/freeswitch#1490]
**Describe the bug**
[ERR] switch_rtp.c:4627 Error Starting timer [soft] 160 bytes per 20ms, async RTP disabled
[ERR] switch_core_media.c:9785 AUDIO RTP REPORTS ERROR: [Socket Error!]
This error often occurs when I stress test FreeSWITCH-1.10.7 using SIPP, it looks like create RTP socket failed and then caused the FS to crash, but not when I do the same with FreeSWITCH-1.6.20
Does anybody know what's going on here?

Here is the function call relationship I found in my test. The "socket" returns 24
switch_core_media.c:8867 switch_rtp_new
switch_rtp.c:4781 switch_rtp_set_local_address
switch_rtp.c:2914 switch_socket_create
switch_apr.c:720 apr_socket_create
sockets.c:104 socket

**Configuration**
vars.xml
`    <X-PRE-PROCESS cmd="set" data="external_rtp_ip=$${local_ip_v4}"/>`
`    <X-PRE-PROCESS cmd="set" data="external_sip_ip=$${local_ip_v4}"/>`
dialplan/public.xml
`    <extension name="test">`
`      <condition>`
`	    <action application="answer"/>`
`	    <action application="record" data="$${recordings_dir}/${uuid}.wav"/>`
`      </condition>`
`    </extension>`
Nothing else has changed, the RTP port range is the default

**Package version or git hash**
FreeSWITCH-1.10.7 installed on CentOS Linux release 7.4.1708

The operating parameters of SIPP like this：
./sipp -r 20 -l 200 -d 10s -rtp_echo 11.8.75.147:5080

**Trace logs**
The log file was too big, so I deleted some lines in the middle
[freeswitch.log](https://github.com/signalwire/freeswitch/files/7750535/freeswitch.log)

**backtrace from core file**
[backtrace.log](https://github.com/signalwire/freeswitch/files/7750538/backtrace.log)

There's another thing I found out:
I install fs as root, and execute chown -R admin:admin /usr/local/freeswitch, run fs as admin, the error occurs
I later tested that running fs as root doesn't cause this error, but it's strange

**Comment by mjerris** [comment]
please install debug symbols.  the backtrace has no symbols.  reopen when you attach a backtrace w/ symbols

**Comment by burne-muz** [comment]
Which installation command should I use? I usually use make && make install @mjerris

**Comment by burne-muz** [comment]
is like this?
export CFLAGS="-g -ggdb"
export MOD_CFLAGS="-g -ggdb"
./configure
make && make install

**Comment by burne-muz** [comment]
I tests found that freeswitch caused this error by using more file handles than the system limit in high concurrency situations
Use `lsof - c freeswitch | wc -l` can view that freeswitch use how much file handle quantity,
CentOS is generally limited to 1024 per process
In the `/ect/security/limits.d/20-nproc.conf` after modify this limit, the problem is solved

**Comment by limdlh** [comment]
Hello burne-muz, did you fixed this issue?
I met the same problem with you.
Could you share your solution?
