### ISSUE TITLE
macOS make mod_verto fails with many "use of undeclared identifier"

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1497]
**Describe the bug**
Both release and master get many of these errors:
```
mod_verto.c:1721:18: error: use of undeclared identifier 'KWS_MAX_HEADERS'
        for (i = 0; i < KWS_MAX_HEADERS; i++) {
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
I can see that libks which supplies at least some KWS definitions is installed in /usr/local/include/libks, such as ks_ssl.h are there.

macOS Monterey 15.1, command line tools 13.2. This may be related to CLT 13 changing something, just a guess.

**To Reproduce**
1. Download release or master
2. bootstrap, configure, make

**Expected behavior**
 Make should complete normally.

**Package version or git hash**
 - Version 1.10.7 and master 1.10.8

**Build logs**
[2 config.txt](https://github.com/signalwire/freeswitch/files/7770746/2.config.txt)
[2 make.txt ](https://github.com/signalwire/freeswitch/files/7770747/2.make.txt)

**Comment by mjerris** [comment]
is this with latest libks from homebrew?  this looks like its trying to build against older libks

**Comment by MarioG-X** [comment]
I installed libks as per doc brew install signalwire/homebrew-signalwire/libks. Of course libks does not build due to #1461 (same as #1367) so I had to modify the code to include the fix. FYI I also spent a day getting around #1474 to try and push past this, but way too many issues.

**Comment by MarioG-X** [comment]
FYI: I tried installing frees switch from homebrew but have no idea who/where it comes from. I deleted all /use/local and started fresh and it also has issues with the problem modules, par of the startup:
`2021-12-24 09:18:10.363338 0.00% [CRIT] switch_loadable_module.c:1750 Error Loading module /usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_verto.so
**dlopen(/usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_verto.so, 0x0006): Library not loaded: @rpath/libks.1.dylib
  Referenced from: /usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_verto.so
  Reason: tried: '/usr/local/lib/libks.1.dylib' (no such file), '/usr/lib/libks.1.dylib' (no such file)**
2021-12-24 09:18:10.465101 0.00% [CRIT] switch_loadable_module.c:1750 Error Loading module /usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_signalwire.so
**dlopen(/usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_signalwire.so, 0x0006): Library not loaded: @rpath/libks.1.dylib
  Referenced from: /usr/local/Cellar/freeswitch/1.10.7_2/lib/freeswitch/mod/mod_signalwire.so
  Reason: tried: '/usr/local/lib/libks.1.dylib' (no such file), '/usr/lib/libks.1.dylib' (no such file)**
`

**Comment by andywolk** [comment]
should be fine now.

**Comment by MarioG-X** [comment]
Can't get to verto build in make due to #1474.

**Comment by andywolk** [comment]
You can remove those failing mods in modules.conf

**Comment by MarioG-X** [comment]
Good for a quick fix if you don't need some modules that won't build but I am trying to get the [macOS wiki](https://freeswitch.org/confluence/display/FREESWITCH/macOS+Installation) back to showing a working status. Thanks very much for working down the other issues today. I was hoping there would only be one left only to fins a new one today. Still, only two to go!

**Comment by MarioG-X** [comment]
Thanks very much for working down the other issues yesterday. I hoped for only be one left, only to find a new one. 5 down and only two to go! BTW,I made minor progress on the first outstanding issue above, I hope it helps. Thanks again!

**Comment by MarioG-X** [comment]
BTW, still on 1.10.6 since 1.10.7 release would never build on macOS. Hope 1.10.8 makes it!
