### ISSUE TITLE
Make fail mod_signalwire unused variable 'release_cb', identical to signalwire/signalwire-c#4 fixed 2018, now unfixed

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1500]
**Describe the bug**
Make fails in mod_signalwire with error below. This was fixed in 2018: Issue https://github.com/signalwire/signalwire-c/issues/4 and PR https://github.com/signalwire/signalwire-c/pull/5 but the fix was reversed recently and needs to be re-implemented.

making all mod_signalwire
  CC       mod_signalwire_la-mod_signalwire.lo
In file included from mod_signalwire.c:28:
In file included from /usr/local/include/signalwire-client-c/client.h:38:
In file included from /usr/local/include/signalwire-client-c/blade/blade.h:33:
/usr/local/include/signalwire-client-c/blade/disconnect.h:44:1: error: unused variable 'release_cb' [-Werror,-Wunused-variable]
SWCLT_JSON_PARSE_BEG(BLADE_DISCONNECT_RQU, blade_disconnect_rqu_t)
^
/usr/local/include/signalwire-client-c/JSON/macros.h:69:10: note: expanded from macro 'SWCLT_JSON_PARSE_BEG'
                void (*release_cb)(target_type **) = (void(*)(target_type **))function_name##_DESTROY;  \
                       ^
**To Reproduce**
1. Download master, bootstrap, configure, make. Tested on Monterey and Catalina, same.

**Package version or git hash**
 - Master 12/28/21 083a9ab1c31b44fb79fdb924e7038653cf24793e

**Comment by MarioG-X** [comment]
Using grep to find "release_cb", I found the error is not coming from FreeSWITCH source, but from the downloaded signalwire-c 1.3.1 from homebrew.

**Comment by MarioG-X** [comment]
Added links to PR signalwire/signalwire-c#5

**Comment by andywolk** [comment]
@MarioG-X 
Try this fix (note `\` at the end of the line):
```
diff --git a/inc/signalwire-client-c/JSON/macros.h b/inc/signalwire-client-c/JSON/macros.h
index 7f157e4..d494122 100644
--- a/inc/signalwire-client-c/JSON/macros.h
+++ b/inc/signalwire-client-c/JSON/macros.h
@@ -251,6 +251,7 @@ KS_BEGIN_EXTERN_C
 	}
 
 #define SWCLT_JSON_PARSE_END()											\
+	(void)release_cb;													\
 	*result = (void *)target;											\
 	return KS_STATUS_SUCCESS;											\
 	}
```

**Comment by andywolk** [comment]
https://github.com/signalwire/signalwire-c/pull/84

**Comment by andywolk** [comment]
remove mod_av from modules.conf

**Comment by andywolk** [comment]
run `make core` instead

**Comment by MarioG-X** [comment]
Removed mod_av from modules.conf and looks like it ran until it hit #1474. I am putting back mod_av and running make core now.

**Comment by andywolk** [comment]
Is this particular issue fixed?

**Comment by MarioG-X** [comment]
Did a "make clean" then "make core" and it ran to the end. So looks fixed once it's in master. Thanks!

**Comment by MarioG-X** [comment]
Will reopen if needed.

**Comment by andywolk** [comment]
You mentioned that this issue is when mod_signalwire is built.
So please confirm that this issue is solved by `make mod_signalwire` and not just by `make core`

**Comment by andywolk** [comment]
You mentioned `switch_core_db` in an issue not even related to that. Here we discuss mod_signalwire
So let's focus on the topic and not just between issues and mention everything everywhere.

**Comment by MarioG-X** [comment]
I guess not, I added the lines:
#define SWCLT_JSON_PARSE_END()
	(void)release_cb;											
	*result = (void *)target;											
	return KS_STATUS_SUCCESS;											
	}
But the make failed:
[make.txt](https://github.com/signalwire/freeswitch/files/8721425/make.txt)

**Comment by andywolk** [comment]
upload your result macros.h

**Comment by MarioG-X** [comment]
[macros.h.txt](https://github.com/signalwire/freeswitch/files/8721430/macros.h.txt)

**Comment by andywolk** [comment]
Be careful. You updated it wrongly. You cut out line endings with `\`

**Comment by MarioG-X** [comment]
I put the lines back in and same error:
#define SWCLT_JSON_PARSE_END()
\
	(void)release_cb;
\
	*result = (void *)target;
\			
	return KS_STATUS_SUCCESS;
\
	}
\

**Comment by andywolk** [comment]
You did it wrongly. Take it from master https://raw.githubusercontent.com/signalwire/signalwire-c/master/inc/signalwire-client-c/JSON/macros.h

**Comment by MarioG-X** [comment]
I downloaded the file an now got:
[make.txt](https://github.com/signalwire/freeswitch/files/8721459/make.txt)

**Comment by andywolk** [comment]
Add `(void)target; \` here
```
#define SWCLT_JSON_DESTROY_END()			\
        (void)target; \
	ks_pool_free(__free_target);			\
}
```

**Comment by MarioG-X** [comment]
That fixed it until it hit the next issue. Thanks!

**Comment by MarioG-X** [comment]
I think the homebrew formula for signalwire-c must be updated as well to pull the changed module.

**Comment by andywolk** [comment]
https://github.com/signalwire/homebrew-signalwire/commit/3494780632d3a4984592f22176dc6cb1d475ff54

**Comment by MarioG-X** [comment]
Works, thank you! One known build issue remaining. Will post over there.

brew uninstall signalwire-c (1.3.1)
brew install signalwire-c (1.3.2)
./configure
make mod_signalwire-c
