### ISSUE TITLE
Segfault in apr_palloc

### ISSUE THREAD

**Issue by wuxz** [signalwire/freeswitch#1502]
**Describe the bug**
v1.10.7
Segfault when in 50 concurrent calls pressure test.
Service is running in docker, debian buster.

**To Reproduce**
1. Compile and run FreeSwitch in docker, base image is debian buster.
2. Run 50 concurrent calls pressure test, controlling FreeSwtcih using ESL. Call to another FreeSwitch using SIP, when the call is connect, do speak_and_detect_speech. The callee will play a wav file.
3. After maybe 30 minutes or 60 minutes, FreeSWITCH crashes.

**Expected behavior**
Please find out the reason and fix it.

**Package version or git hash**
 - Version 1.10.7

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
[20211228T130716Z-bt.txt](https://github.com/signalwire/freeswitch/files/7787526/20211228T130716Z-bt.txt)

**Comment by dragos-oancea** [comment]
does it happen with newer mrcp lib ? https://github.com/signalwire/freeswitch/pull/1071

**Comment by wuxz** [comment]
> does it happen with newer mrcp lib ? #1071

Sorry, what is newer mrcp lib? I have no idea.

**Comment by dragos-oancea** [comment]
just test the branch I pointed out.

**Comment by dragos-oancea** [comment]
I saw in your logs that you use unimrcp, that's why the suggestion....  it's called in the thread that crashes. ```# bt
================================================================================
#0  apr_palloc (pool=pool@entry=0x7fe9501944b8, size=size@entry=192) at memory/unix/apr_pools.c:627
#1  0x00007fe976e8a3a6 in call_resolver (sa=sa@entry=0x7fe96eab2af0, hostname=0x7fe878326e00 "192.168.0.236", family=<optimized out>, port=<optimized out>, p=0x7fe9501944b8, flags=0) at network_io/unix/sockaddr.c:378
#2  0x00007fe976e8a8a2 in find_addresses (p=<optimized out>, flags=0, port=<optimized out>, family=<optimized out>, hostname=<optimized out>, sa=0x7fe96eab2af0) at network_io/unix/sockaddr.c:431
#3  apr_sockaddr_info_get (sa=sa@entry=0x561ed31eaa80, hostname=<optimized out>, family=family@entry=2, port=<optimized out>, flags=flags@entry=0, p=<optimized out>) at network_io/unix/sockaddr.c:568
#4  0x00007fe96eadad5e in mrcp_client_agent_connection_find (descriptor=0x7fe878326178, descriptor=0x7fe878326178, agent=0x7fe96eab2af0) at src/mrcp_client_connection.c:369
#5  mrcp_client_agent_channel_modify (descriptor=0x7fe878326178, channel=0x7fe878326178, agent=0x7fe96eab2af0) at src/mrcp_client_connection.c:420
#6  mrcp_client_agent_msg_process (task=<optimized out>, task_msg=<optimized out>) at src/mrcp_client_connection.c:672
#7  0x00007fe96eae840e in apt_task_msg_process (task=0x561ed31e7458, msg=msg@entry=0x7fe95c007940) at src/apt_task.c:344
#8  0x00007fe96eae7124 in apt_poller_task_wakeup_process (task=0x561ed31eaa80) at src/apt_poller_task.c:208
#9  apt_poller_task_run (base=<optimized out>) at src/apt_poller_task.c:262
#10 0x00007fe96eae7a57 in apt_task_run (thread_handle=0x561ed31eb118, data=0x561ed31e7458) at src/apt_task.c:591
#11 0x00007fe976e8dcdc in dummy_worker (opaque=0x561ed31eb118) at threadproc/unix/thread.c:151
#12 0x00007fe976a47fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#13 0x00007fe9765fd4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by wuxz** [comment]
> does it happen with newer mrcp lib ? #1071

Sorry, I pulled the source code under branch v1.10, but how can I use this newer mrcp lib?

**Comment by wuxz** [comment]
> just test the branch I pointed out.

I saw that this pull request was approved, but the changes do not exist in master branch.  So to use this new lib, I should use the branch in your fork?

**Comment by dragos-oancea** [comment]
it's not our fork, it's a branch of a member of the community which you'll probably want to rebase with our master before building it.

**Comment by wuxz** [comment]
> it's not our fork, it's a branch of a member of the community which you'll probably want to rebase with our master before building it.

In hateeyan/freeswitch, I can not find the commit related to mrcp 1.7 in master branch, it's only in feature-unimrcp branch, but this branch is far away from the master branch.

**Comment by dragos-oancea** [comment]
that's why I told you to rebase... https://git-scm.com/docs/git-rebase

**Comment by xuejun88** [comment]
@dragos-oancea help ,https://github.com/signalwire/freeswitch/issues/1509

**Comment by wuxz** [comment]
> does it happen with newer mrcp lib ? #1071

I fixed this issue using newer mrcp lib. Thank you very much.
