### ISSUE TITLE
"record_post_process_exec_app" Not Firing

### ISSUE THREAD

**Issue by olliebobster** [signalwire/freeswitch#151]
Hello,

When trying to use  record_post_process_exec_app to launch a Shell Script after the Leg-A hangs up during the record, the process does not fire.

I'm running Freeswitch 1.10.1 on Ubuntu 18.04.03 with the following configuration in my dial plan:

<action application="set" data="record_post_process_exec_app=system:/usr/local/freeswitch/scripts/testScript.sh" />
<action application="record" data="/tmp/call.wav 180"/>

The CLI logs show the variable being set as the dialplan is executed:

Dialplan: sofia/external/XXXX@XXXXX
Action set(record_post_process_exec_app=system:/usr/local/freeswitch/scripts/testScript.sh)

If I change the record timeout to 10 seconds and include a system action after the record, the Shell Script executes correctly, so I don't believe there are any problems with it.

Thanks,
Ollie

**Comment by mochouinard** [comment]
One of the potential reason could be that record_post_process_exec_app is not set on the channel you are actually recording.
You could run a different command, like 'info' and check in the log to see if it was executed or not.

**Comment by olliebobster** [comment]
Hello,

Many thanks for the reply and Merry Christmas!

I had a similar thought a few days back and moved the action command, at the start of the Leg (Public Dial plan), but it's still not firing. I also tried your suggestion of trying a basic 'info' command or even a 'touch /tmp/hello.txt' and other than it reporting that the command was set in the logs, it doesn't fire once the Leg A hangs up.

My Dial Plan is a basic Inbound DDI set in public.xml, which then transfers to an internal extension to try and locate someone to pick up the call, if this times out, a message is played and a voicemail is taken with the 'record' command. The record works correctly and records the audio from Leg A, but the post_process never fires once the caller has left a message and hangs up.

Do you have any other ideas why this might not be firing?

Thanks,
Ollie

**Comment by briankwest** [comment]
Its probably exactly what Moc said, you'll need to uuid_dump both sessions while up and active to validate, if you can provide additional steps please reopen.
