### ISSUE TITLE
why get session lost? possible causes?

### ISSUE THREAD

**Issue by xuejun88** [signalwire/freeswitch#1512]
Describe the bug
char *uuid = switch_event_get_header(event, "Caller-Unique-ID")
   session = switch_core_session_locate(uuid);
    if (!session)
        session = switch_core_session_force_locate(uuid);

    if (!session) {
        switch_log_printf(SWITCH_CHANNEL_UUID_LOG(uuid), SWITCH_LOG_INFO, "event %d uuid %s session not found \n",
                          event->event_id, uuid);
        return;
    }

using:
switch_core_session_alloc(session, sizeof(session_data_t));

Expected behavior
Please find out the reason and fix it.

Package version or git hash

Version 1.10.7

**Comment by dragos-oancea** [comment]
it looks like you're trying to make your own module. if the session is not found and you're sure it exists under that uuid maybe the event does not have the header named Caller-Unique-ID ? 

Anyhow, this ticket does not detail the issue properly and it also feels too demanding with your imperative request to "find the reason and fix it" - closing it.
