### ISSUE TITLE
PIDF-LO is not passed properly

### ISSUE THREAD

**Issue by aatif218** [signalwire/freeswitch#1536]
We tried to pass PIDF-LO on a call from A to B. We are facing Leg-B INVITE body having two application/sdb parts within one multipart/mixed.
In sofia sip trace, we are getting unknown Content-Type: multipart/mixed in nua_session. Will it be the root cause for the issue?

We attached Leg-A Message body, Leg-B Message body and siptrace log. If you need any other information, please let us know.

Leg-A Message Body
==================
Content-Type: multipart/mixed; boundary="boundary1"
Content-Length:  1272

--boundary1
Content-Type: application/sdp

v=0
o=user1 53655765 2353687637 IN IP4 66.212.1.2
s=-
c=IN IP4 66.212.1.2
t=0 0
m=audio 6000 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=direction:active

--boundary1
Content-Type: application/pidf+xml
Content-ID: <target...@atlanta.example.com>

<?xml version="1.0" encoding="UTF-8"?>
<presence>
xmlns="urn:ietf:params:xml:ns:pidf"
xmlns:gp="urn:ietf:params:xml:ns:pidf:geopriv10"
xmlns:gbp="urn:ietf:params:xml:ns:pidf:geopriv10:basicPolicy"
xmlns:cl="urn:ietf:params:xml:ns:pidf:geopriv10:civicAddr"
xmlns:gml="http://www.opengis.net/gml";
xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model"
entity="pres:al...@atlanta.example.com">
<dm:device id="target123-1">
<gp:geopriv>
<gp:location-info>
<gml:location>
<gml:Point srsName="urn:ogc:def:crs:EPSG::4326">
<gml:pos>32.86726 -97.16054</gml:pos>
</gml:Point>
</gml:location>
</gp:location-info>
<gp:usage-rules>
<gbp:retransmission-allowed>false
</gbp:retransmission-allowed>
<gbp:retention-expiry>2010-11-14T20:00:00Z
</gbp:retention-expiry>
</gp:usage-rules>
<gp:method>802.11</gp:method>
</gp:geopriv>
<dm:deviceID>mac:1234567890ab</dm:deviceID>
<dm:timestamp>2010-11-04T20:57:29Z</dm:timestamp>
</dm:device>
</presence>

--boundary1--

Leg-B Message Body
==================

Content-Type: multipart/mixed;boundary=0722d95b-e95e-4201-ba75-321f8f0984a3
Content-Length: 1843

--0722d95b-e95e-4201-ba75-321f8f0984a3
Content-Type: application/sdp
Content-Length: 180

v=0
o=user1 53655765 2353687637 IN IP4 66.212.1.2
s=-
c=IN IP4 10.5.8.11
t=0 0
m=audio 11062 RTP/AVP 8
a=direction:active
a=rtpmap:8 PCMA/8000
a=sendrecv
a=rtcp:11063

--0722d95b-e95e-4201-ba75-321f8f0984a3
Content-Type: application/pidf+xml
Content-Length: 959

<?xml version="1.0" encoding="UTF-8"?>
<presence>
xmlns="urn:ietf:params:xml:ns:pidf"
xmlns:gp="urn:ietf:params:xml:ns:pidf:geopriv10"
xmlns:gbp="urn:ietf:params:xml:ns:pidf:geopriv10:basicPolicy"
xmlns:cl="urn:ietf:params:xml:ns:pidf:geopriv10:civicAddr"
xmlns:gml="http://www.opengis.net/gml";
xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model"
entity="pres:al...@atlanta.example.com">
<dm:device id="target123-1">
<gp:geopriv>
<gp:location-info>
<gml:location>
<gml:Point srsName="urn:ogc:def:crs:EPSG::4326">
<gml:pos>32.86726 -97.16054</gml:pos>
</gml:Point>
</gml:location>
</gp:location-info>
<gp:usage-rules>
<gbp:retransmission-allowed>false
</gbp:retransmission-allowed>
<gbp:retention-expiry>2010-11-14T20:00:00Z
</gbp:retention-expiry>
</gp:usage-rules>
<gp:method>802.11</gp:method>
</gp:geopriv>
<dm:deviceID>mac:1234567890ab</dm:deviceID>
<dm:timestamp>2010-11-04T20:57:29Z</dm:timestamp>
</dm:device>
</presence>

--0722d95b-e95e-4201-ba75-321f8f0984a3
Content-Type: application/sdp
Content-Length: 372

v=0
o=FreeSWITCH 1642979226 1642979227 IN IP4 10.5.8.13
s=FreeSWITCH
c=IN IP4 10.5.8.13
t=0 0
m=audio 29900 RTP/AVP 8 9 102 0 18 101
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:102 iLBC/8000
a=fmtp:102 mode=30
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv

--0722d95b-e95e-4201-ba75-321f8f0984a3--

SIP TRACE
=========
nua_common.c:108 nh_create_handle() nua: nh_create_handle: entering
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:637 nua_invite() nua: nua_invite: entering
nua_stack.c:529 nua_signal() nua(0x7f8a18001290): sent signal r_invite
nua_stack.c:569 nua_stack_signal() nua(0x7f8a18001290): recv signal r_invite
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
nua_dialog.c:338 nua_dialog_usage_add() nua(0x7f8a18001290): adding session usage
nta.c:4446 nta_leg_tcreate() nta_leg_tcreate(0x7f8ac4155aa0)
nua_session.c:4624 session_get_description() nua: unknown Content-Type: multipart/mixed
nta.c:2694 nta_tpn_by_url() nta: selecting scheme sip

**Comment by mjerris** [comment]
this is not supported.  if you plan on submitting a patch to support this please reopen the issue

**Comment by davesoft11** [comment]
We need PIDF/LO to work. Any progress on implementing this?
