### ISSUE TITLE
docker/master/Dockerfile is unbuildable

### ISSUE THREAD

**Issue by S-trace** [signalwire/freeswitch#154]
Step 10/26 : RUN apt-get update && apt-get install -y freeswitch-all     && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 687a86e6f98a
Get:1 http://files.freeswitch.org jessie InRelease [4,624 B]
Hit http://security.debian.org jessie/updates InRelease
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:2 http://files.freeswitch.org jessie/main amd64 Packages [70.2 kB]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [915 kB]
Get:4 http://deb.debian.org jessie-updates/main amd64 Packages [20 B]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9,098 kB]
Get:6 http://deb.debian.org jessie/contrib amd64 Packages [59.2 kB]
Get:7 http://deb.debian.org jessie/non-free amd64 Packages [101 kB]
Fetched 10.2 MB in 19s (535 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 freeswitch-all : Depends: freeswitch-meta-all (= 1.9.0~2162~28fc17a~jessie-1~jessie+1) but it is not going to be installed
                  Depends: freeswitch-meta-all-dbg (= 1.9.0~2162~28fc17a~jessie-1~jessie+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y freeswitch-all     && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by tommyNy** [comment]
@S-trace Did you change value of ENV FS_MAJOR ?

**Comment by S-trace** [comment]
No

**Comment by davidplappert** [comment]
same issue. please advise.

**Comment by soroshsabz** [comment]
same issue please merge it.

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/pull/1587
