### ISSUE TITLE
MGCP support

### ISSUE THREAD

**Issue by grinapo** [signalwire/freeswitch#1543]
I see that from time to time someone asks about **MGCP** support, and someone else responds ([like here](https://freeswitch-users.freeswitch.narkive.com/kgI0CY3s/ss7-mgcp-support)) that there is no support, or there were alpha-quality not feature complete tries but no pointers, and there were several bounties left unanswered, mostly in the last decade. It has been suggested as "pretty simple" and "fairly basic".

Since the project was moved here the string "MGCP" does not seem to git a search hit so I would suspect it's not supported. Does anyone know any support in any state of readiness? 

Obviously my wishlist item is that it was supported.

Since I don't expect anyone to do it for my beautiful smile (and it seems no core members felt the need to code it in the last 10 years) I'd like to ask how to make it happen? Shall I contact the core team and make an offer? Shall I ask here (as I just did), whether anyone feels like up to the task in exchange of monetary compensation?

**Describe the solution you'd like**
MGCP supported.

**Describe alternatives you've considered**
Asterisk. 

**Additional context**
Have been repeatedly asked in the last 10+ years.

**Comment by andywolk** [comment]
Hi @grinapo 
Please contact sales at signalwire.com
