### ISSUE TITLE
minimum-session-expires option ignored

### ISSUE THREAD

**Issue by S-trace** [signalwire/freeswitch#155]
Hello.

I have FreeSWITCH Version 1.6.20-37-987c9b9~64bit (-37-987c9b9 64bit) installed in Docker container (built using docker/release/Dockerfile), and have a problem with JsSIP - if Session Timers (Enable Session Timers as per RFC 4028) option is checked in JsSIP, FreeSwitch rejects JsSIP's call (Session-Expires: 90) with SIP/2.0 422 Session Interval Too Small error (Min-SE: 120). 

I have set following options in /etc/freeswitch/sip_profiles/internal.xml :
```
<param name="enable-timer" value="true"/>
<param name="minimum-session-expires" value="90"/>
```
And restarted FreeSwitch, but it still rejects JsSIP's call with exactly same error (Min-SE: 120) - so, minimum-session-expires is ignored.

I tried to install master version using docker/master/Dockerfile but it fails to build an image (opened another issue about this).

Thank you.

**Comment by mjerris** [comment]
please confirm if this is the case on latest freeswitch release.

**Comment by S-trace** [comment]
@mjerris Yes, this issue still persists

**Comment by fcolista** [comment]
Is this issue fixed with FS 1.10.3 ?
With my test, I can't see Session-Expire as yet even with this version.

**Comment by fcolista** [comment]
Are there any update with FS 1.10.4? I haven't seen any reference to RFC 4028 in the ChangeLog.
Thanks.

**Comment by praiseable** [comment]
Apply below setting it will work even on 90 seconds but not less than 90 sec 

 <param name="enable-timer" value="true"/>
    <param name="minimum-session-expires" value="90"/> 
    <param name="session-timeout" value="90"/>

**Comment by praiseable** [comment]
Apply these setting it will set to 90 with out 422 error message  

`<param name="enable-timer" value="true"/>
    <param name="minimum-session-expires" value="90"/> 
    <param name="session-timeout" value="90"/>`

**Comment by deevarvar** [comment]
> Apply these setting it will set to 90 with out 422 error message
> 
> `<param name="enable-timer" value="true"/> <param name="minimum-session-expires" value="90"/> <param name="session-timeout" value="90"/>`

works as expeceted
someone may add this to fs's wiki
one more comment is that seems only restart to make it into effect.
rescan seems not working...

**Comment by praiseable** [comment]
> > Apply these setting it will set to 90 with out 422 error message
> > `<param name="enable-timer" value="true"/> <param name="minimum-session-expires" value="90"/> <param name="session-timeout" value="90"/>`
> 
> works as expeceted
> someone may add this to fs's wiki
> one more comment is that seems only restart to make it into effect.
> rescan seems not working...

Yes rescan works only call routing xmls or lua code changes this is global parameter setting. for global level setting change Freeswitch needs to be restarted
