### ISSUE TITLE
Error opening MoH files with the path containing .loc

### ISSUE THREAD

**Issue by brtgrd** [signalwire/freeswitch#1576]
**Describe the bug**
We found an issue in Freeswitch working with FusionPBX. FusionPBX creates music-on-hold files by path like
/usr/share/freeswitch/sounds/music/domain.local.com/moh/48000/moh.wav. Errors appear in the log and Freeswitch restarts after a while at regular intervals

**To Reproduce**
1. mkdir -p /usr/local/freeswitch/sounds/domain.local.com
2. echo WAV-FILE > /usr/local/freeswitch/sounds/domain.local.com/1.wav
(any audio file can be placed here)
3. Add to /usr/local/freeswitch/conf/autoload_configs/local_stream.conf:
```
  <directory name="moh/48000" path="/usr/local/freeswitch/sounds/domain.local.com">
    <param name="rate" value="48000"/>
    <param name="shuffle" value="true"/>
    <param name="channels" value="1"/>
    <param name="interval" value="10"/>
    <param name="timer-name" value="soft"/>
  </directory>

```
4. The following errors appear in the log, Freeswitch server may crash in one hour or so
```
2022-03-15 16:23:11.496733 97.93% [ERR] switch_core_file.c:336 Unknown file Format [WAV-FILE]
2022-03-15 16:23:11.496733 97.93% [ERR] mod_local_stream.c:361 Can't open WAV-FILE
2022-03-15 16:23:13.496807 97.30% [ERR] switch_core_file.c:336 Unknown file Format [WAV-FILE]
2022-03-15 16:23:13.496807 97.30% [ERR] mod_local_stream.c:361 Can't open WAV-FILE
2022-03-15 16:23:15.496828 96.73% [ERR] switch_core_file.c:336 Unknown file Format [WAV-FILE]
2022-03-15 16:23:15.496828 96.73% [ERR] mod_local_stream.c:361 Can't open WAV-FILE

```
**Expected behavior**
Audio files should not be considered as .loc files

Here is a portion of code which probably causes the issue:
```
src/mod/formats/mod_local_stream/mod_local_stream.c:
                                if (switch_stristr(".loc", path_buf)) {
                                        if ((fd = open(path_buf, O_RDONLY)) < 0) {
                                                switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_ERROR, "Can't open %s\n", fname);
                                                switch_yield(1000000);
                                        }
                                        continue;
                                }

```
**Package version or git hash**
 - Version 1.10.7

**Comment by dragos-oancea** [comment]
try this patch: https://github.com/signalwire/freeswitch/pull/1577

**Comment by brtgrd** [comment]
seems fixed
