### ISSUE TITLE
401 Unauthorized on files.freeswitch.org / Debian repo unavailable

### ISSUE THREAD

**Issue by kevin-olbrich** [signalwire/freeswitch#1580]
Hi,

access to files.freeswitch.org is being denied with http 401 (= debian repositories are down).

The website shows a basic auth windows when trying to access it.

**Comment by crienzo** [comment]
Hello - check here https://freeswitch.org/confluence/display/FREESWITCH/Debian

**Comment by kevin-olbrich** [comment]
Oh, that’s news for me. Thanks for the hint. Is there a documentation why this has been implemented?

**Comment by crienzo** [comment]
Some emails were sent out and there was some discussion in the community slack.
