### ISSUE TITLE
freeswitch-archive-keyring.gpg 401  Unauthorized 

### ISSUE THREAD

**Issue by autooz** [signalwire/freeswitch#1583]
Debian 11 FS istall as https://freeswitch.org/confluence/pages/viewpage.action?pageId=61210850

bug
https://files.freeswitch.org/repo/deb/debian-release/dists/bullseye/InRelease  401  Unauthorized

**Comment by andywolk** [comment]
https://freeswitch.org/confluence/display/FREESWITCH/Debian
