### ISSUE TITLE
Locking down UDP dynamic port range

### ISSUE THREAD

**Issue by roartysa** [signalwire/freeswitch#159]
Hello,

I am having an issue with my FS server talking to a SIP proxy using UDP. Normally when there isn't a firewall in between these 2 servers I have no issues. But when there is a FW between the two servers, the FW is blocking some traffic.

Initially, I had 5060 opened in both directions in the FW and that didn't work. When doing some Wireshark analysis, I was able to see that the initial communication to the proxy is done on 5060 and then when some of the SIP messaging was established for longer periods of time, the messaging from FS to the SIP proxy started to use a dynamic port range. Once FS uses that new port, the proxy starts to use it as well. 

So in doing some research, I tried to change the siwtch.conf.xml to use a distinct UDP RTP port range of 10000 - 16000. The FW was updated to match that range and then we were still seeing traffic being blocked. Then I had them add the 16384-32768 range to the FW rule and although it has improved with less blocked traffic, we are still seeing some communication being blocked on port 424xx range.

So my question is, where is the correct spot to configure FS for these UDP port ranges? I am guessing the rtp-start-port and rtp-end-port configs in the switch.conf.xml file is not the place based on the results I have seen so far.

Thanks for any guidance you can provide!

**Comment by mochouinard** [comment]
It actually the right config...  FS will ask for these ports on it end... BUT... It can't decide on the far end port being open... Sp maybe you have block on port alone and not on destination port to your FS only... Your FS box would have to be able to connect to any port the far end device connect to.  Also, if you do natting, there might be some nat transversal and port will be changed...

So make sure you block on destination port to your FS and not source port.

**Comment by briankwest** [comment]
You may be confusing local vs remote port, the remote can still give you a port number out side the range you've setup FreeSWITCH for.
