### ISSUE TITLE
signalwire/freeswitch-public-base What does this mirror image do?

### ISSUE THREAD

**Issue by itlidaye** [signalwire/freeswitch#1590]
signalwire/freeswitch-public-base What does this mirror image do?

Do you have the latest version of the image that can be used with all modules?

**Comment by andywolk** [comment]
This image is used for testing on Drone CI. 
See https://github.com/signalwire/freeswitch/blob/master/.drone.yml

**Comment by itlidaye** [comment]
Is there an official docker image repository address of the latest version of all modules?

**Comment by andywolk** [comment]
No.

**Comment by itlidaye** [comment]
Can you compile the latest version of the image and push it to the docker hub?
