### ISSUE TITLE
Ansible playbook contribution for https://freeswitch.org/confluence/display/FREESWITCH/Debian to switch to new SignalWire repos

### ISSUE THREAD

**Issue by ghenry** [signalwire/freeswitch#1592]
Hi all,

At SureVoIP and TelcoSwitch we have FreeSWITCH in lots of different roles (30+ servers) from SBCs, Hosted VoIP, APIs etc. so we needed to update the apt repos on our Debian systems.

I've done a small playbook to remove the old style repo, download the gpg key, create the auth file for apt and create the new repo.

I was going to add it here https://freeswitch.org/confluence/display/FREESWITCH/Debian

Is that the best place? I've attached it anyway.

[freeswitch_signalwire_repo.yml.txt](https://github.com/signalwire/freeswitch/files/8316037/freeswitch_signalwire_repo.yml.txt)

Thanks,
Gavin.

**Comment by ghenry** [comment]
Oh, I can't edit that page anyway when logged in. If someone could add it for other, that would be great. Thanks.

**Comment by ghenry** [comment]
Got perms to create pages on the wiki - https://freeswitch.org/confluence/display/FREESWITCH/Ansible+playbook+to+update+your+Debian+repository+to+add+a+SignalWire+Token

**Comment by andywolk** [comment]
Closing this. Please open another issue if you have anything to solve in the code. Also use our slack channels.
