### ISSUE TITLE
Why Debian URL files.freeswitch.org/repo/deb/debian-release now REQUIRED Authentication

### ISSUE THREAD

**Issue by rzevtin** [signalwire/freeswitch#1596]
Hello,

I was going to setup a FreeSwitch again following this documentation from the official site https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster last months it still works.
Now it suddenly asks for a username and password,  accessing https://files.freeswitch.org/repo/deb/ URL is not possible anymore without authentication. Is this just a mistakes or there is a documentation about the username and password else where?

The official doc now can be found [here](https://freeswitch.org/confluence/pages/viewpage.action?pageId=25460805)
Thanks and really appreciate the help.

**Comment by crienzo** [comment]
The new instructions are here: https://freeswitch.org/confluence/display/FREESWITCH/Debian
The instructions for getting a personal access token are here: https://freeswitch.org/confluence/display/FREESWITCH/HOWTO+Create+a+SignalWire+Personal+Access+Token
