### ISSUE TITLE
Locking of loadable modules

### ISSUE THREAD

**Issue by ar45** [signalwire/freeswitch#1599]
It appears that this mutex is used quite often and may unnecessarily block other threads from doing harmless work concurrently.

One example 
https://github.com/signalwire/freeswitch/blob/df81021a11b0ce554cd3fc7571492a2cfa2ef087/src/switch_loadable_module.c#L825-L831

Wouldn't it be better using `switch_thread_rwlock_t` and acquire shared read locks instead?

**Comment by greenbea** [comment]
I often have my Freeswitch hanging; taking a  coredump showed me a mutex lock on the thread running `do_chat_send()`.
This can easily be reproduced by adding a sleep in chatplan

**Comment by anthmFS** [comment]
This could probably be improved. I didn't know anyone uses the chat features on FS. I suppose this function has more contention than other things using this mutex. We can come up with a strategy on this but it might be an intrusive change.

Maybe we should add SMS to mod_signalwire too.

**Comment by anthmFS** [comment]
there is a patch in testing that will trickle down soon

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/commit/edd36639c7a57b2430d1df9787137c39da893dfa
