### ISSUE TITLE
Freeswitch repo password protected

### ISSUE THREAD

**Issue by acomav** [signalwire/freeswitch#1604]
Hi,
  I went to download the keyring.asc for a new build on Debian 11 and received an error from the server.

Connecting to files.freeswitch.org (files.freeswitch.org)|190.102.98.174|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

I can confirm by trying to manually browse the deb and yum repos vis a browser: https://files.freeswitch.org/repo/deb and https://files.freeswitch.org/repo/yum.

Is this by design due to pending changes or an oversight?

Thanks

**Comment by dragos-oancea** [comment]
by design. https://lists.freeswitch.org/pipermail/freeswitch-users/2022-March/135678.html

**Comment by acomav** [comment]
Thanks.   I was reading an old (OBSOLETE) page.  found the right page now.
