### ISSUE TITLE
String comparison problem

### ISSUE THREAD

**Issue by infook-liu** [signalwire/freeswitch#1607]
version: freeswitch 1.10.7 release

The problem is about 12339 lines in switch_core_media.c file. When comparing the string "m=text", there is a problem with the length. It should be 7 instead of 8.

find line:
if (!strncmp("m=text ", p, 8) && *(p + 8) != '0')

**Comment by lazedo** [comment]
shouldn't it be **6** instead ?
like if (!strncmp("m=text ", p, **6**) && *(p + 8) != '0')

**Comment by seven1240** [comment]
should be 7 including the space

**Comment by lazedo** [comment]
@seven1240 @infook-liu sorry, missed the **space**

**Comment by andywolk** [comment]
See https://github.com/signalwire/freeswitch/pull/1615
