### ISSUE TITLE
You must install libmariadb-dev to build mod_mariadb

### ISSUE THREAD

**Issue by itlidaye** [signalwire/freeswitch#1611]
Describe
Compiling mod_mariadb error on Ceontos7

To Reproduce

Uncomment databases/mod_mariadb in modules.conf.
./configure
make
Expected behavior
Compile successfully.

Package versions

Freeswitch version 1.10.7
Centos version 7.9

logs

making all mod_mariadb
make[4]: Entering directory `/opt/freeswitch-1.10.7.-release/src/mod/databases/mod_mariadb'
Makefile:998: *** You must install libmariadb-dev to build mod_mariadb. MariaDB supports non-blocking operations starting with version 5.5.21. libmariadb version should be >= 3.0.9 to support MySQL 8.0.  Stop.
make[4]: Leaving directory `/opt/freeswitch-1.10.7.-release/src/mod/databases/mod_mariadb'
make[3]: *** [mod_mariadb-all] Error 1
make[3]: Leaving directory `/opt/freeswitch-1.10.7.-release/src/mod'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/freeswitch-1.10.7.-release/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/freeswitch-1.10.7.-release'
make: *** [all] Error 2

mariadb version

[root@722ff040aba3 freeswitch-1.10.7.-release]# rpm -qa | grep mariadb
mariadb-libs-5.5.68-1.el7.x86_64
mariadb-devel-5.5.68-1.el7.x86_64
[root@722ff040aba3 freeswitch-1.10.7.-release]# yum list installed |grep mariadb
mariadb-devel.x86_64                1:5.5.68-1.el7               @base          
mariadb-libs.x86_64                 1:5.5.68-1.el7

**Comment by andywolk** [comment]
You need to install mariadb-connector-c https://files.freeswitch.org/repo/yum/centos-release/7/x86_64/mariadb-connector-c-devel-3.0.10-2.el7.centos.x86_64.rpm

**Comment by FlowerGhost** [comment]
Same problem...need your help
my env is in docker freeswitch 1.10.7 ,now want to compiler mod_mariadb.so
i use mariadb-connector-c-3.3.5-src.tar.gz  and  
![image](https://github.com/signalwire/freeswitch/assets/28777365/92b2e25b-599e-40d0-a4e8-51edaff57944)
libmariadb-dev already install,but also Send a warning

**Comment by xiaoyue26** [comment]
> You need to install mariadb-connector-c https://files.freeswitch.org/repo/yum/centos-release/7/x86_64/mariadb-connector-c-devel-3.0.10-2.el7.centos.x86_64.rpm

This download address requires an account and password
