### ISSUE TITLE
building freeswitch fails in ubuntu

### ISSUE THREAD

**Issue by mridullpandey** [signalwire/freeswitch#1613]
making all mod_pgsql
make[4]: Entering directory '/usr/src/freeswitch-1.10.3.-release/src/mod/databases/mod_pgsql'
  CC       mod_pgsql_la-mod_pgsql.lo
mod_pgsql.c: In function ‘pgsql_next_result_timed’:
mod_pgsql.c:722:3: error: enumeration value ‘PGRES_PIPELINE_SYNC’ not handled in switch [-Werror=switch]
  722 |   switch (res->status) {
      |   ^~~~~~
mod_pgsql.c:722:3: error: enumeration value ‘PGRES_PIPELINE_ABORTED’ not handled in switch [-Werror=switch]
cc1: all warnings being treated as errors
make[4]: *** [Makefile:706: mod_pgsql_la-mod_pgsql.lo] Error 1
make[4]: Leaving directory '/usr/src/freeswitch-1.10.3.-release/src/mod/databases/mod_pgsql'
make[3]: *** [Makefile:705: mod_pgsql-all] Error 1
make[3]: Leaving directory '/usr/src/freeswitch-1.10.3.-release/src/mod'
make[2]: *** [Makefile:609: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/freeswitch-1.10.3.-release/src'
make[1]: *** [Makefile:3577: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/freeswitch-1.10.3.-release'
make: *** [Makefile:1292: all] Error 2

following tutorial: https://computingforgeeks.com/how-to-install-freeswitch-pbx-on-ubuntu/

**Comment by mridullpandey** [comment]
making all mod_pgsql
make[4]: Entering directory '/home/lenove/libks/sofia-sip/spandsp/freeswitch-1.10.5/src/mod/databases/mod_pgsql'
  CC       mod_pgsql_la-mod_pgsql.lo

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/commit/9f26a15220b8b8b09c4debe41fe395d25d4cfeec
Please try latest master. But keep in mind that we do not officially support Ubuntu.
