### ISSUE TITLE
FreeSWITCH 1.10.7 unable to set autocommit off using ODBC connector with Mariadb 10.5

### ISSUE THREAD

**Issue by DDaanniieellG** [signalwire/freeswitch#1617]
I am trying to configure a Galera Cluster with 3 MariaDB v10.5 databases and a FreeSWITCH v1.10.7 connected to it over a unixODBC connector v2.3.9. The connection is good and the transactions are handled well, but the FreeSWITCH console goes into an infinite loop printing this error message:

```
[CRIT] switch_core_sqldb.c:2111 ERROR [Unable to Set AutoCommit Off--1], [db="freeswitch",type="odbc"]
[CRIT] switch_core_sqldb.c:2111 ERROR [Unable to Set AutoCommit Off--1], [db="freeswitch",type="odbc"]
[CRIT] switch_core_sqldb.c:2111 ERROR [Unable to Set AutoCommit Off--1], [db="freeswitch",type="odbc"]
[CRIT] switch_core_sqldb.c:2111 ERROR [Unable to Set AutoCommit Off--1], [db="freeswitch",type="odbc"]
```

With FreeSWITCH v1.10.2 it works very well and those error messages do not appear at all. But I want to use the latest version of FreeSWITCH - v1.10.7 (October 24, 2021). MariaDB and the unixODBC connector are also the latest versions.
Can someone please help me resolve this issue?

**Comment by andywolk** [comment]
have you tried using mod_mariadb?

**Comment by andywolk** [comment]
We have not tested FreeSWITCH with Galera Cluster and it may not work at all. Patches are welcome.

**Comment by DDaanniieellG** [comment]
I did not try because I couldn't find a good explanation for how to use mod_mariadb. I will try to search some more and will come back to you later. Any help with some documentation or some tips would be very much appreciated. Thank you for your quick response!

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/blob/master/conf/vanilla/autoload_configs/pre_load_modules.conf.xml
https://github.com/signalwire/freeswitch/blob/master/conf/vanilla/autoload_configs/switch.conf.xml#L185

Also you may have to configure other modules too. Like profiles in mod_sofia
https://github.com/signalwire/freeswitch/blob/master/conf/vanilla/sip_profiles/internal.xml#L240

**Comment by DDaanniieellG** [comment]
I managed to partially solve the issue but some modules don't work using mod_mariadb (mod_sofia, mod_db).
When I set auto-create-schemas and auto-clear-sql to true, FreeSWITCH creates some tables in the cluster, but not all of them (all sip_ tables are not created in the cluster). After FreeSWITCH restart, these tables are created locally because they can't be created in the cluster. Any idea why this is happening?

**Comment by andywolk** [comment]
Hard to tell without logs. May be it needs an index and an auto-increment field to be?

**Comment by scambra** [comment]
I had to disabled autocommit in mariadb adding autocommit=0 to [mysqld] section, otherwise freeswitch was flooding log with this error.

I had an issue creating tables, it failed to create channels table, because row size was too large, I had to create the table manually, changing application_data and presence_data to TEXT instead of VARCHAR(4096), as freeswitch does when using mod-mariadb

**Comment by scambra** [comment]
I got these error in the log again, although autommit is disabled in config, checked with:

```
sudo mysql -e "select @@autocommit"
+--------------+
| @@autocommit |
+--------------+
|            0 |
+--------------+
```

Is there anything else to prevent getting this line flooding the logs?

**Comment by scambra** [comment]
I thought disabling autocommit by default in mariadb would prevent this issue, but switch_core_sqldb.c enables and disables autocommit:

* Line 1001 disables autocommit: https://github.com/signalwire/freeswitch/blob/bf62bd8a7fd01339f4251cc23311b95ed768b109/src/switch_core_sqldb.c#L1001
* Line 1041 enables autocommit: https://github.com/signalwire/freeswitch/blob/bf62bd8a7fd01339f4251cc23311b95ed768b109/src/switch_core_sqldb.c#L1041

I don't know why it's needed, and why it fails to disable autocommit, it looks like result is 1, but SWITCH_ODBC_SUCCESS is 0, although SWITCH_ODBC_FAIL is -1. I found 1 is SQL_SUCCESS_WITH_INFO, so maybe line 1001 should check result >= 0

**Comment by andywolk** [comment]
See if that helps https://github.com/signalwire/freeswitch/pull/1773
