### ISSUE TITLE
Whether freeswitch supports e.164 format number tel: in the sip uri, from, to header fields

### ISSUE THREAD

**Issue by yine** [signalwire/freeswitch#1624]
1. **Question**: I would like to ask you how to change the sip: in the uri, from, to in the invite message sent by freeswitch to tel: ？
2. **Try**: Try using sip_invite_req_uri=tel:+701611183@4.0.146.4:5060 directly, and prompt: URL Error! tel: uri's not supported at this time. See the following code in the sofia_glue.c source code:
```
if (url_str) {
    char *s = NULL;
    if (!strncasecmp(url_str, "sip:", 4)) {
        s = url_str + 4;
    }
    if (!strncasecmp(url_str, "sips:", 5)) {
        s = url_str + 5;
    }
    /* tel: patch from jaybinks, added by MC It compiles but I don't have a way to test it*/
    if (!strncasecmp(url_str, "tel:", 4)) {
        switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(tech_pvt->session),
        SWITCH_LOG_ERROR, "URL Error! tel: uri's not supported at this time\n");
        return SWITCH_STATUS_FALSE;
    }
    if (!s) {
        s = url_str;
    }
    switch_channel_set_variable(channel, "sip_req_uri", s);
}
```

3. I would like to ask teachers, whether freeswitch supports the e.164 number format portability: tel: prefix number format, and how to deal with it?

**Comment by yine** [comment]
resolved.  Modify mod_sofia, libsofia-sip-ua module. Release judgment condition

**Comment by nr-jorge** [comment]
Hello @yine i am tying to fix the same issue would help me with it, i also want to change the sip uri to tel
