### ISSUE TITLE
apt-get install freeswitch-meta-all returning "Unable to locate package freeswitch-meta-all"

### ISSUE THREAD

**Issue by JayCarpenter** [signalwire/freeswitch#163]
Trying to install FreeSWITCH today with:

apt-get update && apt-get install -y freeswitch-meta-all

Returns:

E: Unable to locate package freeswitch-meta-all

**Comment by andywolk** [comment]
You need to setup FreeSWITCH repo first:
https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster
I'm closing this. Please reopen if there is still a problem.

**Comment by einsiedlerkrebs** [comment]
root@sip:~# cat /etc/apt/sources.list.d/freeswitch.list
deb http://files.freeswitch.org/repo/deb/debian-release/ stretch main
deb-src http://files.freeswitch.org/repo/deb/debian-release/ stretch main
root@sip:~# apt search freeswitch-meta-all && echo "Return Success: $?"
Sorting... Done
Full Text Search... Done
Return Success: 0

**Comment by andywolk** [comment]
What architecture are you using? 
`uname -a`

**Comment by einsiedlerkrebs** [comment]
`debian in a linux container (on OpenWRT)

**Comment by andywolk** [comment]
What CPU architecture?

**Comment by einsiedlerkrebs** [comment]
ah ja, this is relevant of course. armv7l Sorry:
`Linux sip 4.4.202-a890a5a94ebb621f8f1720c24d12fef1-0 #1 SMP Sat Nov 16 20:08:40 CET 2019 armv7l GNU/Linux`

**Comment by andywolk** [comment]
But we provide `armhf` and it's in a different repo: https://freeswitch.org/confluence/display/FREESWITCH/Raspberry+Pi

**Comment by einsiedlerkrebs** [comment]
Oh, I didn't see this. Thanks and sorry.
