### ISSUE TITLE
RTP redirect to other conference

### ISSUE THREAD

**Issue by research4me** [signalwire/freeswitch#1630]
Hi, 

I am trying to redirect RTP stream of one client from one conference to another. 
Let's say SIP client A calls conference 3001, he gets RTP port of this conference and starts sending his RTP packets to this port, so that other clients in conference 3001 can hear him. Now I would like to transfer his RTP stream to conference 3002 (so to RTP port of this conference) without him knowing; so without additional SIP negotiation. 
I am thinking something about using some kind of proxy, maybe RTP proxy, so that port for client A to send RTP packets to will always be the same, but when I call some action on this proxy, this proxy would redirect RTP stream from conference's 3001 port to conference's 3002 port. 
This manipulation, which user's stream to which conference's port, should be done dynamically from remote application, so with some kind of call (REST, ... anything). 

Any advice to start research on what to use is very useful. 

Thank you, BR

**Comment by seven1240** [comment]
you can just use `uuid_transfer` or `conference transfer` transfer the call to another conference, there's no re-INVITE.

Questions goes to the mailing list btw.
