### ISSUE TITLE
Freeswitch repository is asking for name and password

### ISSUE THREAD

**Issue by flaviogoncalves** [signalwire/freeswitch#1635]
**Describe the bug**
When trying to install freeswitch the system is asking for name and password:

![image](https://user-images.githubusercontent.com/4958202/163846675-a2aa735f-e04b-472a-a151-502c2a74ac07.png)

**To Reproduce**
Try to download: 
https://files.freeswitch.org/repo/deb/debian-release/freeswitch-archive-keyring.gpg

**Expected behavior**
Downloads used to be open

**Comment by andywolk** [comment]
Please read updated instruction:
https://freeswitch.org/confluence/display/FREESWITCH/Debian

**Comment by flaviogoncalves** [comment]
Sorry, I've just read that you now require signalwire passwords.
