### ISSUE TITLE
The best way to detect if user's phone ringed for outbound call

### ISSUE THREAD

**Issue by lewiszlw** [signalwire/freeswitch#1649]
Hi team,

We use freeswitch to outbound call to users. Recently we are focusing on monitoring calls and want to know how many calls arrived at users' phones and maked their phones ringing. I googled, read freeswitch wikis, found some ways but not very good
1. use mod_spandsp start_tone_detect feature (it seems can't detect CRBT)
2. record early media and compare to standard ringtones prepared in local (need collect as much as standard ringtones in advance)

Really appreciate if you have better way.

P.S. Our systems are in China and only outbound call China users.

**Comment by hien** [comment]
Hello @lewiszlw ,

I'm finding same answer for that. Did you find solutions?

Thanks.
