### ISSUE TITLE
hi guys, does freeswitch offer a alarm notification via email to inform if the sip connections goes down?

### ISSUE THREAD

**Issue by francisit20** [signalwire/freeswitch#1664]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Package version or git hash**
- Version of FreeSWITCH [e.g. 1.10.4]

**Comment by dragos-oancea** [comment]
We have (ESL) events for this. eg: MY_EVENT_GATEWAY_DEL . You'd need a client that catches these events and then consume them in whatever way you see fit in your platform.
