### ISSUE TITLE
sms

### ISSUE THREAD

**Issue by elileo1** [signalwire/freeswitch#167]
2019-12-06 10:55:42.242953 [INFO] mod_sms.c:368 Processing text message 1002->1001 in context public
2019-12-06 10:55:42.242953 [INFO] mod_sms.c:495 CHANNEL_DATA:
Event-Name: [MESSAGE]
Core-UUID: [550efefc-c187-4af7-992a-3ef191ddc5ac]
FreeSWITCH-Hostname: [DESKTOP-64KOHCD]
FreeSWITCH-Switchname: [DESKTOP-64KOHCD]
FreeSWITCH-IPv4: [172.16.30.40]
FreeSWITCH-IPv6: [::1]
Event-Date-Local: [2019-12-06 10:55:42]
Event-Date-GMT: [Fri, 06 Dec 2019 02:55:42 GMT]
Event-Date-Timestamp: [1575600942242953]
Event-Calling-File: [sofia_presence.c]
Event-Calling-Function: [sofia_presence_handle_sip_i_message]
Event-Calling-Line-Number: [4882]
Event-Sequence: [650]
login: [sip:mod_sofia@103.84.139.98:5060]
proto: [sip]
to_proto: [sip]
from: [1002@172.16.211.18]
from_user: [1002]
from_host: [172.16.211.18]
to_user: [1001]
to_host: [172.16.30.40]
from_sip_ip: [172.16.211.18]
from_sip_port: [47322]
to: [1001@172.16.30.40]
subject: [SIMPLE MESSAGE]
context: [public]
type: [message/imdn+xml]
from_full: [<sip:1002@172.16.211.18>;tag=IHSM5NVa9]
sip_profile: [internal]
dest_proto: [sip]
max_forwards: [70]
DP_MATCH: [1001@172.16.30.40]
Content-Length: 200

x渕徎n!D裞6+俋苠?輱筙H伺Zp旤阶E?i缣慺埋??譤蚛?gH棖

my message type is text/plain, why it is message/imdn+xml, how can i config it

**Comment by briankwest** [comment]
What ever sent it was what set the content type and contents, please reopen if you can provide steps or a test case to exhibit the behavior.
