### ISSUE TITLE
[mod_callcenter] support in a multi FS shared DB setup (error: Member xxx <xxx> with uuid xxx in queue xxx@domain.com is gone just before we assigned an agent)

### ISSUE THREAD

**Issue by ccppprogrammer** [signalwire/freeswitch#1674]
**Is your feature request related to a problem? Please describe.**

Right now it's not possible to run `mod_callcenter` in a multi FS shared DB setup as mentioned in the [documentation](https://freeswitch.org/confluence/display/FREESWITCH/mod_callcenter):
`WARNING: Agents and Tiers XML config shouldn't be used in a multi FS shared DB setup.`

If you try to run `mod_callcenter` on a shared DB setup with multiple FS, you will encounter random agent unavailability with this error:
```
2022-06-01 14:42:06.038488 77.73% [DEBUG] mod_callcenter.c:1180 Updated Agent 6f2f4271-0b6d-4c6f-9a22-c3f404f73b51 set state = Receiving
2022-06-01 14:42:06.038488 77.73% [DEBUG] mod_callcenter.c:1705 Member xxx <xxx> with uuid 6652dfaf-0b5d-4f4f-8db1-3438cf865cc6 in queue xxx@domain.com is gone just before we assigned an agent
2022-06-01 14:42:06.058488 77.73% [DEBUG] mod_callcenter.c:1180 Updated Agent 6f2f4271-0b6d-4c6f-9a22-c3f404f73b51 set state = Waiting
```

For more than 6 years, this problem has been periodically discussed, but so far `mod_callcenter` still cannot be used in a multi FS shared DB setup.
* [FreeSWITCH active-active mod_callcenter](https://groups.google.com/g/freeswitch-ru/c/2YOQjwwckB8)
* [FreeSWITCH Active Active Callcenter with shared DB](https://stackoverflow.com/questions/44427980/freeswitch-active-active-callcenter-with-shared-db)
* [[Freeswitch-users] mod_callcenter with Active/Backup Freeswitch servers using a shared mysql database](https://freeswitch-users.freeswitch.narkive.com/qT3g2wyi/mod-callcenter-with-active-backup-freeswitch-servers-using-a-shared-mysql-database)
* [[Freeswitch-users] mod_callcenter multiserver doesn't work](https://lists.freeswitch.org/pipermail/freeswitch-users/2015-November/117015.html)

**Describe the solution you'd like**

Be able to use `mod_callcenter` in a multi FS shared DB setup.

**Package version or git hash**
- FreeSWITCH Version 1.10.7-release-19-883d2cb662~64bit (-release-19-883d2cb662 64bit)

**Comment by greenbea** [comment]
I don't think the freeswitch team has any interest in improving mod_callcenter

**Comment by ccppprogrammer** [comment]
> @greenbea I don't think the freeswitch team has any interest in improving mod_callcenter

Why do you think so?

**Comment by greenbea** [comment]
mod_callcenter is missing a lot of features and has a lot of bugs, but it didn't advance in the last few years. See it yourself

**Comment by ccppprogrammer** [comment]
> @greenbea greenbea mod_callcenter is missing a lot of features and has a lot of bugs, but it didn't advance in the last few years. See it yourself

I know, but no one has ever created feature requests, so we can't know how much the development team is interested or not in this module. That's why I asked you how you know and what your opinion is based on. Let's see what the developers have to say.

**Comment by ccppprogrammer** [comment]
@italorossi Thanks for the tip! 👍

**Comment by JaimeGinorio** [comment]
Any updates or workarounds on this?
