### ISSUE TITLE
freeswitch repository not working

### ISSUE THREAD

**Issue by bharat-ux** [signalwire/freeswitch#1677]
my repo base url
baseurl=http://files.freeswitch.org/yum/$releasever

Error: Cannot retrieve repository metadata (repomd.xml) for repository: freeswitch-source. Please verify its path and try agai

**Comment by andywolk** [comment]
Please follow our instruction.
https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7
