### ISSUE TITLE
make编译出了错误install-recursive

### ISSUE THREAD

**Issue by ZhangBinTing** [signalwire/freeswitch#168]
/Library/Developer/CommandLineTools/usr/bin/make  install-recursive
  CC       src/libfreeswitch_la-switch_core_cert.lo
src/switch_core_cert.c:39:20: error: unused function 'switch_ssl_ssl_lock_callback' [-Werror,-Wunused-function]
static inline void switch_ssl_ssl_lock_callback(int mode, int type, char *file, int line)
                   ^
src/switch_core_cert.c:49:29: error: unused function 'switch_ssl_ssl_thread_id' [-Werror,-Wunused-function]
static inline unsigned long switch_ssl_ssl_thread_id(void)
                            ^
2 errors generated.
make[1]: *** [src/libfreeswitch_la-switch_core_cert.lo] Error 1
make: *** [install] Error 2

**Comment by seven1240** [comment]
what version you try to compile? and what's your openssl version? please install the latest openssl and clone the master branch in a clean dir and try again.

**Comment by foermo4-hao** [comment]
the same issue with openssl@1.1

**Comment by foermo4-hao** [comment]
> what version you try to compile? and what's your openssl version? please install the latest openssl and clone the master branch in a clean dir and try again.

the same issue with openssl@1.1 in macOs

**Comment by teresalazar13** [comment]
same issue here

**Comment by akafanfan** [comment]
same problem

**Comment by Sacherer** [comment]
same issue here。How to solve it?

**Comment by yjmyzz** [comment]
> same issue here。How to solve it?

you can refer this https://github.com/signalwire/freeswitch/issues/176

**Comment by placebokkk** [comment]
This error is cause by [-Werror,-Wunused-function]. The compiler treat Warning as Error. 

In acutualy, CRYPTO_set_id_callback and CRYPTO_set_locking_callback have been deprecated in crypto library
in
> /usr/local/Cellar/node/11.12.0/include/node/openssl/crypto.h

you could see.
```
line 213
# define CRYPTO_set_locking_callback(func)
line 243
# define CRYPTO_set_id_callback(func)
```

So switch_ssl_ssl_lock_callback and switch_ssl_ssl_thread_id is not used and  [-Werror,-Wunused-function] compiler opt will raise error.

The fix method is below:

1. remove the definition of switch_ssl_ssl_lock_callback and switch_ssl_ssl_thread_id
2. set 

```
CRYPTO_set_id_callback(switch_ssl_ssl_thread_id);
CRYPTO_set_locking_callback((void (*)(int, int, const char*, int))switch_ssl_ssl_lock_callback);

```
to

```
CRYPTO_set_id_callback(NULL);
CRYPTO_set_locking_callback(NULL);
```

or just delete this two lines.

**Comment by crienzo** [comment]
closing duplicate
