### ISSUE TITLE
[    ERR] switch_ivr_play_say.c:00262 Setting playback volume to 0

### ISSUE THREAD

**Issue by marcellinog** [signalwire/freeswitch#1682]
**Describe the bug**
After upgrading to the latest version, we noticed in our logs the error
2022-06-07 10:14:00.799952 87.80% [  DEBUG] switch_ivr_play_say.c:00250 Handle play-file:[voicemail/vm-press.wav] (en:en)
2022-06-07 10:14:00.799952 87.80% [    ERR] switch_ivr_play_say.c:00262 Setting playback volume to 0
2022-06-07 10:14:00.799952 87.80% [  DEBUG] switch_ivr_play_say.c:01572 Codec Activated L16@8000hz 1 channels 20ms

**To Reproduce**
IVR interactions, including voicemails

**Expected behavior**
No error in the logs

**Package version or git hash**
FreeSWITCH Version 20.22.1-release+git~20220526T162932Z~5d353b7d6c~64bit (git 5d353b7 2022-05-26 16:29:32Z 64bit)

**Trace logs**
8f0361b5-ebcb-4a31-85d2-6ed558de2103 2022-06-07 09:22:50.219967 90.87% [  DEBUG] switch_ivr_play_say.c:02021 done playing file file_string://digits/1.wav
8f0361b5-ebcb-4a31-85d2-6ed558de2103 2022-06-07 09:22:50.219967 90.87% [  DEBUG] switch_ivr.c:00195 Codec Activated L16@8000hz 1 channels 20ms
8f0361b5-ebcb-4a31-85d2-6ed558de2103 2022-06-07 09:22:50.339951 90.87% [  DEBUG] switch_ivr_play_say.c:00250 Handle play-file:[voicemail/vm-listen_to_recording.wav] (en:en)
8f0361b5-ebcb-4a31-85d2-6ed558de2103 2022-06-07 09:22:50.339951 90.87% [    ERR] switch_ivr_play_say.c:00262 Setting playback volume to 0
8f0361b5-ebcb-4a31-85d2-6ed558de2103 2022-06-07 09:22:50.339951 90.87% [  DEBUG] switch_ivr_play_say.c:01572 Codec Activated L16@8000hz 1 channels 20ms

Error was never observed before upgrade.
Please advise.

**Comment by dragos-oancea** [comment]
even if it says the volume is 0, is it audible ?
does ``` <action function="play-file" volume="10" data="voicemail/vm-press.wav"/>``` work in the sense that is actually taking the volume value? The log message printed with log level ERR is not really an error.

**Comment by dragos-oancea** [comment]
https://github.com/signalwire/freeswitch/pull/1684
