### ISSUE TITLE
CF_AUDIO flag not set by mod_portaudio

### ISSUE THREAD

**Issue by GitHubIsShortOnUsernames** [signalwire/freeswitch#169]
This is a confirmation of https://freeswitch.org/jira/browse/FS-10705

There is no audio coming from portaudio channels in 1.8 or 1.10. Confirmed on a setup which works with 1.6

Setting the CF_AUDIO flag in mod_portaudio.c channel_outgoing_channel() and channel_on_init() fixes it, though not sure if that would be the correct way to do it.

**Comment by anthmFS** [comment]
Yes, that is the correct fix.

**Comment by covici** [comment]
Can you give us the patch, I cannot log into jira to find the old issue.

**Comment by GitHubIsShortOnUsernames** [comment]
Use at your own risk.

[mod_portaudio.patch.zip](https://github.com/signalwire/freeswitch/files/3945773/mod_portaudio.patch.zip)

**Comment by covici** [comment]
Thanks, preliminary testing indicates its working.  Very nice and I
can use the console again.

On Tue, 10 Dec 2019 10:54:57 -0500,
GitHubIsShortOnUsernames wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> Use at your own risk.
> 
> [mod_portaudio.patch.zip](https://github.com/signalwire/freeswitch/files/3945773/mod_portaudio.patch.zip)
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/169#issuecomment-564099309
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

**Comment by dragos-oancea** [comment]
@GitHubIsShortOnUsernames , can you do a PR ?
