### ISSUE TITLE
flag SWITCH_RTP_FLAG_AUDIO_FIRE_SEND_RTCP_EVENT always  0

### ISSUE THREAD

**Issue by 406112767** [signalwire/freeswitch#1694]
siwtch_core_media.c
function switch_core_media_activate_rtp
when set fire_rtcp_events=true
will be set SWITCH_RTP_FLAG_AUDIO_FIRE_SEND_RTCP_EVENT = 1
but next code always reset flags 
so flag SWITCH_RTP_FLAG_AUDIO_FIRE_SEND_RTCP_EVENT always 0

**siwtch_core_media.c:** 8681
> if (switch_channel_var_true(session->channel, "fire_rtcp_events")) {
		flags[SWITCH_RTP_FLAG_AUDIO_FIRE_SEND_RTCP_EVENT] = 1;
		if (switch_channel_test_flag(session->channel, CF_VIDEO_POSSIBLE) &&
			switch_channel_var_true(session->channel, "rtp_video_send_rtcp_message_event")) {
			flags[SWITCH_RTP_FLAG_VIDEO_FIRE_SEND_RTCP_EVENT] = 1;
		}
	}

**siwtch_core_media.c:** 8710
> memset(flags, 0, sizeof(flags));
	flags[SWITCH_RTP_FLAG_DATAWAIT]++;

**Comment by dragos-oancea** [comment]
this has been fixed in master branch a while ago.
