### ISSUE TITLE
switch_rtp_pcap build make error due to #1585

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1704]
**Describe the bug**
 Error below stops make due to #1585

 CCLD     switch_sip
  CC       switch_rtp_pcap.o
switch_rtp_pcap.c:79:24: error: unused function 'test_calc_local_lsr_now' [-Werror,-Wunused-function]
static inline uint32_t test_calc_local_lsr_now(switch_time_t now, uint32_t past /*milliseconds*/) 
                       ^
1 error generated.
make[2]: *** [switch_rtp_pcap.o] Error 1
make[1]: *** [all-recursive] Error 1

This is on macOS Monterey

**To Reproduce**
make

**Expected behavior**
clean make

**Package version or git hash**
 - Version June 29 Master

**Comment by andywolk** [comment]
See if that helps https://github.com/signalwire/freeswitch/pull/1705

**Comment by MarioG-X** [comment]
Yes that did it, thanks! Sorry it took so long I had to stumble around to put in fix then make decided to remake almost everything so it took a while. I brought it up to test.

**Comment by andywolk** [comment]
No problem. Good catch!
