### ISSUE TITLE
vm_fsdb_msg_list broken if you use optional ASC or DESC argument

### ISSUE THREAD

**Issue by MartinJPaterson** [signalwire/freeswitch#1709]
**Describe the bug**
If you use vm_fsdb_msg_list with the optional ASC or DESC argument, then it fails with error:
-ERR Bad Argument: 'ASC'

This is because the validation of the ASC and DESC argument is broken. It does:
```
	} else if (strcasecmp(msg_order, "ASC") || strcasecmp(msg_order, "DESC")) {
		stream->write_function(stream, "-ERR Bad Argument: '%s'\n", msg_order);
```

The || should clearly be &&.

**Comment by dragos-oancea** [comment]
https://github.com/signalwire/freeswitch/pull/1710
