### ISSUE TITLE
Cannot  send sip message "181 Call is being forwarded" via "respond"

### ISSUE THREAD

**Issue by Dgeka25594** [signalwire/freeswitch#1711]
**Describe the bug**
I'm setting up a test lab IMS kamailio (IMS core) + FS (Application Server) and I want to get forwarding. Everything works as it should except FreeSWITCH cannot  send sip message "181 Call is being forwarded" via "respond"

**To Reproduce**
1. dialplan config:
```
<extension name="local_call_ims" continue="true" uuid="ed335d98-d6df-4357-9529-39c3e0448b5c">
	<condition field="destination_number" expression="^(\d{3,16})$">
		<action application="export" data="call_direction=inbound" inline="true"/>
		<action application="set" data="domain_uuid=5adf1663-d133-4e8c-9e5d-21c71ea1454e" inline="true"/>
		<action application="set" data="domain_name=ims.mnc001.mcc001.3gppnetwork.org" inline="true"/>
		<action application="set" data="forwarding_number=79160000113"/>
		<action application="respond" data="181"/>
		<action application="set" data="sip_h_History-Info=<sip:${destination_number}@${domain_name}?Reason=SIP%3Bcause%3D302>index=1,<sip:${}@${forwarding_number};user=phone>;index=1.1"/>
		<action application="bridge" data="sofia/external_TAS/${forwarding_number}@${domain_name}"/>
	</condition>
</extension>
```
3. Subscriber A calls subscriber B, who is forwarded to subscriber C
4. The config specifies that the FreeSWITCH should send subscriber A sip response status 183
5. In the FreeSWITCH logs, the message 
```
EXECUTE [depth=0] sofia/external_TAS/79160000110@ims.mnc001.mcc001.3gppnetwork.org respond(181)
2022-07-06 16:43:12.790869 96.97% [DEBUG] mod_sofia.c:2351 Responding with 181 [Call Is Being Forwarded]
2022-07-06 16:43:12.790869 96.97% [WARNING] mod_sofia.c:2419 Cannot respond.
```
 and no more error information is visible.

**Expected behavior**
FreeSWITCH sends a response with status 183 to subscriber A

**Package version or git hash**
 - FreeSWITCH Version 1.10.7-release~64bit (-release 64bit)

**Trace logs**
Attache
[fs_log.txt](https://github.com/signalwire/freeswitch/files/9055257/fs_log.txt)

**Comment by Dgeka25594** [comment]
Does anyone have any idea how to get more information or how to deal with this error?
`2022-07-06 16:43:12.790869 96.97% [WARNING] mod_sofia.c:2419 Cannot respond.`
The problem is with sending informational messages 1xxx, if you send messages for an example of type 4xx, then FS sends them

**Comment by zusrut** [comment]
according this [link to code](https://github.com/signalwire/freeswitch/blob/19a7debc1b44b48e072482584f844acbde119091/src/mod/endpoints/mod_sofia/mod_sofia.c#L2419)

its not gonna work with codes less then 399

**Comment by justinmarkr** [comment]
Hi @Dgeka25594,

I'm trying to integrate also the Kamailio IMS and FS. Can you share how you configure the Kamailio and FS?

**Comment by Dgeka25594** [comment]
> I'm trying to integrate also the Kamailio IMS and FS. Can you share how you configure the Kamailio and FS?

Thanks, I saw it in the code.

**Comment by Dgeka25594** [comment]
> Hi @Dgeka25594,
> 
> I'm trying to integrate also the Kamailio IMS and FS. Can you share how you configure the Kamailio and FS?

Hello!
this is not the topic of this topic, I close the question, but you can write to me about Kamailio IMS + FS by mail dgeka25594@gmail.com. Whatever I can, I'll help.

**Comment by justinmarkr** [comment]
Hi @Dgeka25594

I've send an email regarding my questions about Kamailio IMS + FS. Thank you
