### ISSUE TITLE
dialog-info+xml can exceed MTU

### ISSUE THREAD

**Issue by yois615** [signalwire/freeswitch#1720]
**Describe the bug**
When using UDP as the SIP transport for mod_sofia, if long domain names and extension names are used, the packet length can easily exceed 1514 bytes, resulting in packet fragmentation.

**To Reproduce**
1. Create a domain called some-long-domain-name.longdomain.example
2. Create two extensions with long numeric values like 12125551212
3. Subscribe the first extension to the second extension for BLF NOTIFY
4. Capture the packets being sent to the subscriber, they are fragmented and not delivered

**Expected behavior**
Packet length should be optimized to strip extraneous data.

**Package version or git hash**
 - Version 1.10.7

**Additonal Notes**
Upon packet capture, it became clear that this function:
https://github.com/signalwire/freeswitch/blob/0365becc0dc43d2c5c002ae8d2653692e6e01f21/src/mod/endpoints/mod_sofia/sofia.c#L3321
Is injecting the Allow:, Allow_events:, and Supported: SIP header tags into every packet.  This is does not appear to be required by RFC-4235 and causes unnecessary data bloat.

**Comment by mjerris** [comment]
these headers are needed by some endpoints… if using protocols that approach mtu it’s recommended (and required by rfc) to support tcp making things smaller to avoid mtu is a losing battle.  you can enable compressed headers to gain a bit more room
