### ISSUE TITLE
I am getting an error when loading mod_av module but not sure if it is a bug

### ISSUE THREAD

**Issue by huangqingbiao8831** [signalwire/freeswitch#1722]
I get the following error when loading mod_av：
2022-07-19 16:07:23.096317 [CRIT] switch_loadable_module.c:1522 Error Loading module /usr/local/freeswitch/mod/mod_av.so
**/lib64/libpango-1.0.so.0: undefined symbol: g_object_replace_qdata**
========================================================================
But the link to mod_av has no errors

[root@kvm81_20 mod]# ldd mod_av.so
        linux-vdso.so.1 =>  (0x00007fffd0056000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f924d4b8000)
        libfreeswitch.so.1 => /usr/local/freeswitch/lib/libfreeswitch.so.1 (0x00007f924ce8e000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f924cc89000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f924ca6d000)
        libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x00007f924c7cf000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f924c510000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f924c2a6000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f924c044000)
        libspeex.so.1 => /lib64/libspeex.so.1 (0x00007f924be2b000)
        libspeexdsp.so.1 => /lib64/libspeexdsp.so.1 (0x00007f924bc18000)
        libedit.so.0 => /lib64/libedit.so.0 (0x00007f924b9db000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f924b7b1000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f924b5ad000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f924b376000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f924b16e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f924af58000)
        libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f924ad2d000)
        libavformat.so.57 => /usr/local/freeswitch/lib/libavformat.so.57 (0x00007f924a916000)
        libavcodec.so.57 => /usr/local/freeswitch/lib/libavcodec.so.57 (0x00007f92493e6000)
        libswscale.so.4 => /usr/local/freeswitch/lib/libswscale.so.4 (0x00007f924915f000)
        libavutil.so.55 => /usr/local/freeswitch/lib/libavutil.so.55 (0x00007f9248eda000)
        libswresample.so.2 => /usr/local/freeswitch/lib/libswresample.so.2 (0x00007f9248cbd000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f9248a4b000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f92485e8000)
        libc.so.6 => /usr/local/lib/libc.so.6 (0x00007f924821a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f924d9d2000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9247f12000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9247cfc000)
        libodbc.so.2 => /lib64/libodbc.so.2 (0x00007f9247a94000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9247884000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f9247651000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f9247424000)
        libssl3.so => /lib64/libssl3.so (0x00007f92471c1000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f9246f99000)
        libnss3.so => /lib64/libnss3.so (0x00007f9246c60000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f9246a30000)
        libplds4.so => /lib64/libplds4.so (0x00007f924682c000)
        libplc4.so => /lib64/libplc4.so (0x00007f9246627000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f92463e9000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f924619c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f9245eb3000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f9245c80000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f9245a7c000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f924586d000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f9245618000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f9245415000)
        libmodplug.so.1 => /usr/local/freeswitch/lib/libmodplug.so.1 (0x00007f924508b000)
        libbluray.so.1 => /usr/local/freeswitch/lib/libbluray.so.1 (0x00007f9244e4a000)
        libgnutls.so.28 => /lib64/libgnutls.so.28 (0x00007f9244b10000)
        libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007f924488f000)
        libmfx.so.0 => /usr/local/freeswitch/lib/libmfx.so.0 (0x00007f924467b000)
        libva.so.1 => /usr/local/freeswitch/lib/libva.so.1 (0x00007f924445b000)
        libzvbi.so.0 => /usr/local/freeswitch/lib/libzvbi.so.0 (0x00007f92441cc000)
        libxvidcore.so.4 => /usr/local/freeswitch/lib/libxvidcore.so.4 (0x00007f9243eb9000)
        libx265.so.165 => /usr/local/freeswitch/lib/libx265.so.165 (0x00007f9243831000)
        libx264.so.148 => /usr/local/freeswitch/lib/libx264.so.148 (0x00007f92434d5000)
        libvpx.so.1 => /usr/local/freeswitch/lib/libvpx.so.1 (0x00007f924314d000)
        libvorbisenc.so.2 => /lib64/libvorbisenc.so.2 (0x00007f9242c7e000)
        libvorbis.so.0 => /lib64/libvorbis.so.0 (0x00007f9242a51000)
        libvo-amrwbenc.so.0 => /usr/local/freeswitch/lib/libvo-amrwbenc.so.0 (0x00007f9242837000)
        libtheoraenc.so.1 => /lib64/libtheoraenc.so.1 (0x00007f924260a000)
        libtheoradec.so.1 => /lib64/libtheoradec.so.1 (0x00007f92423fa000)
        librsvg-2.so.2 => /usr/local/freeswitch/lib/librsvg-2.so.2 (0x00007f92421c4000)
        libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f9241e8d000)
        libgobject-2.0.so.0 => /usr/local/lib/libgobject-2.0.so.0 (0x00007f9241c3d000)
        libglib-2.0.so.0 => /usr/local/lib/libglib-2.0.so.0 (0x00007f924191b000)
        libopus.so.0 => /lib64/libopus.so.0 (0x00007f92416cf000)
        libopenjp2.so.7 => /usr/local/freeswitch/lib/libopenjp2.so.7 (0x00007f924147c000)
        libopencore-amrwb.so.0 => /usr/local/freeswitch/lib/libopencore-amrwb.so.0 (0x00007f9241268000)
        libopencore-amrnb.so.0 => /usr/local/freeswitch/lib/libopencore-amrnb.so.0 (0x00007f924103d000)
        libmp3lame.so.0 => /usr/local/lib/libmp3lame.so.0 (0x00007f9240daf000)
        libgsm.so.1 => /lib64/libgsm.so.1 (0x00007f9240ba3000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f9240865000)
        libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f9240654000)
        libva-drm.so.1 => /usr/local/freeswitch/lib/libva-drm.so.1 (0x00007f9240451000)
        libva-x11.so.1 => /usr/local/freeswitch/lib/libva-x11.so.1 (0x00007f924024b000)
        libvdpau.so.1 => /usr/local/freeswitch/lib/libvdpau.so.1 (0x00007f9240047000)
        libOpenCL.so.1 => /usr/local/freeswitch/lib/libOpenCL.so.1 (0x00007f923fe28000)
        libsoxr.so.0 => /lib64/libsoxr.so.0 (0x00007f923fbc5000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f923f9bb000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f923f7ab000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f923f5a7000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f923f38d000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f923f170000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f923ee06000)
        libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f923ebc4000)
        libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007f923e895000)
        libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007f923e682000)
        libnettle.so.4 => /lib64/libnettle.so.4 (0x00007f923e451000)
        libhogweed.so.2 => /lib64/libhogweed.so.2 (0x00007f923e22a000)
        libgmp.so.10 => /usr/local/lib/libgmp.so.10 (0x00007f923dfb2000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f923ddad000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f923dba1000)
        libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007f923d99a000)
        libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f923d772000)
        libgio-2.0.so.0 => /usr/local/lib/libgio-2.0.so.0 (0x00007f923d425000)
        libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f923d217000)
        libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f923d001000)
        libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f923cdbb000)
        libcroco-0.6.so.3 => /lib64/libcroco-0.6.so.3 (0x00007f923cb7f000)
        libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f923c8d6000)
        libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f923c6c2000)
        libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f923c4be000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f923c296000)
        libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f923c088000)
        libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f923be7d000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f923bc6b000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f923b9df000)
        libgthread-2.0.so.0 => /usr/local/lib/libgthread-2.0.so.0 (0x00007f923b7dd000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007f923b5d5000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f923b3cf000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f923b1a9000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f923af82000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f923ad5c000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f923ab32000)
        libgmodule-2.0.so.0 => /usr/local/lib/libgmodule-2.0.so.0 (0x00007f923a92e000)
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f923a691000)
        libthai.so.0 => /lib64/libthai.so.0 (0x00007f923a485000)
        libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f923a269000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f9239fb3000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f9239daf000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f9239b7d000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f923994f000)

glib2 version  glib2-2.56.1-9.el7_9.x86_64

Does anyone know how to solve this problem, thanks!!!!

**Comment by seven1240** [comment]
you should fill all information in the bug report template

**Comment by huangqingbiao8831** [comment]
The problem has been bothering me for two days, can you give me some advice.
