### ISSUE TITLE
session->read_frame_count is not set consistently

### ISSUE THREAD

**Issue by Five9Voice** [signalwire/freeswitch#1723]
Found what looks like a bug in the setting of session->read_frame_count.

In switch_core_io.c (line 151) this assignment is used 

`session->read_frame_count = (session->read_impl.samples_per_second / session->read_impl.samples_per_packet) * session->track_duration;
`

In switch_core_session.c (line 1702) this assignment is used 

`session->read_frame_count = (session->read_impl.samples_per_second / session->read_impl.samples_per_packet) * seconds;
`

The good thing is that session->track_duration is set on line 1687 so seems to be a simple enough matter to add it.

However, the question is: should session->track_duration be used or not used in the calculation of session->read_frame_count.

**Comment by anthmFS** [comment]
"seconds" It's the frequency of the heartbeat event which is stored in "session->track_duration"
Its initialized at 1687 so the 2 are equivalent.

This part is the samples packets per seconds
session->read_impl.samples_per_second / session->read_impl.samples_per_packet

It multiplied by track_duration aka seconds to tell you how many packets read in that interval

**Comment by dragos-oancea** [comment]
so  yes, session->track_duration be used.
