### ISSUE TITLE
RFC 2833 event durations are not correctly transcoded

### ISSUE THREAD

**Issue by weili-jiang** [signalwire/freeswitch#1724]
**Describe the bug**
When FreeSWITCH is being used to transcode between two codecs of different sample rates (e.g. OPUS 48000 and PCMU 8000), the telephone-event duration field from the sender is sent as is to the receiver without sample rate conversion. This causes the events at the receiver to be the wrong duration.

**To Reproduce**
1. Use any dial plan that allows calls between two parties
2. Party A has OPUS 48000 only (with associated RFC 2833 telephone events)
3. Party B has PCMU 8000 only (with associated RFC 2833 telephone events)
4. Set up call between A and B parties, such that FreeSWITCH is transcoding media
5. Send DTMF from party A
6. Observe that FreeSWITCH sends the DTMF events to party B with a duration 6x longer than expected (corresponding exactly to the multiplier 8000 and 48000). This can be very easily seen in the FreeSWITCH debug logs, where the output event is generated with exactly the same raw duration as the input, without any rate conversion.

**Expected behavior**
When FreeSWITCH is transcoding, RFC 2833 event durations must be rate converted to adjust for different sample rates between the two codecs being used by the A and B parties.

**Package version or git hash**
 - Version 1.10.7

**Trace logs**
[log.txt](https://github.com/signalwire/freeswitch/files/9157744/log.txt)

Observe that a telephone-event duration of 13440 is received with an OPUS sample clock, and incorrectly sent out without conversion down to PCMU sample clock.

**backtrace from core file**
N/A

**Comment by dragos-oancea** [comment]
```2022-07-21 08:35:59.331976 97.67% [DEBUG] sofia.c:7509 Remote SDP:
v=0
o=- 3787180761 203582922 IN IP4 w.w.w.w
s=-
c=IN IP4 w.w.w.w
t=0 0
a=bbbUserAgent
m=audio 51708 RTP/SAVP 102 101
a=rtpmap:102 opus/48000/2
a=fmtp:102 stereo=0;sprop-stereo=0;maxaveragebitrate=12000;maxplaybackrate=8000;cbr=0;useinbandfec=0;usedtx=0
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=label:1
a=rtcp-rsize
a=ssrc:2723759726 cname:sip:999@sipcore
a=ptime:20
a=crypto:2 AEAD_AES_256_GCM inline:9a65rVI7aBJ7D21b5J5gB4zExeXtmeZmvM+GflMRut46cEAwHUABlSlZ5n8=
```

Remote telephone-event  must be at the rate of the audio codec, in this case 48000.
FS is actually offering one at 48000. You should make the UA answer with the right rate for telephone-event.
Please reopen if is still problematic.
