### ISSUE TITLE
play faker early meida when not receive rtp packet

### ISSUE THREAD

**Issue by wangduanduan** [signalwire/freeswitch#1725]
```
bgapi originate user/1000 &bridge(sofia/external/8888@ims.cc)
```

after user 1000 answered the call, fs call 8888.

sometimes

1. the ims not send 180 or 183, 
2. ims send 183 but not send rtp packet of early media, 

then the user 1000 can only listen nothing but silence.

i want to set a faker ringback for the aleg, but once bleg receive  real RTP early media (not just the sip 183/SDP), the faker ringback should stop, and switch to the real early media.

i try to use ringback channel variable, but it just check the 183/SDP, then stop ringback, it not checks  rtp packet.

is any way play faker early media base on rtp not 183/SDP ?

thanks.

**Package version or git hash**
- Version of FreeSWITCH [e.g. 1.10.4]

**Comment by mjerris** [comment]
you can ignore the early media completely and replace it with a fake ring back… gets tricky with international and types of ring back tones but it’s an option. https://freeswitch.org/confluence/plugins/servlet/mobile?contentId=16353370#content/view/16353370
