### ISSUE TITLE
Secure Reliable Transport

### ISSUE THREAD

**Issue by bkmgit** [signalwire/freeswitch#1726]
**Is your feature request related to a problem? Please describe.**
It would be great to allow video consumers to choose receive resolution

**Describe the solution you'd like**
Consider adding support for [SRT](https://github.com/Haivision/srt)

**Describe alternatives you've considered**
-

**Additional context**
This is helpful when streaming to people on connections with greatly varying bandwidth

**Package version or git hash**
NA

**Comment by mjerris** [comment]
patches welcome.  please reopen with a pull request
