### ISSUE TITLE
How to optimize the use of mod_av memory with 1.10 release？

### ISSUE THREAD

**Issue by yuexiajiayan** [signalwire/freeswitch#173]
800m of memory is used for one video chat ，About 200m on the lower version 。
How to optimize parameters in avformat.c avcode.c

**Comment by seven1240** [comment]
can you find out which commit caused that? try https://git-scm.com/docs/git-bisect

**Comment by yuexiajiayan** [comment]
i'm use in mod_conference  , one video chat in 3500 used 800m 
FreeSWITCH Version 1.10.1-release+git~20190820T165404Z~f9990221e6~64bit (git f999022 2019-08-20 16:54:04Z 64bit)

**Comment by seven1240** [comment]
I'm running in docker which is debian 10 with 2 members in conference with 720p input and canvas I don't have this problem

```
root@c0ac665e0147:/#  ps -ef -o pid,cmd,rsz | grep freeswitch
    9  \_ /usr/local/freeswitch/b 318460
```

you must show your evidence how do you measured this and we don't know your os and avcodec version.

if you still have problem, use the git bisect to find out the commit breaking for you would be helpful.
