### ISSUE TITLE
Linphone and sipml5 call each other through WSS protocol

### ISSUE THREAD

**Issue by hpuzz** [signalwire/freeswitch#1731]
Linphone and sipml5 call each other through WSS protocol

FS v1.6 will  report this error

`[ERR] switch_rtp.c:3185 audio Handshake failure 1`

_Originally posted by @tppi in https://github.com/signalwire/freeswitch/issues/532#issuecomment-745029920_

**Comment by mjerris** [comment]
freeswitch 1.6 is beyond eol and doesn’t support modern webrtc, use current versions to support current webrtc

**Comment by hpuzz** [comment]
> freeswitch 1.6 is beyond eol and doesn’t support modern webrtc, use current versions to support current webrtc

When I use sipml5 to connect the freeswitch 1.10.6, It appears an error.Failed to connet to the server.How can I solve the problem?Is the certificate not configured？ Thanks.

**Comment by hpuzz** [comment]
> freeswitch 1.6 is beyond eol and doesn’t support modern webrtc, use current versions to support current webrtc

When I use sipml5 to connect the freeswitch 1.10.6, It appears an error.Failed to connet to the server.How can I solve the problem?Is the certificate not configured？ Thanks.
