### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [signalwire/freeswitch#1737]
Hi!

I am reading the documentation and cannot find the information about supported combinations of OS-Hardware Architcture. Is there any? But for the users will be much easier to get the information about the support status (and different support levels for each) from the documentation.

Maybe some kind of table or something like that will be a good start.

Thanks in advance!

**Comment by mjerris** [comment]
we recommend debian 10 linux intel as that’s our primary dev platform.  it works on some other things as well with differing levels of effort to keep those working

**Comment by zamazan4ik** [comment]
Could you please put this information somewhere into the documentation? That Debian-x86 is the only tested platform. And other OS-Arch combinations are not well-tested by the team. Thanks!
