### ISSUE TITLE
mod_unimrcp: How do I detect that an MRCP session has been established for a specific FreeSwitch channel?

### ISSUE THREAD

**Issue by ajgolledge** [signalwire/freeswitch#1743]
Hi,
I am using mod_unimrcp with the Google Speech Recognition plugin, together with ESL. The speech recognition works fine mostly but I am having problems detecting whether a specific FreeSwitch channel has successfuly established an MRCP session. This is important if we have multiple calls which are trying to perform speech recognition simultaneously and there are not enough licenses to provide all of the clients with an MRCP session.

When an MRCP session is successfully established I see this in the log file:
```
2022-07-22 20:57:09.443803 [INFO] mrcp_client_session.c:455 (ASR-42) Raise App Response ASR-42 <0c7fd688cf934de1> [2] SUCCESS [0]
ac3808fe-09a2-48fa-b8b1-c2e51921400d 2022-07-22 20:57:09.443803 [DEBUG] mod_unimrcp.c:1894 (ASR-42) RECOGNIZER channel is ready, codec = LPCM, sample rate = 8000
ac3808fe-09a2-48fa-b8b1-c2e51921400d 2022-07-22 20:57:09.443803 [DEBUG] mod_unimrcp.c:1578 (ASR-42) CLOSED ==> READY
2022-07-22 20:57:09.443803 [DEBUG] apt_consumer_task.c:141 () Wait for Messages [MRCP Client]
ac3808fe-09a2-48fa-b8b1-c2e51921400d 2022-07-22 20:57:09.443803 [DEBUG] mod_unimrcp.c:1056 (ASR-42) channel is ready

```
An event is also fired at this point which looks like this:
```
RECV EVENT
Event-Subclass: unimrcp::profile_open
Event-Name: CUSTOM
Core-UUID: 4c8182f9-80b3-4696-b19a-61990d795ef6
FreeSWITCH-Hostname: fsx
FreeSWITCH-Switchname: fsx
FreeSWITCH-IPv4: 10.1.10.135
FreeSWITCH-IPv6: ::1
Event-Date-Local: 2022-07-18 19:59:55
Event-Date-GMT: Mon, 18 Jul 2022 17:59:55 GMT
Event-Date-Timestamp: 1658167195948449
Event-Calling-File: mod_unimrcp.c
Event-Calling-Function: speech_on_channel_add
Event-Calling-Line-Number: 1899
Event-Sequence: 11502
MRCP-Profile: unimrcpserver-mrcp-v1
MRCP-Resource-Type: ASR
```
This is all great but I have no way of knowing which FreeSwitch channel the event is related to. I cannot filter this event according to which particular client made the request so all listeners to the event socket will see this event. When the `detect_speech` application is started I also cannot tell whether it was successful in its attempt to establish an MRCP session. Admittedly, when an MRCP session is not able to be opened I do see this in the log file:
```
2022-07-22 20:57:09.543806 [DEBUG] apt_task.c:337 () Process Message [MRCP Client] [0x7f6508000a80;1;0]
2022-07-22 20:57:09.543806 [INFO] mrcp_client_session.c:151 (ASR-43) Receive Answer ASR-43 <new> [c:0 a:0 v:0] Status 0
2022-07-22 20:57:09.543806 [INFO] mrcp_client_session.c:455 (ASR-43) Raise App Response ASR-43 <new> [2] FAILURE [2]
97896665-a643-4357-82eb-5a08bfc07581 2022-07-22 20:57:09.543806 [ERR] mod_unimrcp.c:1914 (ASR-43) RECOGNIZER channel error!
97896665-a643-4357-82eb-5a08bfc07581 2022-07-22 20:57:09.543806 [DEBUG] mod_unimrcp.c:1578 (ASR-43) CLOSED ==> ERROR
2022-07-22 20:57:09.543806 [DEBUG] apt_consumer_task.c:141 () Wait for Messages [MRCP Client]
97896665-a643-4357-82eb-5a08bfc07581 2022-07-22 20:57:09.543806 [DEBUG] mod_unimrcp.c:1062 (ASR-43) Terminating MRCP session

```
and another event is fired but I have the same problem in that I have no way of finding out whcih FreeSwitch channel was being used at the time the MRCP session was attempted to be established. Is there a way to obtain this information? Have I missed something?

**Comment by crienzo** [comment]
Github issues are for reporting bugs. That being said- there is probably a param in mod_unimrcp to not have the channel hold on to the MRCP session if you need it available for other calls when not in use. The ASR requests should fail otherwise.
