### ISSUE TITLE
r_message 900 Internal error at nua_client.c:552

### ISSUE THREAD

**Issue by zygzx** [signalwire/freeswitch#1746]
freeswitch run at vps server. local ip is 192.168.0.4, external ip is 120.48.126.3
when I run in fs_cli got "event r_message 900 Internal error at nua_client.c:552 " ,command as follow:
chat sip|0000000000|1103001@192.168.0.4|hello

sofia-SIP v1.13.8 Release for freeswitch 1.10.16

sofia status profile internal
Name internal
Domain Name N/A
Auto-NAT false
DBName sofia_reg_internal
Pres Hosts 192.168.0.4,192.168.0.4
Dialplan XML
Context default
Challenge Realm auto_from
RTP-IP 192.168.0.4
Ext-RTP-IP 120.48.126.3
SIP-IP 192.168.0.4
Ext-SIP-IP 120.48.126.3
URL sip:mod_sofia@120.48.126.3:8060
BIND-URL sip:mod_sofia@120.48.126.3:8060;maddr=192.168.0.4;transport=udp,tcp
TLS-URL sip:mod_sofia@120.48.126.3:8061
TLS-BIND-URL sips:mod_sofia@120.48.126.3:8061;maddr=192.168.0.4;transport=tls
WS-BIND-URL sip:mod_sofia@192.168.0.4:5066;transport=ws
WSS-BIND-URL sips:mod_sofia@192.168.0.4:7443;transport=wss
HOLD-MUSIC local_stream://moh
OUTBOUND-PROXY N/A
CODECS IN PCMA,G729,AMR-WB
CODECS OUT PCMA,G729,AMR-WB
TEL-EVENT 101
DTMF-MODE rfc2833
CNG 13
SESSION-TO 0
MAX-DIALOG 0
NOMEDIA false
LATE-NEG true
PROXY-MEDIA false
ZRTP-PASSTHRU true
AGGRESSIVENAT true
CALLS-IN 0
FAILED-CALLS-IN 0
CALLS-OUT 0
FAILED-CALLS-OUT 0
REGISTRATIONS 2
MAX-CALLS 0

sofia status profile internal reg 1103001

Call-ID: MGRlZDdkYWU2YjlkOWQxNjMyMzhkNWVkZTlhODZmNTA.
User: 1103001@192.168.0.4
Contact: "1103001" sip:1103001@112.97.60.221:22619;rinstance=6d143823f37fc4cf;fs_nat=yes
Agent: X-Lite release 1100l stamp 47546
Status: Registered(AUTO-NAT)(unknown) EXP(2022-08-06 05:48:59) EXPSECS(86)
Ping-Status: Reachable
Ping-Time: 0.00
Host: UCS
IP: 112.97.60.221
Port: 22619
Auth-User: 1103001
Auth-Realm: 120.48.126.3
MWI-Account: 1103001@192.168.0.4

chat sip|0000000000|1103001@192.168.0.4|hello
Error! Message Not Sent
nua_common.c:108 nh_create_handle() nua: nh_create_handle: entering
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:667 nua_message() nua: nua_message: entering
nua_stack.c:529 nua_signal() nua(0x7f9fac01fe70): sent signal r_message
nua_stack.c:569 nua_stack_signal() nua(0x7f9fac01fe70): recv signal r_message
nua_params.c:484 nua_stack_set_params() nua: nua_stack_set_params: entering
soa.c:280 soa_clone() soa_clone(static::0x232d960, 0x2342070, 0x7f9fac01fe70) called
soa.c:403 soa_set_params() soa_set_params(static::0x27417e0, ...) called
soa.c:403 soa_set_params() soa_set_params(static::0x27417e0, ...) called
nua_stack.c:271 nua_stack_event() nua(0x7f9fac01fe70): event r_message 900 Internal error at nua_client.c:552
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua.c:925 nua_handle_destroy() nua: nua_handle_destroy: entering
nua_stack.c:569 nua_stack_signal() nua(0x7f9fac01fe70): recv signal r_destroy
nua_stack.c:529 nua_signal() nua(0x7f9fac01fe70): sent signal r_destroy
nta.c:4499 nta_leg_destroy() nta_leg_destroy((nil))
soa.c:356 soa_destroy() soa_destroy(static::0x27417e0) called
nua.c:346 nua_handle_bind() nua: nua_handle_bind: entering
nua.c:925 nua_handle_destroy() nua: nua_handle_destroy: entering
nua.c:1169 nua_handle_unref_user() nua nua_handle_unref_user(0x7f9fac01fe70): entering
nua_stack.c:529 nua_signal() nua(0x7f9fac01fe70): sent signal r_handle_unref
nua.c:1162 nua_unref_user() nua: nua_unref_user: entering
nua_stack.c:569 nua_stack_signal() nua(0x7f9fac01fe70): recv signal r_handle_unref
nua_stack.c:529 nua_signal() nua((nil)): sent signal r_unref
nua_stack.c:569 nua_stack_signal() nua((nil)): recv signal r_unref

**Comment by andywolk** [comment]
What FreeSWITCH version hash are you using?

**Comment by andywolk** [comment]
Sounds like you are using your own modified version of FreeSWITCH. We can't support that.
You can re-open that issue if you can provide more details.

**Comment by zygzx** [comment]
FreeSWITCH Version 1.10.6-release~64bi6

**Comment by zygzx** [comment]
I have not change the code!

**Comment by zygzx** [comment]
What detail you need?
