### ISSUE TITLE
Freeswitch cannot be installed in CentOS

### ISSUE THREAD

**Issue by vinson2025** [signalwire/freeswitch#1757]
I have registered the signalwire account. According to this article: https://freeswitch.org/confluence/display/FREESWITCH/CentOS +7 + and + RHEL + 7, freeswitch still cannot be installed and crashes in this place: Yum install - y freeswitch config vanilla freeswitch Lang - * freeswitch sounds - *. What is the reason for this?

**Comment by mjerris** [comment]
please include details of the errors you are receiving

**Comment by vinson2025** [comment]
![image](https://user-images.githubusercontent.com/77615677/183853959-ef37bc93-148f-4e4c-b4a0-60d35144d57f.png)

**Comment by vinson2025** [comment]
![image](https://user-images.githubusercontent.com/77615677/183855074-87474c19-b567-4f77-a5cf-dc198d6dd44a.png)

**Comment by andywolk** [comment]
yum-1.6 repo is obsolete. Please use packages from our `freeswitch.signalwire.com/repo/yum/centos-release` repo as it is described in https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7
