### ISSUE TITLE
There is no AMQP module in CentOS Yum source?

### ISSUE THREAD

**Issue by zanmeipaul** [signalwire/freeswitch#1758]
There is no AMQP module in CentOS Yum source. How can I install it? Are there only two options to install the source code or replace it with Debian?

**Comment by mjerris** [comment]
those or submit pull requests that add it to the centos build

**Comment by zanmeipaul** [comment]
@mjerris   I don't understand. What do I need to do?

**Comment by andywolk** [comment]
This project is supported by the community. That means if you see something missing you can make a Pull Request with changes adding that missing piece. Of course if you have knowledge.

**Comment by zanmeipaul** [comment]
@andywolk  Sorry, my application layer developers do not know how to add Mod_ RMP package of AMQP module. I just want to know how to install mod in CentOS_ AMQP module RMP
