### ISSUE TITLE
The download bandwidth of freeswitch is too slow!

### ISSUE THREAD

**Issue by vinson2025** [signalwire/freeswitch#1759]
The download bandwidth of freeswitch is too slow, often resulting in too long download time, even up to 38 hours!  What is more annoying is that the software package being downloaded is often interrupted, resulting in re downloading. It is hoped that freeswitch will provide 7 * 24 hours stable and reliable high-speed bandwidth so that Chinese customers can download freeswitch software packages.
![image](https://user-images.githubusercontent.com/77615677/183936511-94c01bff-210b-403a-bcf0-dfe717108fbe.png)

**Comment by andywolk** [comment]
I personally do not see a speed issue on my end. And we do not control what bandwidth different ends have.
Speaking of being a customer. If you wish to become our customer feel free to email to sales@signalwire.com so we could figure out what's best in your case.
Closing this issue.

**Comment by mjerris** [comment]
you can setup package caching on your side to address this, the sound file packages are large and change very rarely, you shouldn’t have to keep hitting our servers to deliver those to you.  this appears to be some sort of issue with your internet getting to our package servers in the us.

**Comment by vinson2025** [comment]
Dear andywolk,  I'm only studying freeswitch now and will become a customer of your company when the conditions are ripe. thank you!

**Comment by vinson2025** [comment]
Dear mjerris,  OK, thank y!
