### ISSUE TITLE
How to build freeswitch-1.10.7 Resource in CentOS7

### ISSUE THREAD

**Issue by FlowerGhost** [signalwire/freeswitch#1769]
first====compiler  spandsp-master project
./bootstrap.sh
./configure
make
make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH} 
ldconfig

second===compiler  sofia-sip project
./bootstrap.sh
./configure
make
make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH} 
ldconfig

third====compiler  freeswitch-1.10.7.-release project
./configure

error=========checking for spandsp >= 3.0... configure: error: no usable spandsp; please install **### spandsp3 devel** package or equivalent?

"spandsp3"  search faild in www.

I don't konw del it.

**Comment by andywolk** [comment]
You need packages. Here we have an instruction.
https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7

**Comment by FlowerGhost** [comment]
why?closed my request? i do not how to build it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrey ***@***.***&gt;; 
发送时间: 2022年8月23日(星期二) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [signalwire/freeswitch] How to build freeswitch-1.10.7 Resource in CentOS7 (Issue #1769)





 
Closed #1769 as completed.
 
&mdash;
