### ISSUE TITLE
Playing vp8 and vp9 video from file error

### ISSUE THREAD

**Issue by ivlovric** [signalwire/freeswitch#177]
Hi,

We are trying our video call scenario where we would like to play video from file and format that we need is vp8 or vp9. 
Playing h264 files in same way works well and that video is shown on called side video endpoint. I can confirm also that vp8 and vp9 video files are playable with video player and are not corrupted

System and codec info:
FS Version 1.8.7

> show codec 
type,name,ikey
codec,ADPCM (IMA),mod_spandsp
codec,AMR / Bandwidth Efficient,mod_amr
codec,AMR / Octet Aligned,mod_amr
codec,B64 (STANDARD),mod_b64
codec,G.711 alaw,CORE_PCM_MODULE
codec,G.711 ulaw,CORE_PCM_MODULE
codec,G.722,mod_spandsp
codec,G.723.1 6.3k,mod_g723_1
codec,G.726 16k,mod_spandsp
codec,G.726 16k (AAL2),mod_spandsp
codec,G.726 24k,mod_spandsp
codec,G.726 24k (AAL2),mod_spandsp
codec,G.726 32k,mod_spandsp
codec,G.726 32k (AAL2),mod_spandsp
codec,G.726 40k,mod_spandsp
codec,G.726 40k (AAL2),mod_spandsp
codec,G.729,mod_g729
codec,GSM,mod_spandsp
codec,H263 Video,mod_av
codec,H263+ Video,mod_av
codec,H264 Video,mod_av
codec,LPC-10,mod_spandsp
codec,OPUS (STANDARD),mod_opus
codec,PROXY PASS-THROUGH,CORE_PCM_MODULE
codec,PROXY VIDEO PASS-THROUGH,CORE_PCM_MODULE
codec,RAW Signed Linear (16 bit),CORE_PCM_MODULE
codec,Speex,CORE_SPEEX_MODULE
codec,VP8 Video,CORE_VPX_MODULE
codec,VP9 Video,CORE_VPX_MODULE

> mod_av is loaded

Error VP8:
Input #0, matroska,webm, from '/var/lib/freeswitch/sounds/ib_720p_vp8_webm_const_quality_19_const_framerate_VORBIS.webm':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 
00:01:52.53
, start: 
0.000000
, bitrate: 
N/A
    Stream #0:0
: Video: vp8
      none, 1280x720
, PAR 1:1 DAR 16:9

      
25 fps, 
1k tbn
 (default)
    Metadata:
      DURATION        : 00:01:52,520000000
    Stream #0:1
(eng)
: Audio: vorbis
      44100 Hz, stereo, fltp
 (default)
    Metadata:
      title           : Stereo
      DURATION        : 00:01:52,531000000
2019-12-13 15:13:26.698164 [ERR] avformat.c:1141 Could not find input codec 141

ERROR VP9:
2019-12-13 12:59:39.530200 [INFO] avformat.c:1096 file /var/lib/freeswitch/sounds/ib_720p_vp9_mkv_const_quality_19_const_framerate.mkv is seekable
Input #0, matroska,webm, from '/var/lib/freeswitch/sounds/ib_720p_vp9_mkv_const_quality_19_const_framerate.mkv':
  Metadata:
    title           : ib
    ENCODER         : Lavf58.29.100
  Duration: 00:01:52.57, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: vp9
      none, 1280x720, PAR 1:1 DAR 16:9
      25 fps, 1k tbn (default)
    Metadata:
      DURATION        : 00:01:52,520000000
    Stream #0:1(eng): Audio: aac (LC)
      44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Stereo
      DURATION        : 00:01:52,570000000
2019-12-13 12:59:39.530200 [ERR] avformat.c:1141 Could not find input codec 169

Please advise what we could be missing or doing wrong.
Will provide any logs necessary.

Thanks and kind regards,
Ivica

**Comment by mjerris** [comment]
This is on an old version of freeswitch.  you should try with the latest release on buster and see if it is any better.

**Comment by ivlovric** [comment]
Thanks.

We just tried same with FS 1.10.1 and have same behaviour.
freeswitch@host> version
FreeSWITCH Version 1.10.1-release~64bit ( 64bit)

codecs: (cant see video codecs, but it seems they are integrated into fs core now)

freeswitch@host> show codec
type,name,ikey
codec,ADPCM (IMA),mod_spandsp
codec,AMR / Bandwidth Efficient,mod_amr
codec,AMR / Octet Aligned,mod_amr
codec,B64 (STANDARD),mod_b64
codec,G.722,mod_spandsp
codec,G.723.1 6.3k,mod_g723_1
codec,G.726 16k,mod_spandsp
codec,G.726 16k (AAL2),mod_spandsp
codec,G.726 24k,mod_spandsp
codec,G.726 24k (AAL2),mod_spandsp
codec,G.726 32k,mod_spandsp
codec,G.726 32k (AAL2),mod_spandsp
codec,G.726 40k,mod_spandsp
codec,G.726 40k (AAL2),mod_spandsp
codec,G.729,mod_g729
codec,GSM,mod_spandsp
codec,LPC-10,mod_spandsp
codec,OPUS (STANDARD),mod_opus
codec,iLBC,mod_ilbc

FS 1.10.1 ERROR:
2019-12-13 18:43:24.559537 [DEBUG] avformat.c:1640 sample rate: 8000, channels: 1
2019-12-13 18:43:24.559537 [INFO] avformat.c:1096 file /var/lib/freeswitch/sounds/ib_720p_vp8.mkv is seekable
Input #0, matroska,webm, from '/var/lib/freeswitch/sounds/ib_720p_vp8.mkv':
  Metadata:
    title           : ib
    ENCODER         : Lavf58.29.100
  Duration: 
00:01:52.57
, start: 
0.000000
, bitrate: 
N/A
    Stream #0:0
: Video: vp8
      none, 1280x720
, PAR 1:1 DAR 16:9

      
25 fps, 
1k tbn
 (default)
    Metadata:
      DURATION        : 00:01:52,520000000
    Stream #0:1
(eng)
: Audio: aac (LC)
      44100 Hz, stereo, fltp
 (default)
    Metadata:
      title           : Stereo
      DURATION        : 00:01:52,570000000
2019-12-13 18:43:24.559537 [ERR] avformat.c:1141 Could not find input codec 141

**Comment by ivlovric** [comment]
@mjerris Hope this is now eligable to be reopened.

Thanks,
I
