### ISSUE TITLE
Zombie calls

### ISSUE THREAD

**Issue by vikasSharan** [signalwire/freeswitch#178]
I have debug the issue and found that in switch_core_session_thread(...) it is waiting for session->rwlock to acquire. If lock is acquired, in the end, on the basis of uuid, it will remove uuid from table.
so instead of waiting for a lock replaced with a switch_thread_rwlock_trywrlock. 
![Screenshot from 2019-12-16 12-12-40](https://user-images.githubusercontent.com/58163124/70884973-7b0f2b00-1ffd-11ea-9f11-2d5918748563.png)

**Comment by anthmFS** [comment]
This is a safety mechanism and is correct as is.
If you have sessions stuck here you have another issue somewhere where a read lock is still held or is leaked by somewhere else in the code.  The proposed change will cause countless crashes and instability.

**Comment by vikasSharan** [comment]
session are stucked until they are  killed by freeswitch restart. I have checked an entire code to look for any possible leak for this lock but did not found any.

**Comment by crienzo** [comment]
Please reopen when you get more information about this issue.
