### ISSUE TITLE
How to connect to remote host with MySQL Dbh ?

### ISSUE THREAD

**Issue by abhishekdeshkar** [signalwire/freeswitch#1798]
Hello,

I have been trying to figure out if there is any way to connect to **remote** Database with FreeSwitch API.

FreeSwitch Lua API accepts only: Database name, username & password.

So it establishes the connection to localhost only.

`local dbh = freeswitch.Dbh("odbc://my_db:uname:passwd") -- connect to ODBC database '`

There is no option to provide host name if in case I want to make use of remote database server.

Is there any way ?

P.S: I cannot use pgsql due to limitations on backend. 

API Ref: https://freeswitch.org/confluence/display/FREESWITCH/Lua+with+Database

**Comment by aunghtain** [comment]
You can use odbc connection to connect to remote database. https://freeswitch.org/confluence/pages/viewpage.action?pageId=6586653

follow the installation. Then, add a file /etc/odbc.ini with your remote database configuration like 

[freeswitch]
Driver = MySQL
SERVER = localhost
PORT = 3306
DATABASE = myDatabase
OPTION = 67108864
Socket = /var/lib/mysql/mysql.sock

Then, connect using database name. ("freeswitch" in this example)

**Comment by abhishekdeshkar** [comment]
@aunghtain  I'm using Debian 10 and this doesn't work for me. 

@andywolk Can you please help ?
