### ISSUE TITLE
vad never firing

### ISSUE THREAD

**Issue by davehorton** [signalwire/freeswitch#18]
If I'm not mistaken, this line:

https://github.com/signalwire/freeswitch/blob/15ad4c23e259c1c2dff58f89e9124e5f36dd2e94/src/switch_vad.c#L222

should be 

```
if (score >= vad->thresh)
```
I did some testing with libfvad and vad_state never changes to SWITCH_VAD_STATE_START_TALKING due to the above

**Comment by anthmFS** [comment]
There is more to it than that, will probably be retooling it soon

**Comment by davehorton** [comment]
Fair enough.  I'll look for updates / commit references here when you get to it.  FWIW, I tested on 1.8 with libfvad, which worked; then it appears to have been rewritten in 1.10.1, where it did not work

**Comment by mjerris** [comment]
even what was in 1.8 was not enough.  fvad is packet for packet, needs a whole state machine around it that does not currently exist.

**Comment by davehorton** [comment]
Are you guys open to a PR on this, as I would like to get it working?  If so, do you have any specific requirements in mind for the state machine you envision?

**Comment by crienzo** [comment]
@mjerris there is already a state machine in switch_vad.c- what is missing?

**Comment by crienzo** [comment]
Talked to tony- we'll fix this and make it more obvious what it's doing.

**Comment by seven1240** [comment]
fvad just returns -1, 0, and 1, I just add to the native score system so it's some misleading, refactor to be more obvious would be better.

**Comment by crienzo** [comment]
I have a PR coming for this.

**Comment by davehorton** [comment]
cool can you reference this issue in the commit when you check it in?

**Comment by crienzo** [comment]
Sure- i'll amend the commit to do that.
