### ISSUE TITLE
crashing FS after upgrade 1.10 from 1.6

### ISSUE THREAD

**Issue by andrewudxgen** [signalwire/freeswitch#183]
Dear,

when we have upgraded to 1.10 from 1.6 FS gets crashes ( crash core backtrace response: "Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x00007fe94c46df5a in ?? () from /usr/local/freeswitch/mod/mod_com_g729.so"), we have been purchased g729 licenses and used in 1.6 versions, it was worked fine.

here are the crash core backtrace logs, below are the responses.
+++++++++
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/freeswitch/bin/freeswitch...done.
[New LWP 6824]
[New LWP 6063]
[New LWP 6077]
[New LWP 6073]
[New LWP 6065]
[New LWP 6067]
[New LWP 6064]
[New LWP 6070]
[New LWP 6066]
[New LWP 6068]
[New LWP 6072]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/freeswitch/bin/freeswitch -nc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe94c46df5a in ?? () from /usr/local/freeswitch/mod/mod_com_g729.so
[Current thread is 1 (Thread 0x7fe8ff36e700 (LWP 6824))]
++++++
server Details:
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

please help us with the same. thanks in advance.

**Comment by mjerris** [comment]
try reinstalling latest g729 com module

**Comment by andrewudxgen** [comment]
HI,

sorry for late reply,

we have updated latest Freeswitch and we have uninstall and installed G729 commercial module, but when we are enabled G729 module, its getting crashed again.

Kindly, let us know what would be the other scenario to crash the FS.

Thanks in advance !!!

**Comment by briankwest** [comment]
Did you install the module and re-activate it after you updated? because the signing key was changed about a year ago.

**Comment by sandiprana89** [comment]
Hello Sir,

I have followed mentioned steps in bellow link but getting " mod_com_g729.so is missing"
https://freeswitch.org/confluence/display/FREESWITCH/mod_com_g729

Error:
freeswitch@Logimeter> load mod_com_g729
+OK Reloading XML
-ERR [module load file routine returned an error]

2020-04-29 16:45:16.833526 [INFO] switch_stun.c:897 External ip address detected using STUN: 88.198.146.19
2020-04-29 16:45:16.913557 [INFO] switch_stun.c:897 External ip address detected using STUN: 88.198.146.19
2020-04-29 16:45:16.993524 [INFO] mod_enum.c:884 ENUM Reloaded
2020-04-29 16:45:16.993524 [INFO] switch_time.c:1433 Timezone reloaded 1750 definitions
2020-04-29 16:45:16.993524 [CRIT] switch_loadable_module.c:1786 Error Loading module /usr/lib/freeswitch/mod/mod_com_g729.so
**/usr/lib/freeswitch/mod/mod_com_g729.so: cannot open shared object file: No such file or directory**
freeswitch@Logimeter> freeswitch@Logimeter>

Please help me for fix this issue.

**Comment by sandiprana89** [comment]
version :FreeSWITCH Version 1.10.2-release-14-f7bdd3845a~64bit (-release-14-f7bdd3845a 64bit)
