### ISSUE TITLE
debian11 install failed

### ISSUE THREAD

**Issue by datafeng** [signalwire/freeswitch#1836]
root@sip:/etc/apt/sources.list.d# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
root@sip:/etc/apt/sources.list.d# uname -a
Linux sip 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux

reference this doc:
https://freeswitch.org/confluence/display/FREESWITCH/Debian#Debian-buildfromsource

error info:
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.2+dfsg-1+deb11u1) ...
Errors were encountered while processing:ssmtp freeswitch-mod-voicemail freeswitch-meta-all
 ssmtp
 freeswitch-mod-voicemail
 freeswitch-meta-all

**Comment by andywolk** [comment]
Does not seem related to FreeSWITCH. You probably have a broken debian installation or an interrupted debian dist upgrade in the past.

**Comment by mjerris** [comment]
if you fix the install of libgdk-pixbuf-2.0-0:amd64 (2.42.2+dfsg-1+deb11u1) it should
fix this error.  sounds like something wrong with your debian install
