### ISSUE TITLE
mod_unimrcp missing in FreeSWITCH 1.10.8 

### ISSUE THREAD

**Issue by hheedfeld** [signalwire/freeswitch#1859]
After wondering and doing some research I found this:

`As of 2022.08.29 mod_unimrcp was removed from FreeSWITCH tree and placed in https://github.com/freeswitch/mod_unimrcp`

Can anyone give me a point why this was done?

**Comment by andywolk** [comment]
It is an out of tree module now. You can find it here with building instructions:
https://github.com/freeswitch/mod_unimrcp

**Comment by hheedfeld** [comment]
yes, I read that - but I do not understand why.

**Comment by crienzo** [comment]
We don't maintain unimrcp and moved it to external module so the community can. It is now easier to stay up to date with latest unimrcp library changes in this setup. @seven1240 has volunteered to help maintain the module, if you are interested in helping out, please contact him.
