### ISSUE TITLE
[webrtc]ext-rtp-ip not work behind nginx

### ISSUE THREAD

**Issue by xujialiang** [signalwire/freeswitch#1860]
**Describe the bug**
My freeswitch server is behind a nginx, if set  proxy_pass to a private ip, sip message will use this private ip, if set proxy_pass to a public ip, sip message will use this public ip and sdp will give a private ip.

So, when set  proxy_pass to a private ip, web browser will not connect . So I have to use a public ip in nginx config.

How to improve it? Thanks.

look at this pic.

<img width="689" alt="WX20221110-182326@2x" src="https://user-images.githubusercontent.com/1549351/201066818-8e2f8a17-63e6-4a40-9f05-89577dcfabae.png">

**To Reproduce**
if I set proxy_pass to 10.0.4.9:7443, then remote sdp will give c=IN IP4 10.0.4.9
if I set proxy_pass to 188.168.127.8:7443, then remote sdp will give c=IN IP4 188.168.127.8

**Expected behavior**
sdp use the public ip, such as ext-rtp-ip, ext-sip-ip

**Package version or git hash**
 - 1.10.8

**Trace logs**

**backtrace from core file**

```

**Comment by seven1240** [comment]
Try if prefix with auto-nat: works for you https://marc.info/?l=freeswitch-users&m=139200158022170&w=2

I think it's not a bug but a question. Maybe better ask in the malling list or use the new https://forum.signalwire.community/ .

**Comment by xujialiang** [comment]
> Try if prefix with auto-nat: works for you https://marc.info/?l=freeswitch-users&m=139200158022170&w=2
> 
> I think it's not a bug but a question. Maybe better ask in the malling list or use the new https://forum.signalwire.community/ .

Thanks~
