### ISSUE TITLE
[mod_conference] cannot get endconf_grace_time parameter of conference

### ISSUE THREAD

**Issue by Torqu** [signalwire/freeswitch#190]
After upgrade of freeswitch from 1.6 to 1.10.1 i get a problem with getting endconf_grace_time parameter by lua script

> `<condition field="${conference(${conference_name} get endconf_grace_time)}" expression="30">`

with fs_cli :

> `conference conf_name get endconf_grace_time`

i get the same output as:

> `get <parameter-name>`

Output for fs_cli command:

> `freeswitch@localhost.localdomain> conference conf_100005 get endconf_grace_time
> [DEBUG] esl.c:1495 esl_send() SEND
> api conference conf_100005 get endconf_grace_time
> console_execute: true
> 
> 
> [DEBUG] esl.c:1303 esl_recv_event() RECV HEADER [Content-Type] = [api/response]
> [DEBUG] esl.c:1303 esl_recv_event() RECV HEADER [Content-Length] = [20]
> get \<parameter-name>`

It looks like cannot be found parameter with that name.
In conference.conf.xml profiles i have set this parameter:

> `<param name="endconf-grace-time" value="30"/>`

This code worked in 1.6 version.

I tried also in both places parameter name as 'endconf_grace_time' and endconf-grace-time'. Both didn't worked. I checked all the parameters from the 'get and set' table from https://freeswitch.org/confluence/display/FREESWITCH/mod_conference and everything works except endconf_grace_time.

**Comment by mochouinard** [comment]
Looking at the code, it was changed from endconf_grace_time to endconference_grace_time.  Samething for the <param> settings (but with dash).  That changed in 2015.  Here the commit info :+1: commit d8194e9edbff23293aa0dae6d36f1d818f440914
Author: William King <william.king@quentustech.com>
Date:   Thu Jul 16 16:58:39 2015 -0700

    FS-7845 File rename to remove mod_* prefix to local module C files. Change
    function name prefixes from shorthand 'conf' to longer form
    'conference'. Also fixes the channel variable names which had been
    caught in an over zealous perl -pi -e command...

**Comment by Torqu** [comment]
I checked it. With endconference_grace_time code is working in lua script and fs_cli. Then this parameter on  https://freeswitch.org/confluence/display/FREESWITCH/mod_conference 'get and set' table wasn't updated when that commit was send and now is outdated.

**Comment by mochouinard** [comment]
> I checked it. With endconference_grace_time code is working in lua script and fs_cli. Then this parameter on https://freeswitch.org/confluence/display/FREESWITCH/mod_conference 'get and set' table wasn't updated when that commit was send and now is outdated.
I'm pretty sure this was an error to change the variable name back in 2015... We need to wait for the lead devs to come back from vacation and confirm which one they prefer in 2020 ;)

**Comment by mochouinard** [comment]
@mjerris I think you closed the wrong ticket...

**Comment by David-dp-** [comment]
Is it `endconference_grace_time` in FS v10.5? https://freeswitch.org/confluence/display/FREESWITCH/mod_conference says instead it's `endconf-grace-time`.

Btw, we set `<action application="conference_set_auto_outcall" data="['conference_member_flags=endconf`... but when the first conference attendee closes his verto tab, the conference lives on awhile, so the default value of 0 for `endconf-grace-time` doesn't match my experience.
