### ISSUE TITLE
Dead Link:  freeswitch.com/#getting-started

### ISSUE THREAD

**Issue by fanglijun** [signalwire/freeswitch#1905]
[freeswitch.com/#getting-started](https://freeswitch.com/#getting-started)  link is dead. where is latest document?

**Comment by lx32056127** [comment]
Document address updated to: https://developer.signalwire.com/freeswitch/ but lose their ability to search after the update

**Comment by andywolk** [comment]
We have just enabled the new docs and our team is in process of enabling the search.
https://github.com/signalwire/freeswitch/pull/1907
