### ISSUE TITLE
Missing libg72211 from debian 11 (bullseye)

### ISSUE THREAD

**Issue by wmasilva** [signalwire/freeswitch#1906]
hi,
in debian repository libg7221 is not available for debian 11 (bullseye). 

i couldn't find the lib in git repository to build it, i did found it from the old repository: https://freeswitch.org/stash/users/andywolk/repos/libg7221/browse

**Comment by andywolk** [comment]
Packages should be fixed.
The repo is here: https://github.com/freeswitch/libg7221
Please re-open the issue if there is a problem still.
