### ISSUE TITLE
1.10.9 macOS Sofia-sip build failure incompatible pointer types

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#1922]
**Describe the bug**
This occurs with both the signalwire 1.13.10 and homebrew 1.13.11 versions. Make gets:
making all mod_sofia
  CC       test/test_sofia_funcs-test_sofia_funcs.o
  CC       libsofiamod_la-mod_sofia.lo
  CC       libsofiamod_la-sofia.lo
sofia.c:11490:40: error: incompatible pointer types assigning to 'sip_identity_t *' (aka 'struct sip_identity_s *') from 'sip_error_t *' (aka 'struct msg_error_s *') [-Werror,-Wincompatible-pointer-types]
                        for (id = sip->sip_identity; id; id = id->id_next) {
                                                            ^ ~~~~~~~~~~~
1 error generated.
make[4]: *** [libsofiamod_la-sofia.lo] Error 1

**To Reproduce**
Steps to reproduce : DL, BS, config, make.

**Expected behavior**
Clean build, or at least until the next outstanding error.

**Package version or git hash**
c69c399dd288ce5765aacd347bd7406d7dcc1cd4

[make.txt](https://github.com/signalwire/freeswitch/files/10418716/make.txt)
[bootstrap-config.txt](https://github.com/signalwire/freeswitch/files/10418717/bootstrap-config.txt)

**Comment by andywolk** [comment]
homebrew does not have the latest sofia

**Comment by MarioG-X** [comment]
So there is a Sofia-sip newer than the .10 from signalwire and .11 on homebrew? I don't see it mentioned anywhere on the web. What is the solution if any?

**Comment by andywolk** [comment]
You need sofia-sip Master to be built if you want to build fs Master.

**Comment by MarioG-X** [comment]
Thanks, but since FS does not build anyway due to the other issue, and I could only find a Sofia-sip master that is .11, I will just wait until these are both fixed.

**Comment by andywolk** [comment]
https://github.com/Homebrew/homebrew-core/pull/120925
