### ISSUE TITLE
Mod_http_cache in version 1.10.8 is not working

### ISSUE THREAD

**Issue by gregoriusus** [signalwire/freeswitch#1926]
Caching files stopped working after upgrade.

First file that is in playback (played from URL) is saved as: storage/http_file_cache/00000000000000000000000000000000.wav

And after that all files are played as this cache. Basically it doesn’t cache files anymore and always pulls this one from cache.

This is the log when it is first cached:

EXECUTE [depth=0] sofia/external/041xxxxxxxx@91.199.161.142 playback(http://wav.files.com/109da642-87ed-4596-8b82-ddefd379c3bb.wav)
2023-01-10 23:59:45.823739 97.05% [DEBUG] mod_httapi.c:2665 caching: url:http://wav.files.com/109da642-87ed-4596-8b82-ddefd379c3bb.wav to C:/Program Files/FreeSWITCH/storage/http_file_cache/00000000000000000000000000000000.wav (344649 bytes)

It looks like it doesn’t pass file name down to http_cache or it is passed as 00000…

We are using FS on windows with mod_httapi, but version 1.10.7 works ok.

**To Reproduce**
1. Enable mod_httapi
2. Playback any file

**Package version or git hash**
 - Version [e.g. 1.10.8]

**Comment by andywolk** [comment]
This should fix the issue: https://github.com/signalwire/freeswitch/pull/1927
