### ISSUE TITLE
FreeSWITCH doesn't provide DTMF support when RFC2833 is enabled in SIP profile

### ISSUE THREAD

**Issue by figaro2015** [signalwire/freeswitch#1937]
**Describe the bug**
FreeSWITCH doesn't respond with RFC2833 DTMF capabilities in the 200 OK message when the INVITE from the far end doesn't contain the RFC2833 DTMF attribute. While RFC2833 is enabled in the FreeSWITCH in the corresponding SIP profile.

**To Reproduce**
1. Enable 'liberal-dtmf' and RFC2833 DTMF support in the SIP profile with corresponding parameters:

`<param name="liberal-dtmf" value="true"/>`
`<param name="dtmf-type" value="rfc2833"/>`

2. Issue 'sofia xmlstatus profile external' to verify that RFC2833 DTMF support is enabled for the profile:

`<dtmf-mode>rfc2833</dtmf-mode>`

3. Originate SIP call from a far end (using SIPP or via 'originate' from another FreeSWITCH) such that INVITE SDP won't contain DTMF attribute:

    v=0
   o=matrix 1674520565 1674520566 IN IP4 10.1.1.226
   s=matrix
   c=IN IP4 10.1.1.226
   t=0 0
   m=audio 16738 RTP/AVP 0 13
   a=rtpmap:0 PCMU/8000
   a=rtcp:16739 IN IP4 10.1.1.226
   a=ptime:40

4. Observe that 200 OK SDP from the FreeSWITCH doesn't contain DTMF support either:

   v=0
   o=matrix 1674515120 1674515121 IN IP4 10.1.1.119
   s=matrix
   c=IN IP4 10.1.1.119
   t=0 0
   m=audio 22404 RTP/AVP 0 13
   a=rtpmap:0 PCMU/8000
   a=rtpmap:13 CN/8000
   a=ptime:20
   a=rtcp:22405 IN IP4 10.1.1.119

2023-01-23 23:18:44.313029 [DEBUG] switch_core_media.c:3971 No 2833 in SDP.  Disable 2833 dtmf and switch to INFO

**Expected behavior**
Since RFC2833 DTMF support is enabled for the profile - FreeSWITCH 200 OK SDP should contain the DTMF attribute.
Like so:

v=0
o=FreeSWITCH 1674577792 1674577793 IN IP4 192.168.86.35
s=FreeSWITCH
c=IN IP4 192.168.86.35
t=0 0
m=audio 18040 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
**a=rtpmap:101 telephone-event/8000**
a=fmtp:101 0-15
a=ptime:20

2023-01-24 13:30:32.127668 99.97% [DEBUG] switch_core_media.c:5821 No 2833 in SDP. Liberal DTMF mode adding 101 as telephone-event.

**Package version or git hash**
FreeSWITCH Version 1.10.9-dev+git~20230124T151429Z~3326f4ec57~64bit (git 3326f4e 2023-01-24 15:14:29Z 64bit)

**Comment by dragos-oancea** [comment]
" FreeSWITCH 200 OK SDP should contain the DTMF attribute." - is there any RFC to endorse this statement ? 
It's SDP offer/answer , what would be the point to add "a=rtpmap:101 telephone-event/8000" in the answer , if the originating party does not offer it ? It's not going to be negotiated hence not supported for the call.

**Comment by figaro2015** [comment]
Thank you for the reply. Two comments:

1. If we accept your theory, then FreeSWITCH SDP negotiation implementation becomes somewhat inconsistent. Since setting 'rtp_liberal_dtmf' parameter to 'true' in vars.xml accomplishes exactly what I think is correct. FreeSWITCH replies with 'telephony-event' attribute in the SDP in 200 OK, even when INVITE SDP doesn't contain a DTMF offering.
2. SIP SDP RFC seems to say that the 200 OK should specify the capabilities of the receiver. And the receiver (FreeSWITCH) in this case does have 2833 DTMF enabled.

**Comment by briankwest** [comment]
You didn't offer it in your original invite, so we can't offer it back, This is expected in my understanding of how SIP negotiation works, you can't just send DTMF back to an endpoint that doesn't ask for it, that would be a violation of the RFC.

**Comment by xopnet** [comment]
I think this case should be re-opened.  RFC4733 says this, in paragraph 3 of section 2.5.1.1:

The sender SHOULD indicate what events it supports, using the
   optional "events" parameter associated with the telephone-event media
   type.

In this case "sender" would mean any sender of an SDP body, including the 200 OK response.

**Comment by figaro2015** [comment]
Agreed. The issue should be re-opened.
