### ISSUE TITLE
No audio on FS bypass when using iLBC codec

### ISSUE THREAD

**Issue by sagarmalam** [signalwire/freeswitch#195]
Hello, 

I am facing no audio issue if call is setup using iLBC codec and later on call is bypass using uuid_media API. It is 100 % reproducible. 

From the SIP trace it looks are free switch is offering different PT on either legs which is confusing phones because PT in SDP and PT in RTP does not match. Please check attached pcap and logs.

I have testing using master version : version: 1.10.2-dev git 837e895

[ilbc-testing.zip](https://github.com/signalwire/freeswitch/files/4006956/ilbc-testing.zip)
[ilbc-test.txt](https://github.com/signalwire/freeswitch/files/4006957/ilbc-test.txt)

Please get back to me in case you need any other information.

**Comment by mjerris** [comment]
need debug log with sip trace from the start of the call not just before you do nomedia

**Comment by sagarmalam** [comment]
Please find attached file having debug logs with sip trace from start of call
[ilbc-test-112020.txt](https://github.com/signalwire/freeswitch/files/4014047/ilbc-test-112020.txt)

**Comment by sagarmalam** [comment]
Hello @mjerris , 
Did you get chance to look into it ?

Thanks

**Comment by sagarmalam** [comment]
Hello @mjerris , 
Any update on this ?

**Comment by sagarmalam** [comment]
Hello @mjerris , 
Are you able to work on this ? else can you assign to someone else please ?

**Comment by dragos-oancea** [comment]
does it work with other codecs ? are you sure the issue is ILBC related ? you may try to change the ptime of ILBC from 30 ms to 20 ms , it supports 20 ms too.

**Comment by sagarmalam** [comment]
Thanks for your attention. I have not tested with other other codecs but i doubt that this issue will occurs with all the codecs using dynamic payloads. 

P.S : In my first comment PT means Payload Type not ptime hence changing ptime will not help.

**Comment by sagarmalam** [comment]
I have found solution for this issue by using uuid_media_3p API instead of uuid_media. Closing it.
