### ISSUE TITLE
no usable libjpeg

### ISSUE THREAD

**Issue by DotNeter-Hpf** [signalwire/freeswitch#1951]
**Describe the bug**
The environment is mac m1.
execute ./configure error no usable libjpeg; please install libjpeg devel package or equivalent.

**To Reproduce**
1. cd /usr/local/src
2.git clone https://github.com/signalwire/freeswitch.git
3. cd freeswitch
4. ./bootstrap.sh
5. ./configure

**Expected behavior**
Compilation succeeded

**Package version or git hash**
 - Version [e.g. 1.10.9]

**Comment by andywolk** [comment]
We do not support m1. You will have to figure out what's available and install that, for example:
libjpeg62-turbo-dev | libjpeg-turbo8-dev | libjpeg62-dev | libjpeg8-dev

**Comment by seven1240** [comment]
@DotNeter-Hpf can you try https://github.com/signalwire/freeswitch/pull/1956 ?

**Comment by DotNeter-Hpf** [comment]
@seven1240   I have time today to try and modify configure.ac

**Comment by DotNeter-Hpf** [comment]
@seven1240  Hello, I modified three places in the configure.sh file，But  still wrong
<img width="570" alt="image" src="https://user-images.githubusercontent.com/62707731/217253002-02b18c32-c703-441e-9f47-b8dcaab4cddc.png">

**Comment by seven1240** [comment]
@DotNeter-Hpf did you re- bootstrap? btw the patch is updated, the easy way is to check out the branch and run everything from bootstrap

**Comment by DotNeter-Hpf** [comment]
@seven1240  Refer to # 1956, completely modify the file, execute ./bootstrap.sh  first, and then ./configure ，But there are still problems with the above picture

**Comment by seven1240** [comment]
it sort of worked for me http://www.dujinfang.com/2023/02/07/build-freeswitch-on-apple-m1.html

**Comment by MarioG-X** [comment]
The pull is not complete, I got to get past config with additions but make still fails, see my comments in #1956
