### ISSUE TITLE
multipleAuthors: invalid format - GitLab import

### ISSUE THREAD

**Issue by rohitChaku** [signalwire/freeswitch#1957]
**Describe the bug**
Importing the repository to GitLab from GitHub fails.

**To Reproduce**
1. [Create new project](https://gitlab.com/projects/new) in GitLab
2. [Import Project](https://gitlab.com/projects/new#import_project)
3. Import project via `Repository by URL` and use `https://github.com/signalwire/freeswitch.git`

**Expected behavior**
The project should have cloned successfully.

**Trace logs**
Input params
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/25386284/217443670-537f21e1-0aa9-4089-af47-40bb30a0a61e.png">

Error
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/25386284/217444084-dd1930bd-6e98-4cb2-9ae7-b1a1ba732d68.png">

```
Error importing repository https://github.com/signalwire/freeswitch.git into rohitChaku/freeswitch - 13:creating repository: cloning repository: exit status 128, stderr: "error: object 487128950df6ee433c131b5feaafe81ee86629f4: multipleAuthors: invalid format - multiple 'author' lines
fatal: fsck error in packed object
fatal: fetch-pack: invalid index-pack output".
```

Existing Fixes also do not work: #599

 Any suggestions or alternative options to clone to GitLab.

**Comment by mjerris** [comment]
we are aware of this and won’t fix it as it would require rewriting all history and git hashes to do so.

**Comment by rohitChaku** [comment]
Hello @mjerris thank you for the reply, I did see the issue before, I was mostly looking for possible way to import to GitLab without losing all history, since this is closed, would it be correct to assume it is not possible?

**Comment by seven1240** [comment]
Ask the GitLab admin to disable the fsck while you import.

**Comment by myacksmith** [comment]
@rohitChaku, if you're on a Self-Managed instance, the GitLab admin can add `fetch.fsck.skipList = <sha>` for this problematic commit via the `gitlab.rb` file: https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/files/gitlab-config-template/gitlab.rb.template#L2439-2442

You could also use `fetch.fsckObject = false`, but then you may end up with broken repos because no checks will be done whatsoever.
