### ISSUE TITLE
BRIDGE THREAD DONE but channel not close

### ISSUE THREAD

**Issue by zhouzz1986** [signalwire/freeswitch#1963]
For Version 1.10.7
After the call is hung up normally, the call does not hang up normally, and it will hang up automatically until the maximum call duration is reached
Make the cdr call duration statistics error

What do I need to do to make the cdr statistics correct?

dialplan xml :

<  document type="freeswitch/xml">
  <  section name="dialplan" description="RE Dial Plan For FreeSwitch">
    <  context name="default">
      <  extension name="yyy">
        <  condition field="destination_number" expression="^fs(\d+)$">
                <  action application="set" data="media_bug_answer_req=true"/>
                  <  action application="set" data="RECORD_STEREO=true"/>
                  <  action application="set" data="record_sample_rate=8000"/>
                  <  action application="set" data="enable_file_write_buffering=true"/>
          <  action application="record_session" data="xxxxxxxxx.wav" />
             <  action application="export" data="nolocal:fs_call_id=xxxxxxxxxxxxxxxxxxxx"/>
            <  action application="set" data="hangup_after_bridge=true"/> 
          <  action application="bridge" data="{origination_caller_id_number=xxxxxxxxx,execute_on_answer='sched_hangup +1800'}sofia/internal/****@*****:5060;user=phone"/>
        <  /condition>
      <  /extension>
    <  /context>
  <  /section>
<  /document>

log:
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:47:54.407179 [NOTICE] switch_ivr_bridge.c:731 Channel [sofia/internal/*@*:5060] has been answered
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:47:54.407179 [DEBUG] switch_channel.c:3865 (sofia/internal/*@*:5060) Callstate Change EARLY -> ACTIVE
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:47:54.407179 [DEBUG] sofia.c:7406 Channel sofia/internal/*@*:5060 entering state [completed][200]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:47:54.407179 [DEBUG] switch_ivr_async.c:1717 No silence detection configured; assuming start of speech
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:47:54.507179 [DEBUG] sofia.c:7406 Channel sofia/internal/*@*:5060 entering state [ready][200]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:48:35.247181 [NOTICE] sofia.c:1090 Hangup sofia/internal/*@*:5060 [CS_EXECUTE] [NORMAL_CLEARING]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 11:48:35.247181 [DEBUG] switch_ivr_bridge.c:912 BRIDGE THREAD DONE [sofia/internal/*@*:5060]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_ivr_bridge.c:1895 sofia/internal/*@*:5060 skip receive message [UNBRIDGE] (channel is hungup already)
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_session.c:2914 sofia/internal/*@*:5060 skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:651 (sofia/internal/*@*:5060) State EXECUTE going to sleep
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:585 (sofia/internal/*@*:5060) Running State Change CS_HANGUP (Cur 29 Tot 691231)
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_ivr_async.c:1520 Stop recording file /opt/fs_record_dir/upload/fs_record/2023/02/14/e3fc91ba-eb44-41e3-a1fd-59158ffa8abf.wav
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_ivr_async.c:1597 Channel is hung up
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_media_bug.c:1312 Removing BUG from sofia/internal/*@*:5060
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:848 (sofia/internal/*@*:5060) Callstate Change ACTIVE -> HANGUP
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:850 (sofia/internal/*@*:5060) State HANGUP
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_sofia.c:453 Channel sofia/internal/*@*:5060 hanging up, cause: NORMAL_CLEARING
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:60 sofia/internal/*@*:5060 Standard HANGUP, cause: NORMAL_CLEARING
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:850 (sofia/internal/*@*:5060) State HANGUP going to sleep
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:620 (sofia/internal/*@*:5060) State Change CS_HANGUP -> CS_REPORTING
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:585 (sofia/internal/*@*:5060) Running State Change CS_REPORTING (Cur 28 Tot 691231)
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:936 (sofia/internal/*@*:5060) State REPORTING
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:174 sofia/internal/*@*:5060 Standard REPORTING, cause: NORMAL_CLEARING
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:936 (sofia/internal/*@*:5060) State REPORTING going to sleep
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:611 (sofia/internal/*@*:5060) State Change CS_REPORTING -> CS_DESTROY
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_session.c:1736 Session 690161 (sofia/internal/*@*:5060) Locked, Waiting on external entities
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [NOTICE] switch_core_session.c:1754 Session 690161 (sofia/internal/*@*:5060) Ended
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [NOTICE] switch_core_session.c:1758 Close Channel sofia/internal/*@*:5060 [CS_DESTROY]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:739 (sofia/internal/*@*:5060) Running State Change CS_DESTROY (Cur 27 Tot 691231)
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:749 (sofia/internal/*@*:5060) State DESTROY
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_sofia.c:364 sofia/internal/*@*:5060 SOFIA DESTROY
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_opus.c:719 Opus decoder stats: Frames[2858] PLC[0] FEC[0]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_opus.c:734 Opus encoder stats: Frames[0] Bytes encoded[0] Encoded length ms[0] Average encoded bitrate bps[0]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_opus.c:719 Opus decoder stats: Frames[0] PLC[0] FEC[0]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] mod_opus.c:734 Opus encoder stats: Frames[974] Bytes encoded[52894] Encoded length ms[19480] Average encoded bitrate bps[22271]
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:181 sofia/internal/*@*:5060 Standard DESTROY
4e91949e-ac1a-11ed-a62b-7702869ffec7 2023-02-14 12:17:54.287178 [DEBUG] switch_core_state_machine.c:749 (sofia/internal/*@*:5060) State DESTROY going to sleep

**Comment by andywolk** [comment]
Are you able to make a coredump and provide backtraces for all threads?

**Comment by zhouzz1986** [comment]
@andywolk 
This is the log of the production server, which appears once or more every few days

It was discovered afterwards

I can't able to  make a coredump and provide backtraces for all threads

**Comment by briankwest** [comment]
You'll need to provide backtrace, Please reopen with a trace once you're able to gather it.
