### ISSUE TITLE
DTMF digits can be heard over hold music in a conference

### ISSUE THREAD

**Issue by hamptonng** [signalwire/freeswitch#1964]
**Describe the bug**
When a conference is created and a member within this conference is put on hold and played hold music, they are still able to hear DTMF digits entered by other members in the conference.

**To Reproduce**
Create a conference with three members (memberX, memberY and memberZ) using the dist-dtmf flag on all members
Use the following commands on the conference:

   conference deaf conf memberX
   conference mute conf memberX
   conference hold conf memberX holdmusic.wav

Press a DTMF digit on memberY - memberX can hear the digit through the hold music.

**Expected behavior**
memberZ should hear the DTMF, but memberX should only hear the hold music, no DTMF

**Package version or git hash**
1.10.7

**Comment by briankwest** [comment]
its behaving as expected with the dist-dtmf flag set.

**Comment by hamptonng** [comment]
How do you stop DTMF digits from another party from breaking through hold music then?  This seems very strange behavior.
