### ISSUE TITLE
FreeSwitch Event Viber Voice conversation not working

### ISSUE THREAD

**Issue by thiruk-softsuave** [signalwire/freeswitch#1971]
**Describe the bug**
When try to send voice conversation, it always returning NORMAL_TEMPORARY_FAILURE

**To Reproduce**
1. Send voice conversation to viber number

**Expected behavior**
Voice conversation should reach viber number

**Package version or git hash**
 - Version 1.6.10

**Trace logs**
"hangupCause" : "NORMAL_TEMPORARY_FAILURE",

**Comment by dragos-oancea** [comment]
Sounds like a routing/dialplan problem.
