### ISSUE TITLE
mod_opusfile incorrectly downsamples ogg file to 24khz

### ISSUE THREAD

**Issue by davehorton** [signalwire/freeswitch#199]
My question is about this line:

https://github.com/signalwire/freeswitch/blob/965bd27d5436fc803ef834823617870ebbb98d61/src/mod/formats/mod_opusfile/mod_opusfile.c#L285

I am testing with an ogg file retrieved from Google speech.  When I play it out, the audio sounds terrible and I see this in the log
```
EXECUTE [depth=1] sofia/drachtio_mrf/nobody@54.89.62.165:5060 playback(/tmp/860dc7fc-2cd5-11ea-b88e-7340f4d11c78_1.opus)
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:273 [OGG/OPUS File] Opening File [/tmp/860dc7fc-2cd5-11ea-b88e-7340f4d11c78_1.opus] 48000hz
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:282 [OGG/OPUS File] Channels: 1
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:284 [OGG/OPUS File] Original sampling rate: 24000 Hz
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:292 [OGG/OPUS File] Duration (samples): 356354
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:294 [OGG/OPUS File] Size (bytes): 29181
2020-01-01 20:30:18.428984 [INFO] mod_opusfile.c:297 [OGG/OPUS File] Encoded by: Google Speech using libopus
```
The problem is that the audio sample rate has been set by the code (as shown in the link above) to 24k and freeswitch plays it out at 24k whereas it should be played out at 48k.

In particular [this bit of information](https://github.com/xiph/opusfile/blob/d2577d7fdfda04bc32a853e80e62d6faa2a20859/include/opusfile.h#L56) from the opusfile repo, which in brief says 

>> The <tt>libopusfile</tt> API always decodes files to 48&nbsp;kHz.
   ..
   In general, if you are playing back the audio, you should leave it at
    48&nbsp;kHz, provided your audio hardware supports it.

If I comment out the line in the code that changed the sample rate info to 24K, leaving it at the default of 48K, the audio playout sounds correct.  Also, if I open the retrieved file in Audacity it shows the sample rate as 48K and sounds fine playing.

Is this a bug?  Or is there an alternate explanation to what I have outlined above?

**Comment by dragos-oancea** [comment]
thanks. see https://github.com/signalwire/freeswitch/pull/202 for your fix + another fix. 
I never tested at 24 Khz, perhaps you could upload a Google Speech sample file somewhere so I'll give it a try.

**Comment by davehorton** [comment]
here is an example:

https://drive.google.com/file/d/1TnrJlmvyb8idnkWU6N2mpVQyhNk9HqgJ/view?usp=sharing

**Comment by davehorton** [comment]
BTW, another issue I have noticed in playing an opus file is that I do not get an ESL event when the file completes playing (whereas I do get that event when playing an mp3 or wav). I will open a separate issue on this, unless you feel like your fix is related.

**Comment by dragos-oancea** [comment]
```
$ mediainfo greeting.opus 
General
Complete name                            : greeting.opus
Format                                   : OGG
File size                                : 33.4 KiB
Duration                                 : 8s 835ms
Overall bit rate                         : 31.0 Kbps

Audio
ID                                       : 0 (0x0)
Format                                   : Opus
Duration                                 : 8s 835ms
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 24.0 KHz
Compression mode                         : Lossy
Writing library                          : Google Speech using libopus
```
The file plays okay with the patch.
The missing event is related with the second issue fixed in the PR.
No need to open a separate issue.

**Comment by dragos-oancea** [comment]
@davehorton , https://github.com/signalwire/freeswitch/pull/206 . I believe the clipping is not related with the audio buffer not being drained, the sample_count we print now in debug mode shows exactly the same as the sample count in the ogg/opus header.

**Comment by davehorton** [comment]
In your testing with the file, did you experience the clipping I describe, or not ?

**Comment by dragos-oancea** [comment]
all audio was played. but there's a short noise right after it plays. smaller than half a second I'd say.  So I'd say no. But perhaps the issue depends on the duration of the file. I tested with with test vectors 04 and 12 from here: https://people.xiph.org/~greg/opus_testvectors/

**Comment by dragos-oancea** [comment]
There is no clipping with the file you shared, at least not with https://github.com/signalwire/freeswitch/pull/206 .

**Comment by dragos-oancea** [comment]
In case there's a mismatch about rates and channels between our testing methods, maybe it's useful to know the module also plays multichannel files, like https://people.xiph.org/~greg/opus_testvectors/opus_multichannel_examples/tron.6ch.opus

```
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:274 [OGG/OPUS File] Opening File [/tmp/tron.6ch.opus] 48000hz
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:283 [OGG/OPUS File] Channels: 6
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:285 [OGG/OPUS File] Original sampling rate: 48000 Hz
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:292 [OGG/OPUS File] Duration (samples): 817631
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:294 [OGG/OPUS File] Size (bytes): 688993
2020-01-07 15:18:59.716844 [INFO] mod_opusfile.c:297 [OGG/OPUS File] Encoded by: opus-tools 0.1.0 (using libopus 0.9.10-83-g7143b2d)
```
And the sample count when EOF is right: 
2020-01-07 15:19:16.536882 [DEBUG] mod_opusfile.c:382 [OGG/OPUS File] EOF. sample count: [817631]

**Comment by dragos-oancea** [comment]
this should be fixed in master.

**Comment by davehorton** [comment]
Is there a commit that addresses the clipping?  That PR that somehow got referenced to this issue actually seems unrelated

**Comment by dragos-oancea** [comment]
https://github.com/signalwire/freeswitch/pull/206
