### ISSUE TITLE
switch_core_pvt.h:313:31: error: a function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#2013]
**Describe the bug**
Make fails with message below. May be due to Xcode/Command Line Tools updated to 14.3. I tried: `./configure cxxflags='-Wno-strict-prototypes'` but it made no difference.

`  CC       src/libfreeswitch_la-switch_apr.lo
In file included from src/switch_apr.c:38:
./src/include/private/switch_core_pvt.h:313:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void switch_core_sqldb_destroy();
                              ^
                               void
1 error generated.
`

**To Reproduce**
Download master, bootstrap, config, make

**Expected behavior**
Make success.

**Package version or git hash**
commit 9494148b109ab55c3311abd6b486031d1f7581ca (HEAD -> master, origin/master, origin/HEAD)

**Build logs**
[05 FreeSWITCH bootstrap.txt](https://github.com/signalwire/freeswitch/files/11124268/05.FreeSWITCH.bootstrap.txt)

[06 FreeSWITCH configure.txt](https://github.com/signalwire/freeswitch/files/11124274/06.FreeSWITCH.configure.txt)
[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/11124277/07.FreeSWITCH.make.txt)

**Comment by andywolk** [comment]
Thank you. See https://github.com/signalwire/freeswitch/pull/2014
