### ISSUE TITLE
make fails switch_core_session.c:3008:15: error: variable 'count' set but not used 

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#2015]
**Describe the bug**
Make fails with message below. May be due to Xcode/Command Line Tools updated to 14.3. I tried: `./configure cxxflags='-Wno-unused-but-set-variable'` but it made no difference.

```
  CC       src/libfreeswitch_la-switch_core_session.lo
src/switch_core_session.c:3008:15: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
        int argc, x, count = 0;
                     ^
1 error generated.
make[1]: *** [src/libfreeswitch_la-switch_core_session.lo] Error 1
```

**To Reproduce**
Download master, bootstrap, config, make

**Expected behavior**
Make success.

**Package version or git hash**
commit d1639199c37b2a165cdb05ecedb2d472a7251c9a (HEAD -> master, origin/master, origin/HEAD)

**Comment by andywolk** [comment]
See https://github.com/signalwire/freeswitch/pull/2016
