### ISSUE TITLE
random keyword reserved in mysql 8.0.25

### ISSUE THREAD

**Issue by feiazifeiazi** [signalwire/freeswitch#2018]
SELECT random()
> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '()' at line 1
> 时间: 0.005s

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by andywolk** [comment]
Not enough information. What issue are you describing and what use case?
