### ISSUE TITLE
Freeswitch + keepalived + MySQL(ODBC) - Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by nikkadim** [signalwire/freeswitch#2063]
1) Two Freeswitch (Version 1.10.9) servers Active and Backup with keepalived (as described [here](https://freeswitch.org/confluence/display/FREESWITCH/High+Availability) and [here](https://freeswitch.org/confluence/display/FREESWITCH/HA+keepalived)) to control floating/virtual IPs, that part works fine. 
2) Switched core_db and all profiles from SQLite MySQL (via ODBC)  to sync two FS and start getting the error: "Deadlock found when trying to get lock; try restarting transaction". 

```
2023-04-24 01:33:12.298041 98.90% [ERR] switch_odbc.c:529 ERR: [update sip_registrations set ping_expires = 1682339621 where hostname='fs' and profile_name='external' and ping_expires <= 1682339592 ]

[STATE: HY000 CODE 1213 ERROR: [MySQL][ODBC 5.3(a) Driver][mysqld-5.7.35-log]Deadlock found when trying to get lock; try restarting transaction

]

2023-04-24 01:33:12.298041 98.90% [ERR] switch_core_sqldb.c:728 [db="fs_core";type="odbc"user="broot";pass="**********"] ODBC SQL ERR [STATE: HY000 CODE 1213 ERROR: [MySQL][ODBC 5.3(a) Driver][mysqld-5.7.35-log]Deadlock found when trying to get lock; try restarting transaction

]

update sip_registrations set ping_expires = 1682339621 where hostname='fs' and profile_name='external' and ping_expires <= 1682339592
```

**Describe the bug**
Switched core_db and all profiles from SQLite MySQL (via ODBC) and start getting the error: "Deadlock found when trying to get lock; try restarting transaction". 
**To Reproduce**
1) two Freeswitch (Version 1.10.9) servers Active and Backup with keepalived to control floating/virtual IPs, that part works fine. 
2) Switched core_db and all profiles from SQLite MySQL (via ODBC) and start getting the error: "Deadlock found when trying to get lock; try restarting transaction". 

FreeSWITCH (Version 1.10.9 -release-21-a615e85afc 64bit)
Debian GNU/Linux 11 (bullseye)
MySQL 5.7.35
ODBC 5.3(a) Driver

**Comment by nikkadim** [comment]
> try using mod_mariadb instead of odbc

@andywolk for the core_db?

**Comment by nikkadim** [comment]
switched cored_db and all profiles to  `"mysql://Server=x.x.x.x;Database=dbname;Uid=login;Pwd=passwd"`
and still getting  "Deadlock found when trying to get lock; try restarting transaction"

/etc/freeswitch/autoload_configs/switch.conf.xml
`<param name="core-db-dsn" value="mysql://Server=x.x.x.x;Database=dbname;Uid=login;Pwd=passwd"/>`
and in each profiles:
```
   <param name="odbc-dsn" value="mysql://Server=x.x.x.x;Database=dbname;Uid=login;Pwd=passwd" />
    <param name="track-calls" value="true"/>
```

**Comment by adamseeliger** [comment]
Same errors here using FreeSWITCH v1.10.7 and bitnami/mariadb-galera:10.8.7 docker container.
We don't use the track-calls feature.

**Comment by Len-PGH** [comment]
In `autoload_configs/pre_load_modules.conf.xml` do you have `<load module="mod_mariadb"/>`  comment removed?
