### ISSUE TITLE
Continue_on_fail

### ISSUE THREAD

**Issue by gregoriusus** [signalwire/freeswitch#2098]
I am using continue_on_fail successfully. But have now one specific case. Provider respond with sip status code 600, which FS translate as USER_BUSY. And USER BUSY is not in my continue_on_fail variable, so call does not continue.

So, how can I continue_on_call, if provider respond (sip_invite_failure_status) with sip code 600? Is it possible to expand continue_on_fail to put SIP response code in variable?

**Comment by mjerris** [comment]
the mappings from sip codes to our codes are from rfc.  there isn’t a way to do it by sip codes currently but we’d be happy to review a pull request to add that if you’d like to, but we don’t plan on adding this at this time.

**Comment by mylxf** [comment]
May I ask how you set it to continue calling or continue calling if continue _on_fail=false.
