### ISSUE TITLE
Crash (segfault) on latest master

### ISSUE THREAD

**Issue by florentchauveau** [signalwire/freeswitch#21]
Hello,

FS crashes (SIGSEGV) when reaching a bit of load (approximately 1500 channels and 3000 threads). 

I have attached the fscore_pb output (gdb backtrace). 

Yes, I have tested with latest master: 15ad4c23e259c1c2dff58f89e9124e5f36dd2e94 (as of yesterday) ;)

I can reproduce on both Debian 9 and Debian 10, and FS 1.8, 1.10.1, 1.10.2-dev, and git master 15ad4c23e2.

We use very few features, here is modules.conf.xml:

```
<configuration name="modules.conf" description="Modules">
  <modules>
    <load module="mod_console"/>
    <load module="mod_logfile"/>
    <load module="mod_event_socket"/>
    <load module="mod_sofia"/>
    <load module="mod_commands"/>
    <load module="mod_dptools"/>
    <load module="mod_dialplan_xml"/>
  </modules>
</configuration>
```

Dialplan:
```
<include>
  <context name="sbc">
    <extension name="cce">
      <condition>
        <action application="socket" data="REDACTED async full" />
        <action application="socket" data="REDACTED async full" />
        <action application="socket" data="REDACTED async full" />
        <action application="set" data="sip_rh_X-HupReason=Socket failed" />
        <action application="hangup" data="NETWORK_OUT_OF_ORDER" />
      </condition>
    </extension>
  </context>
</include>
```

We use `<param name="inbound-bypass-media" value="true"/>` in the sofia profile, so FS does not handle RTP at all.

I can provide access to a running server if needed.

Let me know if you need more informations.

[fscore_pb.zip](https://github.com/signalwire/freeswitch/files/3661731/fscore_pb.zip)

**Comment by mjerris** [comment]
[fscore_pb.post.txt](https://github.com/signalwire/freeswitch/files/3664238/fscore_pb.post.txt)

**Comment by mjerris** [comment]
in the future please attach non compressed attatchment for easier access.

**Comment by mjerris** [comment]
can you go into gdb for this core and:

frame 2
print *listener

**Comment by florentchauveau** [comment]
Sure:
```
(gdb) print *listener
$1 = {sock = 0x0, event_queue = 0x0, log_queue = 0x0, pool = 0x0, format = EVENT_FORMAT_PLAIN, flag_mutex = 0x0,
  filter_mutex = 0x0, flags = 0, level = SWITCH_LOG_CONSOLE, ebuf = 0x0, event_list = '\000' <repeats 90 times>,
  allowed_event_list = '\000' <repeats 90 times>, event_hash = 0x0, allowed_event_hash = 0x0, allowed_api_hash = 0x0,
  rwlock = 0x0, session = 0x0, lost_events = 0, lost_logs = 0, last_flush = 0, expire_time = 0, timeout = 0, id = 0,
  sa = 0x0, remote_ip = '\000' <repeats 49 times>, remote_port = 0, filters = 0x0, linger_timeout = 0, next = 0x0,       pollfd = 0x0}
```

**Comment by dragos-oancea** [comment]
it look like you're doing Outbound. Tell us more about your setup.

**Comment by florentchauveau** [comment]
Yes, I am using ESL outbound to "control" the calls. I am using FS as a SIP B2BUA, nothing fancy.

Here are the first commands I send:

- "linger"
- "filter Event-Name CHANNEL_HANGUP_COMPLETE"
- "filter Application bridge"
- "myevents"

and then I execute the following api commands based on events I receive:

- set
- unset
- export
- hangup
- privacy
- sched_hangup
- bridge


The ESL server has a specific thread to consume events as fast as possible. 

I can provide an example dump of an ESL connection if needed.

**Comment by vma** [comment]
Hi,

The crash is likely caused by a null socket dereferencing when calling `switch_socket_opt_set()` in the `listener_run()` function. I have opened PR #95 to add some checks on this function.

It will avoid the crash but does not solve the core issue which is why your listener struct is almost uninitialized. I can try to have a look at your running server if you still have it, please send me a PM.

Best Regards,
Vallimamod.

**Comment by crienzo** [comment]
Open a new issue if this is still happening.
