### ISSUE TITLE
Cannot compile last git (Jan 8th 2020)

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#210]
Here is the error after make

conference_event.c: In function ‘conference_event_mod_channel_handler’:
conference_event.c:111:2: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  111 |  switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);

thanks

**Comment by ROBERT-MCDOWELL** [comment]
Fedora 30 64bits
gcc 9.0

**Comment by ROBERT-MCDOWELL** [comment]
I solved it by changing
const char *action = NULL;
to
const char *action = "";
I don't know if it's right but works.

**Comment by mjerris** [comment]
-    switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);
+    switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action ? action : "N/A", cid);

this i think is right, if someone can test and make into a pr i can merge

**Comment by ROBERT-MCDOWELL** [comment]
Seems to compile fine now, but cannot open a PR dunno why :(
