### ISSUE TITLE
Playback of RAW files does not work since FS 1.10.2

### ISSUE THREAD

**Issue by hheedfeld** [signalwire/freeswitch#212]
Problem occurs since upgrade to FS 1.10.2, getting following error message:

`2020-01-08 10:28:03.286958 [ERR] mod_sndfile.c:202 Error Opening File [/sounds/cache/0bdb774028c9eccdec2c1d864a20d81233aabb154307a64de70b1a774781d18d.raw] [Error. Bad format field in SF_INFO struct when opening a RAW file for read.]`

Same file worked well in previous versions.

Debian 9.11 (Jessie)
FS installed from packages
libsndfile1 Version 1.0.27-3

**Comment by dragos-oancea** [comment]
so what was the libsndfile1 version in the FS version that worked ? as far as I know there's no real standard for ".raw" files and not sure what sort of header needs parsing in the lib. the ".raw" files we can play are headerless. Perhaps you could upload a sample file somewhere.

**Comment by hheedfeld** [comment]
The libsndfile1 version did not change. I just made an upgrade from FS 1.10.1 to 1.10.2 - since then playback of raw files failed. 

I attached a zipped sample file. It's PCM, 8 kHz, mono.

[5f505e601c94954e78b95681e58b66b335d50fbf1922cf736e43f7aaa8b9045d.raw.zip](https://github.com/signalwire/freeswitch/files/4041236/5f505e601c94954e78b95681e58b66b335d50fbf1922cf736e43f7aaa8b9045d.raw.zip)

**Comment by dragos-oancea** [comment]
can you try this PR ?  https://github.com/signalwire/freeswitch/pull/217

**Comment by hheedfeld** [comment]
FreeSWITCH Version 1.10.3-dev+git~20200110T143646Z~3a2f6adb30~64bit (git 3a2f6ad 2020-01-10 14:36:46Z 64bit)

EXECUTE [depth=0] sofia/internal/1001@192.168.76.130 playback(/tmp/4af3b42eaa2fae8cd377b29e862af5d6243d2b2f8a911bd99f1bad71440ef303.raw)

Works like a charm!

**Comment by andywolk** [comment]
Fixed
