### ISSUE TITLE
not support openssl3.x

### ISSUE THREAD

**Issue by depinglin85** [signalwire/freeswitch#2122]
**Is your feature request related to a problem? Please describe.**
I have found that FreeSWITCH does not support OpenSSL 3, but I want to use a third-party library (gRPC) to develop some modules.

**Describe the solution you'd like**
Does FreeSWITCH have any plans to support OpenSSL 3? If so, can you provide an estimated timeline?

**Describe alternatives you've considered**
I tried to include the OpenSSL 3 library in my mod's CMakeLists.txt file. There were no errors during the compilation process. However, when calling a third-party function, I encountered the following error:

Error in non-idempotent operation SynthesizeSpeech: failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2404:6800:4004:826::200a%5D:443: Network is unreachable.

**Package version or git hash**
- Version of FreeSWITCH v1.10.9

**Comment by azzbcc** [comment]
#1767
