### ISSUE TITLE
freeswitch spandsp compilation error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#2158]
**Describe the bug**
make
....
make[4]: Entering directory '/home/src/freeswitch/src/mod/applications/mod_spandsp'
  CC       mod_spandsp_la-mod_spandsp.lo
  CC       mod_spandsp_la-udptl.lo
  CC       mod_spandsp_la-mod_spandsp_fax.lo
  CC       mod_spandsp_la-mod_spandsp_dsp.lo
mod_spandsp_dsp.c: In function 'get_v18_mode':
mod_spandsp_dsp.c:159:17: error: 'V18_MODE_5BIT_4545' undeclared (first use in this function)
  159 |         int r = V18_MODE_5BIT_4545;
      |                 ^~~~~~~~~~~~~~~~~~
mod_spandsp_dsp.c:159:17: note: each undeclared identifier is reported only once for each function it appears in
mod_spandsp_dsp.c:165:29: error: 'V18_MODE_5BIT_50' undeclared (first use in this function)
  165 |                         r = V18_MODE_5BIT_50;
      |                             ^~~~~~~~~~~~~~~~
mod_spandsp_dsp.c: In function 'spandsp_tdd_send_session':
mod_spandsp_dsp.c:216:21: error: too few arguments to function 'v18_init'
  216 |         tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
      |                     ^~~~~~~~
In file included from /usr/local/include/spandsp.h:111,
                 from mod_spandsp.h:50,
                 from mod_spandsp_dsp.c:36:
/usr/local/include/spandsp/v18.h:138:29: note: declared here
  138 | SPAN_DECLARE(v18_state_t *) v18_init(v18_state_t *s,
      |                             ^~~~~~~~
mod_spandsp_dsp.c: In function 'spandsp_tdd_encode_session':
mod_spandsp_dsp.c:263:26: error: too few arguments to function 'v18_init'
  263 |         pvt->tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
      |                          ^~~~~~~~
/usr/local/include/spandsp/v18.h:138:29: note: declared here
  138 | SPAN_DECLARE(v18_state_t *) v18_init(v18_state_t *s,
      |                             ^~~~~~~~
mod_spandsp_dsp.c: In function 'spandsp_tdd_decode_session':
mod_spandsp_dsp.c:341:26: error: too few arguments to function 'v18_init'
  341 |         pvt->tdd_state = v18_init(NULL, FALSE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, pvt);
      |                          ^~~~~~~~
/usr/local/include/spandsp/v18.h:138:29: note: declared here
  138 | SPAN_DECLARE(v18_state_t *) v18_init(v18_state_t *s,
....

**Package version or git hash**
 - Version last git

**Comment by akscf** [comment]
This also present in 1.10.9, as a temporary solution used the following 
(hope not mistaken with additional args in v18_init())
```
--- mod_spandsp_dsp.c   2023-02-03 20:07:30.000000000 +0000
+++ mod_spandsp_dsp.c.fixes     2023-07-13 08:47:35.332074299 +0000
@@ -156,13 +156,13 @@
 {
        switch_channel_t *channel = switch_core_session_get_channel(session);
        const char *var;
-       int r = V18_MODE_5BIT_4545;
+       int r = V18_MODE_WEITBRECHT_5BIT_4545;

        if ((var = switch_channel_get_variable(channel, "v18_mode"))) {
                if (!strcasecmp(var, "5BIT_45") || !strcasecmp(var, "baudot")) {
-                       r = V18_MODE_5BIT_4545;
+                       r = V18_MODE_WEITBRECHT_5BIT_4545;
                } else if (!strcasecmp(var, "5BIT_50")) {
-                       r = V18_MODE_5BIT_50;
+                       r = V18_MODE_WEITBRECHT_5BIT_4545;
                } else if (!strcasecmp(var, "DTMF")) {
                        r = V18_MODE_DTMF;
                } else if (!strcasecmp(var, "EDT")) {
@@ -213,7 +213,7 @@
                return SWITCH_STATUS_FALSE;
        }

-       tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
+       tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, NULL, NULL);


        v18_put(tdd_state, text, -1);
@@ -260,7 +260,7 @@
        }

        pvt->session = session;
-       pvt->tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
+       pvt->tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, NULL, NULL);
        pvt->head_lead = TDD_LEAD;

        v18_put(pvt->tdd_state, text, -1);
@@ -338,7 +338,7 @@
        }

        pvt->session = session;
-       pvt->tdd_state = v18_init(NULL, FALSE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, pvt);
+       pvt->tdd_state = v18_init(NULL, FALSE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, pvt, NULL, NULL);

        if ((status = switch_core_media_bug_add(session, "spandsp_tdd_decode", NULL,
                                                tdd_decode_callback, pvt, 0, SMBF_READ_REPLACE | SMBF_NO_PAUSE, &bug)) != SWITCH_STATUS_SUCCESS) {

```

**Comment by ROBERT-MCDOWELL** [comment]
works! many thanks!

**Comment by akscf** [comment]
you are welcome

**Comment by piotrgregor** [comment]
[This commit](https://github.com/freeswitch/spandsp/commit/d9681c3747ff4f56b1876557b9f6d894b7e6c18d#diff-348092e97708aedff108326c3f98a9ea907ee9a58b5a780e508d5f08503475fb) broke compatibllity between `libspandsp` and `mod_spandsp`. `mod_spandsp` must be updated to use new defines introduced in that commit.
As a workaround reset to something preceding that commit, e.g.:
`git reset --hard 67d2455efe02e7ff0d897f3fd5636fed4d54549e`

**Comment by seven1240** [comment]
https://github.com/signalwire/freeswitch/issues/2184

**Comment by nadirhamid** [comment]
@piotrgregor solution works nicely. It was a headache to debug this, thank you.

**Comment by ikrammuzamil** [comment]
> [This commit](https://github.com/freeswitch/spandsp/commit/d9681c3747ff4f56b1876557b9f6d894b7e6c18d#diff-348092e97708aedff108326c3f98a9ea907ee9a58b5a780e508d5f08503475fb) broke compatibllity between `libspandsp` and `mod_spandsp`. `mod_spandsp` must be updated to use new defines introduced in that commit. As a workaround reset spandsp to something preceding that commit, e.g.: `git reset --hard 67d2455efe02e7ff0d897f3fd5636fed4d54549e` Reconfigure, compile, reinstall spandsp.

thanks dear it's worked

**Comment by Forcheny** [comment]
> [This commit](https://github.com/freeswitch/spandsp/commit/d9681c3747ff4f56b1876557b9f6d894b7e6c18d#diff-348092e97708aedff108326c3f98a9ea907ee9a58b5a780e508d5f08503475fb) broke compatibllity between `libspandsp` and `mod_spandsp`. `mod_spandsp` must be updated to use new defines introduced in that commit. As a workaround reset spandsp to something preceding that commit, e.g.: `git reset --hard 67d2455efe02e7ff0d897f3fd5636fed4d54549e` Reconfigure, compile, reinstall spandsp.

Thanks so much. It works on my lab.

**Comment by 2054686334** [comment]
same at 1.10.12,using docker

**Comment by Jiangzuw** [comment]
@piotrgregor thanks! this way is done

**Comment by tomu4** [comment]
Can't believe this is still not fixed after year and half! Thank you for providing workaround, @akscf , really helped 👍

**Comment by ROBERT-MCDOWELL** [comment]
it's fixed, forgot to close the issue...

**Comment by tomu4** [comment]
> it's fixed, forgot to close the issue...

Actually, I'm not sure it is fixed, I'm just now doing fresh install and I run into this exact issue. Had to do workaround mentioned by akscf.

**Comment by ROBERT-MCDOWELL** [comment]
ha ok so I open it again, the fix I used above has not been override by any git update so....

**Comment by yois615** [comment]
Yes, it's not fixed, I still need to git reset...

**Comment by enesgur** [comment]
It's still happening... v1.10.12

**Comment by ROBERT-MCDOWELL** [comment]
if someone can create a PR for the patch of @akscf above it will wake up FS team I guess.

**Comment by yois615** [comment]
This is not so simple...

Since some people use the Debian package of spandsp to compile freeswitch, applying that workaround to the freeswitch source code will break compiling for those using the package.

**Comment by ROBERT-MCDOWELL** [comment]
ha ok. my bad :(

**Comment by tomu4** [comment]
> This is not so simple...
> 
> Since some people use the Debian package of spandsp to compile freeswitch, applying that workaround to the freeswitch source code will break compiling for those using the package.

Maybe two versions with compilation flag?

**Comment by enesgur** [comment]
maybe this issue number should be added the install page as a known issue.

**Comment by akscf** [comment]
patch for 1.10.12
```
--- mod_spandsp_dsp.c   2025-04-17 03:26:20.700799007 +0400
+++ mod_spandsp_dsp.c.fixes     2025-04-17 03:34:55.643791291 +0400
@@ -156,13 +156,13 @@
 {
        switch_channel_t *channel = switch_core_session_get_channel(session);
        const char *var;
-       int r = V18_MODE_5BIT_4545;
+       int r = V18_MODE_WEITBRECHT_5BIT_4545;

        if ((var = switch_channel_get_variable(channel, "v18_mode"))) {
                if (!strcasecmp(var, "5BIT_45") || !strcasecmp(var, "baudot")) {
-                       r = V18_MODE_5BIT_4545;
+                       r = V18_MODE_WEITBRECHT_5BIT_4545;
                } else if (!strcasecmp(var, "5BIT_50")) {
-                       r = V18_MODE_5BIT_50;
+                       r = V18_MODE_WEITBRECHT_5BIT_4545;
                } else if (!strcasecmp(var, "DTMF")) {
                        r = V18_MODE_DTMF;
                } else if (!strcasecmp(var, "EDT")) {
@@ -213,7 +213,7 @@
                return SWITCH_STATUS_FALSE;
        }

-       tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
+       tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, NULL, NULL);


        v18_put(tdd_state, text, -1);
@@ -260,7 +260,7 @@
        }

        pvt->session = session;
-       pvt->tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL);
+       pvt->tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, NULL, NULL);
        pvt->head_lead = TDD_LEAD;

        v18_put(pvt->tdd_state, text, -1);
@@ -338,7 +338,7 @@
        }

        pvt->session = session;
-       pvt->tdd_state = v18_init(NULL, FALSE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, pvt);
+       pvt->tdd_state = v18_init(NULL, FALSE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, pvt, NULL, NULL);

        if ((status = switch_core_media_bug_add(session, "spandsp_tdd_decode", NULL,
                                                tdd_decode_callback, pvt, 0, SMBF_READ_REPLACE | SMBF_NO_PAUSE, &bug)) != SWITCH_STATUS_SUCCESS) {

```

**Comment by yois615** [comment]
@akscf I believe that a patch for this was merged upstream into Master already.

**Comment by akscf** [comment]
highly unlikely ;)

**Comment by ghost** [comment]
seems to be fixed in upstream tho @ROBERT-MCDOWELL i just compiled on ubuntu 25

**Comment by ROBERT-MCDOWELL** [comment]
confirmed, thanks!
