### ISSUE TITLE
E: Failed to fetch https://freeswitch.signalwire.com/repo/deb/debian-release/dists/buster/InRelease  401  Unauthorized [IP: 

### ISSUE THREAD

**Issue by muyichuanqi** [signalwire/freeswitch#2164]
E: Failed to fetch https://freeswitch.signalwire.com/repo/deb/debian-release/dists/buster/InRelease  401  Unauthorized [IP: 190.102.98.174 443]
E: The repository 'https://freeswitch.signalwire.com/repo/deb/debian-release buster InRelease' is not signed.
The command '/bin/sh -c apt-get update && apt-get install ca-certificates lsb-release -y --no-install-recommends     && echo "machine freeswitch.signalwire.com login signalwire password ${TOKEN}" > /etc/apt/auth.conf     && echo "deb [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg] https://freeswitch.signalwire.com/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list     && apt-get update && apt-get install -y freeswitch-all     && apt-get purge -y --auto-remove ca-certificates lsb-release     && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by muyichuanqi** [comment]
**/freeswitch/docker/examples/Debian11**  **bug**


Step 12/18 : RUN cd /usr/src/libs/spandsp && ./bootstrap.sh && ./configure CFLAGS="-g -ggdb" --with-pic --prefix=/usr && make -j`nproc --all` && make install
 ---> Running in d7029e928664
mkdir: cannot create directory 'config': File exists
configure.ac:21: error: Autoconf version 2.71 or higher is required
configure.ac:21: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
/bin/sh: 1: ./configure: not found

**Comment by andywolk** [comment]
SignalWire Personal Access Tokens (PAT)s are required to access FreeSWITCH install packages.
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/HOWTO-Create-a-SignalWire-Personal-Access-Token_67240087/
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Linux/Debian_67240088/
