### ISSUE TITLE
mod_verto How to do screen sharing without using Google Chrome browser extensions? 

### ISSUE THREAD

**Issue by YongFaGitHub** [signalwire/freeswitch#2165]
Currently, Verto Communicator does not support screen sharing functionality as the corresponding plugin has been discontinued. Can you provide an updated version of this feature or provide an example of how to do screen sharing without using Google Chrome browser extensions?

**Comment by seven1240** [comment]
verto communicator moved to https://github.com/freeswitch/verto-client

there's a new demo https://git.xswitch.cn/xswitch/xcc-examples/src/branch/master/webrtc/es6 which uses https://www.npmjs.com/package/@xswitch/rtc?activeTab=versions maybe you can try if than can help.
