### ISSUE TITLE
mod_vmd -- stalls channel after calling "start"

### ISSUE THREAD

**Issue by nblasgen** [signalwire/freeswitch#218]
I realize that mod_avmd() is recommended, but since mod_vmd() still exists, it should still work.

If you direct a call to a LUA program that calls `session:execute("vmd","start")` it causes Freeswitch to stall.  You can't even kill the channel at that point.  I'm not sure if the same issue exists outside of LUA.

The simple dumbed down LUA script is as follows:

```
session:execute("vmd","start");
session:streamFile("/var/lib/freeswitch/recordings/pc_2");
```

If you comment out the `start` call, it plays the audio, if you leave it uncommented, it locks the channel.

I'm running `FreeSWITCH (Version 1.10.2 -release-13-f7bdd3845a 64bit)`

**Comment by nblasgen** [comment]
In case it matters, since I'm originating this directly to LUA:

`originate {absolute_codec_string='^^:PCMU:PCMA',origination_caller_id_number=???}sofia/gateway/myroute/??? &lua(/tmp/test2.lua)`

**Comment by nblasgen** [comment]
Additionally, worth saying that I also tested today with Freeswitch 1.10.1 (2019-08-20) and master branch (git 975e6a6 2020-01-10 18:38:38Z 64bit) and both also had the same issue.

**Comment by mjerris** [comment]
we have no plans to do any work on this module.  This will almost definitely be deprecated and removed.  I'd suggest moving to mod_avmd.

**Comment by mjerris** [comment]
I've pushed notes to that module so people know its deprecated
