### ISSUE TITLE
modifying logfile in logfile.conf.xml is invalid

### ISSUE THREAD

**Issue by chenyw11** [signalwire/freeswitch#2196]
- Version [1.10.7]

I want to modify log dir, but logfile.conf.xml is invalid.

My modification:
```
<param name="logfile" value="/logs/freeswitch.log"/>
```
After I restart freeswitch, log is still in `/usr/local/freeswitch/log/freeswitch.log`

Then I modified `vars.xml`:
```
<X-PRE-PROCESS cmd="set" data="log_dir=/logs/freeswitch.log"/>
```
After I restart freeswitch, log is still in `/usr/local/freeswitch/log/freeswitch.log`

**Comment by seven1240** [comment]
you can only change the file name other than the log dir, use `freeswitch -log /logs` to change it when you start freeswitch

```
freeswitch -h

	-log [logdir]           -- alternate directory for logfiles
```
