### ISSUE TITLE
global-opened ports 2855+2856 can't be disabled

### ISSUE THREAD

**Issue by sh-dvl** [signalwire/freeswitch#22]
just started with fs 1.10 from git after using a previous version for longer time, but after it has started there're always two ports opened globally: 0.0.0.0:2855 and 0.0.0.0:2856.

after long-time search in documentation without any result, several tries with disabling modules and then deeper look at the code it's clear: there's no possibility to change this behaviour without patching the code. wtf?

because unnecessarily opened ports (and I've really nothing found, that would explain, why this was always necessary in such a way) are always potential risks, this is a bug for me and should be fixed soon.

**Comment by seven1240** [comment]
it's switch_msrp and enabled by default. I'm open to ideas to disable it but the easiest way perhaps to add a `disable-msrp = true` param in `msrp.conf.xml`. Could you make a patch?

**Comment by crienzo** [comment]
Fixed
