### ISSUE TITLE
The header Identity is duplicate from LegA to LegB twice.

### ISSUE THREAD

**Issue by samtroniks** [signalwire/freeswitch#2203]
**Describe the bug**
The header Identity is duplicate from LegA to LegB twice.
I place a call with a header Identity set, I bridge the call then the header is duplicate on the other hand but twice.

**To Reproduce**
1. Bridge a call with a Header Identity

**Expected behavior**
The header would be duplicate but once not twice.

**Package version or git hash**
 - FreeSWITCH (Version 1.10.9 -release-21-a615e85afc 64bit)

**Trace logs**
log from app info : 
LegA
variable_sip_identity: [keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.example.org/XXX.pem>;alg=ES256;ppt="shaken"]
variable_sip_h_identity: [keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.example.org/XXX.pem>;alg=ES256;ppt="shaken"]
variable_sip_i_identity: [keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.example.org/XXX.pem>;alg=ES256;ppt="shaken"]

LegB : 
variable_sip_h_identity: [keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.example.org/XXX.pem>;alg=ES256;ppt="shaken"]

Sip trace : 
legA : 
recv 1693 bytes from udp/[XXXXXXXX]:5060 at 10:15:04.107883:
------------------------------------------------------------------------
INVITE sip:XXXXXXXX@10.78.0.12:5060 SIP/2.0
Via: SIP/2.0/UDP XXXXXXXX:5060;branch=z9hG4bK02B0000b47fbe7f909c
[...]
Content-Length:   309
Content-Type: application/sdp
Identity: keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.xxxx17.pem/>;alg=ES256;ppt="shaken"
Attestation-info: B

LegB
send 1649 bytes to udp/[XXXXXXXX]:5060 at 10:15:04.125649:
------------------------------------------------------------------------
INVITE sip:XXXXXXXX@myprovider.fr SIP/2.0
Via: SIP/2.0/UDP 10.78.0.12;rport;branch=z9hG4bKpatSN0ZjDcvyH
Max-Forwards: 64
From: "+XXXXXXXX" <sip:+XXXXXXXX@10.78.0.12;user=phone>;tag=maNBXKHpKrD5r
To: <sip:XXXXXXXX@myprovider.fr;user=phone>
Call-ID: 71522d1a-b5f7-123c-e096-06ec05b96f04
CSeq: 71493460 INVITE
Identity: keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.xxxx17.pem/>;alg=ES256;ppt="shaken"
Identity: keiJTOJX6VrRZ-UOOqpqpUukjKpg;info=<https://cr-uat.xxxx17.pem/>;alg=ES256;ppt="shaken"

**Comment by xrobau** [comment]
Refer to existing bug https://github.com/freeswitch/sofia-sip/issues/206 (which has a workaround in my freeswitch builder, https://github.com/xrobau/freeswitch-ubuntubuilder/commit/addb1ce6fc8fa4178f7d3eb776a8bafd1fca3a77)

Apparently the cause has been found, and it'll be fixed soon! 
https://forum.signalwire.community/t/problem-with-double-identity-headers-on-b-leg-stir-and-shaken/693/4

**Comment by samtroniks** [comment]
Good News thank you.

**Comment by samtroniks** [comment]
Duplicate bug : https://github.com/freeswitch/sofia-sip/issues/206

**Comment by andywolk** [comment]
@xrobau The bug is in FreeSWITCH not libsofia-sip. Take a look at this: https://github.com/signalwire/freeswitch/commit/9cc7c2d58146a4797fe391a7380a2aeef3f53130

**Comment by garrington** [comment]
This issue remains in Version 1.10.10-release+git~20230813T165739Z~4cb05e7f4a~64bit (git 4cb05e7 2023-08-13 16:57:39Z 64bit), compiled from release branch.  When will a release branch containing the fix for this be made?
