### ISSUE TITLE
no video from freeswitch with h264 mode 0

### ISSUE THREAD

**Issue by eschmidbauer** [signalwire/freeswitch#2205]
**Describe the bug**
A-leg receives no video from freeswitch when b-leg answers with h264 mode=0

**To Reproduce**
1. register h264 video capable softphone with freeswitch
2. dial an extension which executes the bridge to zoomcrc (no auth required from zoom): `<action application="bridge" data="[^^:absolute_codec_string=pcmu,h264]sofia/internal/sip:1@zoomcrc.com"/>`

**Expected behavior**
After the call is answered, we would expect freeswitch to send video both directions. Currently freeswitch is receiving video from softphone, transmitting to zoom, receiving video from zoom, but _not_ transmitting back to softphone.

**Package version or git hash**
 - FreeSWITCH Version 1.10.11-dev+git~20230813T202020Z~b74245d48a~64bit (git b74245d 2023-08-13 20:20:20Z 64bit)

**Trace logs**
[freeswitch.log](https://github.com/signalwire/freeswitch/files/12352778/freeswitch.log)

**Comment by seven1240** [comment]
what if you do `originate [absolute_codec_string=pcmu\,h264]sofia/internal/sip:1@zoomcrc.com &decode_video`
