### ISSUE TITLE
manage-presence / Proxy-authentication required

### ISSUE THREAD

**Issue by skainz92** [signalwire/freeswitch#2244]
Hey, 

i have the following setup: 
Kamailio as SBC, freeswitch handling media and some logic.

One of the things freeswitch should handle is voicemail. 
Works like a charm - but since i upgraded from 1.4.18 to 1.10.8 it doesnt work anymore.

The part that doesnt work is the subscription of the message-summary. 
Here is a trace from the freeswitch-node: ( SUBSCRIBE from kamailio to freeswitch )

recv 833 bytes from udp/[xxx]:5060 at 16:32:55.562057:
------------------------------------------------------------------------
SUBSCRIBE sip:fff@xxx SIP/2.0
Record-Route: <sip:xxx;lr;nat=yes>
Via: SIP/2.0/UDP xxx;branch=z9hG4bK5fd9.8447f9ff3f9883ca1facc7a0b760fd4f.0
Via: SIP/2.0/UDP 10.100.102.26:5060;received=xxx;branch=z9hG4bKb6c8002c7f1179eafae06130a67c13f1;rport=65477
From: "ddd" <sip:fff@xxx>;tag=3619273671
To: "ddd" <sip:fff@xxx>
Call-ID: 1597059919@10_100_102_26
CSeq: 283383984 SUBSCRIBE
Contact: <sip:fff@10.100.102.26:5060;alias=xxx~65477~1>
Max-Forwards: 69
User-Agent: fff
Event: message-summary
Expires: 3600
Allow: NOTIFY
Accept: application/simple-message-summary
Content-Length: 0

send 928 bytes to udp/[xxx]:5060 at 16:32:55.564988:
------------------------------------------------------------------------
SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/UDP xxx;branch=z9hG4bK5fd9.8447f9ff3f9883ca1facc7a0b760fd4f.0;rport=5060
Via: SIP/2.0/UDP 10.100.102.26:5060;received=xxx;branch=z9hG4bKb6c8002c7f1179eafae06130a67c13f1;rport=65477
From: "ddd" <sip:fff@xxx>;tag=3619273671
To: "ddd" <sip:fff@xxx>;tag=Zvjrj1pBt78cB
Call-ID: 1597059919@10_100_102_26
CSeq: 283383984 SUBSCRIBE
User-Agent: xxx
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Proxy-Authenticate: Digest realm="xxx", nonce="asdfasfasdfasdfafa", algorithm=MD5, qop="auth"
Content-Length: 0

I have set manage-presence to "true" on external profile and made sure the request is received on the correct profile.
also i have set "presence_hosts" to _DISABLED_.

I have also made sure that requests from the source-ip are allowed by acl - calls do work just fine, subscriptions dont. 
I have set "auth-calls" and "auth-all-packets" to false. 
Also i have
<param name="local-network-acl" value="localnet.auto"/>

In /conf/autoload_configs/lua.conf.xml i defined a "directory.lua" to handle directory events like so:
<param name="xml-handler-script" value="directory.lua"/>
<param name="xml-handler-bindings" value="directory"/>
This file does not get executed.

The log does not provide anything useful, even on "sofia loglevel all 9".

Any help would be much appreciated!
Thanks!

PS:
I would have send this to the users-list, but the same exact configuration works on version 1.4.18, thats why im opening an issue.

**Comment by seven1240** [comment]
You could disable subsciber auth in sofia profile config, but it's unsecure, see https://github.com/signalwire/freeswitch/security/advisories/GHSA-g7xg-7c54-rmpj

**Comment by skainz92** [comment]
thank you very much! 
its working now.

**Comment by pawelrurka** [comment]
Hello. Where did you disable subscriber auth in sofia profile config? I checked my sofia.conf.xml file and there is no information about it...

**Comment by skainz92** [comment]
<param name="disable-auth-subscriptions" value="true"/>

in your profile config. For example external.xml under sip_profiles.
