### ISSUE TITLE
Debian 12 / Freeswitch 1.10.10 ( spandsp/private/v80.h: No such file or directory )

### ISSUE THREAD

**Issue by skainz92** [signalwire/freeswitch#2248]
Hello, 

i just set up a clean debian 12 server and followed the installation-instructions of freeswitch. 
When compiling freeswitch-1.10.10 i get the following error-message: 

```
making all mod_spandsp
make[4]: Entering directory '/usr/src/freeswitch-1.10.10/src/mod/applications/mod_spandsp'
  CC       mod_spandsp_la-mod_spandsp.lo
In file included from /usr/local/include/spandsp.h:155,
                 from mod_spandsp.h:50,
                 from mod_spandsp.c:39:
/usr/local/include/spandsp/expose.h:69:10: fatal error: spandsp/private/v80.h: No such file or directory
   69 | #include <spandsp/private/v80.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:751: mod_spandsp_la-mod_spandsp.lo] Error 1
make[4]: Leaving directory '/usr/src/freeswitch-1.10.10/src/mod/applications/mod_spandsp'
make[3]: *** [Makefile:731: mod_spandsp-all] Error 1
make[3]: Leaving directory '/usr/src/freeswitch-1.10.10/src/mod'
make[2]: *** [Makefile:632: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/freeswitch-1.10.10/src'
make[1]: *** [Makefile:3716: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/freeswitch-1.10.10'
make: *** [Makefile:1438: all] Error 2
```

I checked - the v80.h file doesnt exist in this directory. however, it exists in /usr/local/include/spandsp/.
I tried to symlink - but then i get a bunch of differen error-messages.
Is it possible that spandsp is not compatible with debian 12 yet? 

regards,

**Comment by andywolk** [comment]
try using older commits of spandsp. it is under heavy development by the author and using master may be not ideal.

**Comment by skainz92** [comment]
Yes. that did it. Thanks very much.

For everybody that runs into the same problem: 

1) git clone https://github.com/freeswitch/spandsp.git
2) cd spandsp/
3) git checkout 0d2e6ac
4) sh autogeh.sh && ./bootstrap.sh && ./configure && make && make install

thats it. 

thank you very much!
regards

**Comment by erseyang** [comment]
> Yes. that did it. Thanks very much.
> 
> For everybody that runs into the same problem:
> 
> 1. git clone https://github.com/freeswitch/spandsp.git
> 2. cd spandsp/
> 3. git checkout 0d2e6ac
> 4. sh autogeh.sh && ./bootstrap.sh && ./configure && make && make install
> 
> thats it.
> 
> thank you very much! regards

that should be sh autogen.sh.
