### ISSUE TITLE
make fails switch_core_sqldb.c:705:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t'

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#2250]
**Describe the bug**
C, C++ and Clang deprecated various syntax and coding over the years. Recent compilers are now disallowing deprecated code, this started in 2020 and is extending in future compiler releases. FreeSwitch code contains deprecated items that previously compiled, but now causes failed building.

This is on macOS Sonoma which requires Command Line Tools 15 Clang and Ventura on an Intel Mac, it would also apply to Apple Silicon.

An example causing the error below:
"In Clang 15, the -Wint-conversion warning has been upgraded to an error. This warning catches when an integer is being implicitly converted to a pointer. One common mistake that this warning will catch is implicit function definitions, where code tries to call a function that has not been declared."

I don't know how to fix this in the code. I tried various flags such as ./configure "--Wno-enum-conversion" and ./configure "--Wno-Wenum-conversion" but just got "unrecognized option". the error messages are:

`src/switch_core_sqldb.c:705:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_exec(dbh->native_handle.odbc_dbh, sql, NULL, &errmsg);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/switch_core_sqldb.c:907:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_exec_string(dbh->native_handle.odbc_dbh, sql, str, len, err);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/switch_core_sqldb.c:1192:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_callback_exec(dbh->native_handle.odbc_dbh, sql, helper_callback, &h, err);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/include/switch_odbc.h:94:3: note: expanded from macro 'switch_odbc_handle_callback_exec'
                switch_odbc_handle_callback_exec_detailed(__FILE__, (char * )__SWITCH_FUNC__, __LINE__, \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/switch_core_sqldb.c:1251:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_callback_exec(dbh->native_handle.odbc_dbh, sql, helper_callback, &h, err);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/include/switch_odbc.h:94:3: note: expanded from macro 'switch_odbc_handle_callback_exec'
                switch_odbc_handle_callback_exec_detailed(__FILE__, (char * )__SWITCH_FUNC__, __LINE__, \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/switch_core_sqldb.c:1308:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_callback_exec(dbh->native_handle.odbc_dbh, sql, callback, pdata, err);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/include/switch_odbc.h:94:3: note: expanded from macro 'switch_odbc_handle_callback_exec'
                switch_odbc_handle_callback_exec_detailed(__FILE__, (char * )__SWITCH_FUNC__, __LINE__, \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/switch_core_sqldb.c:1361:13: error: implicit conversion from enumeration type 'switch_odbc_status_t' to different enumeration type 'switch_status_t' [-Werror,-Wenum-conversion]
                        status = switch_odbc_handle_callback_exec(dbh->native_handle.odbc_dbh, sql, callback, pdata, err);
                               ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/include/switch_odbc.h:94:3: note: expanded from macro 'switch_odbc_handle_callback_exec'
                switch_odbc_handle_callback_exec_detailed(__FILE__, (char * )__SWITCH_FUNC__, __LINE__, \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**To Reproduce**
Download master, bootstrap, config, make

**Expected behavior**
Make success.

**Package version or git hash**
commit 792eee44d0611422cce3c3194f95125916a7d268 (HEAD -> master, origin/master, origin/HEAD)

**Comment by MuneebAhmed568** [comment]
hey, have you found any solution regarding the above problem? I also have the same problem. Trying to Run FreeSwitch on M1.

**Comment by andywolk** [comment]
That's the fix https://github.com/signalwire/freeswitch/pull/2333
