### ISSUE TITLE
mod_spandsp memory leak

### ISSUE THREAD

**Issue by falcazarr** [signalwire/freeswitch#2251]
In the following function, the pointers get set appropriately to remove from the linked list, but the allocated memory is never freed.

In mod_spandsp_fax.c:

```
static int del_pvt(pvt_t *del_pvt)
{
	pvt_t *p, *l = NULL;
	int r = 0;


	switch_mutex_lock(t38_state_list.mutex);

	for (p = t38_state_list.head; p; p = p->next) {
		if (p == del_pvt) {
			if (l) {
				l->next = p->next;
			} else {
				t38_state_list.head = p->next;
			}
			p->next = NULL;
			r = 1;
			break;
		}

		l = p;
	}

	switch_mutex_unlock(t38_state_list.mutex);

	wake_thread(0);

	return r;
}
```

**Comment by boteman** [comment]
FreeSWITCH handles memory pools internally, so it will not release memory to the operating system immediately, or maybe never.

**Comment by falcazarr** [comment]
> FreeSWITCH handles memory pools internally, so it will not release memory to the operating system immediately, or maybe never.

It is a memory leak internally, though, right?

**Comment by andywolk** [comment]
It is not a memory leak. `pvt_t` structs are allocated in a session's memory pool. They will be freed on hangup.

**Comment by falcazarr** [comment]
> It is not a memory leak. `pvt_t` structs are allocated in a session's memory pool. They will be freed on hangup.

Got it.
