### ISSUE TITLE
Error Loading module /usr/local/freeswitch/mod/xml.so

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [signalwire/freeswitch#2252]
**Describe the bug**
On a fresh freeswitch installation of version 1.10.10, I tried to reload xml from fs_cli, and it gave the following error.

```
2023-09-28 17:22:07.889086 99.60% [CRIT] switch_loadable_module.c:1754 Error Loading module /usr/local/freeswitch/mod/xml.so
**/usr/local/freeswitch/mod/xml.so: cannot open shared object file: No such file or directory**
2023-09-28 17:22:07.889086 99.60% [INFO] mod_enum.c:884 ENUM Reloaded
2023-09-28 17:22:07.889086 99.60% [INFO] switch_time.c:1433 Timezone reloaded 1750 definitions

```
Freeswitch was compiled from source, the modules I needed during compilation where commented out, Installation was successfull.
Another thing to note is, there is no such module as xml, on previous freeswitch installation I never encountered this error.
Also check the mod folder there is no file as xml.so, I belive this problem is unique to this version.
**To Reproduce**
Compile and install FreeSWITCH Freeswitch from source, using version 1.10.10 on ubuntu20.04.

**Expected behavior**
Request for mod.xml that doesn't exist or shouldn't exist.

**Package version or git hash**
 - Version [e.g. 1.10.10]

**Comment by andywolk** [comment]
Typo? `xml` instead of `mod_xml` ?

**Comment by mjerris** [comment]
all our mod names are prefixed with mod_ and it appears you missed that in your entry in modules.conf.  this is a config typo

**Comment by AlijiEmmanuel-dev** [comment]
My bad, you are very correct. I used the wrong module name in fs_cli.
I am now able to reload any module at will without getting the error.
