### ISSUE TITLE
No package freeswitch-config-vanilla available.

### ISSUE THREAD

**Issue by ChiMuYuan** [signalwire/freeswitch#2270]
**Describe the bug**
[A clear and concise description of what the bug is.](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Linux/CentOS-7-and-RHEL-7_10289546)
when i run 'yum install -y freeswitch-config-vanilla freeswitch-lang-* freeswitch-sounds-*' got error:
No package freeswitch-config-vanilla available.
No package freeswitch-lang-* available.
No package freeswitch-sounds-* available.

![image](https://github.com/signalwire/freeswitch/assets/26971626/689008e2-69a5-4f03-8d2f-eccff6adb503)

thank you

**To Reproduce**
1. Using this example configuration...
2. Dial into conference using verto
3. Play my_problem_file.mp4 into conference
4. FreeSWITCH crashes

**Expected behavior**

**Package version or git hash**
 - Version [e.g. 1.10.4]

**Trace logs**
Provide freeswitch logs w/ DEBUG and UUID logging enabled

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
(gdb) set pagination off
(gdb) set logging file /tmp/backtrace.log
(gdb) set logging on
Copying output to /tmp/backtrace.log.
(gdb) bt
(gdb) bt full
(gdb) info threads
(gdb) thread apply all bt
(gdb) thread apply all bt full
(gdb) set logging off
Done logging to /tmp/backtrace.log.
(gdb) quit
```

**Comment by ChiMuYuan** [comment]
in ubuntu:
apt update got 404, ....does not have a Release file
![image](https://github.com/signalwire/freeswitch/assets/26971626/21b54e26-c8ed-4809-a8ca-56475145aa51)

can anyone help me?

thank you

**Comment by tmancill** [comment]
Hi @ChiMuYuan .   The [Installation page](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/#installation-methods) documents support for Debian 12 (bookworm) and CentOS 7.  I haven't tried CentOS, but the Debian packages are working well for me.

If you use a distribution other than Debian, you can always build a Debian-based Docker image and run FreeSWITCH as a container.  See https://github.com/signalwire/freeswitch/pull/2234 for instructions on how to build an image using the Debian packages.

**Comment by XM15569722276** [comment]
@tmancill I also use Centos7.  I also encountered the same problem. 
No package freeswitch-config-vanilla available.
No package freeswitch-lang- available.
No package freeswitch-sounds-* available.

**Comment by ChiMuYuan** [comment]
I changed to ubuntu system
