### ISSUE TITLE
Freeswitch responds to inbound late-offer INVITE with RTP/AVP when rtp_secure_media = MANDATORY

### ISSUE THREAD

**Issue by tomeeo** [signalwire/freeswitch#2280]
**Description**

Freeswitch can respond to late-offer Invites when `enable-3pcc=true`.  However, it will only respond with RTP/AVP ( non-secure ) SDP.   We have `<X-PRE-PROCESS cmd="set" data="rtp_secure_media=mandatory"/>`  set in `vars.xml` but we still get a 200OK response with RTP/AVP.   Ultimately once the ACK is received and Freeswitch observes that the settled SDP is not secure, and the call fails to set up ( since Crypto is required ).

**To Reproduce**
1. Set "enable-3pcc=true" in sip profile set to receive inbound call.    Set `rtp_secure_media=MANDATORY` in vars.xml
2. Send late-offer invite into Freeswitch  ( [example sipp scenario](https://github.com/sieteunoseis/sipp/blob/main/scenarios/uac-passive.xml) )
3. Observe SDP attached to the 200 OK that Freeswitch responds with

**Expected behavior**
Freeswitch should follow the `rtp_secure_media=MANDATORY` requirement and respond to late offer Invite with a RTP/SAVP in the 200 OK SDP

**Package version or git hash**
 - [1.10.7]

Here is inbound invite:

```
recv 746 bytes from tls/[x.y.z.q]:41549 at 15:58:52.949040:
------------------------------------------------------------------------
INVITE sip:test@x.y.z.q:5060;transport=tls SIP/2.0
Via: SIP/2.0/TLS x.y.z.q:5567;branch=z9hG4bK79b6.1a970c011ff40715727891c63261d300.0
Via: SIP/2.0/UDP x.y.z.q:5060;received=x.y.z.q;branch=z9hG4bK79b6.1153f75622019d94f74737739b30d08d.0
From: <sip:tester@a.b.c.d:13882>;tag=34744SIPpTag001
To: test <sip:test@x.y.z.q:5060>
Call-ID: 1-34744@10.2.193.27
CSeq: 1 INVITE
Max-Forwards: 68
Contact: <sip:btpsh-652ee274-2bfd-6@a.b.c.d>
Content-Length: 0
```

Here is 200 OK response from FS:

```
send 1238 bytes to tls/[x.y.z.q]:41549 at 15:58:52.949880:
------------------------------------------------------------------------
SIP/2.0 200 OK
Via: SIP/2.0/TLS x.y.z.q:5567;branch=z9hG4bK79b6.1a970c011ff40715727891c63261d300.0;rport=41549
Via: SIP/2.0/UDP x.y.z.q:5060;branch=z9hG4bK79b6.1153f75622019d94f74737739b30d08d.0
From: <sip:tester@a.b.c.d:13882>;tag=34744SIPpTag001
To: test <sip:test@x.y.z.q:5060>;tag=D49p805N7tHrc
Call-ID: 1-34744@10.2.193.27
CSeq: 1 INVITE
Contact: <sip:test@10.x.y.z:5568;transport=tls>
User-Agent: FreeSWITCH-mod_sofia/1.10.7-release+git~20211024T163933Z~883d2cb662~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 240

v=0
o=FreeSWITCH 1697626116 1697626117 IN IP4 10.x.y.z
s=FreeSWITCH
c=IN IP4 10.x.y.z
t=0 0
m=audio 18616 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
```

**Comment by dragos-oancea** [comment]
https://github.com/signalwire/freeswitch/pull/2281 - we're taking steps to make this work, this won't fix it but it's a step towards more clarity.

**Comment by tomeeo** [comment]
@dragos-oancea  curious if you foresee any updates on this anytime soon ?

**Comment by dragos-oancea** [comment]
Maybe you could try a patch ? hint: in switch_core_session_parse_crypto_prefs() , the condition "switch_channel_direction(session->channel) == SWITCH_CALL_DIRECTION_INBOUND" that shows twice should be something like "sdp_type == SDP_TYPE_REQUEST" or "sdp_type == SDP_OFFER" (with https://github.com/signalwire/freeswitch/pull/2281). The sdp_type is in the payload map (payload_map_t) which you can retrieve from the media engine (eg: session->media_handle->engines[SWITCH_MEDIA_TYPE_AUDIO].payload_map).

**Comment by tomeeo** [comment]
@dragos-oancea  I took a crack at a [patch](https://github.com/signalwire/freeswitch/pull/2359) for this.  Turns out that `switch_core_session_parse_crypto_prefs` was not even being called in the inbound NO-SDP / 3pcc = true scenario.  My PR fixes my issue but not sure if there is any collateral damage.  Tests pass 🤷

**Comment by jakubkarolczyk** [comment]
Proper fix has been merged.
https://github.com/signalwire/freeswitch/commit/49029c8575891b4f3a637d43214d5df323760171
Thanks for reporting this problem.
