### ISSUE TITLE
reload tls certificate without service interruption

### ISSUE THREAD

**Issue by abma** [signalwire/freeswitch#2287]
We are using Letsencrypt certificates for freeswitch. It seems its not possible to update the certificate without restarting:

"reloadxml" doesn't make freeswitch use the updated certificate.

I have to run

"sofia profile internal restart"

to make freeswitch use the new certificate which kills the (tcp/tls) connections to the clients.

I'm using freeswitch 1.10.10 on debian bullseye.

**Comment by mjerris** [comment]
This is a limitation of the sip stack sofia-sip.  If you wanted to add a pull request to implement this capability to do this on sofia-sip, do so there and then re-open here once that exists.
