### ISSUE TITLE
Make files in test unit switch_rtp unknown type name 'uint'; did you mean 'int'?

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#229]
Tested in 1.10.2 and 1.10.3-dev+git~20200110T210334Z~4ed2af733d. At the end of make I get: (make attached)
  CC       switch_rtp.o
switch_rtp.c:18:1: error: unknown type name 'uint'; did you mean 'int'?
uint datalen;

This started over a month ago with master but did not appear to affect FS coming up. Then, it is now in 1.10.2. I did not report it because I was busy chasing another issue related to homebrew all xmas week and I thought it was just a master/testing thing. But now that it's in 1.10.2 I thought it should be looked at after this long.

MacOS 10.15.2
[07 FreeSWITCH make.txt.zip](https://github.com/signalwire/freeswitch/files/4055007/07.FreeSWITCH.make.txt.zip)

**Comment by dragos-oancea** [comment]
thanks for reporting. this PR just removes that line: https://github.com/signalwire/freeswitch/pull/230 . var wasn't used .

**Comment by MarioG-X** [comment]
Clean make now, thanks!
