### ISSUE TITLE
problem installing freeswitch repos bookworm

### ISSUE THREAD

**Issue by covici** [signalwire/freeswitch#2301]
Hi.  Trying to install freeswitch using https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Linux/Debian_67240088/#about and I still get signatures cannot be verified.  The gpg key is in /usr/share/keyrings it is /usr/share/keyrings/signalwire-freeswitch-repo.gpg but its not seen  at all.

Thanks.

**Comment by andywolk** [comment]
Just tested. Works for me.

**Comment by covici** [comment]
hmm, so what can I do to fix?  My freeswitch.list in
/etc/apt/sources.list.d  says
deb [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg]
https://freeswitch.signalwire.com/repo/deb/debian-release/ bookworm main
deb-src [signed-by=/usr/share/keyrings/signalwire-freeswitch-repo.gpg]
https://freeswitch.signalwire.com/repo/deb/debian-release/ bookworm main


On Mon, 06 Nov 2023 08:50:15 -0500,
Andrey Volk wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> Just tested. Works for me.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/2301#issuecomment-1794868875
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (quoted-printable)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***

**Comment by Len-PGH** [comment]
@covici what do you get with this command as root user?
```gpg --list-keys --keyring /usr/share/keyrings/signalwire-freeswitch-repo.gpg```

**Comment by covici** [comment]
I get
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search_first failed: Invalid packet


On Mon, 06 Nov 2023 11:20:10 -0500,
Len wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> @covici what do you get with this command as root user?
> ```gpg --list-keys --keyring /usr/share/keyrings/signalwire-freeswitch-repo.gpg```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/2301#issuecomment-1795335821
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***

**Comment by Len-PGH** [comment]
gpg key seems invalid. try wget again.
```wget --http-user=signalwire --http-password=$TOKEN -O /usr/share/keyrings/signalwire-freeswitch-repo.gpg https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg```

**Comment by covici** [comment]
OK, that worked and the apt-get update worked also.

Thanks a lot.

On Mon, 06 Nov 2023 15:32:54 -0500,
Len wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> gpg key seems invalid. try wget again.
> ```wget --http-user=signalwire --http-password=$TOKEN -O /usr/share/keyrings/signalwire-freeswitch-repo.gpg https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/2301#issuecomment-1796387779
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***

**Comment by covici** [comment]
Well, I did the apt-get update, but in looking through the packages it
wants to install, I don't see mod_managed which I will need. How would
I get that one, or do I have to abandon installing the packages and
install from source?

On Mon, 06 Nov 2023 15:32:54 -0500,
Len wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> gpg key seems invalid. try wget again.
> ```wget --http-user=signalwire --http-password=$TOKEN -O /usr/share/keyrings/signalwire-freeswitch-repo.gpg https://freeswitch.signalwire.com/repo/deb/debian-release/signalwire-freeswitch-repo.gpg```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/2301#issuecomment-1796387779
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         ***@***.***
