### ISSUE TITLE
build-deps freeswitch fails on bookworm

### ISSUE THREAD

**Issue by covici** [signalwire/freeswitch#2305]
When I try  to execute apt-get build-deps freeswitch on bookworm, I get the following
Preparing to unpack .../libdc1394-dev_2.2.6-4_amd64.deb ...
Unpacking libdc1394-dev:amd64 (2.2.6-4) ...
dpkg: error processing archive /var/cache/apt/archives/libdc1394-dev_2.2.6-4_amd64.deb (--unpack):
 trying to overwrite '/usr/include/dc1394/camera.h', which is also in package libdc1394-22-dev:amd64 2.2.5-1
Errors were encountered while processing:
 /var/cache/apt/archives/libdc1394-dev_2.2.6-4_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: Failed to process build dependencies

I did rename that file, but still no joy, how to proceed?

Thanks.

**Comment by andywolk** [comment]
If you have broken packages in your system then `apt-get build-dep freeswitch` may fail. We do not maintain any of those packages you mentioned. Try removing old versions of those so there are no conflicts.
Closing this as a non FreeSWITCH question. You can ask questions on our Slack.
