### ISSUE TITLE
[Feature] Sofia Event custom headers

### ISSUE THREAD

**Issue by volga629-1** [signalwire/freeswitch#2307]
Freeswitch Version

```
FreeSWITCH Version 1.10.9-release~64bit ( 64bit)

```

Issue

Many endpoints is sending custom information like Snom on REGISTER supply local lan IP with X-Real-IP header.
Other important information is location services (911) on phones like Yealink and Snom X-Location headers.

Currently custom headers are not included in sofia events  for registration or calling.

Solution 

Sofia Event   will parse all headers and add them to even sofia::register sofia::pre_register sofia_register_attempt  as

```
variable_sip_h_X-name

```

**Comment by greenbea** [comment]
If you're using curl or lua to build the XML files dynamically, then the REQUEST_PARAMS event passes all X sip headers of the registration in the event so you can access it there.

https://github.com/signalwire/freeswitch/blob/master/src/mod/endpoints/mod_sofia/sofia_reg.c#L3173-L3178

**Comment by volga629-1** [comment]
Thank you for reply, I tried find information what will correct way to fetch that event 

That I tried, but get in lua user data and I am not sure if this right way to call it. 

```
local event = freeswitch.Event("REQUEST_PARAMS");
```

**Comment by volga629-1** [comment]
Should I call in lua  hooks REQUEST_PARAMS ?

**Comment by volga629-1** [comment]
Closing issue is has  been resolved with configuration.
