### ISSUE TITLE
freeswitch1.10.10，playback wav file, AMR/8000,  after 10 second, phone will hangup by Reason: SIP;text="QOS"

### ISSUE THREAD

**Issue by JackMa2023** [signalwire/freeswitch#2324]
**Describe the bug**
freeswitch1.10.10，playback wav file, AMR/8000,  after 10 second, phone(VIVO， HUAWEI is ok.) will hangup by Reason: SIP;text="QOS"

**To Reproduce**
1. answer, 
2. loop_playback(+3, /home/test.wav)

**Package version or git hash**
 - Version [e.g. 1.10.10]
![image](https://github.com/signalwire/freeswitch/assets/129134671/8b4a8e43-19a7-4c25-91d9-41572fbd36f5)

**Comment by dragos-oancea** [comment]
It looks it's hangup by the VOLTE network. 
What if you try a lower "default-bitrate" in amr.conf.xml ?
Eg, smallest bitrate:
```
 <param name="default-bitrate" value="0"/>
```

**Comment by JackMa2023** [comment]
> It looks it's hangup by the VOLTE network. What if you try a lower "default-bitrate" in amr.conf.xml ? Eg, smallest bitrate:
> 
> ```
>  <param name="default-bitrate" value="0"/>
> ```

i try it. but it does not work.  
i think is:  there are no rtp  from phone to freeswitch.
 
![image](https://github.com/signalwire/freeswitch/assets/129134671/f14347be-2fb9-4dae-9971-0c129dc3b955)

**Comment by dragos-oancea** [comment]
Make sure AMR shows when you do "show codecs" at fs_cli. It should show like:
```
codec,AMR / Bandwidth Efficient,mod_amr
codec,AMR / Octet Aligned,mod_amr
```

**Comment by JackMa2023** [comment]
> Make sure AMR shows when you do "show codecs" at fs_cli. It should show like:
> 
> ```
> codec,AMR / Bandwidth Efficient,mod_amr
> codec,AMR / Octet Aligned,mod_amr
> ```

1. mod_amr is loaded.
2. vars.xml ：
<X-PRE-PROCESS cmd="set" data="global_codec_prefs=OPUS,G722,PCMU,PCMA,H264,VP8,AMR"/>
  <X-PRE-PROCESS cmd="set" data="outbound_codec_prefs=OPUS,G722,PCMU,PCMA,H264,VP8,AMR"/>
  3. sdp has amr 8k

**Comment by JackMa2023** [comment]
vars.xml:
<X-PRE-PROCESS cmd="set" data="global_codec_prefs=OPUS,G722,PCMU,PCMA,H264,VP8,AMR"/>
  <X-PRE-PROCESS cmd="set" data="outbound_codec_prefs=OPUS,G722,PCMU,PCMA,H264,VP8,AMR"/>

**Comment by dragos-oancea** [comment]
It could be in passthrough. Also the fact that there's no RTP from phone to FS looks like a different problem than a codec problem. You could also upload a pcap.

**Comment by JackMa2023** [comment]
> It could be in passthrough. Also the fact that there's no RTP from phone to FS looks like a different problem than a codec problem. You could also upload a pcap.

thanks, i find the reseaon，because of renegotiation sdp.  and i test it sueccss.
