### ISSUE TITLE
BYE Reason header length limitation

### ISSUE THREAD

**Issue by denyspozniak** [signalwire/freeswitch#2326]
**Describe the bug**
Hello!

I discovered an interesting problem: if, with a simple call established, a BYE is sent from side B with such a Reason header, then the FS will not terminate leg A.
There will also be no errors in the debug log.
If you remove one character, everything will work fine.
It is likely that there is some kind of limitation on the length of the text field.
This is reproduced on version 1.10.10

**To Reproduce**
Simply add similar Reason:
```
BYE sip:100@1.1.1.1:5060;transport=udp SIP/2.0
Reason: Q.850;cause=16;text="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx this line is 106 characters long xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
**Package version or git hash**
FreeSWITCH Version 1.10.10-release-24-4cb05e7f4a~64bit (-release-24-4cb05e7f4a 64bit)

**Comment by andywolk** [comment]
Are you able to compile FreeSWITCH from source to check one thing real quick?

**Comment by denyspozniak** [comment]
@andywolk yes, I can try

**Comment by andywolk** [comment]
See if changing this size helps https://github.com/signalwire/freeswitch/blob/master/src/mod/endpoints/mod_sofia/mod_sofia.c#L491

**Comment by andywolk** [comment]
does it help if you change 128 to 256 here? https://github.com/signalwire/freeswitch/blob/master/src/mod/endpoints/mod_sofia/mod_sofia.c#L491

**Comment by denyspozniak** [comment]
@andywolk 
Yes, now everything works as it should!!!
Thanks!

I'm not sure if there is any restriction on the length of Reason according to the RFC.
It is likely that if such a limit is exceeded, it would be necessary to simply delete this Reason, or the text parameter itself.

**Comment by andywolk** [comment]
@denyspozniak @mahald See if that helps https://github.com/signalwire/freeswitch/pull/2329

**Comment by bferreirq** [comment]
> Got the same issue, MS Teams adds long messages in there 120+ (only for the text) seems to be normal form MS Teams. Will you include/fix this in next Release?

is it fix for you ?
