### ISSUE TITLE
 Audio RTP Errror [ Remote Address Error!]

### ISSUE THREAD

**Issue by amitpaltech** [signalwire/freeswitch#235]
freeswitch working on Ipv6 , clients registered on Ipv4 through a device which converted the packet from ipv4 to ipv6. now when making a call by internal-ipv6 profile call getting disconnected by giving message 'NOT ACCEPTABLE HERE'.  FS show a log Error " Audio RTP error [Remote Address Error!] .

Sip packet received from client having sub_host address of Ipv4 series. but here fs are in Ipv6, 
how can we resolve it .it can work if  sip packet  should be convert to Ipv6 completely.

**Comment by briankwest** [comment]
attach logs and version info for FreeSWITCH

**Comment by briankwest** [comment]
Reopen once you have logs.
