### ISSUE TITLE
Audio Stream Over Websocket

### ISSUE THREAD

**Issue by surabhigarg1234** [signalwire/freeswitch#2432]
Could you please help, how I can stream audio over Websocket using FreeSWITCH?

I have checked but just found one module which is mod_audio_stream but this is not present in FreeSWITCH Master Branch. 

Not a bug.. just a query

**Comment by surabhigarg1234** [comment]
This is not bug.. just a question.

**Comment by hhadzem** [comment]
There is an existing module available [here](https://github.com/drachtio/drachtio-freeswitch-modules/tree/main/modules) - mod_audio_fork.
