### ISSUE TITLE
[mod_unimrcp] Healthcheck from FreeSWITCH to UniMRCP Server

### ISSUE THREAD

**Issue by surabhigarg1234** [signalwire/freeswitch#2437]
Is there any way to send Healthcheck/OPTION packets from FreeSWITCH to UniMRCP(v2) server? 
if yes, what configuration needs to be done for this in FreeSWITCH?

**Comment by seven1240** [comment]
mod_unimrcp was moved to https://github.com/freeswitch/mod_unimrcp

I'm not sure if it's possible to send OPTIONS, but it's SIP so if you find out, please let us know. And PR is welcome.
