### ISSUE TITLE
Can not build libv8 in CentOS 7.9

### ISSUE THREAD

**Issue by homepy** [signalwire/freeswitch#2442]
**Describe the bug**
I want to build the mod_v8, so I need to build the libv8( https://github.com/freeswitch/libv8-packaging.git ) first.
But I found that it seems that the MakeFile only supports to build in Debian.
How to build libv8 in CentOS 7.9 ? I can not find any suggest in the  documents (https://developer.signalwire.com/freeswitch/).

**To Reproduce**
1. Using these commands
git clone https://github.com/freeswitch/libv8-packaging.git /usr/local/src/libs/libv8-packaging
cd /usr/local/src/libs/libv8-packaging/linux
make build

**Package version or git hash**
 - Version [e.g. 1.10.11]

**Comment by andywolk** [comment]
Unfortunately we do not support mod_v8 for CentOS.

**Comment by homepy** [comment]
I found it.

# install v8-6.2.91 and v8-devel-6.2.91 from a third-party yum repo okay
yum install http://repo.okay.com.mx/centos/7/x86_64/release/libicu57-57.1-12.el7.x86_64.rpm http://repo.okay.com.mx/centos/7/x86_64/release/v8-6.2.91-7.el7.x86_64.rpm  http://repo.okay.com.mx/centos/7/x86_64/release/v8-devel-6.2.91-7.el7.x86_64.rpm  --skip-broken
