### ISSUE TITLE
Error opening unknow file end with codec pcma/pcmu/opus

### ISSUE THREAD

**Issue by TechGuyVN** [signalwire/freeswitch#2445]
**Describe the bug**
Our freeswitch core through this error, i have no idea with this
`2024-04-26 09:06:58.028720 70.50% [ERR] mod_native_file.c:74 Error opening /mnt/data/freeswitch/recordings/contact4/.PCMA
2024-04-26 09:07:00.608698 69.83% [ERR] mod_native_file.c:74 Error opening /mnt/data/freeswitch/recordings/david/.PCMA
`
can Anyone have this issued and how to fix, please help me solve this

**Package version or git hash**
 - Version : FreeSWITCH Version 1.10.11-release-25-f24064f7c9~64bit (-release-25-f24064f7c9 64bit)

**Comment by suiyuemanbu** [comment]
if you 
playback(/mnt/data/freeswitch/recordings/contact4/)
That's when the problem you're talking about happens.

**Comment by TechGuyVN** [comment]
I mean where .pcma come from , I didn’t setting this type, it’s codec of audio stream

**Comment by iamtalhaasghar** [comment]
> I mean where .pcma come from , I didn’t setting this type, it’s codec of audio stream

same here, having same problem / issue

**Comment by iamtalhaasghar** [comment]
> if you playback(/mnt/data/freeswitch/recordings/contact4/) That's when the problem you're talking about happens.
> 
> you should playback(/mnt/data/freeswitch/recordings/contact4.wav)

this is the answer i was doing `switch_play_file('a-m')` changed it to `switch_play_file('a-m.wav')` and the error was gone.
