### ISSUE TITLE
Unable to continue recording when call is on hold

### ISSUE THREAD

**Issue by bhagatsameer** [signalwire/freeswitch#248]
We have a client who would like to continue call recording when the Agent is placing the call on hold ( playing default MOH / played using Local stream) but recording gets paused (record_session). Hence the final call recording does not have call hold duration due to which the call duration and recording duration does not match.

How can we continue recording when the call is placed on hold?

**Freeswitch Version** : FreeSWITCH Version 1.6.20-37-987c9b9~64bit (-37-987c9b9 64bit)

**Comment by briankwest** [comment]
Please test on 1.10.2

**Comment by royalpinto** [comment]
@briankwest issue seems to be present on v1.10.5 too.

I tried an internal call too from a user (agent) to another user. When the caller puts on hold, the recording pauses but when the callee puts on hold, the recording does not pause.
