### ISSUE TITLE
./configure does not say which dependencies are missing

### ISSUE THREAD

**Issue by evandrocoan** [signalwire/freeswitch#249]
There are only few Linux distros supported (which use dependency installer as):
```
wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -
 
echo "deb http://files.freeswitch.org/repo/deb/debian-release/ stretch main" > /etc/apt/sources.list.d/freeswitch.list
echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ stretch main" >> /etc/apt/sources.list.d/freeswitch.list
 
apt-get update
  
# Install dependencies required for the build
apt-get build-dep freeswitch
```

If you want to install Freeswich in any other distro, the `./configure` does not say which dependencies are missing.

The only way to install Freeswitch in some other distro as Ubuntu 19, it to run the `make` command and see the errors and search on google for the missing dependency.

The problem about this workflow is that every time you find a missing dependency by running make, you have to restart the whole process again, i.e.: delete all source files, clone the Freeswitch repository again, and run `./bootstrap.sh`, `./configure` and make again otherwise it will not detect the installed dependency.

**Comment by briankwest** [comment]
You appear to be missing libks for mod_signalwire.

**Comment by mjerris** [comment]
Configure DOES say which deps are not found.
