### ISSUE TITLE
Freeswitch not relaying 180 Ringing after 183 Session Progress

### ISSUE THREAD

**Issue by skainz92** [signalwire/freeswitch#2490]
Hi, 

It seems that freeswitch is not relaying 180 Ringing it receives on B-Leg to A-Leg, after a Session Progress. 
I've tried setting ignore_early_media to ring_ready, but in that case freeswitch always relays a 180 to the A-Channel when it receives a 183 on B-Channel, which means early-media wouldn't work. ( As far as i've understood it )

Is there a way to tell freeswitch to relay that 180? 
Im on version 1.10.10, debian12

thank you very much!
regards

**Comment by briankwest** [comment]
It shouldn't, the numbers should never go down, once you've hit 183 you can't go back to 180.
