### ISSUE TITLE
Freeswitch right away Answers the  late-offer INVITE without checking Dialplan flow if enable-3pcc=true

### ISSUE THREAD

**Issue by surabhigarg1234** [signalwire/freeswitch#2493]
Currently, as mentioned in title - Freeswitch Right Away Answers the  late-offer INVITE without checking Dialplan flow whether that call needs to be answered or not if enable-3pcc=true.

Also, if I dont enable "enable-3pcc=true" then FreeSWITCH disconnects the call saying 3pcc flag is not enabled 

Is there anyway where in case of late-offer INVITE , freeswitch first check dialplan whether the call needs to be answered or not and then only it answer the call?

**Comment by garg-s-app** [comment]
Hi Team,

Can anyone help me out here. 

How can freeswitch first check dialplan whether the call needs to be answered or not and then only it answer the call in case of  late-offer INVITE ?

**Comment by surabhigarg1234** [comment]
Hi Team,
Could anyone help on how can  freeswitch first check dialplan whether the call needs to be answered or not and then only it answer the call in case of  late-offer INVITE?

**Comment by jakubkarolczyk** [comment]
It works as expected. Use `enable-3pcc=proxy` instead.
