### ISSUE TITLE
error load module mod_xml_curl

### ISSUE THREAD

**Issue by zongshikeqi** [signalwire/freeswitch#2558]
I install FreeSwitch-1.10.11 with macOS Homebrew, and i want to use mod_xml_curl to call my server application.
by default no mod_xml_curl.so, i download source code and make the mod_xml_curl.so, then copy to /lib/freeswitch/mod/
![20240801-161256](https://github.com/user-attachments/assets/aaabd8f9-c7d1-430a-8ff0-721c50400267)

modules.conf.xml
![20240801-162652](https://github.com/user-attachments/assets/3d2c1aee-b132-4153-b7b9-efe52a0c8bfb)

when i start service, load error
```
[CRIT] switch_loadable_module.c:1754 Error Loading module /usr/local/Cellar/freeswitch/1.10.11/lib/freeswitch/mod/mod_xml_curl.so
**dlopen(/usr/local/Cellar/freeswitch/1.10.11/lib/freeswitch/mod/mod_xml_curl.so, 0x0006): Library not loaded: /usr/local/freeswitch/lib/libfreeswitch.1.dylib
  Referenced from: <21D91070-0CFB-3D81-9ED2-6F86616E7083> /usr/local/Cellar/freeswitch/1.10.11/lib/freeswitch/mod/mod_xml_curl.so
  Reason: tried: '/usr/local/freeswitch/lib/libfreeswitch.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/freeswitch/lib/libfreeswitch.1.dylib' (no such file), '/usr/local/freeswitch/lib/libfreeswitch.1.dylib' (no such file)**
```

**Comment by zongshikeqi** [comment]
i copy the libfreeswitch.1.dylib to path /usr/local/freeswitch/lib/
and restart service, load fail
```
2024-08-01 16:21:55.507731 0.00% [CONSOLE] switch_loadable_module.c:1772 Successfully Loaded [mod_logfile]
2024-08-01 16:21:55.511687 0.00% [CONSOLE] switch_loadable_module.c:1772 Successfully Loaded [mod_enum]
2024-08-01 16:21:55.511699 0.00% [NOTICE] switch_loadable_module.c:273 Adding Dialplan 'enum'
2024-08-01 16:21:55.511712 0.00% [NOTICE] switch_loadable_module.c:329 Adding Application 'enum'
2024-08-01 16:21:55.511725 0.00% [NOTICE] switch_loadable_module.c:389 Adding API Function 'enum'
2024-08-01 16:21:55.511736 0.00% [NOTICE] switch_loadable_module.c:389 Adding API Function 'enum_auto'
Assertion failed: (MAIN_XML_ROOT != NULL), function switch_xml_open_cfg, file switch_xml.c, line 2505.
zsh: abort      ./freeswitch


```

**Comment by suiyuemanbu** [comment]
what is   libfreeswitch.1.dylib, Never needed this file.

**Comment by a-rose** [comment]
I think this says your config for mod_xml_curl was not found:

`Assertion failed: (MAIN_XML_ROOT != NULL), function switch_xml_open_cfg, file switch_xml.c, line 2505.`

You need a section in your config that contains the config to be loaded by the module:
`<configuration name="xml_curl.conf" description="cURL XML Gateway"> ... </configuration>`

Have a look at https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Modules/mod_xml_curl_1049001/, there is an example config

**Comment by seven1240** [comment]
why download and copy? you should build everything, mixing binary release and mod built only from source you might get dependency issues.
