### ISSUE TITLE
Build FreeSWITCH w/ mod_v8 on Debian 12 Bookworm (arm64) not possible

### ISSUE THREAD

**Issue by hheedfeld** [signalwire/freeswitch#2621]
Trying to build FreeSWITCH 1.10.12 w/ mod_v8 on Debian Bookworm (arm64).

Bookworm on arm64 seems to have lib8-dev replaced by libnode-dev.

apt install libv8-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libnode-dev' instead of 'libv8-dev'
The following NEW packages will be installed:
  libnode-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 503 kB of archives.
After this operation, 3321 kB of additional disk space will be used.
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [38 B]
Get:2 https://cdn-aws.deb.debian.org/debian bookworm/main arm64 libnode-dev arm64 18.19.0+dfsg-6~deb12u2 [503 kB]
Fetched 503 kB in 0s (4519 kB/s)     
Selecting previously unselected package libnode-dev.
(Reading database ... 99188 files and directories currently installed.)
Preparing to unpack .../libnode-dev_18.19.0+dfsg-6~deb12u2_arm64.deb ...
Unpacking libnode-dev (18.19.0+dfsg-6~deb12u2) ...
Setting up libnode-dev (18.19.0+dfsg-6~deb12u2) ...

configure throws this error:

`checking for v8-6.1_static >= 6.1.298... checking for v8fs_static >= 6.1.298... checking for v8 >= 6.1.298... configure: error: You need to either install libv8-6.1-dev (>= 6.1.298), libv8fs-dev (>= 6.1.298) or disable mod_v8 in modules.conf`

So what can I do to fulfill this v8 depency on Bookworm (arm64)?

**Comment by andywolk** [comment]
mod_v8 on arm is not supported.
