### ISSUE TITLE
att_xfer not working if i enable mod_xml_curl 

### ISSUE THREAD

**Issue by kkbhanu88** [signalwire/freeswitch#285]
I am using ESL for att_xfer by send msg 
my senario as follows.
A calls to DID and connected to B, B transfer call to C then am using sendmsg on B channel uuid after i can see call originating and disconnecting after 10 seconds with destination_out_of_order , all these extension are registered by mod_xml_curl 
EXECUTE [depth=0] sofia/internal/11290@192.168.72.30:5060 att_xfer({origination_uuid=63b2838b-dc00-469b-b752-a4bc23a48f37,origination_caller_id_number=9191,ignore_early_media=true,attxfer=true}user/12346)

here i am facing following issues;
call is being originated & call was not answered ,i received 180 Ringing and  CHANNEL_BRIDGE event received.

FS sending cancel after 10 seconds.

att_xfer is working fine if i configured through dial plan , if  i enable mod_xml_curl the above problem is occuring.
is this a bug?

for details am please check screen-shot .
![image](https://user-images.githubusercontent.com/44552693/73535698-3115c380-444a-11ea-9d97-dbdd67bc5f36.png)

**Comment by briankwest** [comment]
You're not returning the proper XML in the responses to the curl requests that FreeSWITCH is issuing.  What do the debug logs show is taking place?

**Comment by briankwest** [comment]
not a bug, its a config issue.
