### ISSUE TITLE
Missing UPDATE packet based on UA

### ISSUE THREAD

**Issue by extremerotary** [signalwire/freeswitch#307]
Currently I am running version 1.6.20.
In this version, when transferring calls, certain devices do not receive an UPDATE packet to properly display the caller's CID. In these situations, the Allow header includes UPDATE, but no update is sent from FreeSWITCH. Looking through the code for mod_sofia.c, I see there are some UAs defined between lines 1797 and 1944.

Example devices include Digium and Grandstream GRP.
I did notice in FreeSWITCH v1.8 that the UA was updated from "Grandstream GXP" to just "Grandstream", so i suspect the GRP models will receive UPDATEs on v1.8.

My question is - why are UAs used to determine whether to send UPDATE packets instead of using the Allow header? I would expect that if the device sends UPDATE in the Allow header, then always send the update. If UPDATE is not present in the Allow header, then check UAs known to support it, and make a determination from there.

**Comment by mjerris** [comment]
1.6 is long since eol.  please retry this on latest release and reopen if there is still an issue in the latest 1.10.x release
