### ISSUE TITLE
SDP address

### ISSUE THREAD

**Issue by telegant** [signalwire/freeswitch#317]
When I use lan ip(Opensips Dispatcher Address) invite to FreeSwitch,  reply 183/200 SDP address is a lan ip, cannot establish RPT connection. 
Freeswitch profile ext-sip-ip/ext-rtp-ip is a wan ip

thanks.

**Comment by briankwest** [comment]
Please join the mailing list for assistance.

**Comment by TBG-FR** [comment]
Same issue here, did you manage to solve your issue ? Do you remember how ?

**Comment by telegant** [comment]
@TBG-FR  in opensips check early media 180/183/200, if has SDP, use sdp_mangle_ip() replease lan ip to wan ip
