### ISSUE TITLE
Verto conference not working in Safari 12.0 above

### ISSUE THREAD

**Issue by vishalmpai** [signalwire/freeswitch#320]
Hello everyone

We are trying to use the Verto conference on Safari 13.0 above using IPAD it get stuck on connecting... part before entering in conference. Some time it enters the conference and leave the conference within 1 second.

on console we are getting this error
InvalidAccessError: Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

Our FreeSWITCH Version 1.6.20~64bit.

Any help would be highly appreciated.

**Comment by briankwest** [comment]
Update the the latest, we haven't supported 1.6.x in over two years.

**Comment by vishalmpai** [comment]
Thank you @briankwest. Will do that and let you know.
