### ISSUE TITLE
mod_opus does not compile on the 1.6 branch.

### ISSUE THREAD

**Issue by kareemhamdy** [signalwire/freeswitch#321]
When building from source on CentOS 7, mod_opus does not compile.

Opus has been installed:

 - wget https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
 - tar zxvf  opus-1.3.1.tar.gz
 - cd opus-1.3.1
 - ./configure && make && make install

I tried in the freeswitch configure script to use the CFLAGS, and no success, it's unable to process the source files.

In the mod_opus Makefile, I commented out the error section, and it built mod_opus without issue.

--

making all mod_opus
make[4]: Entering directory `/opt/install/freeswitch/src/mod/codecs/mod_opus'
Makefile:892: *** You must install libopus-dev to build mod_opus.  Stop.
make[4]: Leaving directory `/opt/install/freeswitch/src/mod/codecs/mod_opus'
make[3]: *** [mod_opus-all] Error 1
make[3]: Leaving directory `/opt/install/freeswitch/src/mod'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/install/freeswitch/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/install/freeswitch'
make: *** [all] Error 2

**Comment by dragos-oancea** [comment]
if you insist on building Opus from sources you should make sure pkg-config finds the .pc file .

**Comment by briankwest** [comment]
Add the path to opus.pc into PKG_CONFIG_PATH
