### ISSUE TITLE
Issue when destination number has extended unicode characters

### ISSUE THREAD

**Issue by geo-matheou** [signalwire/freeswitch#324]
Hello, 

I have an issue with switch_core_sqldb.c when I make a call to a destination number that includes extended unicode characters (e.g., 1000%f1). I get the following log in fs_cli:

2020-02-11 14:14:54.407805 [ERR] switch_core_sqldb.c:1347 ERR: [SELECT * FROM v_extensions WHERE domain_uuid = '882e97d3-f30d-44ef-acb7-1a026fd652d4' and (extension = '1001󥟯r number_alias = '1001󥧠and enabled = 'true' ]
[ERROR:  invalid byte sequence for encoding "UTF8": 0xf1 0x27 0x20 0x6f
]

How can I solve this issue taking into account that a sip client can make a call to a destination number with any format.

**Comment by andywolk** [comment]
Please show your database creation script

**Comment by andywolk** [comment]
If your database name is freeswitch then show the output of:
```
SHOW CREATE DATABASE `freeswitch`;
```
And for the table:
```
SHOW CREATE TABLE `freeswitch`.`v_extensions`;
```

**Comment by geo-matheou** [comment]
It seems that the above commands are not supported by psql. I am using freeswitch as a part of FusionPBX. Below you can find the script:

#set client encoding
sudo -u postgres psql -p $database_port -c "SET client_encoding = 'UTF8';";

#add the database users and databases
sudo -u postgres psql -p $database_port -c "CREATE DATABASE fusionpbx;";
sudo -u postgres psql -p $database_port -c "CREATE DATABASE freeswitch;";

#add the users and grant permissions
sudo -u postgres psql -p $database_port -c "CREATE ROLE fusionpbx WITH SUPERUSER LOGIN PASSWORD '$database_password';"
sudo -u postgres psql -p $database_port -c "CREATE ROLE freeswitch WITH SUPERUSER LOGIN PASSWORD '$database_password';"
sudo -u postgres psql -p $database_port -c "GRANT ALL PRIVILEGES ON DATABASE fusionpbx to fusionpbx;"
sudo -u postgres psql -p $database_port -c "GRANT ALL PRIVILEGES ON DATABASE freeswitch to fusionpbx;"
sudo -u postgres psql -p $database_port -c "GRANT ALL PRIVILEGES ON DATABASE freeswitch to freeswitch;"

**Comment by andywolk** [comment]
yeah, those were for mysql, never mind then

**Comment by geo-matheou** [comment]
Also, attached you can find the information for v_extensions

![v_extensions](https://user-images.githubusercontent.com/34241098/74247791-4fec4380-4cef-11ea-8a34-45a7eea3e980.PNG)

**Comment by andywolk** [comment]
Please figure out what collation is set to the database and to the table first.

**Comment by geo-matheou** [comment]
en_US.UTF-8 is set for the entire db.

**Comment by geo-matheou** [comment]
However, is there any configuation in FreeSWITCH that can trim invalid utf8 characters?

**Comment by geo-matheou** [comment]
Also, @andywolk, it would be nice if FS trims invalid characters at the beginning of a call (e.g., < 32 & >= 127, in ascii code, from the destination number and sip variables). This is beacuse control and extended characters cause a lot of issues in database drivers.  In our case we have issues when we manage CDRs in both postgresql and mongo. Maybe I am wrong, but what do you think? :)

**Comment by mjerris** [comment]
v_extensions is not a freeswitch table.  Maybe this is part of fusion?  you should talk to them about how they are accessing and encoding those fields.

**Comment by geo-matheou** [comment]
Thank you @mjerris. I will investigate further this issue.
