### ISSUE TITLE
RTCP UNPROTECT ERR version 1.10.2

### ISSUE THREAD

**Issue by huongbn** [signalwire/freeswitch#335]
Hi guys, I'm just upgrade to version 1.10.2 latest. But when calling, I have audio delay between 2-5s, I check log with this issue
900b4870-1db9-4742-83a2-89c5bd8e709e 2020-02-12 09:54:28.414531 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
900b4870-1db9-4742-83a2-89c5bd8e709e 2020-02-12 09:54:28.414531 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 0 VER 2 LEN 188
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:30.334531 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:30.334531 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 0 VER 2 LEN 192
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:34.274533 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:34.274533 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 87 VER 1 LEN 207116
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:48.074532 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:48.074532 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 251 VER 1 LEN 80888
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:51.134533 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:51.134533 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 130 VER 3 LEN 138080
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:53.034541 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR
c331cdad-9981-4038-9295-bda8fb418a7e 2020-02-12 09:54:53.034541 [WARNING] switch_rtp.c:6952 INVALID RTCP PACKET TYPE 0 VER 2 LEN 228

**Comment by briankwest** [comment]
Please provide a full debug log with sip trace from start to finish, along with the full version string and OS info.

**Comment by blerest** [comment]
@huongbn I have same error "RTCP UNPROTECT ERR" every 5 seconds using WebRTC client. How did you solve issue?

**Comment by dragos-oancea** [comment]
It's possible your client has an issue with SRTP.
