### ISSUE TITLE
Lua 5.3 not support in 1.10

### ISSUE THREAD

**Issue by umanda** [signalwire/freeswitch#336]
Hey Guys,
I am setting up FreeSwitch 10 and I want to use Lua 5.3. But it seems like FreeSwitch 10 build for Lua 5.2. Is there any chance or method to configure FS10 with Lua 5.3
I tried to custom build on FreeSwitch, but it is not working for me.

**Comment by briankwest** [comment]
You add  lua5.3 lua-5.3 to configure.ac where it checks for LUA version.  Please test and perform a PR against the issue once you're done.

Thanks

**Comment by umanda** [comment]
I fixed it What I did was added the following configuration. In this approach, you no need to build or change release configure.ac.

```
<!-- File : /etc/freeswitch/autoload_configs/lua.conf.xml  -->

<configuration name="lua.conf" description="LUA Configuration">
<settings>
	<!-- Injecting Lua 5.3 This location might be differ -->
	<param name="script-directory" value="/usr/local/share/lua/5.3/?.lua"/>
	<param name="script-directory" value="/usr/local/share/lua/5.3/?/init.lua"/>
	<param name="script-directory" value="/usr/local/lib/lua/5.3/?.lua"/>
	<param name="script-directory" value="/usr/local/lib/lua/5.3/?/init.lua"/>
	<param name="script-directory" value="./?.lua"/>
	<!-- My Custom directories -->
	<param name="script-directory" value="/usr/share/freeswitch/scripts/sofia-lua/libs/common/?.lua"/>
</settings>
</configuration>
```
