### ISSUE TITLE
mod_mariadb fails with latest libmariadb3 on Debian 10

### ISSUE THREAD

**Issue by fsmeets** [signalwire/freeswitch#376]
Something changed in the symbols of libmariadb3 version 1:10.3.22-0+deb10u1. Trying to start Freeswitch 1.10.2 gives the following error message

2020-02-16 09:02:35.551266 [CRIT] switch_loadable_module.c:1786 Error Loading module /usr/lib/freeswitch/mod/mod_mariadb.so
**/usr/lib/freeswitch/mod/mod_mariadb.so: symbol mysql_get_timeout_value version libmysqlclient_18 not defined in file libmariadb.so.3 with link time reference**

Reverting to libmariadb3 version 1:10.3.18-0+deb10u1 makes everything work again. 

There is also a Debian bug about this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951210

**Comment by andywolk** [comment]
FreeSWITCH Release packages have been rebuilt. Please update your installation.
Put a comment if there is an issue still.

**Comment by bshirazi** [comment]
Hi @andywolk 
I have similar problem used FreeSWITCH Release packages and mariadb 10.4 
I see this error:
2020-06-21 09:39:22.887575 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/lib/freeswitch/mod/mod_mariadb.so
**/usr/lib/freeswitch/mod/mod_mariadb.so: symbol mysql_get_timeout_value, version libmysqlclient_18 not defined in file libmariadb.so.3 with link time reference** 

Regards
Shirazi

**Comment by summer789** [comment]
@andywolk

**Comment by summer789** [comment]
@andywolk   I'm having this issue with debian9 and Mariadb 15.1 and FreeSWITCH version: 1.10.11

**Comment by summer789** [comment]
@bshirazi   Did you solve this problem?

**Comment by andywolk** [comment]
Debian 9 is end of life and not supported anymore.

**Comment by summer789** [comment]
> Debian 9 is end of life and not supported anymore.

👌🏻
