### ISSUE TITLE
mod_hiredis issue with tls 

### ISSUE THREAD

**Issue by murugancmi** [signalwire/freeswitch#403]
When i use tls connection for  mod_hiredis  getting following error 

2020-02-21 10:07:30.748720 [ERR] hiredis_profile.c:233 hiredis: unable to connect
2020-02-21 10:07:30.748720 [ERR] mod_hiredis.c:169 hiredis: profile[default] error executing [get test] reason:[

**Comment by andywolk** [comment]
Please provide more information

**Comment by murugancmi** [comment]
I have plan to use mod_hiredis for limit ,So i enable mod_hiredis module and add my redis server details  in hiredis.com like bellow

**<configuration name="hiredis.conf" description="mod_hiredis">
  <profiles>
    <profile name="default">
      <connections>
        <connection name="primary"><param name="hostname" value="ind-redis-d.digitalocean.com"/>
          <param name="password" value=""/>
          <param name="port" value="25061"/>
          <param name="timeout_ms" value="500"/>
        </connection>
      </connections>
      <params>
        <param name="ignore-connect-fail" value="true"/>
      </params>
    </profile>
  </profiles>
</configuration>**

But when we load mod_hiredis i am getting following error 

**2020-02-21 11:37:50.528717 [ERR] hiredis_profile.c:233 hiredis: unable to connect**

My redis server running in secure connection  tls

**Comment by andywolk** [comment]
```
2020-02-21 10:07:30.748720 [ERR] mod_hiredis.c:169 hiredis: profile[default] error executing [get test] reason:[
```
What's the `reason` in the log?

**Comment by crienzo** [comment]
I’m pretty sure tls is not supported.  Look into stunnel as a workaround.

**Comment by murugancmi** [comment]
> ```
> 2020-02-21 10:07:30.748720 [ERR] mod_hiredis.c:169 hiredis: profile[default] error executing [get test] reason:[
> ```
> 
> What's the `reason` in the log?

I get this output from freeswitch console. @crienzo  said TLS not supported is there any other way to connect

**Comment by murugancmi** [comment]
> ```
> 2020-02-21 10:07:30.748720 [ERR] mod_hiredis.c:169 hiredis: profile[default] error executing [get test] reason:[
> ```
> 
> What's the `reason` in the log?

in console i can see reason [] , Look like mod_hiredis not support TLS redis connection my understanding is correct or i am missing any configuration if i use with out TLS connection its working fine.

**Comment by murugancmi** [comment]
Hello team update to support TLS support for redis

**Comment by crienzo** [comment]
stunnel is an ok workaround.

**Comment by murugancmi** [comment]
Any update about this workaround
