### ISSUE TITLE
Problem with download & install

### ISSUE THREAD

**Issue by markggallagher** [signalwire/freeswitch#409]
I apologize if this is answered elsewhere; I did look but could not find anything similar. 

I feel sure I'm missing something basic. I'm trying to download and install freeswitch on Debian 10 using the instructions found here: https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster

I am getting this error:

Ign:1 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster InRelease
Err:2 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

What am I missing here? Full output below.

root@debian-1:/home/pbxuser1# apt-get update && apt-get install -y gnupg2 wget lsb-release
Ign:1 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster InRelease
Err:2 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Hit:5 http://security.debian.org/debian-security buster/updates InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@debian-1:/home/pbxuser1# wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -
--2020-02-23 22:31:22--  https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc
Resolving files.freeswitch.org (files.freeswitch.org)... 190.102.98.174, 2803:d000:fffe::174
Connecting to files.freeswitch.org (files.freeswitch.org)|190.102.98.174|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3155 (3.1K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   3.08K  --.-KB/s    in 0s      

2020-02-23 22:31:22 (26.4 MB/s) - written to stdout [3155/3155]

OK
root@debian-1:/home/pbxuser1#  
root@debian-1:/home/pbxuser1# echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list
root@debian-1:/home/pbxuser1# echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list
root@debian-1:/home/pbxuser1#  
root@debian-1:/home/pbxuser1# # you may want to populate /etc/freeswitch at this point.
root@debian-1:/home/pbxuser1# # if /etc/freeswitch does not exist, the standard vanilla configuration is deployed
root@debian-1:/home/pbxuser1# apt-get update && apt-get install -y freeswitch-meta-all
Ign:1 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster InRelease
Err:2 cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease                   
Get:5 http://files.freeswitch.org/repo/deb/debian-release buster InRelease [3,933 B]
Hit:6 http://security.debian.org/debian-security buster/updates InRelease     
Get:7 http://files.freeswitch.org/repo/deb/debian-release buster/main Sources [4,288 B]
Get:8 http://files.freeswitch.org/repo/deb/debian-release buster/main amd64 Packages [57.4 kB]
Reading package lists... Done       
E: The repository 'cdrom://[Debian GNU/Linux 10.3.0 _Buster_ - Official amd64 DVD Binary-1 20200208-12:08] buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@debian-1:/home/pbxuser1# fs_cli -rRS
bash: fs_cli: command not found

**Comment by andywolk** [comment]
This is not related to FreeSWITCH. APT is broken. You need to fix your apt. See what errors it gives. Missing cd in the drive.
