### ISSUE TITLE
"norecord" command invalid

### ISSUE THREAD

**Issue by tangshiixang** [signalwire/freeswitch#41]
version: freeswitch 1.8
When I send the following Verto signaling on the web side:
[{
        "jsonrpc":      "2.0",
        "method":       "verto.broadcast",
        "params":       {
                "eventChannel": "conference-mod.3595@my.domain",
                "data": {
                        "application":  "conf-control",
                        "command":      "norecord",
                        "id":   null,
                        "value":        "all"
                },
                "sessid":       "ea51f1bc-1ea3-4201-2eaf-ce17e008d25a"
        },
        "id":   17
}]

freeswitch send the following  responses:

{
        "data": {
                "action":       "response",
                "error":        "Invalid Command"
        },
        "eventChannel": "conference-mod.3595@my.domain"
}

[{
        "jsonrpc":      "2.0",
        "id":   11252,
        "method":       "verto.event",
        "params":       {
                "data": {
                        "action":       "response",
                        "error":        "Invalid Command"
                },
                "eventChannel": "conference-mod.3595@my.domain",
                "eventSerno":   7
        }
}]

But when I use the following command at fs_cli:
conference 3595 norecord  all

it's ok!

**Comment by cdosoftei** [comment]
Configure the broadcast payload as:

```json
data: {
  "application": "conf-control",
  "command": "recording",
  "id": "all",
  "value": "stop"
}
```

The [event handler](https://github.com/signalwire/freeswitch/blob/15ad4c23e259c1c2dff58f89e9124e5f36dd2e94/src/mod/applications/mod_conference/conference_event.c#L145) does not currently support the `norecord` command but it does support the `recording` counterpart.

**Comment by tangshiixang** [comment]
@cdosoftei Thank you! But are 'norecord all' and 'recording stop all' the same? I want to remove the recorded file instead of stopping the recording.

**Comment by cdosoftei** [comment]
Indeed, `recording stop all` will not remove the recording file, however it could be used to achieve the desired behaviour if combined with an additional file deletion operation.

**Comment by seven1240** [comment]
you can make a pr to stop the record. however, deleting the file is beyond the control of such a command.
