### ISSUE TITLE
Clang no longer supports passing flags via --extra-cflags=,  causing immediate make failure

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#42]
Make fails with: '-fvisibility=hidden' not supported - issued from libvpx
FreeSWITCH Master and  1.10.1 Current Public Release
Catalina 10.15.0 with Command Line Tools 11.0
This was not an issue since OS X 10.6 until now, probably from an updated clang.

Command Line Tools **does support** -fvisibility=hidden, I tested it on the command line. However, FreeSwitch uses --extra-cflags='-fvisibility=hidden', and apparently, it's the passing via extra-cflags that's the problem.

Clang and gcc commands both support -fvisibility=hidden, but they do not support --extra-cflags="-fvisibility=hidden". So it's the --extra-cflags that's the problem.

At first I thought it may be related to https://freeswitch.org/jira/browse/FS-11968?filter=-2 , but I tested using a temp fix and it is not related.

I opened a problem with Apple Dev but it looks like the change is valid. I tried changing a few things in configure.ac, etc. to see if there is compiler recognition problem but nothing so far. I don't know enough on how to change configure stuff to get fvisability added via flags instead of extra-cflags, which is only used in libvpx.

Files attached.
[05 FreeSWITCH configure.txt](https://github.com/signalwire/freeswitch/files/3704147/05.FreeSWITCH.configure.txt)
[06 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/3704151/06.FreeSWITCH.make.txt)

**Comment by MarioG-X** [comment]
It is not related to FS-11968. I added temp fix and did configure and make and same error.

**Comment by MarioG-X** [comment]
Will open a problem with Apple Dev after verifying this feature is actually missing. I will also try changing a few things in configure.ac, etc. to see if there is compiler recognition problem. Will post when I have more info.

**Comment by MarioG-X** [comment]
If anyone can help... Turns out clang and gcc commands both support -fvisibility=hidden, but they do not support --extra-cflags="-fvisibility=hidden". So it's the --extra-cflags that's the problem.

**Comment by mjerris** [comment]
can you give me some more info on steps to reproduce for this myself?

**Comment by MarioG-X** [comment]
To reproduce you must be on macOS Catalina 10.15 and install FS using macFI or manually:
1. Install FS prerequisites from homebrew
2. Download master or GA
3. bootstrap if master
4. ./configure
5. make. <- fails in first 25 lines

I modified **1 files** (attached) and got past the error although probably not a permanent solution:
freeswitch/make.in to move $(VISIBILITY_FLAG) to cflags.
libs/libvpx/Makefile: libs/libvpx/.update
	cd libs/libvpx && CC="$(CC)" CXX="$(CXX)" CFLAGS="$(CFLAGS) $(VISIBILITY_FLAG)" CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" ./configure --enable-pic --disable-docs --disable-examples --disable-install-bins --disable-install-srcs --disable-unit-tests --size-limit=16384x16384
[Makefile.in.txt](https://github.com/signalwire/freeswitch/files/3722116/Makefile.in.txt)

I modified **3 files
** (attached) to make sure Catalina 10.15 was detected:
libs/libvpx/configure to handle Catalina SSE
libs/libvpx/build/make/configure.sh to handle Catalina SSE
libs/libvpx/build/make/configure.sh to handle Catalina SSE

[configure.txt](https://github.com/signalwire/freeswitch/files/3722124/configure.txt)
[configure.sh.txt](https://github.com/signalwire/freeswitch/files/3722122/configure.sh.txt)
[iosbuild.sh.txt](https://github.com/signalwire/freeswitch/files/3722120/iosbuild.sh.txt)

And after all that, make now fails on what looks like an obsoleted compiler warning option. I found many instances on the web where '-Wno-extended-offsetof' is no longer valid and must be changed to '-Wno-invalid-offsetof'? [-Wunknown-warning-option] See attached make. If you want a separate problem opened then let me know

[make 1.txt](https://github.com/signalwire/freeswitch/files/3722127/make.1.txt)

**Comment by mjerris** [comment]
can you check out this PR please

**Comment by MarioG-X** [comment]
Good!

**Comment by MarioG-X** [comment]
I have been trying to figure out how to make pull changes, no luck so far. So extra mullah if you squeeze in my additions to three 3 Libvpx files above to go to darwin25 so Libvpx compiles with correct sse code.

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/70
