### ISSUE TITLE
MSRP: call partially  disconnected after uuid_capture_text

### ISSUE THREAD

**Issue by sergey-safarov** [signalwire/freeswitch#456]
Call partially  disconnected after uuid_capture_text
To reproduce issue need add into dialplan
```xml
    <extension name="park">
      <condition>
        <action application="answer"/>
        <action application="park"/>
      </condition>
    </extension>
```
Make call with SIP client with MSRP (message) media. I use [Blink](http://icanblink.com/)

Then inside `fs_cli` need execute `uuid_capture_text`.

Then cancel call and execute command show calls.
Canceled call still exist in output.

Tested current master 2d727b7b31b507707fb5982785a8d8bb77b1e67f

Test log attached
[msrp_test.log](https://github.com/signalwire/freeswitch/files/4261941/msrp_test.log)

**Comment by seven1240** [comment]
maybe somewhere need to check switch_channel_ready() and exit, patch is welcome.

**Comment by andywolk** [comment]
https://github.com/signalwire/freeswitch/pull/2038
