### ISSUE TITLE
Mac 1.10 install error

### ISSUE THREAD

**Issue by YichiHuang** [signalwire/freeswitch#489]
avformat.c:1145:24: error: implicit declaration of function 'av_rescale_q' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                handle->duration = av_rescale_q(context-...
                                                   ^
avformat.c:2472:9: error: implicit declaration of function 'av_rescale_q' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
                pts = av_rescale_q(*((uint64_t *)img->user_priv), st->ti...
                      ^
2 errors generated.

**Comment by seven1240** [comment]
please try the latest master looks like it's already fixed.

**Comment by hthetiot** [comment]
I confirm the issue is fixed, here is my build process on mac, including deps install, in case its usefull for any one.
- https://gist.github.com/hthetiot/cbe6e1df571e1e4f76b04f7502434ce9

**Comment by seven1240** [comment]
seems it's fixed. and 1.10.7 is out, please open a new issue if still have problem.
