### ISSUE TITLE
Please add Other-Leg-Gateway-Name variable

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [signalwire/freeswitch#49]
Please add Other-Leg-Gateway-Name variable it is needed to fill in radius attribute h323-gw-id  on answer leg(A-Leg) and h323-remote-id on originate leg. (B-leg). 
Currently It is possible to get other-leg ip address but absolutely not possible to get other leg gateway name.

**Comment by crienzo** [comment]
Hello.  You may submit a pull request with this change and we can review it.

**Comment by jpVm5jYYRE1VIKL** [comment]
i am not developer
