### ISSUE TITLE
cacheable needed for dialplan with xml_curl

### ISSUE THREAD

**Issue by AD35583** [signalwire/freeswitch#492]
use xml_curl can control FS outside easily. 
for directory can use  cacheable to avoid frequently calling from FS.  when you dialing again and again,  only one request arrived in website. 

BUT for dialplan,  there is no optimized logic. I tried to add cacheable in context node and extension node.  every calling would request to website. 

wishing  add cacheable to dialplan and clean cache by xml_flush_cache command manually .  it can reduce lots of requests bewteen FS and website. 


**Comment by mjerris** [comment]
Its not practical because the input params would rarely be the same.  it is by design that this does not exist.

**Comment by AD35583** [comment]
> Its not practical because the input params would rarely be the same. it is by design that this does not exist.

when thousands of  invites coming,  the  http will  take long time ..... 
for high perf,   I cache every context node xml in website only and quickly response the result for the matched context  params.  but it also waste time for http req & res. 
so I propose the issue.

**Comment by ashbrener** [comment]
There is definitely a use case for an infrequently changing remote dynamic dialplan, that if anything may only depend on non-call session variables such as Core-UUID.
