### ISSUE TITLE
brew 1.10.2 upgrade failure

### ISSUE THREAD

**Issue by chenrui333** [signalwire/freeswitch#493]
relates to https://github.com/Homebrew/homebrew-core/pull/51435

```
01:56:44 Making all in tests/unit
01:56:44   CC       switch_event.o
01:56:44   CC       switch_hash.o
01:56:44   CC       switch_ivr_originate.o
01:56:44   CC       switch_utils.o
01:56:44   CC       switch_core.o
01:56:44   CC       switch_console.o
01:56:44   CC       switch_vpx.o
01:56:44   CC       switch_core_file.o
01:56:44   CC       switch_ivr_play_say.o
01:56:44   CC       switch_core_codec.o
01:56:44   CC       switch_rtp.o
01:56:44   CC       switch_xml.o
01:56:44 switch_rtp.c:18:1: error: unknown type name 'uint'; did you mean 'int'?
01:56:44 uint datalen;
01:56:44 ^~~~
01:56:44 int
01:56:44 1 error generated.
01:56:44 make[2]: *** [switch_rtp.o] Error 1
01:56:44 make[2]: *** Waiting for unfinished jobs....
01:56:44 make[1]: *** [all-recursive] Error 1
01:56:44 make: *** [all] Error 2
01:56:44 
```

full jenkins build log, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/58857/version=catalina/console

**Comment by seven1240** [comment]
sounds like it's already fixed in the latest master.

**Comment by mjerris** [comment]
switch_rtp.c line 18 is in the middle of the license header comment.  This does not appear to be code as exists in freeswitch.

**Comment by chenrui333** [comment]
> sounds like it's already fixed in the latest master.

Sounds like I just need to wait for the next release?

**Comment by mjerris** [comment]
it was in the unit test, here is where its fixed:

commit 4bef44b7b0aca79c27b6b208b5e0011e048a30c1
Author: Dragos Oancea <dragos@signalwire.com>
Date:   Mon Jan 13 18:23:13 2020 +0000

    [unit-tests] fix build switch_rtp on MacOS

**Comment by mjerris** [comment]
As he said the fix is alreay in tree now.

**Comment by chenrui333** [comment]
Great, thanks for clarifying it.

Also I just tested with the HEAD, it works well for me.
