### ISSUE TITLE
make mod_unimrcp ERROR of Freeswitch 1.10.2 public release on Mac 10.14

### ISSUE THREAD

**Issue by YichiHuang** [signalwire/freeswitch#496]
Hi,
I compiled the mod_unimrcp and got errors as follows:
`making all mod_unimrcp
cd /usr/local/src/freeswitch/libs/unimrcp && /Library/Developer/CommandLineTools/usr/bin/make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal -I build/acmacros 
aclocal: configure.ac: 41: macro `AM_INIT_AUTOMAKE' not found in library
aclocal: configure.ac: 51: macro `AM_PROG_CC_C_O' not found in library
aclocal: configure.ac: 57: macro `AM_CONDITIONAL' not found in library
aclocal: macro `_LT_COMPILER_PIC' required but not defined
aclocal: macro `_LT_DECL_SED' required but not defined
aclocal: macro `_LT_DECL_SED' required but not defined
aclocal: macro `_LT_FUNC_STRIPNAME_CNF' required but not defined
aclocal: configure.ac: 123: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 131: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 139: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 147: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 149: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 157: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 165: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 170: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 175: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 180: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 185: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 205: macro `AM_CONDITIONAL' not found in library
aclocal: configure.ac: 207: macro `AM_CONDITIONAL' not found in library
make[4]: *** [aclocal.m4] Error 1
make[3]: *** [/usr/local/src/freeswitch/libs/unimrcp/platforms/libunimrcp-client/libunimrcpclient.la] Error 2
make[2]: *** [mod_unimrcp-all] Error 1
make[1]: *** [mod_unimrcp] Error 2
make: *** [mod_unimrcp] Error 2
`

**Comment by mjerris** [comment]
please follow published installation instructions for a supported platform.
