### ISSUE TITLE
[FreeSWITCH Crashes]

### ISSUE THREAD

**Issue by bilalabbasi55** [signalwire/freeswitch#497]
Hi Team,
I have a system running under production, and rarely i get FreeSWITCH server crash generating below error in logs(PFA).
Mar  9 08:49:18 fs01 kernel: [15753345.281515] freeswitch[17569]: segfault at 45 ip 00007f21953b1845 sp 00007f20020c3b50 error 4 in libcrypto.so.1.0.2[7f2195280000+238000]

System Details:OS: Debian 9.11
uname -a: Linux fs01.xxxxx.com 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
FreeSWITCH Version: FreeSWITCH Version 1.8.7~64bit ( 64bit)

Can some one guide me how can i sort this issue?
P.S: I know the first thing i should try here is to update to 1.10, but its production system and i really want to know that it will get solved once we update to 1.10. 

Regards
Abbasi

**Comment by briankwest** [comment]
Please attach a backtrace 

https://freeswitch.org/confluence/display/FREESWITCH/Debugging#Debugging-GettingaBacktrace

**Comment by briankwest** [comment]
Please reopen once you have the info requested.
