### ISSUE TITLE
mod_http_cache playback issue 

### ISSUE THREAD

**Issue by amitpaltech** [signalwire/freeswitch#498]
Hi all,
I am using mod_http_cache to play file from cloud. but it is not playing getting error ( invalid rate or channel count).

let me know what wrong with here.

following are the switch debug.

 18:09:48.067137 sofia.c:7301 Channel sofia/internal/1001@192.168.1.45 entering state [early][183]
EXECUTE [depth=0] sofia/internal/1001@192.168.1.45 playback(https://www.dropbox.com/s/ed04804lvcrwfxz/6777-6788-inbound-2020-03-07-13-04-28-3593ee15-8f3b-4c82-944f-1992b3826ab5.mp3)
 18:09:48.067137 mod_http_cache.c:659 Locked cache
 18:09:48.067137 [INFO] mod_http_cache.c:751 Cache MISS: size = 0 (0 MB), hit ratio = 0/1
 18:09:48.087112 mod_http_cache.c:816 Adding https://www.dropbox.com/s/ed04804lvcrwfxz/6777-6788-inbound-2020-03-07-13-04-28-3593ee15-8f3b-4c82-944f-1992b3826ab5.mp3(/usr/local/freeswitch/http_cache/ad/467fb6-5728-4c00-b210-011c1d39d2fd.mp3) to cache index 0
 18:09:48.087112 mod_http_cache.c:670 Unlocked cache
 18:09:48.087112 mod_http_cache.c:1117 opening /usr/local/freeswitch/http_cache/ad/467fb6-5728-4c00-b210-011c1d39d2fd.mp3 for URL cache
 18:09:49.507186 mod_http_cache.c:638 HTTP/1.1 200 OK
 18:09:49.507186 mod_http_cache.c:638 Server: nginx
 18:09:49.507186 mod_http_cache.c:638 Date: Wed, 11 Mar 2020 12:39:49 GMT
 18:09:49.507186 mod_http_cache.c:638 Content-Type: text/html; charset=utf-8
 18:09:49.507186 mod_http_cache.c:638 Transfer-Encoding: chunked
 18:09:49.507186 mod_http_cache.c:638 Connection: keep-alive
 18:09:49.507186 mod_http_cache.c:638 Vary: Accept-Encoding
 18:09:49.507186 mod_http_cache.c:638 Vary: Accept-Encoding
 18:09:49.507186 mod_http_cache.c:638 Cache-Control: no-cache
 18:09:49.507186 mod_http_cache.c:638 Content-Security-Policy: base-uri 'self' ; child-src https://www.dropbox.com/static/serviceworker/ blob: ; connect-src https://* ws://127.0.0.1:*/ws ; default-src https://www.dropbox.com/playlist/ https://www.dropbox.com/v/s/playlist/ https://*.dropboxusercontent.com/p/hls_master_playlist/ https://*.dropboxusercontent.com/p/hls_playlist/ ; font-src https://* data: ; form-action 'self' https://www.dropbox.com/ https://dl-web.dropbox.com/ https://photos.dropbox.com/ https://paper.dropbox.com/ https://showcase.dropbox.com/ https://www.hellofax.com/ https://app.hellofax.com/ https://www.hellosign.com/ https://app.hellosign.com/ https://help.dropbox.com/ https://navi.dropbox.jp/ https://selfguidedlearning.dropboxbusiness.com/ https://instructorledlearning.dropboxbusiness.com/ https://sales.dropboxbusiness.com/ https://dropboxconnect.co.uk/ https://accounts.google.com/ https://api.login.yahoo.com/ https://login.yahoo.com/ https://pal-test.adyen.com https://2e83413d8036243b-Dropbox-pal-live.adyenpayments.com/ ; frame-ancestors 'self' ; frame-src https://* carousel: dbapi-6: dbapi-7: dbapi-8: dropbox-client: itms-apps: itms-appss: ; img-src https://* data: blob: ; media-src https://* blob: ; object-src 'self' https://cfl.dropboxstatic.com/static/ https://www.dropboxstatic.com/static/ https://flash.dropboxstatic.com https://swf.dropboxstatic.com https://dbxlocal.dropboxstatic.com ; report-uri https://www.dropbox.com/csp_log?policy_name=metaserver-whitelist ; script-src 'unsafe-eval' https://www.dropbox.com/static/api/ https://www.dropbox.com/page_success/ https://cfl.dropboxstatic.com/static/js/ https://www.dropboxstatic.com/static/js/ https://cfl.dropboxstatic.com/static/src/dws-ensemble-appshell/ https://www.dropboxstatic.com/static/src/dws-ensemble-appshell/ https://cfl.dropboxstatic.com/static/previews/ https://www.dropboxstatic.com/static/previews/ https://cfl.dropboxstatic.com/static/api/ https://www.dropboxstatic.com/static/api/ https://cfl.dropboxstatic.com/static/cms/ https://www.dropboxstatic.com/static/cms/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ 'unsafe-inline' ; style-src https://* 'unsafe-inline' 'unsafe-eval' ; worker-src https://www.dropbox.com/static/serviceworker/ blob:
 18:09:49.507186 mod_http_cache.c:638 Content-Security-Policy-Report-Only: frame-ancestors 'self' 'self' ; report-uri https://www.dropbox.com/csp_log?policy_name=metaserver-experimental ; script-src 'unsafe-eval' 'unsafe-inline' https://*
 18:09:49.507186 mod_http_cache.c:638 Dropbox-Streaming: V=1
 18:09:49.507186 mod_http_cache.c:638 Pragma: no-cache
 18:09:49.507186 mod_http_cache.c:638 Referrer-Policy: origin-when-cross-origin
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: seen-sl-signup-modal=VHJ1ZQ%3D%3D; expires=Fri, 10 Apr 2020 12:39:49 GMT; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: locale=en; Domain=dropbox.com; expires=Mon, 10 Mar 2025 12:39:49 GMT; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: gvc=Mjk3OTEwNjc4NDc3Njk5NzE1MjEzMTUzMTE0OTE4NTE3MTkyNTU1; expires=Mon, 10 Mar 2025 12:39:49 GMT; httponly; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: flash=; Domain=dropbox.com; expires=Wed, 11 Mar 2020 12:39:49 GMT; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: puc=; expires=Wed, 11 Mar 2020 12:39:49 GMT; httponly; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: bang=; Domain=dropbox.com; expires=Wed, 11 Mar 2020 12:39:49 GMT; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: t=OoqgVFDdzljGmOvwmBmWA22i; Domain=dropbox.com; expires=Sat, 11 Mar 2023 12:39:49 GMT; httponly; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 Set-Cookie: __Host-js_csrf=OoqgVFDdzljGmOvwmBmWA22i; expires=Sat, 11 Mar 2023 12:39:49 GMT; Path=/; secure
 18:09:49.507186 mod_http_cache.c:638 X-Content-Type-Options: nosniff
 18:09:49.507186 mod_http_cache.c:638 X-Dropbox-Request-Id: 6a12150b23fd33bab4ec8ed82eb58811
 18:09:49.507186 mod_http_cache.c:638 X-Frame-Options: DENY
 18:09:49.507186 mod_http_cache.c:638 X-Robots-Tag: noindex, nofollow, noimageindex
 18:09:49.507186 mod_http_cache.c:638 X-Xss-Protection: 1; mode=block
 18:09:49.507186 mod_http_cache.c:638 Strict-Transport-Security: max-age=15552000; includeSubDomains
 18:09:49.507186 mod_http_cache.c:638
 18:09:49.927150 [WARNING] mod_http_cache.c:1165 URL https://www.dropbox.com/s/ed04804lvcrwfxz/6777-6788-inbound-2020-03-07-13-04-28-3593ee15-8f3b-4c82-944f-1992b3826ab5.mp3 downloaded in 1844 ms
 18:09:49.927150 mod_http_cache.c:659 Locked cache
 18:09:49.927150 mod_http_cache.c:670 Unlocked cache
 18:09:49.967109 [ERR] mod_shout.c:739 Error opening /usr/local/freeswitch/http_cache/ad/467fb6-5728-4c00-b210-011c1d39d2fd.mp3 (invalid rate or channel count)
 18:09:49.967109 [ERR] mod_http_cache.c:1742 Failed to open HTTP cache file: /usr/local/freeswitch/http_cache/ad/467fb6-5728-4c00-b210-011c1d39d2fd.mp3, https://www.dropbox.com/s/ed04804lvcrwfxz/6777-6788-inbound-2020-03-07-13-04-28-3593ee15-8f3b-4c82-944f-1992b3826ab5.mp3
EXECUTE [depth=0] sofia/internal/1001@192.168.1.45 hangup()
 18:09:49.967109 [NOTICE] mod_dptools.c:1380 Hangup sofia/internal/1001@192.168.1.45 [CS_EXECUTE] [NORMAL_CLEARING]

**Comment by dragos-oancea** [comment]
does it only happen with stereo files ?

**Comment by amitpaltech** [comment]
Dear dragos-oancea ,
no, with mono and stereo files have same problem.
I also test with .wav having same issue.

actually I have two requirement.
1: I want to play / record from cloud.
===> I thinks this could be  possible by mod_httapi or mod_http_cache.
2: I want to play  / record from live streaming.
==>  I want to know , how can I achieve this from freeswitch end. 

Thanks dragos for prompt reply. hope you understand my requirements

**Comment by amitpaltech** [comment]
issue is in cloud and it is resolve 
once again thanks to dragos-oancea

**Comment by ChuanjiaCai** [comment]
hi， i got the fail about mod_http_cache:
[ERR] mod_http_cache.c:1174 Received curl error 6 HTTP error code 0 trying to fetch https://guanjia.10010.com/data_voice/2020/7/6/31,620c995c648a96.mp3
[INFO] mod_http_cache.c:773 Failed to download URL https://guanjia.10010.com/data_voice/2020/7/6/31,620c995c648a96.mp3
![image](https://user-images.githubusercontent.com/17684060/88249016-b2516300-ccd5-11ea-9b23-3a4c9806665b.png)
