### ISSUE TITLE
Missing ilbc codec in buster

### ISSUE THREAD

**Issue by tinpotnick** [signalwire/freeswitch#503]
Hi,

I wanted to get away from having to compile so tried the Debian buster release - as per the latest instructions.

The ilbc codec appears to be missing (also siren and maybe others). ilbc is quite important for us - is this meant to be in the release for an apt install?

Thanks

Nick

**Comment by andywolk** [comment]
`apt-cache search ilbc`
https://files.freeswitch.org/repo/deb/debian-release/pool/main/libi/libilbc/
What does `apt-cache policy libilbc1` say?

**Comment by tinpotnick** [comment]
apt-cache search ilbc
libilbc-dev - iLBC (internet Low Bitrate Codec) development libraries
libilbc1 - iLBC (internet Low Bitrate Codec)
libilbc1-dbgsym - debug symbols for libilbc1

apt-cache policy libilbc1
libilbc1:
  Installed: (none)
  Candidate: 0.0.1~buster-1
  Version table:
     0.0.1~buster-1 500
        500 http://files.freeswitch.org/repo/deb/debian-release buster/main amd64 Packages

**Comment by tinpotnick** [comment]
I have been doing a little digging.

in debian/bootstrap.sh

There is 

avoid_mods=(

Which includes quite a lot of useful modules, including codecs/mod_ilbc

This is as far as I have go - so at some point someone decided not to include quite a few modules - could some of these be now included?

I have no experience of the debian build system - so I am learning on the fly here...

**Comment by tinpotnick** [comment]
Hi again,

I just spent a bit more time on this. I tried building deb packages as per instructions on https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster - but first I tried in a podman container - which didn't work so I have tried in a full debian buster vm. This is also having issues.
On the first run of ./debian/util.sh build-all -aamd64 -cbuster

libs/libvpx/third_party/libyuv/source/mjpeg_decoder.cc                                                                      freeswitch-1.10.3-dev+git~20200316T201743Z~ac64d8e78d/libs/libvpx/third_party/libyuv/source/mjpeg_validate.cc                                                                     freeswitch-1.10.3-dev+git~20200316T201743Z~ac64d8e78d/libs/libvpx/third_party/libyuv/source/planar_functions.cc                                                                   freeswitch-1.10.3-dev+git~20200316T201743Z~ac64d8e78d/libs/libvpx/third_party/libyuv/source/rotate.cc                                                                             freeswitch-1.10.3-dev+git~20200316T201743Z~ac64d8e78d/libs/libvpx/third_party/libyuv/source/rotate_any.cc                                                                         freeswitch-1.10.3-dev+git~20200316T201743Z~ac64d8e78d/libs/libvpx/third_party/libyuv/source/rotate_argb.cc                                                                        ./debian/util.sh: line 167: 18319 Broken pipe             git archive -v --worktree-attributes --format=tar --prefix=freeswitch-$uver/ HEAD                                            18320 Killed                  | xz -c -${zl}v > $orig                                                                                                                        ./debian/util.sh error: unclean working tree

???

**Comment by tinpotnick** [comment]
Can anyone provide exact instructions on how to build Debian modules? The instructions I have found do not seem to work.
