### ISSUE TITLE
FreeTDM compilation error Debian 10 Buster (gcc 8 related?)

### ISSUE THREAD

**Issue by avidarep** [signalwire/freeswitch#506]
When building from source and including the FreeTDM library I am getting the following warnings/errors:

In file included from src/ftdm_io.c:40:
src/ftdm_io.c: In function ‘ftdm_channel_process_media’:
./src/include/private/ftdm_core.h:135:30: error: ‘strncpy’ output may be truncated copying 79 bytes from a string of length 127 [-Werror=stringop-truncation]
 #define ftdm_set_string(x,y) strncpy(x, y, sizeof(x)-1)

**Comment by briankwest** [comment]
FreeTDM is unsupported.
