### ISSUE TITLE
Freeswitch-1.10.2 - Debian 10 install issue 

### ISSUE THREAD

**Issue by markggallagher** [signalwire/freeswitch#508]
**I get as far as compiling the makefile, but then get this error:**

root@debian-1:/usr/src/freeswitch-1.10.2.-release# make && make install
make  all-recursive
make[1]: Entering directory '/usr/src/freeswitch-1.10.2.-release'
Making all in .
make[2]: Entering directory '/usr/src/freeswitch-1.10.2.-release'
make[2]: Leaving directory '/usr/src/freeswitch-1.10.2.-release'
Making all in src
make[2]: Entering directory '/usr/src/freeswitch-1.10.2.-release/src'
Making all in mod
make[3]: Entering directory '/usr/src/freeswitch-1.10.2.-release/src/mod'

making all mod_amr
make[4]: Entering directory '/usr/src/freeswitch-1.10.2.-release/src/mod/codecs/mod_amr'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/usr/src/freeswitch-1.10.2.-release/src/mod/codecs/mod_amr'

making all mod_av
make[4]: Entering directory 

'/usr/src/freeswitch-1.10.2.-release/src/mod/applications/mod_av'

Makefile:1396: *** You must install libavformat-dev to build mod_av.  Stop.
make[4]: Leaving directory '/usr/src/freeswitch-1.10.2.-release/src/mod/applications/mod_av'
make[3]: *** [Makefile:701: mod_av-all] Error 1
make[3]: Leaving directory '/usr/src/freeswitch-1.10.2.-release/src/mod'
make[2]: *** [Makefile:607: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/freeswitch-1.10.2.-release/src'
make[1]: *** [Makefile:3575: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/freeswitch-1.10.2.-release'
make: *** [Makefile:1290: all] Error 2

**I have installed and re-installed libavformat-dev several times:**

root@debian-1:~# sudo apt-get install libavformat-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavformat-dev is already the newest version (7:4.1.4-1~deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Any suggestions are appreciated!**

**Comment by markggallagher** [comment]
This issue solved. Ran "make clean" and then fresh "make". Solved libavformat-dev error, but finding others. Running "make clean" each time installing new library.

**Comment by iamtalhaasghar** [comment]
> This issue solved. Ran "make clean" and then fresh "make". Solved libavformat-dev error, but finding others. Running "make clean" each time installing new library.

Thanks @markggallagher
