### ISSUE TITLE
Run 2 applications on api_on_answer

### ISSUE THREAD

**Issue by Sp0rN** [signalwire/freeswitch#513]
Hi Guys,

Quick question, im trying to run 2 api commands on api_on_answer,specifically:

sched_api +(length of a dynamically generated tts file) none uuid_break ${uuid} all
Then
uuid_broadcast ${uuid} playback::tone_stream... aleg.

Essentially because im playing a tonestream, I cannot specify how long to play the tone, only how many times it loops, so the idea here is to schedule the uuid_break to happen after the length of the tts file so to cut the tone and carry on with the dial plan, but how do i do both of these commands on api_on_answer.

Any suggestions would be greatly appreciated.

**Comment by briankwest** [comment]
Just delimit them with ;; between them and it will run them all.

**Comment by Sp0rN** [comment]
Thanks Brian, However this isnt performing the expected behavior, the dialplan ends up looking like this:

<action application="export" data="nolocal:api_on_answer=sched_api +5 none uuid_break ${uuid} all ;;uuid_broadcast ${uuid} tone_stream://%(400,200,400,33);%(400,2000,400,33);loops=3 aleg"/>

But its not performing the expected behaviour, i.e schedule uuid break in 5 seconds, then play the broadcast to the aleg. Is the syntax correct?
