### ISSUE TITLE
WebRTC websocket crash

### ISSUE THREAD

**Issue by huongbn** [signalwire/freeswitch#515]
Hi, I'm running WebRTC with 1100 extension, and extenssion register to freeswitch websocket port 7443. But I have socket overloaded and extension register to socket fail and it is crashed.
![image](https://user-images.githubusercontent.com/33228286/76920542-50838580-68fe-11ea-86a6-c597a96c978b.png)
When socket crash, receive queue up to 65 and extension not register to socket. Can you help me with this issue
Thank you so much!

**Comment by crienzo** [comment]
If this is still happening, please open a new issue.  Follow the issue template instructions for providing full backtrace with debug symbols.
