### ISSUE TITLE
WebRTC: No DTLSv1.2 on Windows

### ISSUE THREAD

**Issue by waht** [signalwire/freeswitch#517]
Hi,

I am using FreeSWITCH 1.10.2 x64 on Windows. I get the following warning in Chrome DevTools when my client web application using SIP.js connects to FreeSWITCH:

> "[Deprecation] Your partner is negotiating an obsolete (D)TLS version. Support for this will be removed in M81, around March 2020. Please check with your partner to have this fixed."
([Corresponding Chrome Issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=10261))

I confirmed that the same application does not work with Firefox Developer Edition which already has [disabled TLS1.x variants](https://blog.mozilla.org/webrtc/removing-old-versions-of-dtls/).

In the FreeSWITCH logs I can see the following message when I try to connect with Firefox

> "[ERR] switch_rtp.c:3266 audio Handshake failure 1. This may happen when you use legacy DTLS v1.0 (legacyDTLS channel var is set) but endpoint requires DTLS v1.2."

I do not have `legacyDTLS` configured, and based on the [commit where the flag was added](https://github.com/signalwire/freeswitch/commit/9682d2c2c97255fd5f47587bba08c7929eace42b) it is not default.

The Windows build of FreeSWITCH [seems to use OpenSSL 1.0.2k](https://github.com/signalwire/freeswitch/blob/15ad4c23e259c1c2dff58f89e9124e5f36dd2e94/w32/openssl-version.props), which should support DTLSv1.2.

I tried to change `sip_tls_version` from "tlsv1,tlsv1.1,tlsv1.2" to "tlsv1.2", but to no avail.

Am I missing some configuration option or is this a bug?

**Comment by waht** [comment]
Here is a minial example with as much default FreeSwitch configuration as possible:

1. Download & Install the latest FreeSwitch release.
2. In `vars.xml` change `domain_name` to `localhost`:
```
<X-PRE-PROCESS cmd="set" data="domain_name=localhost"/>
```
3. Add the following at the end of `sip_profiles/external.xml`:
```
        <param name="ws-binding" value="127.0.0.1:5088" />
	<param name="accept-blind-reg" value="true"/>
	<param name="apply-candidate-acl" value="any_v4.auto" />
	<param name="apply-inbound-acl" value="loopback.auto" />
```
4. Also in `sip_profiles_external.xml` change `context` to `delay`: i.e.
```
<param name="context" value="delay"/>
```
5. Create a new dialplan file `conf/dialplan/delay.xml` with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<include>
  <context name="delay">
	<X-PRE-PROCESS cmd="include" data="default/*.xml"/>
  </context>
</include>

```
6. Start FreeSwitch 
7. Open Firefox
8. Open https://jsfiddle.net/123c5ybk/11/ and click on "Call"
8.1. After the connection was established you will hear the current date & time
10. Disable DTLSv1.0 by setting `media.peerconnection.dtls.version.min` to `771` at the URL `about:config`
11. Open https://jsfiddle.net/123c5ybk/11/ again (or click on "Run" button) and click on "Call"
11.1 This time there is no audio, the FreeSwitch console shows `[ERR] switch_rtp.c:3266 audio Handshake failure 1. This may happen when you use legacy DTLS v1.0 (legacyDTLS channel var is set) but endpoint requires DTLS v1.2.`

**Comment by waht** [comment]
I was able to reproduce the problem using the above configuration with Version 1.8.7 (64bit Windows and Debian - using the [FreeSwitch Docker Container](https://github.com/signalwire/freeswitch/tree/master/docker/release) - I changed the release from 1.6 to 1.8). 
However the problem does not occur on Debian 10 using 1.10.2. 

As a result I think the Windows build of 1.10.2 is to blame here.

**Comment by waht** [comment]
I have found the culprit: The macro `HAVE_OPENSSL_DTLSv1_2_method` is unset when building with Visual Studio. I found it in [configure.ac](https://github.com/signalwire/freeswitch/blob/7effdf05652885b722bbf9fc22ec82022ce3d8e6/configure.ac#L1611) but I'm afraid the macro is not set when using Visual Studio.

When forcing the Code to use the DTLSv1.2 methods in [switch_rtp.c](https://github.com/signalwire/freeswitch/blob/65fa90894ef5b67215a5a5cd5ca7915a3185bd3a/src/switch_rtp.c#L3765) and [switch_core_media.c](https://github.com/signalwire/freeswitch/blob/65fa90894ef5b67215a5a5cd5ca7915a3185bd3a/src/switch_core_media.c#L8482) DTLSv1.2 is used as expected.

**Comment by hthetiot** [comment]
Chrome 83.0.4103.61 Warning:
- [Deprecation] Your partner is negotiating an obsolete (D)TLS version. Support for this will be removed in M81, around April 2020. Please check with your partner to have this fixed.

Already Failing in Safari Version 13.1 (15609.1.20.111.8).

**Comment by andywolk** [comment]
Please reopen the issue if the problem exists still.

**Comment by sohneg** [comment]
Hey. I'm facing a switch_rtp.c:3185 audio Handshake failure 1
It looks like it's the same problem. I work with FS 1.6.20 on Centos and try to make a call with jsSIP in the browser (windows). Is there any solution?
