### ISSUE TITLE
make fails: src/switch_core_cert.c:39:20: error: unused function 'switch_ssl_ssl_lock_callback' [-Werror,-Wunused-function]

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#518]
On 1.10.2 and 1.10.3-dev+git~20200316T185705Z~ac64d8e78d~64bit (git ac64d8e 2020-03-16 18:57:05Z 64bit.

This error causes make to fail and has been there a while. macOS 10.15.3 (also 10.13, 10.14), clang. It appears it's the only unused function(s).

  CC       src/libfreeswitch_la-switch_core_cert.lo
src/switch_core_cert.c:39:20: error: unused function 'switch_ssl_ssl_lock_callback' [-Werror,-Wunused-function]
static inline void switch_ssl_ssl_lock_callback(int mode, int type, char *file, int line)
                   ^
src/switch_core_cert.c:49:29: error: unused function 'switch_ssl_ssl_thread_id' [-Werror,-Wunused-function]
static inline unsigned long switch_ssl_ssl_thread_id(void)
                            ^
2 errors generated.
make[1]: *** [src/libfreeswitch_la-switch_core_cert.lo] Error 1
make: *** [all] Error 2

**Comment by seven1240** [comment]
duplicated https://github.com/signalwire/freeswitch/issues/176

**Comment by MarioG-X** [comment]
I added info to #176 and will continue there. Sorry for the duplicate.

**Comment by mjerris** [comment]
fixed in https://github.com/signalwire/freeswitch/commit/546bebbe5e7936a834f5be28ade91808f548215b
