### ISSUE TITLE
Bug #510 closed without any cause

### ISSUE THREAD

**Issue by pRiVi** [signalwire/freeswitch#525]
Bug #510 was closed without any cause... Please tell why it was closed and further what we can do, maybe money, to get this resolved **AND NOT JUST CLOSED**!

**Comment by pRiVi** [comment]
This bug is reported over a year ago, is easy to reproduce, has been closed without resolving multiple times, and leads to a unusable software for any SIP provider in TCP mode - for example telekom.de - the germany main telephony company with about 40 million customers.

**Comment by crienzo** [comment]
re-opening #510
