### ISSUE TITLE
-ERR sofia Command not found! 

### ISSUE THREAD

**Issue by donweasel** [signalwire/freeswitch#527]
Hello,
i have tried several times to install  FreeSwitch on Debian10 and every time when im in fs_cli and perform any of the sofia commnads i get this:
**-ERR sofia Command not found!**

could somebody help how to solve this?
Thanks 

FreeSWITCH (Version 1.10.2 -release-14-f7bdd3845a 64bit) is ready

followed all ways on this page
https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster

**Comment by seven1240** [comment]
looks like mod_sofia is not correctly loaded. type `load mod_sofia` in your console and see if you can get more information.

**Comment by andywolk** [comment]
See `external_rtp_ip` and `external_sip_ip` in `vars.xml`. If STUN server fails then these variables will be empty and sofia won't load. Try explicitly set an ip address or use different STUN server.

**Comment by donweasel** [comment]
Hi @seven1240 see attached logs. its failing

[error mod_sofia.txt](https://github.com/signalwire/freeswitch/files/4374542/error.mod_sofia.txt)

**Comment by seven1240** [comment]
so it's stun failed. and Andy already gave you the answer.

**Comment by donweasel** [comment]
Yup all good after that. thanks !!
