### ISSUE TITLE
[mod_verto] Safari 13.1: Verto no longer works

### ISSUE THREAD

**Issue by nblasgen** [signalwire/freeswitch#532]
I actually believe this is an issue with Safari and maybe not with Freeswitch, but I can't fully confirm at this time.  Plus I'm running FS 1.6.20 and currently unable to test against a recent release.

Authentication is fine.  Calling any extension inside Freeswitch, or having Freeswitch call me, results in the line ringing and connecting, but immediately disconnected.

````
2020-03-26 07:00:15.644680 [ERR] switch_rtp.c:3185 audio Handshake failure 1
2020-03-26 07:00:15.644680 [INFO] switch_rtp.c:3186 Changing audio DTLS state from HANDSHAKE to FAIL
````

A good connection results in a line about Fingerprint being verified, and then going into SETUP.  So something about the Fingerprint must be failing.

The purpose of this "issue" is to see if someone else can verify if this is an issue on a current branch or not.  If it's not an issue, I'll figure out how to upgrade to a later release.  According to the customer, this wasn't an problem with Safari 13.05 but is an issue with Safari 13.1.  This is on a Macbook and not being tested from a mobile device.

**Comment by dong2** [comment]
FS v1.6 + sipml5  over wss

This bug will still appear

[ERR] switch_rtp.c:3185 audio Handshake failure 1
