### ISSUE TITLE
Crashing FreeSWITCH (Version 1.10.1-release git f999022 2019-08-20 16:54:04Z 64bit) on heavy load

### ISSUE THREAD

**Issue by bee-jarvis** [signalwire/freeswitch#533]
Hi as mentioned in subject line, we put 1500 calls in one conference after disconnecting all calls with conference hup all Freeswitch is crashing 
[20200324T165325Z-bt.txt](https://github.com/signalwire/freeswitch/files/4386427/20200324T165325Z-bt.txt)
frequntly here i attached backtrace file. please check once.

**Comment by italorossi** [comment]
That was fixed at 1.10.2.

https://github.com/signalwire/freeswitch/pull/95
https://github.com/signalwire/freeswitch/issues/21

**Comment by kkbhanu88** [comment]
thanks for the reply, 
i have updated freeswitch to 1.10.2  and after that also my FS is crashed.

my use case: 
me doing a conference call with 2000 people in that around 1700 people are on call , call was smooth till 30 minutes. after completion of call we are disconnecting conference by command
conference <conferenceroom> hup all.
then immediately FS is crashed. 
here i am attaching my complete server configuration and crash file aswell.
please conculde 
1.why this is happened only on conference hangup
2.what is the minimum configuration of server to make 1000 calls?
[20200408T072514Z-bt.txt](https://github.com/signalwire/freeswitch/files/4448956/20200408T072514Z-bt.txt)
![image](https://user-images.githubusercontent.com/44552693/78757525-42bf9e00-799a-11ea-8394-e7b262aeb6d0.png)
![image](https://user-images.githubusercontent.com/44552693/78757663-7e5a6800-799a-11ea-89df-e2e8d22f06c2.png)

**Comment by andywolk** [comment]
See if that fixes your problem https://github.com/signalwire/freeswitch/pull/636
