### ISSUE TITLE
question: How to suggest updates to documentation?

### ISSUE THREAD

**Issue by toraritte** [signalwire/freeswitch#54]
Now that FreeSWITCH is on Github, but the documentation is still on Confluence, I'm confused how to suggest edits. One can leave an inline comment or create a JIRA issue, but not sure whether that is the proper way.

**Comment by crienzo** [comment]
Hello.  FreeSWITCH confluence edits are community-driven.  You may request access to confluence if you'd like to become an editor.

**Comment by toraritte** [comment]
Thanks, I already have a login, and the page says it's "unrestricted" and anyone can edit, but I just can't figure out what I am missing. How could I become an editor, or just suggest edits? Thanks for the help!

**Comment by crienzo** [comment]
@toraritte send us your username and @andywolk can set it up.  You can reply here or PM us in slack.

**Comment by toraritte** [comment]
Username is "toraritte". Thanks again!
