### ISSUE TITLE
[mod_pgsql] usage of odbc-dsn leads to `transaction block` error

### ISSUE THREAD

**Issue by impactpopov** [signalwire/freeswitch#543]
FreeSWITCH Version 1.10.2-release-14-f7bdd3845a~64bit (-release-14-f7bdd3845a 64bit)
Debian GNU/Linux 9.12 (stretch)
Tried on three different hosts and with postgres 11/9.6/pgbouncer(local/remote)
seems like freeswitch tries to use same transaction for all new requests all the time even after error on previous request

With sofia with `sofia profile internal restart(stop/start)` or even right after restart of freeswitch got errors:
`2020-04-03 08:17:37.757178 [DEBUG] mod_pgsql.c:747 Query (update sip_registrations set ping_expires = 1585901394 where hostname='host' and profile_name='internal' and ping_expires <= 1585901357 ) returned PGRES_FATAL_ERROR
2020-04-03 08:17:37.757178 [ERR] mod_pgsql.c:523 Error executing query:
ERROR:  current transaction is aborted, commands ignored until end of transaction block`
pg_stst_activity shows one abandoned idle request 

with core db got same errors with its own requests.

coredump made in runetime
[tttt.txt](https://github.com/signalwire/freeswitch/files/4425887/tttt.txt)

error easy to reproduce

**Comment by andywolk** [comment]
Try latest master
https://github.com/signalwire/freeswitch/commit/3d650f4f694d0f0f51bde285796a7f43059f7119#diff-7c063dd9ef98f3e13d3e601ea0411a95

**Comment by impactpopov** [comment]
FreeSWITCH Version 1.10.3-dev-2387-bbca42cbf5~64bit (-dev-2387-bbca42cbf5 64bit)

Thanks. Seems problem was solved. Do you know when it will b in release version?
