### ISSUE TITLE
Max queue size reached

### ISSUE THREAD

**Issue by majidshirazy** [signalwire/freeswitch#55]
Why queue size is not configurable in freeswitch?

**Comment by crienzo** [comment]
Queue sizes are sized large enough not to be exceeded under normal operation.  Exceeding a queue size is generally a symptom of overloading the process.

**Comment by majidshirazy** [comment]
I have this issue on 150 concurrent calls in my FS, is that overload?

**Comment by gedixss** [comment]
I had this problem in Freeswitch version 1.6.20. And This problem occurs on only ~100 concurent calls.

**Comment by bilalabbasi55** [comment]
I am facing that problem too, did anyone found the reason for that?

**Comment by dragos-oancea** [comment]
Your app does not read / dequeue the events fast enough.

**Comment by bilalabbasi55** [comment]
@dragos-oancea  Thanks for your time, but we are really not using mod_event_socket, how ever we are using mod_xml_curl, does that really uses even_socket underlaying for getting the dialplan through API?

**Comment by anthmFS** [comment]
Are you maybe leaving fs_cli parked in a terminal somewhere that is blocking or too slow to keep up with the log messages?
That error is verbatim from mod_event_socket so that's likely the cause.

**Comment by Len-PGH** [comment]
On one of the Cluecon Weekly calls this topic came up and the scenerio was with lua listening for all events.  The box couldn't keep up with all the events FreeSWITCH was sending so the fix was to only listen for only the needed events and not "all"
