### ISSUE TITLE
Compiling freeswitch with GCC 9 requires patch.

### ISSUE THREAD

**Issue by zooptwo** [signalwire/freeswitch#565]
` a/src/mod/applications/mod_conference/conference_event.c
+++ b/src/mod/applications/mod_conference/conference_event.c
@@ -107,13 +107,14 @@ void conference_event_mod_channel_handler(const char *event_channel, cJSON *json
                        }
                }
        }
-
-       switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);
+        
        if (zstr(action)) {
                goto end;
        }
+       switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);
+
        SWITCH_STANDARD_STREAM(stream);
        if (!strcasecmp(action, "kick")) {
`

**Comment by zooptwo** [comment]
`--- a/src/mod/applications/mod_conference/conference_event.c
+++ b/src/mod/applications/mod_conference/conference_event.c
@@ -107,13 +107,14 @@ void conference_event_mod_channel_handler(const char *event_channel, cJSON *json
                        }
                }
        }
-
-       switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);
+        
        if (zstr(action)) {
                goto end;
        }
+       switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "conf %s CMD %s [%s] %s\n", conference_name, key, action, cid);
+
        SWITCH_STANDARD_STREAM(stream);
        if (!strcasecmp(action, "kick")) {`

**Comment by zooptwo** [comment]
No clue why that won't paste right, but action cannot be null otherwise GCC 9 doesn' tlike it so just moved below the check for null that was already in the code.

**Comment by mjerris** [comment]
i’m happy to review a pull request to fix this.  please open one up with your fix
