### ISSUE TITLE
fs_path sequential request 

### ISSUE THREAD

**Issue by volga629-1** [signalwire/freeswitch#570]
Freeswitch version 

```
freeswitch@fs1.svc.lan> version 
FreeSWITCH Version 1.10.1-release~64bit (-release 64bit)

```
Issue:

Sofia is not following fs_path in  Registration contact to send sequential request. Instead it send to client Request URI.

Result:
Keepalive  Ping OPTIONS or NOTIFY ( mwi ) failing to reach the client.

Expected Result:
 Generated packet will follow fs_path and will be sent to upstream proxy.

Logs:

![fs_path](https://user-images.githubusercontent.com/59034879/79694640-fe5cb980-8247-11ea-9ef1-b9dbfb67c7ee.png)

```
+OK log level info [6]
freeswitch@fs1.svc.lan> sofia status profile internal reg
Registrations:
=================================================================================================
Call-ID:    	102651MjNlYTQ5YzgxMjkyZGMwYWVmNjgzNjhjZTgyMDg3Yzc
User:       	100@demo.sip.lan
Contact:    	"100" <sip:100%40demo.sip.lan@192.168.50.10:5060;fs_path=sip%3A100%4092.168.50.10%3A5060>
Agent:      	X-Lite release 5.8.3 stamp 102651
Status:     	Registered(UDP)(unknown) EXP(2020-04-19 19:24:36) EXPSECS(1435)
Ping-Status:	Unreachable
Ping-Time:	32003.52
Host:       	fs1.svc.lan
IP:         	192.168.50.10
Port:       	5060
Auth-User:  	100
Auth-Realm: 	demo.sip.lan
MWI-Account:	100@demo.sip.lan

```

**Comment by volga629-1** [comment]
Lesson learned Path: header should include correct <>.
Closing.

**Comment by briankwest** [comment]
Attach a full trace please from start to finish.
