### ISSUE TITLE
FS crashes with "double free or corruption" in mod_cdr_pg_csv

### ISSUE THREAD

**Issue by fatihorhan** [signalwire/freeswitch#572]
Hello all,

Our env:
Centos 7 64-bit (bare metal, 32 core Xeon, 64g ram)
freeswitch compiled (with postgresql-devel yum package and mod_pgsql) at commit https://github.com/signalwire/freeswitch/commit/60fa01976f57038f3608cd88ab0ac81262e82f10.

We had 3 crashes in 1 month period:
`double free or corruption (out)` error on 25 Mar and 15 Apr.
`double free or corruption (fasttop)` on 22 Apr

Logs extracted from core dumps for last 2 crashes attached. Core dumps show that crashes happen after writing a CDR record to Postgresql (the record exists in the DB). This FS instance writes thousands of CDRs per day but somehow crashes after one.

Here is one of the backtraces:
```
Thread 1 (Thread 0x7fe336868700 (LWP 61037)):
#0  0x00007feb60806207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007feb608078f8 in __GI_abort () at abort.c:90
#2  0x00007feb60848d27 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7feb6095a678 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007feb60851489 in malloc_printerr (ar_ptr=0x7feb60b96760 <main_arena>, ptr=<optimized out>, str=0x7feb6095a780 "double free or corruption (out)", action=3) at malloc.c:5004
#4  _int_free (av=0x7feb60b96760 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3843
#5  0x00007feb62f0a60d in freePGconn (conn=0x7fe5ac1356a0) at fe-connect.c:3546
#6  0x00007feb62f0c3b7 in PQfinish (conn=<optimized out>) at fe-connect.c:3725
#7  0x00007feb56c82941 in insert_cdr (values=0x7fe488286050 "'DENIZ','1002','905302938635','outbound.lua','2020-04-15 12:24:41',null,'2020-04-15 12:24:45','2020-04-15 12:25:01',20,0,'USER_BUSY','e9e90e81-b669-49da-b508-42e61481a18a','PCMU','PCMU','sbshayvancili"...) at mod_cdr_pg_csv.c:289
#8  my_on_reporting (session=0x7feb3af2c4a8) at mod_cdr_pg_csv.c:385
#9  0x00007feb631e486d in switch_core_session_reporting_state (session=session@entry=0x7feb3af2c4a8) at src/switch_core_state_machine.c:936
#10 0x00007feb631e53f8 in switch_core_session_run (session=0x7feb3af2c4a8) at src/switch_core_state_machine.c:610
#11 0x00007feb631df6fe in switch_core_session_thread (thread=<optimized out>, obj=0x7feb3af2c4a8) at src/switch_core_session.c:1709
#12 0x00007feb631db163 in switch_core_session_thread_pool_worker (thread=0x7fe480070c00, obj=<optimized out>) at src/switch_core_session.c:1772
#13 0x00007feb634c2bd0 in dummy_worker (opaque=0x7fe480070c00) at threadproc/unix/thread.c:151
#14 0x00007feb60ba4dd5 in start_thread (arg=0x7fe336868700) at pthread_create.c:307
#15 0x00007feb608cdead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

There are no error in the postgresql logs, other FS instances continue to use the same postgresql db while this one crash, there is nothing unusual in the freeswitch.log, CDR record and the channel look normal. I checked the newer commits and saw nothing related.

I appreciate any help debugging and/or solving this crash.

[bt-apr-22.log](https://github.com/signalwire/freeswitch/files/4516298/bt-apr-22.log)
[bt-apr-15.log](https://github.com/signalwire/freeswitch/files/4516300/bt-apr-15.log)

**Comment by mjerris** [comment]
Looks like likely an error in postgres libs.  Can you reliably reproduce this?  if so can you test on debian 10 to confirm its a lib issue?

**Comment by fatihorhan** [comment]
Unfortunately I can't reproduce.
Would compiling with a newer different version of postgresql-devel help? There is an updated package.
