### ISSUE TITLE
Control FS using C or C++

### ISSUE THREAD

**Issue by arthur-s** [signalwire/freeswitch#576]
Hello everyone, please can someone provide me any example how to control calls using pure C or C++? E.g., answer the call. Where from to start? Of course, I can choose lua/javascript/python for this task, but I'm interrested how to do it wih C/C++ (as scripting interface, no ESL). Thank you in advance.

**Comment by mjerris** [comment]
if you are looking to not do a scripting interface or esl, check out any of the modules in the application directory like mod voicemail or rss
