### ISSUE TITLE
Install Problem on Debian Buster

### ISSUE THREAD

**Issue by dodgemead** [signalwire/freeswitch#579]
New Install of Debian Buster
Linux FreeSwitch 4.19.0-8-686-pae #1 SMP Debian 4.19.98-1 (2020-01-26) i686 GNU/Linux

I followed the instructions on freeswitch site for debian buster install. 
I ran this command

apt-get update && apt-get install -y gnupg2 wget lsb-release
wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -
 
echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list
echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list

It appeared to have ran fine. 

I then ran the command:
apt-get update && apt-get install -y freeswitch-meta-all

It errored with:

root@FreeSwitch:~# apt-get update && apt-get install -y freeswitch-meta-all
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package freeswitch-meta-all

I found that in /etc/apt/sourcelist.d the freeswitch.list had not been created. 
I manually created it and then ran the last command again,
I then ran apt update after this.

I then ran the command again.

root@FreeSwitch:/etc/apt# apt-get update && apt-get install -y freeswitch-meta-all
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Ign:2 http://files.freeswitch.org/repo/deb/debian-release `lsb_release InRelease
Err:3 http://files.freeswitch.org/repo/deb/debian-release `lsb_release Release
  404  Not Found [IP: 190.102.98.174 80]
Hit:4 http://deb.debian.org/debian buster InRelease
Hit:5 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
E: The repository 'http://files.freeswitch.org/repo/deb/debian-release `lsb_release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I am really not sure what I am doing wrong. I have worked with Linux over the years but mainly as a user. If someone could give me some guidance on resolving this I would appreciate it. 

DM

**Comment by andywolk** [comment]
We use the same instruction for Buster and Stretch, this is why `lsb_release
-sc` is a command, but in your case it is just text.
You can see that by the output: The repository '
http://files.freeswitch.org/repo/deb/debian-release `lsb_release Release'
does not have a Release file.
What you are doing wrong is you are missing ` symbols around.
Right answer:
echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release
-sc` main" > /etc/apt/sources.list.d/freeswitch.list
echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/
`lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list

Please read docs carefully:
https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster
  `lsb_release -sc` returns buster on buster so final string will be: "deb
http://files.freeswitch.org/repo/deb/debian-release/ buster main"

вс, 26 апр. 2020 г. в 00:58, dodgemead <notifications@github.com>:
