### ISSUE TITLE
Is freeswitch/src/mod/say/mod_say_he/mod_say_he.c Production-tested?

### ISSUE THREAD

**Issue by RebBlumstein** [signalwire/freeswitch#583]
Has anyone production-tested the Hebrew mod-say code? Any issues? Do you need better/different voice samples?

**Comment by avimar** [comment]
@ShaharHD your name Shahar Hadas seems to be at the top of the file. Did you have publicly available audio files for this module?

**Comment by ShaharHD** [comment]
They weren't mines to start with. I've used the recordings done by the Hebrew University of Jerusalem.

This project being almost 9 years old ... but I think I still have the hard drive of that FreeSwitch machine which had all the recordings.
The problem is that hard drive is in a Storage Unit in the US and I'm right now in Israel due to Covid-19
I have another NAS in the US which I might be able to get access to - but it'll take some time.
Will update.

I should have both the recordings WAV files, and an audacity project with the original MP3 file which holds all the raw recordings (that's what I remember).

**Comment by mtghr** [comment]
Yisroel meir

Do you have enough channels (phone lines) to handle this?

**Comment by avimar** [comment]
@mtghr yes, my carrier assured me that channels won't be a problem

**Comment by RebBlumstein** [comment]
BTW @avimar is the guy who's really handling this project. I just speak Hebrew a little better.

**Comment by avimar** [comment]
@ShaharHD I've gotten the hebrew audio files of `Daniel` and added audio files from Hebrew U. I didn't get any raw files from them, though.

Uploaded here:  https://gofile.io/?c=KCQDAA

With the standard version, though, I think there were some issues and there's a mix of different speakers, both male and female, on the audio. I was hoping there was a cleaner set done somewhere.

**Comment by ShaharHD** [comment]
@avimar When I finished the project back then, I've sent them updated audio files where I fixed some of those issues.

I'm guessing what you got is a mix of various audio files, but I don't remember if my version had mixed speaker voices ... but as it was working, I assume there were all in one voice.

Ask Yehavi if he still has the `daniel.v1.zip` I sent him a link for 8 years ago ...

**Comment by ShaharHD** [comment]
@avimar I've downloaded the files you sent. They've added other various custom messages.

The `mod_say_he` core is using `digits`, `ivr` and other various folders. it seems those are all in the original "Daniel" voice.

There are some exceptions for new recordings which are now needed and didn't exist back then.

Regarding raw files - it's a `mp3` file he sent me back then.

**Comment by ShaharHD** [comment]
@avimar @RebBlumstein 
Got it :)
here's the raw MP3 file
[Daniel-recordings.mp3.zip](https://github.com/signalwire/freeswitch/files/4541640/Daniel-recordings.mp3.zip)

Also attached the version of recordings I had on that NAS server. don't know from where or what version. sorry.
[he.zip](https://github.com/signalwire/freeswitch/files/4541647/he.zip)

**Comment by mjerris** [comment]
this appears resolved from comments. please reopen if not

**Comment by mtghr** [comment]
Dataphone Stretch
    
    

    
    
        table {
            border-spacing: 0;
            border-collapse: collapse;
            width: 100%;
        }

        td {
            padding: 0;
        }

        p {
            font-size: 16px;
        }

        img {
            border: 0;
        }

        .content {
            line-height: 26px;
            font-size: 15px;
        }

        .bluelink {
            text-decoration: none;
            color: #140D39 !important;
        }

        span.Object {
            color: inherit !important;
        }

        span.Object-hover {
            color: inherit !important;
            text-decoration: none !important;
        }

        u+.body .gmail-blend-screen {
            background: #000;
            mix-blend-mode: screen;
        }

        u+.body .gmail-blend-difference {
            background: #000;
            mix-blend-mode: difference;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
            line-height: 100%;
        }

        a[x-apple-data-detectors=true] {
            color: inherit !important;
            text-decoration: inherit !important;
        }

        @media screen and (max-width: 599.98px) {


            .column-wrapper .padding {
                padding-right: 0 !important;
                padding-left: 0 !important;
            }

            .column-wrapper {
                padding: 0 30px !important;
            }

        }

        @media screen and (max-width: 499.98px) {
            .column-wrapper {
                padding: 0 20px !important;
            }
        }

        @media screen and (max-width: 399.98px) {
            .column-wrapper {
                padding: 0 10px !important;
            }
        }


        :root {
            color-scheme: light dark;
            supported-color-schemes: light dark;
        }

        @media (prefers-color-scheme: dark) {

            body,
            table,
            .darkmode-bg {
                background: #FEFEFE !important;
                color: #140D39 !important;
            }

            [data-ogsc] body,
            table,
            .darkmode-bg {
                background: #FEFEFE !important;
                color: #140D39 !important;
            }

            .darkmode-transparent {
                background-color: transparent !important;
            }

            [data-ogsc] .darkmode-transparent {
                background-color: transparent !important;
            }

        }

         
        @import ***@***.***,400..800;1,400..800&display=swap');
    
    





    
        

            
            
                                
                ‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏
            
            

            

            


                
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                            
                                
                                    
                                        Get your Business up to

                                        
                                            
                                        
                                        Speed.
                                    
                                
                            
                        
                        
                            
                                
                                    
                                        Line by Line.
                                    
                                
                            
                            
                                
      
                                        
                                    

                                
                            
                            
                                
                                
                            
                        
                    
                
                

                
                
                    
                        
                            
                                
                                    
                                        
                                        
                                            
                                                                         
                                                          

        
        
        Hi Reply+Aijueggq5ynje65uqynf6h54wf6g7evbnhhcilo53a,

        We hope you're doing great.

        We want to remind you that the carriers have made 10DLC registration mandatory for businesses sending SMS messages. Starting October 31, 2024, any unregistered numbers could face message blocking, meaning your messages may not reach your customers.

        To better understand what this means and why it's important, you can check out our blog posts:
        
            What Happens When Carriers Block Unregistered 10DLC Numbers?
            10DLC Registration: Why It’s Important for Your Business SMS
        

        If you haven’t completed your 10DLC registration yet, please reach out to our support team at ***@***.***, and they will guide you through the process to avoid disruptions.

        Let us know if you have any questions.

           


                                                                                      
                                                        
                                                    
                                                



                                                

                                            
                                        
                            
                        
                    
                
            
            
            
            

            
            
                
                    
                        
                            
                                
                                    
                                
                            
                        
                        
                            
                                
                                  
                                   
                                     
                                               Unsubscribe
                                                                        
                                    |
                                    
                                        Privacy Policy
                                    
                                    |
                                    
                                        Contact Us
                                    
                                
                            
                        
                    
                
            

            
                
                    
                        
                            
                                
                                    © 2024 Dataphone, Inc.
                                
                                
                                    All rights reserved.
                                
                                
                                    1449 37th St, 612B, Brooklyn, New York 11218, US
                                
                            

                        
                    
                
            

            
                
                    
                        
                            
                                
                                    Follow us on
