### ISSUE TITLE
Extension not registering

### ISSUE THREAD

**Issue by Inteleweb** [signalwire/freeswitch#587]
**[WARNING] sofia_reg.c:2929 Can't find user xxxxxxxxxx from xxxxxxxx
You must define a domain called xxxxxx**

![image](https://user-images.githubusercontent.com/64444863/80429720-9dd31980-88e4-11ea-971d-474f8aa075e0.png)

I'm getting the above error and my phone won't register. I have searched online but there is not much help.

**Comment by mjerris** [comment]
The error message tells you exactly what needs to be done.  The phone is attempting to use the user in the error message but no such user is in the directory.
