### ISSUE TITLE
Crash from failed assert(*nh->nh_prev == nh) in nua_stack.c

### ISSUE THREAD

**Issue by GitHubIsShortOnUsernames** [signalwire/freeswitch#596]
Hello,

we've recently had a production system crash on a failed assert. There was nothing out of the ordinary going on and we can't make out the underlying cause. Any help would be greatly appreciated.

FreeSWITCH Version 1.10.2-release+git~20191231T140119Z~f7bdd3845a~64bit (git f7bdd38 2019-12-31 14:01:19Z 64bit)

Log and trace attached.

Thanks,

Thomas

[trace_n_log.zip](https://github.com/signalwire/freeswitch/files/4557332/trace_n_log.zip)

**Comment by andywolk** [comment]
Investigating this without original FreeSWITCH logs (not the edited ones) would be the waste of time.
We will be happy to review your PR as a solution for this.
Please ask for re-open the issue if you have more details.
You can always contact sales@signalwire.com for paid support.

**Comment by flam-flam-flam** [comment]
> 你好，
> 
> 我们最近因断言失败而使生产系统崩溃。没有什么不寻常的事情，我们无法找出根本原因。任何帮助将不胜感激。
> 
> FreeSWITCH版本1.10.2-release + git~20191231T140119Z~[f7bdd38〜64bit](https://github.com/signalwire/freeswitch/commit/f7bdd3845a91c77ff6c776a70ae2fc9d7f7d3f86)（git[ f7bdd38](https://github.com/signalwire/freeswitch/commit/f7bdd3845a91c77ff6c776a70ae2fc9d7f7d3f86) 2019-12-31 14：01：19Z 64bit）
> 
> 日志和跟踪已附加。
> 
> 谢谢，
> 
> 汤玛士
> 
> [trace_n_log.zip](https://github.com/signalwire/freeswitch/files/4557332/trace_n_log.zip)

Hello, I also encountered this problem，Do you solve this trouble？

**Comment by flam-flam-flam** [comment]
> Hello,
> 
> we've recently had a production system crash on a failed assert. There was nothing out of the ordinary going on and we can't make out the underlying cause. Any help would be greatly appreciated.
> 
> FreeSWITCH Version 1.10.2-release+git~20191231T140119Z~[f7bdd38](https://github.com/signalwire/freeswitch/commit/f7bdd3845a91c77ff6c776a70ae2fc9d7f7d3f86)~64bit (git [f7bdd38](https://github.com/signalwire/freeswitch/commit/f7bdd3845a91c77ff6c776a70ae2fc9d7f7d3f86) 2019-12-31 14:01:19Z 64bit)
> 
> Log and trace attached.
> 
> Thanks,
> 
> Thomas
> 
> [trace_n_log.zip](https://github.com/signalwire/freeswitch/files/4557332/trace_n_log.zip)

Hello, I also encountered this problem，Do you solve this trouble？

**Comment by GitHubIsShortOnUsernames** [comment]
We haven't encountered this since upgrading to 1.10.3. The latest FS releases helped a lot with stability, I suggest you update to the latest version.

**Comment by flam-flam-flam** [comment]
> We haven't encountered this since upgrading to 1.10.3. The latest FS releases helped a lot with stability, I suggest you update to the latest version.

that is great,  thanks!    I will try
