### ISSUE TITLE
FreeBSD 12.1 compile error

### ISSUE THREAD

**Issue by RDP1974** [signalwire/freeswitch#597]
hello,
I'm trying to compile latest freeswitch with FreeBSD 12.1 default install with clang 8.
With postgresql (version 12 installed)
On make I get this error:
diff: unrecognized option `--version'
diff missing: Try installing diffutils via your package manager.

pkg update && upgrade and freebsd-update done

any hint?

**Comment by mjerris** [comment]
we don’t maintain anything for freebsd but we are happy to take patches from the community with fixes if they don’t break other platforms.  Looks like diff isn’t installed based on that error

**Comment by RDP1974** [comment]
hello, diff is installed.
