### ISSUE TITLE
freeswitch ulimits

### ISSUE THREAD

**Issue by asterlab** [signalwire/freeswitch#60]
hello,
I have installed freeswitch on a debian buster successfully. I have set up the ulimits in the freeswitch.service, in the /etc/profile... around everywhere but the Max open files  still equals to 999999. where on earth freeswitch takes that value ?

**Comment by asterlab** [comment]
` cat /usr/lib/systemd/system/freeswitch.service
;;;;; Author: Travis Cross <tc@traviscross.com>

[Unit]
Description=freeswitch
Wants=network-online.target
Requires=network.target local-fs.target
After=network.target network-online.target local-fs.target

[Service]
; service
Type=forking
PIDFile=/run/freeswitch/freeswitch.pid
Environment="DAEMON_OPTS=-nonat"
Environment="USER=freeswitch"
Environment="GROUP=freeswitch"
EnvironmentFile=-/etc/default/freeswitch
#ExecStartPre=/usr/sbin/ethtool -G ens18 rx 32 tx 32
#ExecStartPre=/usr/sbin/ethtool -G ens19 rx 32 tx 32
ExecStartPre=echo vegas > /proc/sys/net/ipv4/tcp_congestion_control
ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/log/freeswitch /etc/freeswitch /usr/share/freeswitch /var/run/freeswitch
ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait ${DAEMON_OPTS}
TimeoutSec=45s
Restart=always
; exec
;User=${USER}
;Group=${GROUP}
LimitCORE=infinity
LimitNOFILE=1024000
LimitNPROC=infinity
LimitSTACK=infinity
LimitRTPRIO=infinity
LimitRTTIME=infinity
LimitMEMLOCK=infinity
LimitMSGQUEUE=infinity
LimitSIGPENDING=infinity
IOSchedulingClass=realtime
IOSchedulingPriority=2
CPUSchedulingPolicy=rr
CPUSchedulingPriority=89
UMask=0007
NoNewPrivileges=false

; alternatives which you can enforce by placing a unit drop-in into
; /etc/systemd/system/freeswitch.service.d/*.conf:
;
; User=freeswitch
; Group=freeswitch
; ExecStart=
; ExecStart=/usr/bin/freeswitch -ncwait -nonat -rp
;
; empty ExecStart is required to flush the list.
;
; if your filesystem supports extended attributes, execute
;   setcap 'cap_net_bind_service,cap_sys_nice=+ep' /usr/bin/freeswitch
; this will also allow socket binding on low ports
;
; otherwise, remove the -rp option from ExecStart and
; add these lines to give real-time priority to the process:
;
; PermissionsStartOnly=true
; ExecStartPost=/bin/chrt -f -p 1 $MAINPID
;
; execute "systemctl daemon-reload" after editing the unit files.

[Install]
WantedBy=multi-user.target
`

**Comment by crienzo** [comment]
999999 is probably the maximum your OS allows you to set.   Check `/proc/sys/fs/file-max`

**Comment by asterlab** [comment]
cat /proc/sys/fs/file-max 
1024001 


Renato Gallo

**Comment by asterlab** [comment]
grep -RH 999999 /etc/ 

/etc/samba/smb.conf:; idmap config YOURDOMAINHERE : range = 100000-999999 
/etc/login.defs:# The values must be inside the 1000-999999999 range. 

the process has /bin/false as shell so login has nothing to do with it and I don't think samba has anything to do with it 

Renato Gallo

**Comment by asterlab** [comment]
can you reopen the issue now ?

**Comment by crienzo** [comment]
This is a system administration issue, not a freeswitch problem.

**Comment by asterlab** [comment]
since everywhere in the system the limit has been set (yes even into freeswitch.service) I think that this issue should be reopened, there's no 999999 anywhere.
