### ISSUE TITLE
Fix issues reported by LGTM

### ISSUE THREAD

**Issue by stweil** [signalwire/freeswitch#601]
LGTM now ignores the problem described in issue #599 and has analyzed the freeswitch code. There are currently [361 alerts](https://lgtm.com/projects/g/signalwire/freeswitch/), some of them look critical. I won't be able to fix a large number of them personally and ask therefore people who know the code better for help.

**Comment by seven1240** [comment]
those are just demos and example code and some are out-dated. would better to ignore all of them before we fix all the C/C++ code.

A lot or static analysis been done and most issues already fixed. It will be useful to actually build the C/C++ code and see if there's still any alerts.

**Comment by stweil** [comment]
> It will be useful to actually build the C/C++ code and see if there's still any alerts.

Pull request #603 should enable that.

**Comment by stweil** [comment]
See also https://github.com/signalwire/libks/pull/73 which fixes some errors reported by LGTM in `libks`.

**Comment by mjerris** [comment]
the html5 dir is unmaintianed and will be moved to a new repo for archival purposes... once we move if you would like to maintain you are welcome to create patches to fix these issues but we do not plan on maintainging this code further
