### ISSUE TITLE
Invalid Naming on sounds, which is actually used (typo)

### ISSUE THREAD

**Issue by avimar** [signalwire/freeswitch#606]
https://github.com/signalwire/freeswitch/blob/197a6a6564bca0c12ee6685306963b17c0818a3d/docs/phrase/phrase_en.xml#L619
Looks  like callie actually ships with ivr-ivalid_sound_prompt which reads "the invalid sound prompt".

Not to be confused with https://github.com/signalwire/freeswitch/blob/197a6a6564bca0c12ee6685306963b17c0818a3d/docs/phrase/phrase_en.xml#L549

Which reads "invalid sound prompt"

**Comment by mjerris** [comment]
feel free to open a PR to correct typos like this.
