### ISSUE TITLE
Inbound Gateway Doesn't Work as Expected

### ISSUE THREAD

**Issue by zek** [signalwire/freeswitch#609]
I have 2 freeswitch instances (Lets call them A & B). They are connected to each other as gateway.

I execute bridge `sofia/gateway/gatewayb/600` from SwitchA to SwitchB

```
INVITE sip:600@172.254.0.3:5061 SIP/2.0
Via: SIP/2.0/UDP 172.254.0.2;rport;branch=z9hG4bKX73Hgjyt4DBNF
Max-Forwards: 69
From: "phone9" <sip:phone9@[172.254.0.3:5061]>;tag=B67mFH5av4pUH
To: <sip:600@172.254.0.3:5061>
Call-ID: 59db14bd-085a-1239-8789-0242acfefe03
CSeq: 19727702 INVITE
Contact: <sip:gw+gatewayb@172.254.0.2:5060;transport=udp;gw=gatewayb>
User-Agent: Custom
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, NOTIFY
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 506
X-FS-Support: update_display,send_info
```

You can see there's no `;gw=gatewayb` in Invite URI but in Contact. I expect it to find out `gw` from Contact. You can see my destination-number is `600`.

As I can understand from source code ( https://github.com/Deepwalker/FreeSWITCH/blob/master/src/mod/endpoints/mod_sofia/sofia.c#L6552 )  FS detecting inbound gateway either from

- SIP Invite Req uri (INVITE sip:600@172.254.0.3:5061?gw=gw_name SIP/2.0)
- Destination number (gw+gw_name)

So It can never resolve `inbound gateway` unless I execute bridge `sofia/gateway/gatewayb/600;gw=gw_name`

The other problem here is,

`SwitchA` has `gatewayb`
`SwitchB` has `gatewaya`

`SwitchB` receives `gw` as `gatewayb` and it can't find `gatewayb` since it's not defined. Therefore I must define gateway names same in both switch. 

-------
Edit:

I'm able to set `gw` as below. But I didn't see any documentation regarding it.

![image](https://user-images.githubusercontent.com/3463291/81104058-a21db900-8f1a-11ea-9a76-8548042dab3e.png)

As I know Asterisk, matches gateways by ip. FS resolves it by given `gw` in uri. Is this secure? Any gateway can act as another gateway.

**Comment by briankwest** [comment]
What problem are you trying to solve?  because 'gw' isn't designed to resolve or be of any use to anyone but FreeSWITCH itself when you receive a call back to the registered contact on that outbound registration.
