### ISSUE TITLE
Crashing FreeSWITCH version: 1.10.2-release+git~20191231T140119Z~f7bdd3845a~64bit[Program terminated with signal SIGABRT, Aborted.]

### ISSUE THREAD

**Issue by bee-jarvis** [signalwire/freeswitch#612]
Hi Team,
 i am facing frequent crash with latest version after disconnecting all calls at atime by using conference <confroomname> hangup all,this is happening randomly.
please found attached tracefile.
[20200506T065202Z-bt.txt](https://github.com/signalwire/freeswitch/files/4585340/20200506T065202Z-bt.txt)

**Comment by andywolk** [comment]
Please open gdb and show the ouput of:
```
set max-value-size unlimited
set print pretty on
set print elements 0

thread 1
frame 8
print *session
```

**Comment by bee-jarvis** [comment]
help me i am unable to found thread 1 how can i get information from gdb.
![image](https://user-images.githubusercontent.com/44552693/81316693-872d7f00-90a9-11ea-9232-6c76faae672b.png)

**Comment by andywolk** [comment]
How did you get `20200506T065202Z-bt.txt` ?
Use `gdb /path/to/freeswitch /path/to/core/file`
and repeat those commands

**Comment by bee-jarvis** [comment]
hi Andywolk am generating backtrace from scripts of Freeswitch,
here is the outputh what you asked about.


[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/freeswitch/bin/freeswitch -nc -nonat'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f35d26ac700 (LWP 64688))]
(gdb) set max-value-size unlimited
(gdb) set print pretty on
(gdb) set print elements 0
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f35d26ac700 (LWP 64688))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      in ../sysdeps/unix/sysv/linux/raise.c
(gdb) frame 8
#8  0x00007f3e00b28e1e in listener_run (thread=<optimized out>, obj=0x7f3d5458cbd8) at mod_event_socket.c:2642
2642                            switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(session), SWITCH_LOG_ERROR, "Unable to lock session!\n");
(gdb) print *session
$1 = {
  pool = 0x7f3d5458b4f8,
  thread = 0x0,
  thread_id = 0,
  endpoint_interface = 0x0,
  id = 0,
  flags = SSF_NONE,
  channel = 0x0,
  event_hooks = {
    outgoing_channel = 0x7f3d5458cc98,
    receive_message = 0x7f3d5458ccb8,
    receive_event = 0x7f3e04fc41d0 <thread_cond_cleanup>,
    read_frame = 0x7f3e04fc5ea0 <apr_pool_cleanup_null>,
    video_read_frame = 0x0,
    write_frame = 0x0,
    video_write_frame = 0x0,
    text_write_frame = 0x0,
    text_read_frame = 0x0,
    kill_channel = 0x0,
    send_dtmf = 0x0,
    recv_dtmf = 0x0,
    state_change = 0x0,
    state_run = 0x0
  },
  read_codec = 0x0,
  real_read_codec = 0x0,
  write_codec = 0x0,
  real_write_codec = 0x7f379c6e3a30,
  video_read_codec = 0x7f3d55179928,
  video_write_codec = 0x0,
  read_impl = {
    codec_type = SWITCH_CODEC_TYPE_AUDIO,
    ianacode = 0 '\000',
    iananame = 0x0,
    fmtp = 0x0,
    samples_per_second = 0,
    actual_samples_per_second = 0,
    bits_per_second = 0,
    microseconds_per_packet = 0,
    samples_per_packet = 0,
    decoded_bytes_per_packet = 0,
    encoded_bytes_per_packet = 1415105464,
    number_of_channels = 61 '=',
--Type <RET> for more, q to quit, c to continue without paging--

**Comment by andywolk** [comment]
Try compiling with this fix and see if that helps https://github.com/signalwire/freeswitch/pull/636
