### ISSUE TITLE
After entering the conference room from the public network, the server periodically initiates invite

### ISSUE THREAD

**Issue by freeeyes** [signalwire/freeswitch#628]
Users can enter the conference room normally.
But 1 minute after entering, the client will receive an INVITE client request initiated by the server.
However, this situation does not appear on the internal network, and it will appear on the public network.
Is it because some timers judge that the server caused by timeout will actively send INVITE to the client?
Does anyone has encountered a similar situation?
Thinks.

Log here

tport.c:4183 tport_pend() tport_pend(0x7f9b040042c0): pending 0x7f9b040ed6f0 for udp/XXX.XXX.XXX.XXX:5060 (already 1)
nta.c:8937 _nta_outgoing_timer() nta_outgoing_timer: 1/2 resent, 0/89 tout, 0/94 term, 0/183 free
nta.c:1296 agent_timer() nta: timer set next to 1018 ms
soa.c:1302 soa_init_offer_answer() soa_init_offer_answer(static::0x7f9b041dfe60) called
soa.c:1426 soa_generate_offer() soa_generate_offer(static::0x7f9b041dfe60, 0) called
soa_static.c:1148 offer_answer_step() soa_static_offer_answer_action(0x7f9b041dfe60, soa_generate_offer): called
soa_static.c:1029 soa_sdp_mode_set() soa_sdp_mode_set(0x7f9b041f55a0, (nil), ""): called
soa.c:1270 soa_get_local_sdp() soa_get_local_sdp(static::0x7f9b041dfe60, [(nil)], [0x7f9b2fffeb38], [0x7f9b2fffeb34]) called
nta.c:2665 nta_tpn_by_url() nta: selecting scheme sip
tport.c:4611 tport_by_name() tport(0x7f9b04004770): found 0x7f9b041cbd60 by name tcp/XXX.XXX.XXX.XXX:16475
tport.c:3280 tport_tsend() tport_tsend(0x7f9b041cbd60) tpn = tcp/XXX.XXX.XXX.XXX:16475
tport.c:3617 tport_vsend() tport_vsend(0x7f9b041cbd60): 1034 bytes of 1034 to tcp/XXX.XXX.XXX.XXX:16475
tport.c:3515 tport_send_msg() tport_vsend returned 1034
send 1034 bytes to tcp/[XXX.XXX.XXX.XXX]:16475 at 15:07:46.036440:

INVITE sip:XXXXXXX@XXX.XXX.XXX.XXX:16475;received=XXX.XXX.XXX.XXX:16475;transport=tcp SIP/2.0
Via: SIP/2.0/TCP XXX.XXX.XXX.XXX:5060;rport;branch=z9hG4bKjXyea4ZS5ypHD
Max-Forwards: 70

**Comment by mjerris** [comment]
I can’t tell definitively due to edited and truncated logs but sounds like session timers
