### ISSUE TITLE
Crash (segfault) on 1.10

### ISSUE THREAD

**Issue by kaduww** [signalwire/freeswitch#63]
Hello,

I'm running FS 1.10 as a SBC on a Debian 9 envirorment, installed by apt-get and it's frequently crashing.

freeswitch@srv-4l-tel-sbc02> status
UP 0 years, 0 days, 2 hours, 11 minutes, 46 seconds, 403 milliseconds, 143 microseconds
FreeSWITCH (Version 1.10.1 -release-12-f9990221e6 64bit) is ready
451839 session(s) since startup
722 session(s) - peak 4876, last 5min 816 
36 session(s) per Sec out of max 800, peak 507, last 5min 51 
4866 session(s) max
min idle cpu 0.00/95.90
Current Stack Size/Max 240K/8192K

It creashes when running abount 1500 calls  (3000 sessions) after a couple of hours, using two sofia profiles per call.

The corefile backtrace are attached.

[thread_apply_all_bt.txt](https://github.com/signalwire/freeswitch/files/3740562/thread_apply_all_bt.txt)
[bt.txt](https://github.com/signalwire/freeswitch/files/3740563/bt.txt)
[bt_full.txt](https://github.com/signalwire/freeswitch/files/3740564/bt_full.txt)
[info_threads.txt](https://github.com/signalwire/freeswitch/files/3740565/info_threads.txt)
[thread_apply_bt_full.txt](https://github.com/signalwire/freeswitch/files/3740566/thread_apply_bt_full.txt)

**Comment by vma** [comment]
Hi,
Maybe I am missing something but your backtrace doesn't say where the crash occurs exactly. Can you use fscore_pb to gather the crash data. You may also need to install the dbg symbols.

**Comment by crienzo** [comment]
Reopen w/ if this is still happening with latest FS.  Make sure you have debugging symbols in the backtraces.
