### ISSUE TITLE
intall at arm64 error

### ISSUE THREAD

**Issue by dropn** [signalwire/freeswitch#632]
root@ecs-6aa3-0001:~# apt-get update
Get:1 http://files.freeswitch.org/repo/deb/debian-release buster InRelease [3,933 B]
Get:2 http://files.freeswitch.org/repo/deb/debian-release buster/main Sources [4,323 B]
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://security.debian.org/debian-security buster/updates InRelease
Hit:5 http://deb.debian.org/debian buster-updates InRelease
Hit:6 http://deb.debian.org/debian buster-proposed-updates InRelease
Hit:7 http://deb.debian.org/debian buster-backports InRelease
Fetched 8,256 B in 3s (2,661 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://files.freeswitch.org/repo/deb/debian-release buster InRelease' doesn't support architecture 'arm64'

**Comment by dropn** [comment]
doesn't support architecture 'arm64'

**Comment by andywolk** [comment]
We don't support `arm64`. Only `armhf` for Raspberry Pi and it's in a different repo: https://freeswitch.org/confluence/display/FREESWITCH/Raspberry+Pi

**Comment by dropn** [comment]
> arm64

thanks very much
