### ISSUE TITLE
[mod_conference] clear-vid-floor missing from the conference channel event handler

### ISSUE THREAD

**Issue by FrenchHipster** [signalwire/freeswitch#644]
Hi,

Using FreeSwitch + Verto, I noticed that the `clear-vid-floor` command cannot be used through the conference channel.

Looking at this file: `src/mod/applications/mod_conference/conference_event.c` I can see `vid-floor` but no `clear-vid-floor`.

For reference, here is a sample Verto command I send through WebSocket:
```
{"id":1,"jsonrpc":"2.0","method":"verto.broadcast","params":{"callID":"XXXX","eventChannel":"conference-mod.XXXX","sessid":"XXXXX","data":{"application":"conf-control","command":"vid-floor","value":"force","id":"1234"}}}
```

And I would expect to similarly be able to send:
```
{"id":1,"jsonrpc":"2.0","method":"verto.broadcast","params":{"callID":"XXXXX","eventChannel":"conference-mod.XXXXX","sessid":"XXXXX","data":{"application":"conf-control","command":"clear-vid-floor"}}}
```

**Comment by mjerris** [comment]
yep your right it’s not there

**Comment by FrenchHipster** [comment]
I'm guessing it's on purpose, then?

Is there a way to use the `clear-vid-floor` command through Verto then? I wasn't able to find any documentation on this.
