### ISSUE TITLE
freeswitch does not set scope variable on second alternative during bridging

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [signalwire/freeswitch#645]
using bridge command with following dialing line 

`<action application="bridge" data="[DESTGWNAME=TS44]sofia/gateway/TS44/+31111111111|[DESTGWNAME=GW58]sofia/gateway/GW58/+31111111111"/>`

In case if call failed to first option (TS44) call automatically have to go to GW58. For both B-legs scope variable have to be installed but in reality scope variable DESTGWNAME exist only on B-leg which sent out to first gateway(TS44). On b-leg to GW58 variable not set.

**Comment by briankwest** [comment]
Thats the purpose of doing it with [] vs <> or {}, so you can scope it to the specific B-Leg in your case you have other data to indicate which gateway it went out of.

**Comment by jpVm5jYYRE1VIKL** [comment]
Did you really read what issue is ? 
ISSUE : 
Variable DESTGWNAME empty on B-leg to GW58 and case if call to TS44 failed. 
So call to GW58 passed but variable NOT SET.
