### ISSUE TITLE
Using Outbound routes to block international mobiles

### ISSUE THREAD

**Issue by Inteleweb** [signalwire/freeswitch#648]
Hi

I'm trying to use FreeSWITCH outbound routes and toll codes to allow calls to Landlines but not mobiles for example for the UK

> Allow all 44 except 447

How would I do this?
Regards,

**Comment by avimar** [comment]
Perhaps the simplest is to set up a matching extension matches on `447`. Then it plays an error / hangup in error and it won't reach the "real" outbound routing.

You can be a little fancier by having a user variable that affects if this matches. See: https://github.com/signalwire/freeswitch/blob/master/conf/insideout/dialplan/default/01_example.com.xml

Another option is to make the regex match only what you want, e.g. `^44[^7]...` but you still need to do something with that call.

**Comment by avimar** [comment]
p.s. probably would want to block +449 premium numbers if not already blocked.

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom

**Comment by briankwest** [comment]
This is not the place for this.  Please join the mailing list or IRC
