### ISSUE TITLE
Use lua script to receive cdr report

### ISSUE THREAD

**Issue by freeeyes** [signalwire/freeswitch#660]
I tried to use lua script hook to receive the bill report from cdr, but it doesn't seem to work.
Can be set on call routing
`<action application = "set" data = "session_in_hangup_hook = true" />  
<action application = "set" data = "api_hangup_hook = lua a.lua $ {uuid}" />  `

But this is not a bill report

Is there any way to make Lua associated with the bill event?
thanks.

**Comment by briankwest** [comment]
We do not support doing billing in this manner, you'll need to review the CDR modules to do billing.
