### ISSUE TITLE
Allow to rewrite o= and and s= fields in SDP for mod_verto

### ISSUE THREAD

**Issue by enp** [signalwire/freeswitch#663]
Hi,

Please allow to rewrite o= and and s= fields in SDP in mod_verto in the same way as it was implemented in mod_sofile. Looks like this feature requires to uncomment line https://github.com/signalwire/freeswitch/blob/master/src/mod/endpoints/mod_verto/mod_verto.c#L2472

**Comment by mjerris** [comment]
i'd review a PR for this issue if you create one.
