### ISSUE TITLE
DTLS in windows version and ios 13.5

### ISSUE THREAD

**Issue by nick-grange** [signalwire/freeswitch#668]
Hi,

I am using FreeSWITCH 1.10.3 x64 on Windows. I get the following warning in the Freeswitch log when my client web application using SIP.js connects to FreeSWITCH from Safari ios 13.5

[WARNING] switch_rtp.c:3271 audio Handshake failure 1. This may happen when you use legacy DTLS v1.0 (legacyDTLS channel var is set) but endpoint requires DTLS v1.2.1
[INFO] switch_rtp.c:3272 Changing audio DTLS state from HANDSHAKE to FAIL

I'm assuming this is related to issue #517 ?

**Comment by nick-grange** [comment]
Hi,

Does anyone know when this maybe fixed, just upgraded to 1.10.4 but still getting this error?

2020-08-17 17:26:03.199937 [WARNING] switch_rtp.c:3275 audio Handshake failure 1. This may happen when you use legacy DTLS v1.0 (legacyDTLS channel var is set) but endpoint requires DTLS v1.2.
2020-08-17 17:26:03.199937 [INFO] switch_rtp.c:3276 Changing audio DTLS state from HANDSHAKE to FAIL

**Comment by eduardo-miller** [comment]
Hi,

Does anyone know when this maybe fixed?

**Comment by nick-grange** [comment]
Hi, 

I have no idea, i don't think anyone has even looked at it, i also don't know how you ask anyone too apart from logging it here...

**Comment by andywolk** [comment]
Please reopen the issue if the problem exists still.

**Comment by gregoriusus** [comment]
Hi!

Guys, can you roll out this update ASAP as google chrome requires DTLS 1.2 and verto is not working because of this. It's a big issue for anyone using windows installation.

**Comment by gbfarah** [comment]
Can we have this resolved.... Current windows installation does not support DTLS 1.2 ....

**Comment by sohneg** [comment]
Is there any fix?
