### ISSUE TITLE
Detecting speech during playback of multiple files

### ISSUE THREAD

**Issue by hheedfeld** [signalwire/freeswitch#669]
I use DETECT_SPEECH in JS called from dialplan as following:

`session.execute("set", "playback_delimiter=&");`
`var asrPrompt = "sounds/1.wav&silence_stream://500&sounds/2.wav&silence_stream://500&sounds/3.wav&silence_stream://3000";`
`session.execute("detect_speech", "unimrcp:local {start-input-timers=true,speech-language=DE-de}builtin:grammar/digits builtin");`
`var rc = session.streamFile(asrPrompt, onInput, DTMFmask);`
`session.execute("detect_speech", "stop");`
`return(rc);`

When the caller speaks during the change from one file playback to another, no event is fired but session.streamFile stops and returns 'false'. 

Is there any way to the achieve this issue?

**Comment by seven1240** [comment]
maybe `file_string://`

**Comment by hheedfeld** [comment]
good hint, will give it a try! Thank you.
