### ISSUE TITLE
freeswitch is not starting 

### ISSUE THREAD

**Issue by sudo-riyad** [signalwire/freeswitch#671]
When I try to restart freeswitch, I am getting error and its not starting. 

root@debian:/etc/systemd/system/multi-user.target.wants# systemctl restart freeswitch
Job for freeswitch.service failed because the control process exited with error code.
See "systemctl status freeswitch.service" and "journalctl -xe" for details.

root@debian:/etc/systemd/system/multi-user.target.wants# systemctl status freeswitch
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-06-03 10:55:30 CEST; 4min 8s ago
  Process: 2474 ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/log/freeswitch /etc/freeswitch /usr/share/freeswitch /var/run/freeswitch (code=exited, status=0/SUCCESS)
  Process: 2475 ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait ${DAEMON_OPTS} (code=exited, status=1/FAILURE)

Jun 03 10:55:29 debian freeswitch[2475]: FreeSWITCH[2475] Error starting system! pid:2476
Jun 03 10:55:29 debian systemd[1]: freeswitch.service: Control process exited, code=exited, status=1/FAILURE
Jun 03 10:55:29 debian systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Jun 03 10:55:29 debian systemd[1]: Failed to start freeswitch.
Jun 03 10:55:30 debian systemd[1]: freeswitch.service: Service RestartSec=100ms expired, scheduling restart.
Jun 03 10:55:30 debian systemd[1]: freeswitch.service: Scheduled restart job, restart counter is at 13.
Jun 03 10:55:30 debian systemd[1]: Stopped freeswitch.
Jun 03 10:55:30 debian systemd[1]: freeswitch.service: Start request repeated too quickly.
Jun 03 10:55:30 debian systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Jun 03 10:55:30 debian systemd[1]: Failed to start freeswitch.
~

 Can anyone help me to sort this out?

**Comment by mjerris** [comment]
you should check the logs or start freeswitch manually in the forground to see the errors.
