### ISSUE TITLE
Unable to bind AWS EC2 Public IP to WSS 7443 port for WebRTC

### ISSUE THREAD

**Issue by djl2** [signalwire/freeswitch#675]
Environment
EC2: Debian 9 Stretch
Network:  In public subnet with AWS EIP
FreeSWITCH Version 1.10.3-release-15-129de34d84~64bit
FusionPBX 4.5.14
EC2 is configured for public DNS and CA Cert is deployed.

I've spent a great deal of time attempting to get FreeSwitch/FusionPBX WebRTC working.  Currently, I'm able to send and answer video calls between SIPjs clients.  However, I'm only getting one-way audio at best (sometimes no audio).

Everything I read indicates one-way audio issues is typically a NAT issue. However, my EC2 instance is not behind NAT, it's in a public subnet with a public EIP/private IP.

To configure my EC2, I followed this AWS EC2 support page for guidance to force FS to use my AWS EIP (instead of Private IP).

https://freeswitch.org/confluence/display/FREESWITCH/Amazon+EC2. 
	
	<X-PRE-PROCESS cmd="set" data="bind_server_ip=[AWS EIP]"/>
	<X-PRE-PROCESS cmd="set" data="external_rtp_ip=[AWS EIP]"/>
	<X-PRE-PROCESS cmd="set" data="external_sip_ip=[AWS EIP]"/>

All the SIP ports are now correctly bound to the Public IP.

I then enabled WebRTC on the Internal profile--  wss-binding:  7443  	True	 

PROBLEM!
The problem appears to be that WSS port 7443 is bound to the EC2 Private IP address.  As I understand it, it should be bound to the Public IP.

How do I force FreeSwitch to bind WSS to the Public IP?

![FusionPBX-SIP-Status](https://user-images.githubusercontent.com/6354008/83824652-b4675000-a69c-11ea-8072-e8c71b892571.png)

More info

	- SSL Cert is configure for public DNS
	- We are not going through a Proxy.
	- We are not using Verto.
	- I've also disabled SIP ALG on my home router, as some docs have suggested.

Any further guidance or suggestions would greatly appreciated.  Thanks!  Darrell

**Comment by mjerris** [comment]
sip-ip is the configuration for the ip to bind to.
