### ISSUE TITLE
weird behaviour with tasks

### ISSUE THREAD

**Issue by descartin** [signalwire/freeswitch#676]
related to issues https://github.com/signalwire/freeswitch/issues/577 and https://github.com/signalwire/freeswitch/issues/575

it affects versions both 1.6.19 running in ubuntu 16 and 1.8.2 running in debian9

Dear all

we applied some weeks ago the patch

commit 6f2466eb35346c849144f01ce198bd617f0c4bef
Author: Chris Rienzo <chris@signalwire.com>
Date:   Mon Apr 22 17:10:46 2019 -0400

    FS-11801 [core] Update scheduler to allow destruction of running task
to see if the fsw was behaving ok, and we have been observing it during all these days. It has been ok and we have not seen the tasks increasing more then they should accoding to the sessions of the FSW, but we have experiencing twice that it seems the number of tasks (seen with 'show tasks' command) seems to get flat.
See a graph of its value
image
![image](https://user-images.githubusercontent.com/7767994/83902211-42eed680-a75c-11ea-995f-0e3e6fe528b9.png)

it got stuck at 22:50 gmt+2 may 22th
image
![image](https://user-images.githubusercontent.com/7767994/83902231-497d4e00-a75c-11ea-8c49-b3e4fb31a91c.png)

and some hours later we start to see that the fsw takes several seconds trying to schedule functions (we are using session:execute("sched_hangup","+" .. duration), and api:execute("sched_api","+" .. duration .. " none uuid_ring_ready " .. uuid)) and it actually cannot schedule them.

Could you please take a look or give us any clue about this issue to understand why this is happening?

thanks a lot and regards
david

**Comment by mjerris** [comment]
1.6 and 1.8 are EOL.  please see if this is an issue in latest releases and reopen if it is.

**Comment by descartin** [comment]
hello Mike

ok then please take a look at issue https://github.com/signalwire/freeswitch/issues/577
i tried to install 1.10.2 and seems i got a limit on the number of max sessions.

Besides, i would like you to understand that this issue is not easy to duplicate since affects live production systems and we don't know which scenario creates it. 
I'm trying to provide you all the information i can, i would need you to at least take a look and consider the issue, the versions affected are 1.6.19 Jul 13th 2017 commit and for 1.8.2 a Sep 26th 2018 commit. And the patch i think can be related to this is from Arpil 2019. I don't see any other commit related to tasks, scheduler, etc. Maybe there is but i could not see it.

We already tried a patch from 1.10 related to tasks deletion, but in the case issue of 577 was solved and we moved our production systems to 1.10, maybe when we finish the deployment the version installed is also EOL, so we will be again in the same situation.

regards
david
