### ISSUE TITLE
Support for AEAD_256_GCM

### ISSUE THREAD

**Issue by donileo** [signalwire/freeswitch#691]
I have a Cisco IP8861 phone that seems to implement `AEAD_256_GCM` fro SRTP crypto but not `AEAD_256_GCM_8 `which is what FS supports. When FS passes `AEAD_256_GCM_8` crypto fails to be negotiated. I believe these two crypto schemes are different given that in vars.xml the following is stated: 

```
 AEAD_AES_256_GCM_8
      ____________________________________________________________________________
      This algorithm is identical to AEAD_AES_256_GCM (see Section 5.2 of
      [RFC5116]), except that the tag length, t, is 8, and an
      authentication tag with a length of 8 octets (64 bits) is used.
      An AEAD_AES_256_GCM_8 ciphertext is exactly 8 octets longer than its
      corresponding plaintext.
```

Can support `AEAD_256_GCM` be added ? I'm thinking it shouldn't be too difficult given `AEAD_AES_256_GCM_8` is already supported?

**Comment by zandeez** [comment]
To expand (from my own testing) the Cisco 88XX Series with MPP firmware support two cyphers, AEAD_AES_256_GCM and AES_CM_128_HMAC_SHA1_80, you configure the preferred one in the settings. 

With encryption set to mandatory and set as AES 128 on the Cisco, outgoing calls from the device to FreeSWITCH work fine, but the other way does not, it appears the Cisco seems to think that AEAD_AES_256_GCM_8 and AEAD_AES_256_GCM are equivalent and sends back AEAD_AES_256_GCM in the SDP even though it wasn't in the invite from FreeSWITCH. 

Because of this, SRTP is effectively unusable on this series of devices.

**Comment by donileo** [comment]
> To expand (from my own testing) the Cisco 88XX Series with MPP firmware support two cyphers, AEAD_AES_256_GCM and AES_CM_128_HMAC_SHA1_80, you configure the preferred one in the settings.
> 
> With encryption set to mandatory and set as AES 128 on the Cisco, outgoing calls from the device to FreeSWITCH work fine, but the other way does not, it appears the Cisco seems to think that AEAD_AES_256_GCM_8 and AEAD_AES_256_GCM are equivalent and sends back AEAD_AES_256_GCM in the SDP even though it wasn't in the invite from FreeSWITCH.
> 
> Because of this, SRTP is effectively unusable on this series of devices.

Right on. I submitted an issue to the Cisco Community forums for this issue though no replies yet.  https://community.cisco.com/t5/ip-telephony-and-phones/ip-8861-srtp-issues-with-aes-256-gcm-8/td-p/4102733

**Comment by zandeez** [comment]
Hi Guys,

Sorry this isn't 100% resolved but the situation is much improved.

Calls initiated from the device complete correctly, calls initiated by FreeSWITCH have one-way audio (Cisco logs cite decryption errors)

I'm having a look through to see if I can work out what is going on here.

**Comment by donileo** [comment]
Yes I’m seeing the same issue with regards to the one way audio on calls initiated by FS.

**Comment by zandeez** [comment]
So I've gone back to matching with the space and putting the non _8 version first and have it working. This leads me to believe that the device is matching substrings just like FreeSWITCH. The logs don't tell me which offer the Cisco has accepted.

Given that we can't change the behaviour of the Cisco, the non _8 version is technically more secure and therefore should be preferred, and that having the space added in is a complete hack, we should look at tokenising the SDP lines instead or substring matching.
