### ISSUE TITLE
Issue with Port audio in raspberry pi 4 (debian buster)

### ISSUE THREAD

**Issue by sudo-riyad** [signalwire/freeswitch#700]
I have loaded mod_portaudio. But after that when after pa rescan the device, i found no device in the device list. While the pi is connected to a bluetooth speaker and also a headset with a aux cable and those are working fine in the system. 

Can anyone please help me to sort out this issue. 

Thanks

**Comment by mjerris** [comment]
you should work with the developers of portaudio on this issue
