### ISSUE TITLE
mod_rayo returns error on exec_conference_api

### ISSUE THREAD

**Issue by gsiehien** [signalwire/freeswitch#704]
When executing conference API command mod_rayo expects an answer to begin with "OK"

as you can see here:

[https://github.com/signalwire/freeswitch/blob/master/src/mod/event_handlers/mod_rayo/mod_rayo.c#L2216](https://github.com/signalwire/freeswitch/blob/master/src/mod/event_handlers/mod_rayo/mod_rayo.c#L2216)

Conference API changed some time ago and now returns "+OK" so mod_rayo fails with "protocol error".

**Comment by mjerris** [comment]
we’d be happy to review a PR to fix this issue
