### ISSUE TITLE
Some typo at the cli help

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#707]
Hi,
[root@node76 ~]# /home/freeswitch/bin/fs_cli
[ERROR] fs_cli.c:1691 main() Error Connecting []
Usage: /home/freeswitch/bin/fs_cli [-H <host>] [-P <port>] [-p <secret>] [-d <level>] [-x command] [-t <timeout_ms>] [profile]

  -?,-h --help                    Usage Information
...
  -t, --timeout                   Timeout for API commands (in miliseconds)
  -T, --connect-timeout           Timeout for socket connection (in miliseconds)
....
miliseconds should be milliseconds

Best

**Comment by mjerris** [comment]
we’d be happy to review a pull request with these changes

**Comment by ROBERT-MCDOWELL** [comment]
done! :D
