### ISSUE TITLE
issue  with the FreeSWITCH Version 1.10.3-release.5~64bit (-release.5 64bit)

### ISSUE THREAD

**Issue by meselek6** [signalwire/freeswitch#710]
Hello Team,

I have installed  freeswicth using the automatic  procedure on centos as below:

yum install -y https://files.freeswitch.org/repo/yum/centos-release/freeswitch-release-repo-0-1.noarch.rpm epel-release
yum install -y freeswitch-config-vanilla freeswitch-lang-* freeswitch-sounds-*
systemctl enable freeswitch

the installation is done successfully. the issue  that No Sofia  has been loaded. it means that the  sofia is not listening on sip port 5060.

Please  help  what I have  missed....

**Comment by mjerris** [comment]
this bug report contains no information to attempt to troubleshoot this issue
