### ISSUE TITLE
mod_opusfile: Makefile.am does not honor configure vars

### ISSUE THREAD

**Issue by jelmd** [signalwire/freeswitch#718]
Makefile.am for mod_opusfile is buggy: Does not "pick up" the configure results, i.e. configure finds libopusenc and enables it. However, the related *.c files are compiled without the proper flags and thus writing/recording opus files will fail with a generic error (and no log.error gets emitted explaining the problem =8-( ).

**Comment by mjerris** [comment]
we’d be happy to review a pull request for this issue
