### ISSUE TITLE
freeswitch HA

### ISSUE THREAD

**Issue by amitpaltech** [signalwire/freeswitch#723]
how FS can recover Ringing/Ringwait calls in HA mode

**Comment by amitpaltech** [comment]
how can achieve it

**Comment by seven1240** [comment]
recover probably mostly designed/working with calls already setup. for calls still in progress, it's find to dial again.

**Comment by amitpaltech** [comment]
> recover probably mostly designed/working with calls already setup. for calls still in progress, it's fine to dial again.

**Thanks Seven for your  response.**

I accept your words. but one of us major customer Required 'Call In Progress' HA.
and this is our urgent requirement. is any alternate mechanism to fulfill this requirement?
I have one more Issue in hold call recovery in HA.
In my present scenario when A dial to B and B hold the call and  we make fail over of FS. Then Held party did't recover.

these two scenario are major concern of us with customer perspective.

Can we get the solution around Free switch ASAP.

**Comment by amitpaltech** [comment]
Thanks Seven for your response.

I accept your words. but one of us major customer Required 'Call In Progress' HA.
and this is our urgent requirement. is any alternate mechanism to fulfill this requirement?
I have one more Issue in hold call recovery in HA.
In my present scenario when A dial to B and B hold the call and we make fail over of FS. Then Held party did't recover.

these two scenario are major concern of us with customer perspective.

Can we get the solution around Free switch ASAP.

**Comment by jungle-boogie** [comment]
See this confluence page:
https://freeswitch.org/confluence/display/FREESWITCH/High+Availability

**Comment by mjerris** [comment]
we do not recover those calls.
