### ISSUE TITLE
FreeSWITCH not passing any RTP to A Leg ($150 Bounty to get this mystery solved)

### ISSUE THREAD

**Issue by nbhatti** [signalwire/freeswitch#729]
Hello,

Call comes in from User-Agent -> Sippy Softswitch to local extension. Dialplan is to play delay_echo function. Call successfully connects, RTP starts flowing in from A-Leg but FreeSWITCH does not replies back with any RTP. I tried music on hold, bridged another registered extension etc.. I have tried this with FreeSWITCH Version 1.10.4-dev git 00113c4 and also with freeswitch-1.8.7 thinking maybe it's something to do with FreeSWITCH version but both versions exhibit the same. Both FreeSWITCH and UAC are on the same Public network there is no NAT in between, However the actual call scenario is something like this

Cisco Call Manager -> PRI to E1 Convertor -> Sippy Softswitch -> FreeSWITCH

Interestingly when I replace FreeSWITCH with Asterisk both default config, Audio works fine with Asterisk on the same server with same call scanario. This makes me think either something to do with FreeSWITCH config or I have no clue what's going on.

Log and configuration files are here: 
[FreeSWITCH logs and SIP trace](https://github.com/signalwire/freeswitch/files/4915022/v1_fs_v1.8.7.log)
[Asterisk SIP Trace only](https://github.com/signalwire/freeswitch/files/4915023/v1-asterisk-13.34.0.log)
[Sofia Config](https://github.com/signalwire/freeswitch/files/4915044/sofia.conf.txt)

The dialplan is as simple as

```
<extension name="local-delay-echo">
	<condition field="destination_number" expression="^73715050001110$">
		<action application="answer"/>
		<action application="delay_echo" data="5000"/>
	</condition>
</extension>
```
Appreciate support to get this resolved.

**Comment by mjerris** [comment]
these traces can not be reviewed due to them being edited to obscure important details.

**Comment by nbhatti** [comment]
Traces re-uploaded with no obscure info. It was only the IP address last few octets changed.
[FreeSWITCH logs and SIP trace](https://github.com/signalwire/freeswitch/files/4915340/v2_fs_v1.8.7.log)
[Asterisk SIP Trace only](https://github.com/signalwire/freeswitch/files/4915341/v2-asterisk-13.34.0.log)
[Sofia Config](https://github.com/signalwire/freeswitch/files/4915347/sofia.conf.log)

**Comment by nbhatti** [comment]
@mjerris traces uploaded again if you can re-open the issue.

Thanks.
