### ISSUE TITLE
FreeSWITCH not passing any RTP to A Leg ($150 Bounty to get this mystery solved)

### ISSUE THREAD

**Issue by nbhatti** [signalwire/freeswitch#730]
(With correct logs attached)

Hello,

Call comes in from User-Agent -> Sippy Softswitch to local extension. Dialplan is to play delay_echo function. Call successfully connects, RTP starts flowing in from A-Leg but FreeSWITCH does not replies back with any RTP. I tried music on hold, bridged another registered extension etc.. I have tried this with FreeSWITCH Version 1.10.4-dev git 00113c4 and also with freeswitch-1.8.7 thinking maybe it's something to do with FreeSWITCH version but both versions exhibit the same. Both FreeSWITCH and UAC are on the same Public network there is no NAT in between, However the actual call scenario is something like this

Cisco Call Manager -> PRI to E1 Convertor -> Sippy Softswitch -> FreeSWITCH

Interestingly when I replace FreeSWITCH with Asterisk both default config, Audio works fine with Asterisk on the same server with same call scenario. This makes me think either something to do with FreeSWITCH config or I have no clue what's going on.

Log and configuration files are here: 
[FreeSWITCH logs and SIP trace](https://github.com/signalwire/freeswitch/files/4915340/v2_fs_v1.8.7.log)
[Asterisk SIP Trace only](https://github.com/signalwire/freeswitch/files/4915341/v2-asterisk-13.34.0.log)
[Sofia Config](https://github.com/signalwire/freeswitch/files/4915347/sofia.conf.log)

The dialplan is as simple as

```
<extension name="local-delay-echo">
	<condition field="destination_number" expression="^73715050001110$">
		<action application="answer"/>
		<action application="delay_echo" data="5000"/>
	</condition>
</extension>
```
Appreciate support to get this resolved.

**Comment by mjerris** [comment]
toss a log on here from latest freeswitch release, calling to the playback application instead of delay echo, please turn off the sofia debug but leave the sip trace and enable media debug for the call.

**Comment by nbhatti** [comment]
New call from Version 1.10.4-dev git 677f14b with Playback audio file
```
<extension name="local-delay-echo">
    <condition field="destination_number" expression="^73715050001110$">
    <action application="log" data="INFO Inbound call CallUUID ${call_uuid} SIPCallID ${sip_call_id}- from ${caller_id_number} to ${destination_number}"/>
    <action application="playback" data="suite-espanola-op-47-leyenda.wav"/>
    </condition>
</extension>
```
[1545_1_Media_Trace.log](https://github.com/signalwire/freeswitch/files/4918448/1545_1_Media_Trace.log)
[1545_1_SIP_Trace.log](https://github.com/signalwire/freeswitch/files/4918449/1545_1_SIP_Trace.log)

**Comment by dragos-oancea** [comment]
you may have stun related issues:
W sofia/internal/04232152273@43.225.99.130 b= 332 43.225.99.155:25300 43.225.99.130:62256 0.0.0.0:0 pt=8 ts=105600 seq=50149 m=1

I don't think that " 0.0.0.0:0" is right. 

 T>>>T>>>T>>>switch_log_printf(SWITCH_CHANNEL_SESSION_LOG_CLEAN(rtp_session->session), SWITCH_LOG_CONSOLE,
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  "W %s b=%4ld %s:%u %s:%u %s:%u pt=%d ts=%u seq=%u m=%d\n",
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  rtp_session->session ? switch_channel_get_name(switch_core_session_get_channel(rtp_session->session)) :       "NoName",
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  (long) bytes,
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  my_host, switch_sockaddr_get_port(rtp_session->local_addr),
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  old_host, rtp_session->remote_port,
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  tx_host, switch_sockaddr_get_port(rtp_session->rtp_from_addr),
 T>>>T>>>T>>>T>>>T>>>T>>>T>>>  send_msg->header.pt, ntohl(send_msg->header.ts), ntohs(send_msg->header.seq), send_msg->header.m);

 tx_host, switch_sockaddr_get_port(rtp_session->rtp_from_addr) = 0.0.0.0:0 in your case, which is bad. Check your config.

**Comment by nbhatti** [comment]
yes I see that too, 0.0.0.0:0 is no host no port. When I register a phone on Sippyswitch and call FreeSWITCH (My SIP client behind double NAT), FreeSWITCH is happy to send/receive media, but only in the call logs above it refuses to work. 

Both FreeSWITCH and Sippyswitch are on public IP addresses and there is no NAT in between. However Sippyswitch handles NAT behind the scenes. As far as visibility goes FreeSWITCH (43.225.99.155) only sees and talks to Sippyswitch (43.225.99.130). I have tried with default vanilla config and the results are the same. I have tried a lot of params can you suggest which one in particular to look for?

**Comment by mjerris** [comment]
i was looking for a freeswitch debug log with sip trace and media debug all in the same file.

**Comment by mjerris** [comment]
but also what Dragos said.  Check your ext-rtp-ip config.  if you are not behind nat, remove that config.

**Comment by nbhatti** [comment]
I will remove ext-rtp-ip and test, but I already have rtp-ip set explicitly to the IP 43.225.99.155. Here is the 
[Combined log for the call earlier](https://github.com/signalwire/freeswitch/files/4927842/15-45-49.023656_freeswitch.log)

**Comment by nbhatti** [comment]
Could not find the root cause still yet, ended up running another Proxy in front of FS which handles this situation quite well. Closing this issue as unresolved.
