### ISSUE TITLE
Debain 10 fails to install

### ISSUE THREAD

**Issue by atuxnull** [signalwire/freeswitch#731]
Running a virtual machine with debian 10 x64 bit and i am trying to install Freeswitch (1.10) by following the instructions from the wiki. I have tried both methods and both failed:
### ** Install from Git**
```
root@debian: /etc/systemd/system $ systemctl start freeswitch
Failed to start freeswitch.service: Unit freeswitch.service is masked.
root@debian: /etc/systemd/system $
```
```
root@debian: /etc/systemd/system $ ll | grep freeswitch
lrwxrwxrwx 1 root root    9 Jul 16 09:07 freeswitch.service -> /dev/null
root@debian: /etc/systemd/system $
```

### **Install from deb repo**
```
root@debian: ~ $ service freeswitch stop
root@debian: ~ $ service freeswitch start
root@debian: ~ $ service freeswitch status
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-07-14 13:23:58 EEST; 6s ago
  Process: 813 ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait ${DAEMON_OPTS} (code=exited, status=0/S
  Process: 810 ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/log/freeswitch /etc/freeswitch
 Main PID: 814 (freeswitch)
    Tasks: 34 (limit: 4915)
   CGroup: /system.slice/freeswitch.service
           └─814 /usr/bin/freeswitch -u freeswitch -g freeswitch -ncwait -nonat

Jul 14 13:23:56 fsopen216 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jul 14 13:23:56 fsopen216 systemd[1]: Stopped freeswitch.
Jul 14 13:23:56 fsopen216 systemd[1]: Starting freeswitch...
Jul 14 13:23:56 fsopen216 freeswitch[813]: 814 Backgrounding.
Jul 14 13:23:58 fsopen216 freeswitch[813]: FreeSWITCH[813] Waiting for background process pid:814 to be ready.....
Jul 14 13:23:58 fsopen216 freeswitch[813]: FreeSWITCH[813] System Ready pid:814
Jul 14 13:23:58 fsopen216 systemd[1]: Started freeswitch.
lines 1-17/17 (END)
root@fsopen216: ~ $ fs_cli -rRS
[ERROR] fs_cli.c:1691 main() Error Connecting []
[INFO] fs_cli.c:1697 main() Retrying
[ERROR] fs_cli.c:1691 main() Error Connecting []
^CInterrupted.
root@debian: ~ $
```

Any ideas on how to fix those issues and have Freeswitch installed in my system please?

**Comment by matt9j** [comment]
I'm having a similar issue, but was able to debug a little further. Disabling the systemd service and running directly from the command line, I am able to see logging indicating a missing symbol in the mod_event_socket.so, which prevents the CLI from working even though the main freeswitch process is okay. 
`root@rccn:~# /usr/bin/freeswitch -u root -g freeswitch -c -nonat`

...

```
1:48:35.636534 [NOTICE] switch_loadable_module.c:412 Adding API Function 'console'
2020-07-17 01:48:35.637031 [CONSOLE] switch_loadable_module.c:1804 Successfully Loaded [mod_logfile]
2020-07-17 01:48:35.637751 [CONSOLE] switch_loadable_module.c:1804 Successfully Loaded [mod_cdr_pg_csv]
2020-07-17 01:48:35.638120 [CRIT] switch_loadable_module.c:1786 Error Loading module /usr/lib/freeswitch/mod/mod_event_socket.so
**/usr/lib/freeswitch/mod/mod_event_socket.so: undefined symbol: cJSON_AddNumberToObject**
```

**Comment by atuxnull** [comment]
Any update please?

**Comment by matt9j** [comment]
This problem still persists with the latest release 1.10.4 on debian 10. Additionally 1.10.4 breaks mod_sofia with undefined symbol `ntatag_srv_503`.

**Comment by matt9j** [comment]
@atuxnull it turns out that the way my image was built was pulling in an old version of libfreeswitch and libsofia-sip-ua0. If I install the latest version of freeswitch and its dependencies from the debian-release repo (see https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster), I am able to get freeswitch running and attach via fs_cli.

**Comment by atuxnull** [comment]
@matt9j  Thanks for the reply. i have done another attempt to install from debian-release repo and still i got the same issue.

**Comment by matt9j** [comment]
Maybe you have a different root cause error than I did? If you stop the systemd service, can you start freeswitch directly from the command line? If so, do you have any errors in the startup log? In my case I saw a missing symbol that prevented mod_event_socket from starting, which is needed to communicate with fs_cli.

**Comment by atuxnull** [comment]
@matt9j thanks for the reply. 
I did around 30 clean installs of Freeswitch in Debian 9 & 10(mainly) some through GIT while other through the debian-enabled repo. I did follow the installation instructions from the wiki, but FS failed to connect.
Keeping it short, i have tried a solution proposed from the FS users mailing list and it is to edit the event_socket.conf and change the parameter from     <param name="listen-ip" value="::"/> to     <param name="listen-ip" value="0.0.0.0"/>
Now everything seems to work fine.
In my honest opinion, I think this is something that needs to be either rectified in the installation script or either mention it to the wiki.

**Comment by matt9j** [comment]
Hmm, interesting. It does seem like the event_socket is more fragile than freeswitch core itself, and if the event socket fails to come up it's impossible to connect via the CLI. It might be nice in the future too if there was more logging to journald/syslog as freeswitch is starting to help debug event socket issues. Regardless I am glad you got it working!
