### ISSUE TITLE
ODBC on Freeswitch 1.10

### ISSUE THREAD

**Issue by leandronvoip** [signalwire/freeswitch#737]
Hi,

I am upgrading my system to freeswitch 1.10. I use ODBC for core with external database. I am using CENTOS 7 and MariaDB.

When I change switch.conf.xml with this parameters, the server freeswitch start but the console and modules don't load.
 <param name="core-db-dsn" value="odbc://database:user:password"/>

I already try activate on pre_load_modules.conf.xml the parameter without success.
<load module="mod_mariadb"/>

**Comment by andywolk** [comment]
You don't have to use ODBC anymore as there is `mod_mariadb` now with what FreeSWITCH is able to connect to MariaDB directly without the ODBC layer. Make sure `mod_mariadb` is enabled in `pre_load_modules.conf.xml` and `mariadb://` or `mysql://` prefix is used in `switch.conf.xml` instead of `odbc://`. Also, make sure `pre_load_modules.conf.xml` does have right file permissions like the other conf files.

**Comment by leandronvoip** [comment]
Hi.

thanks for the fast answers.
I check permission and are OK.
I enable mod_mariadb on pre_load_modules.conf.xml

I try use the follow parameters without success:
<param name="core-db-dsn" value="mariadb://**database:user:password**"/>
<param name="core-db-dsn" value="mysql://**database:user:password**"/>
<param name="core-db-dsn" value="mysql://hostaddr=127.0.0.1 dbname=**database** user=**user** password='**password**' options='-c client_min_messages=NOTICE'" /
<param name="core-db-dsn" value="mysql://127.0.0.1,dbname=**database**,user=**user**,password=**password**"/>
<param name="core-db-dsn" value="mysql://127.0.0.1;dbname=**database**;user=**user**;password=**password**"/>
<param name="core-db-dsn" value="mysql://127.0.0.1/**database**;user=**user**;password=**password**"/>
<param name="core-db-dsn" value="mariadb://Server=localhost;Database=**database**;Uid=**user**;Pwd=**password**;" />

Error on start freeswitch:
```
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2020-07-20 11:49:51 UTC; 15s ago
  Process: 1615 ExecReload=/usr/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 32504 ExecStart=/usr/bin/freeswitch -nc -nf $FREESWITCH_PARAMS (code=exited, status=255)
 Main PID: 32504 (code=exited, status=255)

Jul 20 11:49:34 ip-172-31-40-225.sa-east-1.compute.internal systemd[1]: Started FreeSWITCH.
Jul 20 11:49:34 ip-172-31-40-225.sa-east-1.compute.internal freeswitch[32504]: ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
Jul 20 11:49:34 ip-172-31-40-225.sa-east-1.compute.internal freeswitch[32504]: ERROR: Could not set nice level
Jul 20 11:49:51 ip-172-31-40-225.sa-east-1.compute.internal systemd[1]: freeswitch.service: main process exited, code=exited, status=255/n/a
Jul 20 11:49:51 ip-172-31-40-225.sa-east-1.compute.internal systemd[1]: Unit freeswitch.service entered failed state.
Jul 20 11:49:51 ip-172-31-40-225.sa-east-1.compute.internal systemd[1]: freeswitch.service failed.
```

**Comment by mjerris** [comment]
dont start freeswitch with systemd, run at the command line so you can see the errors that come out on the console.

**Comment by leandronvoip** [comment]
The mod_mariadb not are installed. I will install and if need I reopen a issue. You can close now. Thank you.
