### ISSUE TITLE
mod_conference If a person's net is not good, the whole canvas will be stuck ,   The entire canvas can be jammed by a single user to continue playing

### ISSUE THREAD

**Issue by yuexiajiayan** [signalwire/freeswitch#744]
When one person gets stuck, the whole canvas gets stuck. Other individuals can't just get stuck in the canvas without affecting it

need update mod_conference  conference_video.c?

**Comment by seven1240** [comment]
what means stuck? what's your FreeSWITCH version and OS ?

**Comment by yuexiajiayan** [comment]
If a person's net is not good, the whole canvas will be stuck. Can you let him get stuck without affecting the whole canvas
in debian9 fs1.10.3

**Comment by seven1240** [comment]
if a person's net is not good, it will failed to decode and show some no video avatar. I never see the whole canvas been stuck.

**Comment by yuexiajiayan** [comment]
> if a person's net is not good, it will failed to decode and show some no video avatar. I never see the whole canvas been stuck.

Thank you very much, Mr. Du. I limit the upload and download of 50kb / s on the router. Sometimes it gets stuck
