### ISSUE TITLE
How to Develop Modules

### ISSUE THREAD

**Issue by haeferer** [signalwire/freeswitch#748]
Hi, 

very nice work. I'am a great fan of freeswitch and the OS idea.

I think i need to start to build own modules. Is there a point to start from (i known some tutorials, but they
seem to be out of state, especialy the books :) ).

My first question would be the perfect Development Enviroment to develop modules (Eclips, etc. ) ? 
I believe debian is the best os to develop on ?

Thx for your ideas

Andreas

**Comment by seven1240** [comment]
core developers using emacs. I use vscode.

**Comment by crienzo** [comment]
There are many kinds of modules.  If you are just looking to add FreeSWITCH internal APIs and dialplan APPs, you can look at mod_commands and mod_dptools.  Those are the simplest types of modules to create.  There is also https://github.com/freeswitch/mod_mosquitto which shows how to make your module external to FreeSWITCH so you can install FreeSWITCH from packages and add your own modules from source.

**Comment by crienzo** [comment]
Also, any existing docs on writing modules should still be pretty accurate.  The interface to FS core hasn't changed much; we've only added a new database interface as of 1.10.

**Comment by haeferer** [comment]
> most core developers using emacs. I use vscode.

Ok, i'm also a great fan of vscode. I will try this. (debian would be best?)

**Comment by haeferer** [comment]
> There are many kinds of modules. If you are just looking to add FreeSWITCH internal APIs and dialplan APPs, you can look at mod_commands and mod_dptools. Those are the simplest types of modules to create. There is also https://github.com/freeswitch/mod_mosquitto which shows how to make your module external to FreeSWITCH so you can install FreeSWITCH from packages and add your own modules from source.

Ok, i wil start at mosquitto

Thx
