### ISSUE TITLE
mod_conference wants non existent pin when moderator enters

### ISSUE THREAD

**Issue by covici** [signalwire/freeswitch#753]
I have a conference whose profile includes (amoung other things) the following entries 
<param name="conference-flags" value="wait-mod" .  I tested with a member in the conference.  Now when I used another extension to enter the conference with flags{moderator|endconf} I get the message asking for a pin.  There is no pin in the conference.  Adding a moderator pin did not work either.  Nothing in the logsto give me any insight.

Running under Debian 10.

**Comment by mjerris** [comment]
incomplete bug report.

**Comment by covici** [comment]
What else do you need?

On Fri, 24 Jul 2020 12:32:35 -0400,
Michael Jerris wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> incomplete bug report.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/signalwire/freeswitch/issues/753#issuecomment-663624584
> [2  <text/html; UTF-8 (7bit)>]

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com
