### ISSUE TITLE
mod_conference: conference_api_sub_saymember returns -ERR every time

### ISSUE THREAD

**Issue by TelephonyMan** [signalwire/freeswitch#757]
The problem is very straight forward. The function conference_api_sub_saymember() returns an error message even when the function has succeeded. The direct link to the bug is [here](https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_conference/conference_api.c#L2953).

The correct code should be: 
	stream->write_function(stream, "+OK (saymember)\n");

**Comment by andywolk** [comment]
I will be happy to review your PR

**Comment by TelephonyMan** [comment]
My apologies. I mostly work with in-house git repos. I am unfamiliar with making changes to public repos. So I am new at this. 
I tried push a new branch, but I don't have access rights to push it. I am not sure what is the usual procedure.

**Comment by TelephonyMan** [comment]
1.10.6 fixes it.
