### ISSUE TITLE
originate_retry_sleep_ms with originate_retries not working 

### ISSUE THREAD

**Issue by sangeethkumarakkaraju** [signalwire/freeswitch#771]
Hello 
i am trying to  use originate_retries with originate_retry_sleep_ms using below  command and  i am facing issues 

this is working with 1 min retry 
bgapi originate {call_count_secs=10,campaign_id=4429,oid=231725,ignore_early_media=true,originate_timeout=30,originate_retries=2,originate_retry_sleep_ms=60000,caller_id_number=67695506,sip_from_uri=67695506@XXXX,effective_caller_id_number=67695506,origination_caller_id_number=67695506,url={"fees":"male;Eng;100;2020-06-13"}}sofia/external/9860276396@XXXX &lua(pupilMarkCreateCall.lua)

but same command if i set as  15mins  after retry 
it doesnot work 
bgapi originate {call_count_secs=10,campaign_id=4429,oid=231725,ignore_early_media=true,originate_timeout=30,originate_retries=2,originate_retry_sleep_ms=300000,caller_id_number=67695506,sip_from_uri=67695506@XXXX,effective_caller_id_number=67695506,origination_caller_id_number=67695506,url={"fees":"male;Eng;100;2020-06-13"}}sofia/external/9860276396@XXXX &lua(pupilMarkCreateCall.lua)

Please correct me 

Freeswitch version : FreeSWITCH Version 1.8.7+git~20190702T200609Z~6047ebddfc~64bit (git 6047ebd 2019-07-02 20:06:09Z 64bit)

Ubuntu
Linux localhost.localdomain 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

AME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

**Comment by briankwest** [comment]
1.8.7 is EOL retry this on the latest 1.10 please.

**Comment by sangeethkumarakkaraju** [comment]
@briankwest   May i know  how to update the freeswitch 1.8 to 1.10 

i had tried to  install 1.10 and i get the below error


git clone  https://github.com/signalwire/freeswitch.git
git checkout v1.10
./bootstrap -j
./configure 

and i see the error 
   **checking for spandsp >= 1.99... configure: error: no usable spandsp; please install spandsp devel package or equivalent**

**Comment by mjerris** [comment]
follow the install instructions on confluence to install needed dependencies.
