### ISSUE TITLE
certificate reload on HUP

### ISSUE THREAD

**Issue by sergey-safarov** [signalwire/freeswitch#775]
I want to change the certificate used by FreeSwitch without stopping the service.
To do this I expect to send `HUP` signal. After I expect to see the new certificate on new connections to `SIP`, `WebRTC`, `Verto` sockets.
Now FreeSwitch still uses certificate loaded on daemon start.

**Comment by mjerris** [comment]
happy to review patches to allow behavior like this.

**Comment by NotherGithubAccount** [comment]
Just to add to this: Certificates are now limited to one year. It'll be very difficult to upgrade the certificate on a busy server if a full restart is required.

**Comment by grahamstreet** [comment]
Has anyone make progress towards this goal of `reload wss.pem` on HUP?

**Comment by eliliam** [comment]
This was closed as complete, does that mean that it reloads on `HUP` signals? If so, is there any documentation about this?

**Comment by sergey-safarov** [comment]
We placed Kamailio proxy as frontend and cert reload now completed on Kamailio.
