### ISSUE TITLE
Freeswitch 1.10.3 crash 

### ISSUE THREAD

**Issue by mbodbg** [signalwire/freeswitch#777]
Freeswitch crashed after it was running a couple of days.

Linux fsprod3 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
FreeSWITCH Version 1.10.3-release-15-129de34d84~64bit (-release-15-129de34d84 64bit)
installed from debian packages

Find attached the backtrace.
[backtrace.log](https://github.com/signalwire/freeswitch/files/5036922/backtrace.log)

**Comment by andywolk** [comment]
You should update. This is fixed in FreeSWITCH v1.10.4 release.
See https://github.com/freeswitch/sofia-sip/commit/ad495cfbf87a54db99af2b4c225e4650156788e6#diff-727662d08426a79f9921c87546e1b8b4
