### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#779]
**Describe the bug**
checking for spandsp >= 1.99... configure: error: no usable spandsp; please install spandsp devel package or equivalent
make: *** [Makefile:1478: config.status] Error 1

last git today august 7th.

the problem is where is spandsp-devel sources or pacakge version 1.99?

**Comment by mjerris** [comment]
what os?  check the wiki install instructions for your os they are mostly updated now

**Comment by ROBERT-MCDOWELL** [comment]
Fedora 31 64bits, it's mostly CentOS like.
ok I go to the wiki and try again thanks

**Comment by ROBERT-MCDOWELL** [comment]
spandsp compiled well, sofia-sip not

Making all in su-glib
make[3]: Entering directory '/home/src/sofia-sip/libsofia-sip-ua-glib/su-glib'
         LTCOMPILE su_source.lo
su_source.c:191:3: warning: ‘GStaticMutex’ is deprecated: Use 'GMutex' instead [-Wdeprecat                                                                                                                                                    ed-declarations]
  191 |   GStaticMutex     sup_obtained[1];
      |   ^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:129:9: note: declared here
  129 | typedef struct
      |         ^~~~~~
su_source.c:193:3: warning: ‘GStaticMutex’ is deprecated: Use 'GMutex' instead [-Wdeprecat                                                                                                                                                    ed-declarations]
  193 |   GStaticMutex     sup_mutex[1];
      |   ^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:129:9: note: declared here
  129 | typedef struct
      |         ^~~~~~
su_source.c: In function ‘su_source_port_init’:
su_source.c:281:3: warning: ‘g_static_mutex_init’ is deprecated: Use 'g_mutex_init' instea                                                                                                                                                    d [-Wdeprecated-declarations]
  281 |   g_static_mutex_init(self->sup_obtained);
      |   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:146:9: note: declared here
  146 | void    g_static_mutex_init           (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~
su_source.c:283:3: warning: ‘g_static_mutex_init’ is deprecated: Use 'g_mutex_init' instea                                                                                                                                                    d [-Wdeprecated-declarations]
  283 |   g_static_mutex_init(self->sup_mutex);
      |   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:146:9: note: declared here
  146 | void    g_static_mutex_init           (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~
su_source.c: In function ‘su_source_port_deinit’:
su_source.c:293:3: warning: ‘g_static_mutex_free’ is deprecated: Use 'g_mutex_clear' inste                                                                                                                                                    ad [-Wdeprecated-declarations]
  293 |   g_static_mutex_free(self->sup_mutex);
      |   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:148:9: note: declared here
  148 | void    g_static_mutex_free           (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~
su_source.c:294:3: warning: ‘g_static_mutex_free’ is deprecated: Use 'g_mutex_clear' inste                                                                                                                                                    ad [-Wdeprecated-declarations]
  294 |   g_static_mutex_free(self->sup_obtained);
      |   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:148:9: note: declared here
  148 | void    g_static_mutex_free           (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~
In file included from ../../libsofia-sip-ua/su/su_module_debug.h:42,
                 from ../../libsofia-sip-ua/su/su_port.h:49,
                 from su_source.c:64:
su_source.c: In function ‘su_source_finalize’:
../../libsofia-sip-ua/su/sofia-sip/su_log.h:104:104: error: expected expression before ‘)’                                                                                                                                                     token
  104 | #define su_llog(_l, _ll, _f, ...) _su_llog(_l, _ll, __FILE__, __SOFIA_FUNC__, __LI                                                                                                                                                    NE__, _f, __VA_ARGS__)
      |                                                                                                                                                                                                                                                            ^
../../libsofia-sip-ua/su/sofia-sip/su_debug.h:209:29: note: in expansion of macro ‘su_llog                                                                                                                                                    ’
  209 | #define su_debug_9(_f, ...) su_llog(SU_LOG, 9, _f, __VA_ARGS__)
      |                             ^~~~~~~
../../libsofia-sip-ua/su/sofia-sip/su_debug.h:217:45: note: in expansion of macro ‘su_debu                                                                                                                                                    g_9’
  217 | #define SU_DEBUG_9(x) (SU_LOG_LEVEL >= 9 ? (su_debug_9 x) : (void)0)
      |                                             ^~~~~~~~~~
su_source.c:317:3: note: in expansion of macro ‘SU_DEBUG_9’
  317 |   SU_DEBUG_9(("su_source_finalize() called\n"));
      |   ^~~~~~~~~~
su_source.c: In function ‘su_source_thread’:
su_source.c:360:13: warning: Deprecated pre-processor symbol
  360 |     g_static_mutex_unlock(self->sup_obtained);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:360:5: warning: ‘g_static_mutex_get_mutex_impl’ is deprecated: Use 'GMutex' in                                                                                                                                                    stead [-Wdeprecated-declarations]
  360 |     g_static_mutex_unlock(self->sup_obtained);
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:150:9: note: declared here
  150 | GMutex *g_static_mutex_get_mutex_impl (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:360:13: warning: g_mutex_unlock
  360 |     g_static_mutex_unlock(self->sup_obtained);
      |             ^~~~~~~~~~~~~~~~
su_source.c:366:13: warning: Deprecated pre-processor symbol
  366 |     g_static_mutex_lock(self->sup_obtained);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:366:5: warning: ‘g_static_mutex_get_mutex_impl’ is deprecated: Use 'GMutex' in                                                                                                                                                    stead [-Wdeprecated-declarations]
  366 |     g_static_mutex_lock(self->sup_obtained);
      |     ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:150:9: note: declared here
  150 | GMutex *g_static_mutex_get_mutex_impl (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:366:13: warning: g_mutex_lock
  366 |     g_static_mutex_lock(self->sup_obtained);
      |             ^~~~~~~~~~~~~~
su_source.c: In function ‘su_source_prepare’:
su_source.c:397:5: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecate                                                                                                                                                    d-declarations]
  397 |     GTimeVal  gtimeval;
      |     ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/gtypes.h:551:8: note: declared here
  551 | struct _GTimeVal
      |        ^~~~~~~~~
su_source.c:399:5: warning: ‘g_source_get_current_time’ is deprecated: Use 'g_source_get_t                                                                                                                                                    ime' instead [-Wdeprecated-declarations]
  399 |     g_source_get_current_time(gs, &gtimeval);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/giochannel.h:33,
                 from /usr/include/glib-2.0/glib.h:54,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/gmain.h:549:10: note: declared here
  549 | void     g_source_get_current_time (GSource        *source,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c: In function ‘su_source_dispatch’:
su_source.c:463:5: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecate                                                                                                                                                    d-declarations]
  463 |     GTimeVal  gtimeval;
      |     ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/gtypes.h:551:8: note: declared here
  551 | struct _GTimeVal
      |        ^~~~~~~~~
su_source.c:468:5: warning: ‘g_source_get_current_time’ is deprecated: Use 'g_source_get_t                                                                                                                                                    ime' instead [-Wdeprecated-declarations]
  468 |     g_source_get_current_time(gs, &gtimeval);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/giochannel.h:33,
                 from /usr/include/glib-2.0/glib.h:54,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/gmain.h:549:10: note: declared here
  549 | void     g_source_get_current_time (GSource        *source,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c: In function ‘su_source_lock’:
su_source.c:508:13: warning: Deprecated pre-processor symbol
  508 |   g_static_mutex_lock(self->sup_mutex);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:508:3: warning: ‘g_static_mutex_get_mutex_impl’ is deprecated: Use 'GMutex' in                                                                                                                                                    stead [-Wdeprecated-declarations]
  508 |   g_static_mutex_lock(self->sup_mutex);
      |   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:150:9: note: declared here
  150 | GMutex *g_static_mutex_get_mutex_impl (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:508:13: warning: g_mutex_lock
  508 |   g_static_mutex_lock(self->sup_mutex);
      |             ^~~~~~~~~~~~~~
su_source.c: In function ‘su_source_unlock’:
su_source.c:516:13: warning: Deprecated pre-processor symbol
  516 |   g_static_mutex_unlock(self->sup_mutex);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:516:3: warning: ‘g_static_mutex_get_mutex_impl’ is deprecated: Use 'GMutex' in                                                                                                                                                    stead [-Wdeprecated-declarations]
  516 |   g_static_mutex_unlock(self->sup_mutex);
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:110,
                 from su_source.c:46:
/usr/include/glib-2.0/glib/deprecated/gthread.h:150:9: note: declared here
  150 | GMutex *g_static_mutex_get_mutex_impl (GStaticMutex *mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
su_source.c:516:13: warning: g_mutex_unlock
  516 |   g_static_mutex_unlock(self->sup_mutex);
      |             ^~~~~~~~~~~~~~~~
In file included from ../../libsofia-sip-ua/su/su_module_debug.h:42,
                 from ../../libsofia-sip-ua/su/su_port.h:49,
                 from su_source.c:64:
su_source.c: In function ‘su_source_port_create’:
../../libsofia-sip-ua/su/sofia-sip/su_log.h:104:104: error: expected expression before ‘)’                                                                                                                                                     token
  104 | #define su_llog(_l, _ll, _f, ...) _su_llog(_l, _ll, __FILE__, __SOFIA_FUNC__, __LI                                                                                                                                                    NE__, _f, __VA_ARGS__)
      |                                                                                                                                                                                                                                                            ^
../../libsofia-sip-ua/su/sofia-sip/su_debug.h:209:29: note: in expansion of macro ‘su_llog                                                                                                                                                    ’
  209 | #define su_debug_9(_f, ...) su_llog(SU_LOG, 9, _f, __VA_ARGS__)
      |                             ^~~~~~~
../../libsofia-sip-ua/su/sofia-sip/su_debug.h:217:45: note: in expansion of macro ‘su_debu                                                                                                                                                    g_9’
  217 | #define SU_DEBUG_9(x) (SU_LOG_LEVEL >= 9 ? (su_debug_9 x) : (void)0)
      |                                             ^~~~~~~~~~
su_source.c:1087:3: note: in expansion of macro ‘SU_DEBUG_9’
 1087 |   SU_DEBUG_9(("su_source_port_create() called\n"));
      |   ^~~~~~~~~~
make[3]: *** [Makefile:1387: su_source.lo] Error 1
make[3]: Leaving directory '/home/src/sofia-sip/libsofia-sip-ua-glib/su-glib'
make[2]: *** [Makefile:581: all-recursive] Error 1
make[2]: Leaving directory '/home/src/sofia-sip/libsofia-sip-ua-glib'
make[1]: *** [Makefile:504: all-recursive] Error 1
make[1]: Leaving directory '/home/src/sofia-sip'
make: *** [Makefile:425: all] Error 2

**Comment by andywolk** [comment]
Try using `./configure.gnu` for sofia when you configure

**Comment by ROBERT-MCDOWELL** [comment]
bingo! is it a bug or should I keep in mind to not forget to run ./configure.gnu in the future?

**Comment by ROBERT-MCDOWELL** [comment]
After compiled everything and install FS, systemctl gives an error:

Aug 08 12:21:45 node76 freeswitch[42848]: /usr/local/freeswitch/bin/freeswitch: error while loading shared libraries: libspandsp.so.6: cannot open shared object file: No such file or directory

**Comment by ROBERT-MCDOWELL** [comment]
ok libspandsp.so error fixed, I had to run ldconfig again.

**Comment by xbipin** [comment]
im facing same issue on raspberry pi, i installed libspandsp-dev libsofia-sip-ua-dev but still i get configure: error: no usable spandsp; please install spandsp devel package or equivalent

**Comment by johnnybubonic** [comment]
Same here. As far as I'm able to tell, the last release of [spandsp](https://www.soft-switch.org/) was in 2012, [version 0.0.6](https://www.soft-switch.org/downloads/). Where is there a "1.99" version of spandsp?

**Comment by ROBERT-MCDOWELL** [comment]
https://github.com/freeswitch/sofia-sip
https://github.com/freeswitch/spandsp

**Comment by xbipin** [comment]
> 
> 
> https://github.com/freeswitch/sofia-sip
> https://github.com/freeswitch/spandsp

i git cloned those to the /usr/local/src/freeswitch/libs directory but still it complains cant find spandsp

**Comment by xbipin** [comment]
ok i finally managed to get it to work, had to git clone sofia-sip and spandsp, then bootstrap, config, make, make install and ildconfig both of those then run the normal freeswitch bootstrap, config, make and make install after which everything works fine on both debian stretch and buster on the raspberry pi

**Comment by harishruparel** [comment]
Facing same error on Ubuntu 18.04:
downloaded freeswitch-1.10.4.-release and installed from there..
checking for spandsp >= 1.99... configure: error: no usable spandsp; please install spandsp devel package or equivalent
Please provide solution.

**Comment by harishruparel** [comment]
Also error:
checking for sofia-sip-ua >= 1.12.12... configure: error: no usable sofia-sip; please install sofia-sip-ua devel package or equivalent

**Comment by mjerris** [comment]
if you are finding this issue and still having problems please read the comments on this issue for resolution.

you need to either install new packages for these libraries as detailed in our install docs or download/compile/build the following:

https://github.com/freeswitch/sofia-sip
https://github.com/freeswitch/spandsp

**Comment by ghenry** [comment]
Hi all,

I'm stuck on this too after install spandsp from that repo. Looking at `configure.ac`is seems it's looking for `pkg-config` but that doesn't come with the source build:

https://github.com/signalwire/freeswitch/blame/65d0665a95daf1b030d8dc24d5838305403a2c57/configure.ac#L723

Any way round this?

Thanks.

**Comment by ghenry** [comment]
So I ended up building the spandsp rpm on my Fedora 34:

```
rpmdev-setuptree
sudo bash yum-prepare.sh 
rpmbuild -ba spandsp.spec 
sudo rpm -i /home/ghenry/rpmbuild/RPMS/x86_64/spandsp3-*
```

and the same for sofia-sip:

```
Wrote: /home/ghenry/rpmbuild/SRPMS/sofia-sip-1.13.4-1.fc34.src.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-glib-devel-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-glib-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-glib-debuginfo-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-utils-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-utils-debuginfo-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-devel-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-debuginfo-1.13.4-1.fc34.x86_64.rpm
Wrote: /home/ghenry/rpmbuild/RPMS/x86_64/sofia-sip-debugsource-1.13.4-1.fc34.x86_64.rpm
```

but I had to patch the sofia-sip.spec:

```
diff --git a/sofia-sip.spec b/sofia-sip.spec
index 5ea1a52..62d6714 100644
--- a/sofia-sip.spec
+++ b/sofia-sip.spec
@@ -58,7 +58,7 @@ Requires:       sofia-sip = %{version}-%{release}
 Command line utilities for the Sofia SIP UA library.
 
 %prep
-%setup0 -q -n sofia-sip-%{version}%{?work:work%{work}}
+%setup0 -q -n sofia-sip
```

All building now and found by pkg-config.

Thanks.

**Comment by ghenry** [comment]
Argghhh:

```
  CC       src/libfreeswitch_la-switch_core_media.lo
src/switch_core_media.c:2225:111: error: argument 2 of type ‘switch_core_media_flag_t[15]’ with mismatched bound [-Werror=array-parameter=]
 2225 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[SCMF_MAX])
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ./src/include/switch.h:143,
                 from src/switch_core_media.c:33:
./src/include/switch_core_media.h:200:111: note: previously declared as ‘switch_core_media_flag_t[]’
  200 | SWITCH_DECLARE(void) switch_media_handle_set_media_flags(switch_media_handle_t *smh, switch_core_media_flag_t flags[]);
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2471: src/libfreeswitch_la-switch_core_media.lo] Error 1

```

**Comment by ghenry** [comment]
Maybe I shouldn't be on master :-)

**Comment by ghenry** [comment]
Same on v1.10, so must be my system. Apologies for the noise.

**Comment by ROBERT-MCDOWELL** [comment]
this happens when you have ffmpeg 4.4 libs which apparently are too new for FS.
I had to reinstall ffmpeg 4.3.2 libs to make it compile again.

**Comment by ghenry** [comment]
Is that not a configure issue then?

**Comment by ROBERT-MCDOWELL** [comment]
no

**Comment by ghenry** [comment]
Hi,

I'd like to learn what this error has to do with ffmpeg. If you have the time to explain, I'd love to learn.

Thanks,
Gavin.

**Comment by ROBERT-MCDOWELL** [comment]
mod_av depends on ffmpeg libs

**Comment by ghenry** [comment]
Thanks. I meant more low level. Why, at compile time:

src/switch_core_media.c:2225:111: error: argument 2 of type
‘switch_core_media_flag_t[15]’ with mismatched bound
[-Werror=array-parameter=]

switch_core_media_flag_t is an enum.
