### ISSUE TITLE
Why Freeswitch Allocate Big Memory but Really use very small

### ISSUE THREAD

**Issue by TechGuyVN** [signalwire/freeswitch#780]
**Describe the bug**
My System using Freeswitch to make call, i notice about 4 5 days, freeswitch will allocation 90% memory ( VIRT in Top command) but really use very Small about 30% Memory. At this time, just with few calls were made.

**To Reproduce**
Let's Freeswitch run 4-5day, and using Top command to look 

**My question:**
Why Freeswitch Allocate so much memory ?
How can i free the memory FS Allocated, and how can i Avoid it ?

**Comment by crienzo** [comment]
Be only concerned about RES memory.  This is how FS works.

**Comment by TechGuyVN** [comment]
hi @crienzo , thanks for your answer, i noticed that when have 0 call a long time but FS still allocated a huge memory cause many call before get thought,  when i restart freeswitch , everything ok, memory release, can i free the memory freeswitch allocated but no use ?
