### ISSUE TITLE
Freeswitch 1.8.7 crashes randomly with empty core dump on centos 7.2 Kernel 5.1.0

### ISSUE THREAD

**Issue by sagarmalam** [signalwire/freeswitch#79]
FreeSWITCH crashes randomly with empty core dump. Not reproducible manually. Please find attached core dump and dmesg output

[dmesg.txt](https://github.com/signalwire/freeswitch/files/3774586/dmesg.txt)
[core.13183.txt](https://github.com/signalwire/freeswitch/files/3774587/core.13183.txt)

Freeswitch is running with root user.I have also check ulimits : 
[root@freeswitch-3-1 freeswitch]# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048500
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) unlimited
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

I understand that FS 1.10 is released hence i dont expect fix from FS developers but please if you can provide me some hint or direction on how to debug it further.

Thanks in advance for help and attention.

**Comment by mjerris** [comment]
There is no symbol info in that backtrace so it is impossible to tell with the supplied info.  I am going to close this issue but please re-open if you can install symbol data and re-run a backtrace with those installed

**Comment by sagarmalam** [comment]
Thanks for Reply.
Can you please help me how to install symbol data and re run backtrace ? 
Also did you took a look at dmesg, does it have any leads ?
