### ISSUE TITLE
Can't set cid_type to pid

### ISSUE THREAD

**Issue by zek** [signalwire/freeswitch#807]
**Package version or git hash**
 - Version master

**Describe the bug**

I'm trying to use cid_type for custom extensions (which is not bridged to any user). 

I defined following param in profile and FS sends `P-Asserted-Identity` on bridged calls.

```
        <param name="caller-id-type" value="pid"/>
```

However this is not working for non-bridged calls e.g. an extension with simple `queue` application.

I've debugged a bit and `tech_pvt->cid_type` is always 0. Probably we're not setting it from `caller-id-type` or `sip_cid_type` therefore it just uses default value which is `rpid`.

https://github.com/signalwire/freeswitch/blob/master/src/mod/endpoints/mod_sofia/mod_sofia.c#L257

**Comment by mjerris** [comment]
happy to review PR's to address this

**Comment by zek** [comment]
@mjerris okay I've created a PR please take a look at it.

**Comment by zek** [comment]
As you can see from the picture, FS sends `P-Asserted-Identity` after this change.

![image](https://user-images.githubusercontent.com/3463291/90556250-41507e80-e1a1-11ea-9494-f1b2ba537ac5.png)
