### ISSUE TITLE
Freeswitch 1.10.5 crash

### ISSUE THREAD

**Issue by mbodbg** [signalwire/freeswitch#814]
[backtrace.log.zip](https://github.com/signalwire/freeswitch/files/5107654/backtrace.log.zip)
**Describe the bug**
Freeswitch 1.10.5 crashed 

**To Reproduce**
FS was running about one day with 40-80 channels parallel
[backtrace.log](https://github.com/signalwire/freeswitch/files/5107642/backtrace.log)

**Expected behavior**
No crash

**Package version or git hash**
FreeSWITCH Version 1.10.5-release-17-25569c1631~64bit (-release-17-25569c1631 64bit)
Linux fsprod3 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

**Trace logs**
N/A

**backtrace from core file**

[backtrace.log.zip](https://github.com/signalwire/freeswitch/files/5107666/backtrace.log.zip)

**Comment by tinpotnick** [comment]
Hi, was this resolved?

**Comment by andywolk** [comment]
@mbodbg Do you have IPv6 in your setup?

**Comment by andywolk** [comment]
I believe it's fixed. See https://github.com/freeswitch/sofia-sip/pull/123
Reopen if the issue exists still.
