### ISSUE TITLE
autoconf not found. You need autoconf version 2.59 or newer installed

### ISSUE THREAD

**Issue by ontur00** [signalwire/freeswitch#828]
A use Debian 10

console
root@tsFsDebian:/usr/local/src/# git clone https://github.com/signalwire/freeswitch.git
root@tsFsDebian:/usr/local/src/# cd /freeswitch
root@tsFsDebian:/usr/local/src/freeswitch# ./bootstrap.sh
bootstrap: checking installation...
bootstrap: **autoconf not found.
           You need autoconf version 2.59 or newer installed
           to build FreeSWITCH from source.**

Why this is not working ?

**Comment by andywolk** [comment]
Make sure you have everything to start building.
https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster
