### ISSUE TITLE
PostgreSQL in the core. Script do not create table

### ISSUE THREAD

**Issue by ontur00** [signalwire/freeswitch#829]
I am using manual of using postgres at freeswitch : https://freeswitch.org/confluence/display/FREESWITCH/PostgreSQL+in+the+core

I am using Centos 7
Type at console:
yum install libpq-devel
cd /usr/local/src
git clone https://github.com/signalwire/freeswitch.git
cd freeswitch
./bootstrap.sh
./configure --enable-core-pgsql-support

and after script i check if there are any new tables at postgres look like at the site
![image](https://user-images.githubusercontent.com/11216422/91568560-c5df9180-e945-11ea-851a-837af85967b9.png)

[root@localhost freeswitch]# su - postgres
-bash-4.2$ psql -U postgres

postgres-# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

postgres=# \dt
Did not find any relations.

I have questi do i need create this manul or there is another script to create db user table ?

**Comment by andywolk** [comment]
`--enable-core-pgsql-support` configure flag is obsolete. Tables are created on the fly when FreeSWITCH starts for the first time.

**Comment by ontur00** [comment]
So how can i check the postgres tables created.

[root@localhost freeswitch]# fs_cli -rRS
Or maybe another question i need to create cluster HA where i can find proper manual ?
