### ISSUE TITLE
Add verto_punt API command

### ISSUE THREAD

**Issue by tessercat** [signalwire/freeswitch#832]
I'd like to be able to punt verto connections based on sessid.

The `verto_punt` command should take a sessid as input and do basically what `attach_jsock` does when a new jsock with the same `uuid_str` is already attached: send a `verto.punt` message to the jsock, print a warning log, delete the jsock from `jsock_hash` and set `nodelete` and `drop` on the jsock so its thread can clean it up.

I don't know what the command should return, but my patch returns the sessid of the punted jsock on success, nothing otherwise. (I noticed that if the function doesn't write anything to the `SWITCH_STANDARD_API` stream, the command doesn't seem to exist, though it works as intended.)

I've attached a git diff patch for discussion based on `mod_verto.c` from FreeSWITCH 1.10.5. If this gets noticed and gets some feedback, I can submit a pull request for review.

[punt.diff.gz](https://github.com/signalwire/freeswitch/files/5143467/punt.diff.gz)

**Comment by tessercat** [comment]
I've been looking more closely at punting sessions, and I've discovered that it's possible to log in without supplying a sessid at all, so this feature request makes sense only if `check_auth` also checks for the existence of sessid along with login/passwd.

Was the original intention of the verto module to allow multiple registration by default, or was it an oversight? The module punts the old client when a new client logs in with the same login, passwd and sessid, but the module allows login with no sessid, and there's no limit on the number of clients that can log in with the same login/passwd but different sessids. Feature or bug, I can't figure it out, but if I want to provide a service that delivers per-session login/passwd to a JavaScript client either in the web page that serves the JavaScript client or in a separate request, the current system seems open to misuse, an issue also raised in #571.

**Comment by mjerris** [comment]
yes you can login multiple times with same creds,but not with the same sessionid as thats how you do call recovery on client side, by design.  if you'd like a path reviewed please create a pull request for it.
