### ISSUE TITLE
Carrier-Grade NAT (RFC 6598) addresses should be treated as NAT addresses

### ISSUE THREAD

**Issue by BrentBaccala** [signalwire/freeswitch#834]
I've running FreeSWITCH 1.10.4-dev+git~20200515T214527Z~e1f63ce5b1~64bit. which is the current version in the bigbluebutton Ubuntu repository.

Most devices can connect to my IPv4-only server, but my Verizon cell phone can not.

This seems to be due to the phone using an IP address from the 100.64.0.0/10 block, reserved in RFC 6598 for Carrier-Grade NAT.  These addresses are private to the telcos and should probably be treated just as we'd treat other NAT addresses.

So, that means that 100.64.0.0/10 is missing from "wan.auto", "wan_v4.auto" and "nat.auto".  A case can also be made for adding an "rfc6598.auto", since there's already an "rfc1918.auto".

I fixed this locally by creating an XML list to replace "wan_v4.auto", but this block of addresses should probably be added to all of the mentioned lists in switch_core.c.

**Comment by mjerris** [comment]
feel free to make a PR to address this issue for review.
