### ISSUE TITLE
webrtc on google chrome vs 85 stop working with FS

### ISSUE THREAD

**Issue by erezl** [signalwire/freeswitch#838]
Hi
We have a problem with making webrtc calls to freeswitch since google updated Chrome to version 85.
It seems that chrome is only supproting DTLSv1.2, and for some reason, FS (vs 1.10.5) is not.
that the error from FS log:
2020-09-01 13:46:42.430640 [WARNING] switch_rtp.c:3271 audio Handshake failure 1. This may happen when you use legacy DTLS v1.0 (legacyDTLS channel var is set) but endpoint requires DTLS v1.2.

Best regards
Erez Lavie

**Comment by cdosoftei** [comment]
@erezl -- you can try #835, it's addressing the root of the problem.

Alternatively, you can remove/rename your `dtls-srtp.pem` file as FreeSWITCH will regenerate it with an appropriate version; you can typically find the said file in your FreeSWITCH configuration directory under `certs/` or `tls/`.

**Comment by melekoktay** [comment]
We got similar issue on **Debian 8**. You can use Debian 9 or 10 instead.

**If you use Debian 8**
If you could not update Debian 8 , You could generate "**dtls-srtp.pem**" on Debian 9 and move this file to your Debian 8 !

or 

Create self-signed certificate yourself and replace it with your "**dtls-srtp.pem**" file
