### ISSUE TITLE
mod_janus

### ISSUE THREAD

**Issue by daniel-lucio** [signalwire/freeswitch#84]
I see reference in the confluence, but where it is? I don't find it.

**Comment by crienzo** [comment]
The link in confluence is accurate.

**Comment by jungle-boogie** [comment]
For completeness, this is the link to Confluence:
https://freeswitch.org/confluence/display/FREESWITCH/mod_janus

**Comment by daniel-lucio** [comment]
https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1695/diff

**Comment by saurik** [comment]
Is the status of this being in the form of a pull request still current? (As far as I can tell I can't access that Stash link as it seems to be behind some kind of BitBucket enterprise account management?)

**Comment by richardscreene** [comment]
I was the original author of this module at my previous company.  The freeswitch repo moved from bitbucket to GitHub which probably explains why the PR is no longer accessible.   One of the nice freeswitch Devs should be able to help....

**Comment by luke-harris** [comment]
I've found myself in need of the janus module and have written a script that will create a full build with the janus module enabled.

An account can be created to access the old repositories here:
https://freeswitch.org/jira

[build_fs_with_janus.sh.gz](https://github.com/signalwire/freeswitch/files/4624891/build_fs_with_janus.sh.gz)

**Comment by crienzo** [comment]
If anybody wants to maintain the module, we can host it in github.com/freeswitch/mod_janus.  modules.conf can link to out of tree modules.

**Comment by richardscreene** [comment]
OK, @crienzo I'll maintain it!  What do I have to do?  My email is rscreeneATyahooDOTcoDOTuk

**Comment by crienzo** [comment]
@richardscreene make a github repo w/ mod_janus as an external module.  You can follow github.com/freeswitch/mod_mosquitto as an example.  Once it's all set up, let us know and we can clone it to the freeswitch org and set you up as maintainer.

**Comment by richardscreene** [comment]
@crienzo Is the outoftree code working?  I ask because when I try to load the mod_mosquitto code I get:
```
freeswitch@Richards-MBP> load mod_mosquitto
2020-08-11 16:51:25.042303 [INFO] switch_stun.c:897 External ip address detected using STUN: 31.48.149.61
2020-08-11 16:51:25.132269 [INFO] switch_stun.c:897 External ip address detected using STUN: 31.48.149.61
2020-08-11 16:51:25.312244 [INFO] mod_enum.c:884 ENUM Reloaded
2020-08-11 16:51:25.312244 [INFO] switch_time.c:1430 Timezone reloaded 1750 definitions
2020-08-11 16:51:25.322254 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/local/freeswitch/mod/mod_mosquitto.so
**dlopen(/usr/local/freeswitch/mod/mod_mosquitto.so, 6): Symbol not found: _event_handler
  Referenced from: /usr/local/freeswitch/mod/mod_mosquitto.so
  Expected in: flat namespace
 in /usr/local/freeswitch/mod/mod_mosquitto.so**

+OK Reloading XML
-ERR [module load file routine returned an error]
```

It would appear that only the mod_mosquitto.c file is compiled.  The other .c files are not.  My mod_janus repo (https://github.com/richardscreene/mod_janus) is showing similar behaviour.

Has it worked for anyone else or is it likely that I'm doing something wrong??

**Comment by mjerris** [comment]
I haven't tried it on osx.  it should work.

**Comment by richardscreene** [comment]
@crienzo I've put it all in this repo https://github.com/richardscreene/mod_janus
(The build problem I had was becuase I did not have openssl-dev installed.  It did give me a warning and then proceeded to carry on despite not creating the makefile.  I didn't even need openssl!!)

**Comment by richardscreene** [comment]
@luke-harris Its good to know that someone is making use of it!

I have included the changes that you made:
janus-room-pin is still present.  It is also now used when creating a room to set the PIN.
There is an additional channel variable janus-user-token that is used when setting the user's token on joining (no method is provided to set the allowed tokens in the create room request).
An additional per-server config item auth-token may be set which is appended to the polling query string.

These are all described in the README.

I apologise that you'll have to modify your configuration!

Please try out the new repo (when it's done) and report back with any problems!

**Comment by crienzo** [comment]
@richardscreene I've sent an invite for you to administer github.com/freeswitch/mod_janus.  Accept the invite and push your copy of the repo, and you're all set.

**Comment by richardscreene** [comment]
@crienzo All done!  Thanks for your help!

**Comment by crienzo** [comment]
I've added a link to your module in modules.conf.in
