### ISSUE TITLE
Problems about libtool

### ISSUE THREAD

**Issue by zero-git616** [signalwire/freeswitch#844]
I want to build FreeSWITCH 1.10.5 from source.
I follow this tutorial to do that : https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7
But when I use "make" command, it doesn't work.
This is a part of error log:

../libtool: line 816: X--mode=compile: command not found
../libtool: line 966: *** Warning: inferring the mode of operation is deprecated.: command not found
../libtool: line 967: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
../libtool: line 1110: Xgcc: command not found
../libtool: line 1110: X-DHAVE_CONFIG_H: command not found
../libtool: line 1110: X-DPACKAGE="expat": command not found
../libtool: line 1110: X-DVERSION="expat_1.95.2": command not found
../libtool: line 1110: X-I.: command not found
../libtool: line 1110: X-I..: command not found
../libtool: line 1110: X-I/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib: No such file or directory
../libtool: line 1110: X-g: command not found
../libtool: line 1110: X-O2: command not found
../libtool: line 1110: X-c: command not found
../libtool: line 1138: Xxmlparse.c: command not found
../libtool: line 1161: X: command not found
../libtool: line 1166: libtool: compile: cannot determine name of library object from `': command not found
make[3]: *** [xmlparse.lo] Error 1
make[3]: Leaving directory `/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib'
make[2]: Leaving directory `/usr/local/src/freeswitch/libs/apr-util/xml/expat'
make[2]: Entering directory `/usr/local/src/freeswitch/libs/apr-util'
/bin/sh /usr/local/src/freeswitch/libs/apr/libtool --silent --mode=link  gcc -g -O2 -pthread  -g -O2  -DHAVE_CONFIG_H -D_REENTRANT -D_GNU_SOURCE   -I/usr/local/src/freeswitch/libs/apr-util/include -I/usr/local/src/freeswitch/libs/apr-util/include/private  -I/usr/local/src/freeswitch/libs/apr/include  -I/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib  -version-info 2:8:2    -o libaprutil-1.la -rpath /usr/lib crypto/apr_md5.lo crypto/uuid.lo crypto/apr_sha1.lo crypto/getuuid.lo crypto/apr_md4.lo encoding/apr_base64.lo hooks/apr_hooks.lo misc/apr_reslist.lo misc/apr_rmm.lo misc/apr_date.lo misc/apu_version.lo misc/apr_queue.lo uri/apr_uri.lo xml/apr_xml.lo strmatch/apr_strmatch.lo xlate/xlate.lo   -luuid -lrt -ldl -lcrypt  -lpthread -L/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib -lpq /usr/local/src/freeswitch/libs/apr-util/xml/expat/lib/libexpat.la /usr/local/src/freeswitch/libs/apr/libapr-1.la -luuid -lrt -ldl -lcrypt -lpthread
libtool: link: cannot find the library `/usr/local/src/freeswitch/libs/apr-util/xml/expat/lib/libexpat.la'
make[2]: *** [libaprutil-1.la] Error 1
make[2]: Leaving directory `/usr/local/src/freeswitch/libs/apr-util'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/freeswitch/libs/apr-util'
make: *** [libs/apr-util/libaprutil-1.la] Error 2

I'm a student and I want to learn about FreeSWITCH. Please help me. Thank you very much.

**Comment by mjerris** [comment]
something dirty in the tree.  completely clean the checkout and start over.
