### ISSUE TITLE
FreeSWITCH 1.10 sends 183 after reload XML

### ISSUE THREAD

**Issue by VMGuy** [signalwire/freeswitch#847]
Currently my dialplan contains
- ring_ready
- ignore_early_media=true
- bridge user/...

After rebooting the server FreeSWITCH sends [proceeding][180] and that's it.
Everything looks fine.

But when I do a reload XML it suddenly starts sending [proceeding][180] followed by [early][183].
This causes a missing ring tone for the callers.
After reboot it returns to the 180 only until I do a reload XML again.

I checked that using version 1.10.3 and 1.10.5.

Log file content after reload XML:
`040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.816227 [DEBUG] sofia.c:7326 Channel sofia/external/+49xxxxxxxx@provider.de entering state [early][183]
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_ivr_originate.c:1407 Play Ringback Tone [%(1000,4000,425)]
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_core_codec.c:223 sofia/external/+49xxxxxxxx@provider.de Push codec L16:100
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_ivr_originate.c:1333 Raw Codec Activation Success L16@8000hz 1 channel 20ms
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_channel.c:3565 (sofia/external/+49xxxxxxxx@provider.de) Callstate Change RINGING -> EARLY
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [NOTICE] mod_sofia.c:2596 Pre-Answer sofia/external/+49xxxxxxxx@provider.de!
040c017a-02ae-4de7-8e13-dd74e8d3080c
040c017a-02ae-4de7-8e13-dd74e8d3080c a=sendrecv
040c017a-02ae-4de7-8e13-dd74e8d3080c a=ptime:20
040c017a-02ae-4de7-8e13-dd74e8d3080c a=fmtp:101 0-16
040c017a-02ae-4de7-8e13-dd74e8d3080c a=rtpmap:101 telephone-event/8000
040c017a-02ae-4de7-8e13-dd74e8d3080c a=rtpmap:8 PCMA/8000
040c017a-02ae-4de7-8e13-dd74e8d3080c m=audio 63400 RTP/AVP 8 101
040c017a-02ae-4de7-8e13-dd74e8d3080c t=0 0
040c017a-02ae-4de7-8e13-dd74e8d3080c c=IN IP4 87.184.108.32
040c017a-02ae-4de7-8e13-dd74e8d3080c s=FreeSWITCH
040c017a-02ae-4de7-8e13-dd74e8d3080c o=FreeSWITCH 1599636699 1599636700 IN IP4 87.184.108.32
040c017a-02ae-4de7-8e13-dd74e8d3080c v=0
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] mod_sofia.c:2593 Ring SDP:
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_core_media.c:9007 sofia/external/+49xxxxxxxx@provider.de Set rtp dtmf delay to 40
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_core_media.c:8984 sofia/external/+49xxxxxxxx@provider.de Set 2833 dtmf receive payload to 101
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_core_media.c:8977 sofia/external/+49xxxxxxxx@provider.de Set 2833 dtmf send payload to 101
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_rtp.c:4450 Starting timer [soft] 160 bytes per 20ms
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:19.796254 [DEBUG] switch_core_media.c:8663 AUDIO RTP [sofia/external/+49xxxxxxxx@provider.de] 192.168.x.y port 31778 -> a.b.c.d port 22660 codec: 8 ms: 20
040c017a-02ae-4de7-8e13-dd74e8d3080c 2020-09-10 03:08:15.396245 [INFO] switch_ivr_originate.c:1275 Sending early media
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:15.396245 [DEBUG] switch_channel.c:3437 (sofia/internal/24@192.168.x.y:5060) Callstate Change DOWN -> RINGING
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:15.396245 [NOTICE] sofia.c:7437 Ring-Ready sofia/internal/24@192.168.x.y:5060!
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:15.396245 [DEBUG] sofia.c:7326 Channel sofia/internal/24@192.168.x.y:5060 entering state [proceeding][180]
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:14.656227 [DEBUG] switch_core_state_machine.c:663 (sofia/internal/24@192.168.x.y:5060) State CONSUME_MEDIA going to sleep
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:14.656227 [DEBUG] switch_core_state_machine.c:663 (sofia/internal/24@192.168.x.y:5060) State CONSUME_MEDIA
df170065-ba95-4b34-b9f3-3808e51c628f 2020-09-10 03:08:14.656227 [DEBUG] sofia.c:7326 Channel sofia/internal/24@192.168.x.y:5060 entering state [calling][0] `

**Comment by mjerris** [comment]
somehow you are setting ringback

[DEBUG] switch_ivr_originate.c:1407 Play Ringback Tone [%(1000,4000,425)]
