### ISSUE TITLE
switch_url_encode is not encoding character '%'

### ISSUE THREAD

**Issue by kaaelhaa** [signalwire/freeswitch#85]
Resurfacing this from the old FS Jira (FS-11499).

FreeSWITCH is not doing URL encoding of '%' as FreeSWITCH then is lead to believe the string has been encoded already.

This is particularly bad if Call-ID contains '%' (I'm looking at you, Ericsson MSC!) and an outbound event socket application is depending on it. When the event socket application sends a `connect` to FreeSWITCH, CHANNEL_DATA is dumped to the application without proper URL encoding of `CHANNEL_UNIQUE_ID`, `UNIQUE_ID`, `variable_uuid`, etc. and the application then fails doing URL decoding due to an invalid encoding sequence. This is not something the client should handle.

*Example*
The original Call-ID: `u{cX82048234578%bekJulHgQiB0e@example.net`
The FreeSWITCH URL encoded Call-ID: `u%7BcX82048234578%bekJulHgQiB0e%40example.net`
Proper URL encoded Call-ID: `u%7BcX82048234578%25bekJulHgQiB0e%40example.net`

I've been triaging this and it seems to have been introduced with FreeSWITCH v1.4.16 (commit 76370f4d1767bb0dcf828a3d6cde6e015b2cfa03. It's still present in master although an option for double encoding has been introduced which to some extend mitigates the missing encoding if modules have been updated to use this option.
It seems some modules are still using the implementation which does not do proper URL encoding (mod_event_socket for instance).

**Comment by briankwest** [comment]
Please test on 1.10.x and open a reopen if it persists, we don't provide support for 1.4, 1.6 or 1.8.
