### ISSUE TITLE
mod_sofia cannot start

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#861]
**Describe the bug**
2020-09-18 01:17:11.275991 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/local/freeswitch/mod/mod_sofia.so
**/usr/local/freeswitch/mod/mod_sofia.so: undefined symbol: ntatag_srv_503*

**To Reproduce**
last git today
compile standard options.

**Comment by mjerris** [comment]
install the latest sofia-sip library.  check install instructions on the wiki

**Comment by ROBERT-MCDOWELL** [comment]
ok done, fixed thanks. there was old sofi-sip libs somwehere on my system.
