### ISSUE TITLE
[Urgent] Recently have issue with Chrome85+ and due to which facing complete outage with my application.

### ISSUE THREAD

**Issue by kumail-raza** [signalwire/freeswitch#862]
Hi Guys,

6df69a68-8b7d-4089-a474-87ef88770503 2020-09-17 04:21:20.708331 [ERR] switch_rtp.c:3082 audio Handshake failure 1
6df69a68-8b7d-4089-a474-87ef88770503 2020-09-17 04:21:20.708331 [INFO] switch_rtp.c:3083 Changing audio DTLS state from HANDSHAKE fail...

Recently we encounter and issue with Chrome85, our applications stops working, but while investigation I found that on Chrome86(beta) and Chrome87(canary) application is working fine, but with following warning which I do not observed on Chrome85(stable)

**[Deprecation] Your partner is negotiating an obsolete (D)TLS version. Support for this will be removed in M81, around April 2020. Please check with your partner to have this fixed.**

**Comment by kumail-raza** [comment]
**More details:**
On Chrome85, user get connected but after connecting following event received (occured)

```js
__tsip_transport_ws_onmessage
SIPml-api.js?svn=179:1 recv=BYE sips:1000@df7jal23ls0d.invalid;rtcweb-breaker=yes;click2call=no;transport=wss SIP/2.0
Via: ....
From: .....
To: .....
Call-ID: ID: xxx-xx-xx-xx
CSeq: 25658160 BYE
Content-Length: 0
Max-Forwards: 70
User-Agent: FreeSWITCH-mod_sofia/1.6.6-13-d2d0b32~64bit
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,MESSAGE,INFO,UPDATE,REGISTER,REFER,NOTIFY,PUBLISH,SUBSCRIBE
Supported: path,replaces
Reason: text="DESTINATION_OUT_OF_ORDER";cause=27;text="DESTINATION_OUT_OF_ORDER"

SIPml-api.js?svn=179:1 State machine: x0000_Any_2_Terminated_X_iBYE
SIPml-api.js?svn=179:1 === INVITE Dialog terminated ===
SIPml-api.js?svn=179:1 PeerConnection::stop()
SIPml-api.js?svn=179:1 SEND: SIP/2.0 200 OK
Via: ....
From: ....
To: .....
Contact: <sips:1000@df7jal23ls0d.invalid;transport=wss>
Call-ID: xxx-xx-xx-xx
CSeq: 25658160 BYE
Content-Length: 0

SIPml-api.js?svn=179:1 ==session event = terminated
```

**Reason: text="DESTINATION_OUT_OF_ORDER";cause=27;text="DESTINATION_OUT_OF_ORDER"**
> https://freeswitch.org/confluence/display/FREESWITCH/Hangup+Cause+Code+Table
**DESTINATION_OUT_OF_ORDER**
This cause indicates that the destination indicated by the user cannot be reached because the interface to the destination is not functioning correctly. The term "not functioning correctly" indicates that a signal message

**Comment by andywolk** [comment]
What freeswitch version is this?

**Comment by kumail-raza** [comment]
@andywolk 

We are able to resolve this issue by upgrading the openssl on our server and removing the previous DTLS-SRTP.pem file (which basically auto generated by freeswitch). 

Thanks for the response.
