### ISSUE TITLE
sofia_parse_all_invite_headers() in mod_sofia, sofia.c - doesn't parse the Identity: header

### ISSUE THREAD

**Issue by FredWemyss** [signalwire/freeswitch#867]
Testing on 1.10.5 - Identity: headers get consumed on inbound packets.

Tracing backwards - the trouble is that the sofia library used by sofia.c - has been updated to push the Identity: header into a sip_identity value - and we just need to add a line to sofia_parse_all_invite_headers() to get the header parsed again. It used to get added before the library change through the "Loop through unknown headers" section - but it's no longer unknown to the parsing library, so it's no longer added.

Compiling up a version and adding in:

sofia_add_invite_header_to_chanvars(channel, nh, sip->sip_identity, "sip_i_identity");

Works like a charm again. If we can get this merged in, should make life easier.

**Comment by mjerris** [comment]
sounds right.  please create a pull request to add this

**Comment by hnimminh** [comment]
Hi @FredWemyss 
is there any reason that you use **sip_i_identity** (not use **sip_h_identity**)
I run on FreeSWITCH 1.10.6 seem `sip_i_identity` is not getable what is version of your current freeswitch?

**Comment by FredWemyss** [comment]
We run on FreeSwitch 1.10.6 over here -

***@***.***> show status
UP 0 years, 3 days, 8 hours, 57 minutes, 46 seconds, 350 milliseconds, 783
microseconds
FreeSWITCH (Version 1.10.6 -release-18-1ff9d0a60e 64bit) is ready

sip_h_Identity=${sip_i_identity}

Is the string we set to pass on the identity header to the bridged call -
sip_i_identity should have the
contents of the inbound call - and is set on the outbound like all the
other headers - with the sip_h_ prefix.

The sip_i_identity header won't be available unless there is an actual
Identity: header on the inbound call.
Not sure what version of libsofia is required for it to be visible - but if
you did a full 1.10.6 stable release, it should
be there. If you did a compile from snapshot - maybe not.

             -Fred

**Comment by hnimminh** [comment]
hmm, I test on the inbound call scenario only (voicemail & IVR), our dialplan based on lua script and esl event, , sip_h_Identity is working good but **sip_i_identity** is not appear on the CHANNEL_CREATE. quite weird!

**Comment by FredWemyss** [comment]
Do you have -

<param name="parse-all-invite-headers" value="true"/>

Set on the inbound sip_profile? F/S doesn't normally look at the Identity:
header. So you need to set that for it to parse it.

For older versions of F/S that's all you needed for the variable to be
seen.. but eventually libsofia started addressing the Identity header in
it's own
structure - hence the need for a patch to F/S to get it to show up.

**Comment by hnimminh** [comment]
yes, I did,
other unknown header like sip_i_Diversion or sip_i_test is working, just  not **sip_i_identity**

**Comment by FredWemyss** [comment]
Well, that makes it a little trickier to figure out.

Do you see it defined in mod_sofia, at least?

Here's a 1.10.6 version with it defined -
***@***.***:~# strings /usr/lib/freeswitch/mod/mod_sofia.so | grep -i
sip_ | grep -i ident
sip_p_asserted_identity_class
sip_p_preferred_identity_class
sip_P-Asserted-Identity
sip_P-Preferred-Identity
sip_h_identity
sip_i_identity
sip_i_p_asserted_identity
sip_i_p_preferred_identity
***@***.***:~#

And here's an older version where it isn't defined.. so old it isn't aware
that there is anything special
about the identity header.

***@***.***:~# strings /usr/lib/freeswitch/mod/mod_sofia.so | grep -i sip_
| grep -i ident
sip_P-Asserted-Identity
sip_i_p_asserted_identity
sip_i_p_preferred_identity
sip_P-Preferred-Identity
***@***.***:~#

**Comment by hnimminh** [comment]
on my side
```
root@****# strings /usr/local/lib/freeswitch/mod/mod_sofia.so  | grep -i sip_ | grep -i ident
sip_p_asserted_identity_class
sip_p_preferred_identity_class
sip_P-Asserted-Identity
sip_P-Preferred-Identity
sip_h_identity
sip_i_identity
sip_i_p_asserted_identity
sip_i_p_preferred_identity
sip_438_Invalid_identity_header
sip_identity_s
sip_identity_t
sip_p_asserted_identity_class
sip_436_Bad_identity_info
sip_428_Use_identity_header
sip_identity_class
sip_identity
sip_p_preferred_identity_class
sip_p_asserted_identity_s
sip_p_asserted_identity_t
sip_p_preferred_identity_s
sip_p_preferred_identity_t
sip_p_preferred_identity_class
sip_p_asserted_identity_class
root@devsbc:/home/admin# fscli -x status
UP 0 years, 0 days, 22 hours, 57 minutes, 49 seconds, 444 milliseconds, 953 microseconds
FreeSWITCH (Version 1.10.6-release  64bit) is ready
28 session(s) since startup
0 session(s) - peak 2, last 5min 0 
0 session(s) per Sec out of max 100, peak 2, last 5min 0 
3000 session(s) max
min idle cpu 0.00/99.50
Current Stack Size/Max 240K/8192K```

**Comment by hnimminh** [comment]
I'm thinking result are not same due to different of source your is `Version 1.10.6 -release-18-1ff9d0a60e 64bit` and mine is `Version 1.10.6-release`

**Comment by FredWemyss** [comment]
Should know about it.

All I can think of - guessing from the devsbc hostname that this is a lab
VM - is to toss a full INVITE with an
Identity: header at it - and have it hit the info application to dump all
the channel variables, and see if comes up.
Last I checked libsofia doesn't do any checks on Identity: for correctness
outside of any other SIP header - so you should
be able to send:

Identity: test

For a header and have it pop on the channel variable list. That's useless
for STIR/SHAKEN, but should be good enough for
Freeswitch variable matching.

And if that doesn't work - try a clean debian VM, and install F/S from the
debian packages, and see if it works then. Should
at least narrow down where the issue is.

**Comment by FredWemyss** [comment]
Yeah, I'm using the debian packages here - which to my knowledge is the
only "supported" configuration. It works
fine under FreeBSD compiled from scratch, but for production use, we
usually stick to official supported.

It's nice being able to upgrade with apt-get update as well.

**Comment by hnimminh** [comment]
Thanks for your advice, 
In fact, I trying to collect all **Identity** for post-process analytics. as the  https://datatracker.ietf.org/doc/html/rfc8224#page-7 ```the Identity header field is now allowed to appear more than one time in a SIP request.```

That what I trying to archive

**Comment by FredWemyss** [comment]
Has libsofia been updated to work with multiple headers?

Last time I looked at it - which was a year ago, of course - the
sip_identity field they stored in was a single element - not an array or
list. So while it is certainly legal to have multiple Identity headers -
even really required for trying to do call forwarding with STIR/SHAKEN
support - Freeswitch can only ever see a single header (at most!) until
that changes.

**Comment by hnimminh** [comment]
right! sofia-lib was not support for multiple Identity header

https://github.com/freeswitch/sofia-sip/blob/dac47692d1c2a52e2a8aec0825187370f44198fb/libsofia-sip-ua/sip/sofia-sip/sip.h#L484
```
struct sip_identity_s
{
  sip_common_t   id_common[1];	/**< Common fragment info */
  sip_error_t   *id_next;		/**< Link to next (dummy) */
  char const    *id_value;		/**< Identity text as shown in SIP Header */
  char const	*id_info;		/**< Field containing URL of the cert */
  char const    *id_signed_identity_digest;	/**< Digest */
  char const	*id_info_alg;		/**< Field containing alg of the cert */
  char const	*id_info_ppt;		/**< Field containing PASSporT Type */
  msg_param_t const *id_info_params;	/**< Field containing extensions */
};
```
