### ISSUE TITLE
Distorted sound for one of conference members when AMR-WB codec used

### ISSUE THREAD

**Issue by rafaltelaczynski** [signalwire/freeswitch#879]
**Describe the bug**
We are using FreeSWITCH with AMR/AMR-WB modules loaded to put 2 members on a conference. 
The problem is that when AMR-WB codec is negotiated for A-party, the second member to join the conference hears distorted sound(sometimes it lasts couple seconds, in some cases it lasts until the end of the call). There is no such sound heard by first member participant, nor is it generated by it(verified by decoding audio from RTP packets sent from first member participant towards FreeSWITCH). Moreover, distorted sound to second member can be heard after decoding RTP packets sent from FreeSWITCH towards second conference participant - proof that it is not the issue with second participant phone or so. 
Intrestingly, there is no such issue when AMR codec is used(tested by removing AMR-WB from global_codec_prefs) - the sound is OK for both participant throughout the whole duration of the conference.

Considering that everything is OK when AMR codec used instead of AMR-WB, it seems like the issue is not with conference feature itself, but using AMR-WB during conference. We played with some of the FreeSWITCH parameters related to RTP(e.g. auto-rtp-bugs, rtp-rewrite-timestamps, send_silence_when_idle, etc.) but none of it helped.

We tested this configuration in 2 separate environments and it was present in both.

**To Reproduce**
You'd need to setup a conference for atleast 2 participants with AMR-WB codec negotiated for first participant joining the conference. The distorted sound will be heard by second participant after it joins the conference.

**Expected behavior**
Audio received by second participant should be atleast as clear as when AMR codec is used.

**Package version or git hash**
- FreeSWTICH v1.10.5
- both mod_amrwb and mod_amr loaded 

**Evidence**
Attached, FreeSWITCH logs as well as audio files in both RAW and encoded to playable AMR files regarding A-party audio sent towards FreeSWITCH and what FreeSWITCH sent towards B-party for AMR(as a proof that there is no issue) and AMR-WB(issue heard in `amrwb_to_amrwb_fs_to_b_party_rtp.amr` file).

Unfortunately, due to exposed IP addresses and other sensitive data, I'm not able to share network traces containing SIP communication/RTP packets. All communication is visible in FreeSWITCH log, though.

[conf_amrwb_issue_evidence.zip](https://github.com/signalwire/freeswitch/files/5310444/conf_amrwb_issue_evidence.zip)

If you need any more information regarding the issue, please, feel free to contact.

**Comment by dragos-oancea** [comment]
use command "amrwb_debug on" at fs_cli before taking the AMR-WB log ,  and command "amr_debug on"  when taking the AMR log. As opposed with bridging, with conferencing FS is generating the 200 OK directly, with nothing being copied from the other leg. I noticed the "octet-align=0"   in fmtp of AMR (generated by FS) . So this means BE (Bandwidth Efficient) mode. But when using AMR-WB, it's missing the octet-align=0 so it means octet-align is 1 (per RFC, if it's not present it should be set to 1)  . But it's curious, because the code adding that should have run. Can you flip the "volte" setting in your amrwb.conf.xml ?

**Comment by dragos-oancea** [comment]
You can try this older PR: https://github.com/signalwire/freeswitch/pull/684/files . use force-oa=1 in the xml cfg, so it will do OA.

**Comment by dragos-oancea** [comment]
Actually RFC says "If 0 or if not present, bandwidth-efficient operation is employed." , so it should be BE both your cases.

**Comment by rafaltelaczynski** [comment]
Yes, mode is BE for both cases.

Attached, freeswitch log for AMR/AMR-WB with AMR debug flag on.
[fs_logs_amr_debug_on.zip](https://github.com/signalwire/freeswitch/files/5311852/fs_logs_amr_debug_on.zip)

**Comment by rafaltelaczynski** [comment]
When OA is forced the log is filled with AMRWB decoder errors as the network still sends the RTPs using BE mode and no voice is exchanged between two parties. 

Per `RFC 4867, 8.3.1` , when no `octet-align=1` is received in initial offer, we can not change it(which we do when forcing OA mode).
`An SDP answerer MUST include, in the SDP answer
         for a payload type, the following parameters unmodified from
         the SDP offer (unless it removes the payload type): "octet-
         align"; "crc"; "robust-sorting"; "interleaving"; and
         "channels".  The SDP offerer and answerer MUST generate AMR or
         AMR-WB packets as described by these parameters.`

[force_oa_freeswitch.log](https://github.com/signalwire/freeswitch/files/5326190/force_oa_freeswitch.log)

**Comment by dragos-oancea** [comment]
I didn't say to force it.  I said to use this change to try OA: https://github.com/signalwire/freeswitch/pull/684/files
The PR says "originating", but it will work in your case with conferencing too. It's simply a matter of setting a flag.

**Comment by dragos-oancea** [comment]
Ultimately you can change the order in which OA & BE are initiated in the code, so it would default to OA.
I still don't know why we don't send "octet-align=0" in SDP, in your case. I know it should be the same, but nevertheless, the function generating fmtp maybe is not called.

**Comment by dragos-oancea** [comment]
maybe the wording "force-oa" is not right, it should be "use-oa" , since it would simply enable OA and reflect in SDP accordingly. Did you try the patch ?

**Comment by rafaltelaczynski** [comment]
Yes, the most recent log files I sent was from an attempt with the patch applied. If I understand it correctly going by the mod_amrwb.c module from PR, when "force-oa=1" and "octet-align" is missing(or even "octet-align=0"?), it will send "octet-align=1" in outgoing FMTP which is what is happening in the logs I sent and not entirely correct?

As for missing "octet-align=0", it is probably due to change introduced not to put "octet-align" at all when it was not detected in incoming FMTP(this should not be an issue as when missing is should be treated as "octet-align=0", but I can always revert that change and retest if needed).

**Comment by dragos-oancea** [comment]
OK, so the peer does not respect the SDP ? Anyhow, does bridging work for you with same network/UEs ? This code was tested with bridging, both OA and BE, with VoLTE devices. I supposed this must be a SDP related error, since you mentioned conferencing, but perhaps it's something else.

**Comment by dragos-oancea** [comment]
Bridging with transcoding I mean.

**Comment by rafaltelaczynski** [comment]
Yes, I can confirm that there is no such issue at all when bridge is used instead of conference for this scenario.

**Comment by rafaltelaczynski** [comment]
After detailed analysis of network traffic from many attempts of conferencing with AMR-WB, there is no obvious correlation between SDP negotiation and distorted sound noticed. Especially since there are some cases when distorted sound is present for the duration of the call, long after any SDP exchange is finished.

You mentioned that AMR-WB code was tested with bridging only. Could you, please, provide me with an information whether testing of AMR-WB with conferencing is planned within future release?

**Comment by dragos-oancea** [comment]
there is no specific plan about it. did you try to change the conference rate ? does anything change ? 
if you record inside the conference (with conference API command "conference confname record /tmp/foo.wav" ) is the audio clear ?

**Comment by dragos-oancea** [comment]
one member AMR and one AMR-WB works fine ?

**Comment by dragos-oancea** [comment]
try to apply this patch and then capture logs with "amrwb_debug on" . https://github.com/signalwire/freeswitch/pull/976 
it will show the session too. easier to distinguish the 2nd member.

**Comment by rafaltelaczynski** [comment]
Answering your questions below.
1) We tried all conferences rates, as well as most of other conference settings - no differences noticed.
2) The audio recorded during conference is clear - no distored sound can be heard when playing the recorded file.
3) The problem seems to occur when atleast one of the members uses AMR-WB codec.

Attached log with patch applied and amrwb_debug ON.
[20201217_fs_amrwb_session_log.log](https://github.com/signalwire/freeswitch/files/5708010/20201217_fs_amrwb_session_log.log)

**Comment by dragos-oancea** [comment]
If you grep the log for "AMRWB decoder" and then look at the session IDs to identify the both devices you'll see they both send data at irregular intervals (it looks like ptime varies during the call - DTX enabled in UEs ? ), eg: 160 ms, 60 ms - the "regular" interval of 20 ms is present too. The encoder is called each 20 ms. You can increase the "interval" setting in conference config to 60 for example - see if it makes a difference in the way audio is distorted, it won't fix it (AMRWB is implemented only at 20 ms) . If you can make the UEs send data at 20 ms intervals (as negotiated in SDP)  I think the issue will be solved.

**Comment by dragos-oancea** [comment]
Also try to use the jitterbuffer, it might help. https://freeswitch.org/confluence/display/FREESWITCH/JitterBuffer

**Comment by rafaltelaczynski** [comment]
1. Tried adjusting conference interval from auto value to 20,60 and, higest available, 120 - no difference in sound distortion noticed.
2. Tried using jitter buffer with extended set of configuration parameters(default 60:200:20, as well as some higher ones like 100:400:40) - no difference in sound distorion noticed(confirmed in logs for each try that jitterbuffer was indeed enable & active). Also, tested flag like rtp_jitter_buffer_plc for a hope that it would make any difference - sadly, it didn't.
3. I'm afraid that it is impossible from our point-of-view to force UEs to send data at 20ms interval. The negotiated 'ptime' is indeed 20ms, but going by the RFC:
```
a=ptime:<packet time>

         This gives the length of time in milliseconds represented by
         the media in a packet.  This is probably only meaningful for
         audio data, but may be used with other media types if it makes
         sense.  It should not be necessary to know ptime to decode RTP
         or vat audio, and it is intended as a recommendation for the
         encoding/packetisation of audio.  It is a media-level
         attribute, and it is not dependent on charset.
```
The negotiatied value is only a recommendation, not mandatory to respect it.
I'm wondering whether introducing additional SDP parameter of 'maxptime' with value 20ms in FreeSWITCH SDP would help in any way:
```
      a=maxptime:<maximum packet time>

         This gives the maximum amount of media that can be encapsulated
         in each packet, expressed as time in milliseconds.  The time
         SHALL be calculated as the sum of the time the media present in
         the packet represents.  For frame-based codecs, the time SHOULD
         be an integer multiple of the frame size.  This attribute is
         probably only meaningful for audio data, but may be used with
         other media types if it makes sense.  It is a media-level
         attribute, and it is not dependent on charset.  Note that this
         attribute was introduced after RFC 2327, and non-updated
         implementations will ignore this attribute.
```
I'm aware that it is not 100% cases fix as, as it is stated in RFC, all pre-RFC2327 UEs would just ignore that parameter anyway, but it might be enough for our case. Do you happen to know if it is possible to force this parameter in FreeSWITCH SDP/could point where would that need to be done just for the testing purpose(could be hardcoded, even)? 

4. During testing there were some cases when conference sound was not distorted even when AMR-WB codec was used(~5% of cases). Going by the logs and comparing them with logs from attempts when sound distortion was evident these are the key takeaways:

4.1. It looks like irregular interval is not problematic - for good sound case there were packets with 60-160ms between them not causing a single distortion throughout the call.
4.2. For each bad sound case there is 'Dropping floor' message, going by few attempts I think it can be correlated with start of sound distortion(e.g. when sound distortion start 1-2s after conference is setup this line is printed with similar delay)
```
2021-03-26 11:27:16.749908 [ALERT] conference_member.c:1098 Dropping floor 88
```
4.3. For each bad sound case there are multiple occurence of lines such as below. This is not the case for good sound cases(altough, they are present, just in way lower amount). The occurence in bad cases seems to be somehow correlated with 'Dropping floor' log - no occurence before that line in any case for bad sound scenario.
```
2021-03-26 11:27:16.909910 [ALERT] conference_loop.c:1059 TRACK 13095 13095 1/0 0.000000
```
4.4. There are also audio stat lines. The flaws ammount is exactly 0 for all cases(good and bad ones), so I'm not sure if it is any helpful indication.
```
795d67ac-d423-47c0-a340-c5d0a2605ea7 2021-03-26 12:08:29.649907 [ALERT] switch_rtp.c:1604 sofia/default/48691645628@10.24.39.4:15060 audio stat 100.00 2/2 flaws: 0 mos: 4.50 v: 0.00 0.00/0.00
```

Attached, logs for both good and bad sound cases that were used for above analysis. Could you, please, take a look and see if you notice anything suspicious?

[20210326_amrwb_conf_bad_filtered.log](https://github.com/signalwire/freeswitch/files/6211379/20210326_amrwb_conf_bad_filtered.log)
[20210326_amrwb_conf_good_filtered.log](https://github.com/signalwire/freeswitch/files/6211380/20210326_amrwb_conf_good_filtered.log)

**Comment by dragos-oancea** [comment]
did you try to set to true channel variable "rtp_media_autofix_timing" ? 
It seems "Dropping floor" messages are just a consequence of the real issue which is synchronization. 
In the lucky good cases the both devices and the conference timer are in sync with multiples of 20 ms.  
Also try to make the devices behave differently with changing the fmtp settings we have now under param "volte".

**Comment by dragos-oancea** [comment]
hard to tell what is going on without a pcap file. you could send the pcap to dragos@freeswitch.org and I'l take a look based on time and priorities.

**Comment by rafaltelaczynski** [comment]
What was tried but did not help:
- higher jitterbuffer values(160ms)
- `a:maxptime=20` addition in SDP
- cherrypicking DTX (https://github.com/signalwire/freeswitch/commit/7fc5d9a7c36337b15a5c7044bdaecdc82d95d94b) patch from `master`

In the end, it turns out https://github.com/signalwire/freeswitch/commit/f7a424a263680ddcfd974548a61668779e093759 commit is problematic - after reverting it, not only did the UEs accept modified mode-set, the sound is clear as well, no distortion noticed even after mutliple attempts.

**Comment by dragos-oancea** [comment]
Re on what we've discussed over email: We either make it work with the RFC4867 patch in (ideally) or we add a cfg var to enable/disable it.  
There are some UEs that drop the reply without that commit (f7a424a), we can't simply revert it. 
What I've seen from the logs and pcaps is that these UEs send some sort of DTX: eg: sending a 5 byte payload each 80 or 60 ms. If I remember correctly without that commit we send default mode-set in the reply, or the mode-set set in the cfg.

**Comment by rafaltelaczynski** [comment]
Without that commit we send single, highest value(best quality) matching mode-set from the offer, e.g. for offer of `mode-set=0,1,2,4` we would answer with `mode-set=4`

**Comment by dragos-oancea** [comment]
Does the UE behaviour make sense, per RFC, in this case ? "mode-set=0,1,2,4" does not mean it should use DTX.

**Comment by rafaltelaczynski** [comment]
I think it is not related. Per RFC4867:
For AMR-WB, SID frames act as DTX functionality:
```
The operation of sending CN parameters at regular intervals during silence periods is
   usually called discontinuous transmission (DTX) or source controlled
   rate (SCR) operation.  The AMR or AMR-WB frames containing CN
   parameters are called Silence Indicator (SID) frames.
```
And they are allowed no matter the negotiated mode-set:
```
mode-set:  Restricts the active codec mode set to a subset of all
               modes, for example, to be able to support transport
               channels such as GSM networks in gateway use cases.
               Possible values are a comma-separated list of modes from
               the set: 0,...,8 (see Table 1a [4]).  The SID frame type
               9, SPEECH_LOST (frame type 14), and NO_DATA (frame type
               15) are never included in the mode set, but can always
               be used.
```

I just noticed that for some reason, when only single mode-set is answered, the UEs do not send SID frames(only single one present in PCAP vs over 50 for each attempt when the same mode-set is sent in the answer as was received in the offer(pre-RFC4867 compliancy revert)) so it might be that the root cause of the issue is still with AMRWB SID frames being incorrectly decoded and it is working just because of missing SID frames.

**Comment by dragos-oancea** [comment]
yes, it could be related with the interpretation of SID, and what we do when we get it. It's also sent at irregular intervals.
The SID frame is passed to the decoder just like regular frame, but perhaps it's more to do here, taking the interval into account.

A bug in the lib related to SID frames:
https://sourceforge.net/p/opencore-amr/mailman/message/36987783/
But it's about setting last param of D_IF_decode() which currently we don't do.
Have you tried  the master branch of the lib ? Maybe there are some other fixes too, although it seems there is not much activity around that code.  
https://sourceforge.net/p/opencore-amr/code/ci/master/tree/

**Comment by dragos-oancea** [comment]
https://github.com/signalwire/freeswitch/pull/1190

**Comment by dragos-oancea** [comment]
2915d3aba8f52e34a7fd258fbd4182fddfa42879 provides a knob to answer with just one "mode-set" .

**Comment by rafaltelaczynski** [comment]
Despite the patch helping with overall sound quality for AMR-WB, we were still facing the issue with poor quality in cases when there was FreeSWITCH generated silence(no media from any of the parties).

The issue has been resolved completely after upgrading AMR-WB related libraries to more recent versions(the versions in CentOS repository are really outdated, e.g. opencore-amr is in version 0.1.3, which is almost 10 years old). Below the exact information regarding pre/post-update versions:
- opencore-amr(0.1.3 -> 0.1.5)
- opencore-amr-devel(0.1.3 -> 0.1.5)
- vo-amrwbenc-devel(0.1.2-1 -> 0.1.3-14)

**Comment by rafaltelaczynski** [comment]
@Jakihiko you would have to modify the source code and compile FreeSWITCH.

It can be added the same way `ptime` parameter is: https://github.com/signalwire/freeswitch/blob/master/src/switch_core_media.c#L10666

Although, keep in mind this is global change that is going to affect all scenarios.
