### ISSUE TITLE
RAW Signed Linear decoder error for RTP packet with AMR payload and Frame Type=NO_DATA(15)

### ISSUE THREAD

**Issue by rafaltelaczynski** [signalwire/freeswitch#880]
**Describe the bug**
Scenario: A-party is answered on FreeSWITCH with AMR codec negotiated, record application is executed with file extension MP3.
When RTP packet with AMR payload and Frame Type=NO_DATA(15) is received, AMR decoder is not able to decode it properly causing error that is then propagated to `switch_code_io` module. Going by the code it seams that the same will happen for every Frame Type > 8. Moreover, `switch_core_io` module indicates that when more than 10 such errors happen it will go into error handling as seen here: `switch_core_io.c:636`

`2020-10-01 08:29:22.444170 [ERR] mod_amr.c:219 AMR decoder (BE): Invalid Table Of Contents (TOC): 0xf
646dbc80-4831-4463-8b9c-86f40996daa2 2020-10-01 08:29:22.444170 [ERR] switch_core_io.c:633 Codec RAW Signed Linear (16 bit) decoder error! [1]`

![image](https://user-images.githubusercontent.com/71707322/94788223-93f19d00-03d3-11eb-951d-4a65428fc2c4.png)

**To Reproduce**
1. Dial into FreeSWITCH and answer the call with AMR codec negotiated.
3. Execute record app with file extension MP3
4. Generate RTP packet with payload type=AMR and Frame Type > 8.

**Expected behavior**
This Frame Type should be handled without error as it is in line with RFC 4867.

**Package version or git hash**
 - Freeswitch v1.10.5

**Trace logs**
Example RTP packet that will cause this behaviour: [ft_no_data_rtp.pcapng.zip](https://github.com/signalwire/freeswitch/files/5310693/ft_no_data_rtp.pcapng.zip)
NOTE: you need to decode it as RTP and type 98 as AMR dynamic payload type in AMR protocol preferences for Wireshark to decode it properly.

**Comment by dragos-oancea** [comment]
thanks for reporting.

**Comment by dragos-oancea** [comment]
it looks like a matter of allowing the two special frame types  SPEECH_LOST and NO_DATA  , with a frame size of 2 bytes.

**Comment by dragos-oancea** [comment]
can you please test this patch ? https://github.com/signalwire/freeswitch/pull/1083 . if all fine we can do the same for AMR-WB . SPEECH_LOST is only for AMR-WB.

**Comment by rafaltelaczynski** [comment]
The patch was tested, it is working correctly for AMR packets with FT=NO_DATA(15).

**Comment by dragos-oancea** [comment]
thanks

**Comment by dragos-oancea** [comment]
we merged #1083 . can you test this one too ?  https://github.com/signalwire/freeswitch/pull/1098  . It's for AMRWB. Also, if you could provide pcap files with AMR and AMWRB streams as produced by modern VoLTE devices would be nice - we'll add them to the unit tests.

**Comment by rafaltelaczynski** [comment]
Tested AMR-WB fix for both SPEECH_LOST and NO_DATA - both are OK, thank you.

Attached RTPs for AMR and AMR-WB pcap. Although they are 6 months old, it should be sufficient for you. Let me know if it is not.

[rtp_pcaps.zip](https://github.com/signalwire/freeswitch/files/6100099/rtp_pcaps.zip)

**Comment by dragos-oancea** [comment]
thanks
