### ISSUE TITLE
Cannot clone freeswitch-contrib

### ISSUE THREAD

**Issue by sbasurto** [signalwire/freeswitch#882]
I do not know if this is the right place, I tried to send email to freeswitch-users but my email never arrives. So I will try here,

When I try to clone freeswitch-contrib it ask for user name and password. There is a default username and password to clone it?

git clone https://freeswitch.org/stash/scm/fs/freeswitch-contrib.git
Cloning into 'freeswitch-contrib'...
Username for 'https://freeswitch.org': 
Password for 'https://freeswitch.org': 
fatal: Authentication failed for 'https://freeswitch.org/stash/scm/fs/freeswitch-contrib.git/'

How can I clone freeswitch-contrib repo?

Thanks in advance.

**Comment by andywolk** [comment]
It is here now: https://github.com/freeswitch/freeswitch-contrib
