### ISSUE TITLE
Transcoding 44.1kHz Opus to PCMU/A in conference produces clipping throughout the stream

### ISSUE THREAD

**Issue by David-dp-** [signalwire/freeswitch#896]
**Describe the bug**
We use FS 1.10.5 on Debian 10 with current verto and default Opus config. We transcode 44.1kHz down to 8kHz in our custom conference config, and this produces clipping all during the conference stream.
```    <profile name="custom_conference">
      <param name="domain" value="$${domain}"/>
      <param name="rate" value="8000"/>
      <param name="channels" value="2"/>
      <param name="interval" value="20"/>
      <param name="energy-level" value="0"/>
      <param name="caller-controls" value="none"/>
      <param name="caller-id-name" value="$${outbound_caller_name}"/>
      <param name="caller-id-number" value="$${outbound_caller_id}"/>
      <param name="comfort-noise" value="false"/>
      <param name="conference-flags" value="video-floor-only|rfc-4579|livearray-sync|minimize-video-encoding"/>
      <param name="video-mode" value="mux"/>
      <param name="video-layout-name" value="1x1"/>
      <param name="video-canvas-size" value="320x240"/>
      <param name="video-canvas-bgcolor" value="#333333"/>
      <param name="video-layout-bgcolor" value="#000000"/>
      <param name="video-codec-bandwidth" value="1mb"/>
      <param name="video-fps" value="15"/>
      <param name="max-members" value="2"/>
<!--      <param name="terminate-on-silence" value="5"/> -->
      <param name="endconf-grace-time" value="5"/>
    </profile>
```
I tried changing from: 
```
   <param name="comfort-noise" value="false"/> 
``` 
to:
```
   <param name="comfort-noise" value="0"/>
   <param name="auto-gain-level" value="-2000"/>
```
And there's now clipping only during the loudest parts. But I think this gain setting is already extreme and I'd like to know if there's a less brute-force way to eliminate clipping.

**To Reproduce**
1. Configure a conference with `<param name="rate" value="8000"/>` and set up a server to be callee and record the audio
2. Dial into conference using verto
3. Speak into conference
4. Examine the callee's recording and notice the clipping

**Expected behavior**
The callee's recording should have similar amplitude as FS's and generally have no clipping.

**Package version or git hash**
 - Version 1.10.5

**Trace logs**
N/A

**backtrace from core file**
N/A

**Comment by dragos-oancea** [comment]
I tried to reproduce this quickly using Linphone and the cfg you shown. there was no clipping. Library version: libopus 1.2~alpha2 . There's no 44.1kHz opus btw, it's 48 khz.

**Comment by David-dp-** [comment]
What questions can I answer to move this forward? Would a sample SDP or log help? Can they be shared privately?

**Comment by dragos-oancea** [comment]
yes, you could send FS DEBUG log to : dragos@freeswitch.org

**Comment by David-dp-** [comment]
This problem turned out to be user error.

We use the conference so verto users can have one-on-one calls with an automated peer. That peer has to be behind Asterisk. We had `rate` in `conference.conf.xml` set to 8000 and we also had the codec in Asterisk set to pcma,pcmu which essentially sets its sampling rate to 8kHz also. (Having it set in both places seems like the result of an experiment whose config wasn't minimized once its aims were met.) One would think that transcoding would happen just once due to the sampling rate being the same on both sides, but removing `rate` from the conference settings eliminated the clipping problem.

Note: Commenting-out in conference.conf.xml isn't sufficient; it seems it's read by something other than an xml parser.
