### ISSUE TITLE
DTLS handshaking of audio/video call fails if MTU size is set to less then 1200 bytes

### ISSUE THREAD

**Issue by figaro2015** [signalwire/freeswitch#903]
DTLS negotiation on audio and video calls fails if MTU size for the interface FreeSWITCH runs on is set to less then 1200 bytes. Looks like the implementation of the FreeSWITCH assumes 1200 bytes to be the minimum MTU size for the interface and segments the DTLS certificate packet based on that size.

The bug is 100% reproducible. Just set the MTU for the interface FreeSWITCH runs on to any number less than 1200 bytes (like for example 1100 bytes) and try to place Verto or WebRTC calls. You will see that no audio and/or video media is flowing.
An example of the command to set the MTU is as follows:

ifconfig <if_name> mtu 1100

This bug is present in the latest 1.10.6 release and on the HEAD of the master branch.

Attached please find a screenshot of the Wireshark capture of the DTLS packets for the failure case. FreeSWITCH runs on 192.168.86.37 and the client is on 192.168.86.31. 
![DTLS_fails_1100_mtu](https://user-images.githubusercontent.com/11821347/95819988-19caed80-0cdc-11eb-895e-3fc0877e33f2.png)

**Comment by anthmFS** [comment]
can be overridden with channel variable "rtp_dtls_mtu" (defaults to 1200)

Also 
SWITCH_DEFAULT_VIDEO_SIZE is defined at compile-time setting the MTU for several of the codecs etc also to 1200
We choose not to make this configurable because running an MTU so small with RTC traffic is not recommended.
