### ISSUE TITLE
No need "precondition" in Supported:

### ISSUE THREAD

**Issue by nevian427** [signalwire/freeswitch#904]
Hi,

FreeSWITCH adds precondition option with 100rel enable. We don't need it to work with 100rel.
There is an old bug FS-6221 where precondition moved from mandatory to optional part but correct way to clean it out.
FS doesn't support preconditions at all as per sources.

1. Vanila config
2. Set profile  <param name="enable-100rel" value="true"/>
3. Register two users or simple gw
4. Make call between users or via gw

INVITE sip:+79641234567@176.xx.xx.3 SIP/2.0
Via: SIP/2.0/UDP 83.xx.xx.142;rport;branch=z9hG4bK2j3X353U8QQKc
Max-Forwards: 67
From: <sip:+79011234567@176.xx.xx.3>;tag=6H8K6vBXtH8UD
To: <sip:+79641234567@176.xx.xx.3>
Call-ID: 34f87d71-16d5-4eed-9523-0fa2fb217b73
CSeq: 26739475 INVITE
Contact: <sip:gw+tele2_79011234567@83.xx.xx.142:5060;transport=udp;gw=tele2_79011234567>
User-Agent: ES FS SBC
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, PRACK, NOTIFY
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, refer
Privacy: none
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 216
P-Asserted-Identity: <sip:+79011234567@176.xx.xx.3>

v=0
o=nobody 1602566261 1602566262 IN IP4 83.xx.xx.142
s=nobody
c=IN IP4 83.xx.xx.142
t=0 0
m=audio 20258 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20

**Expected behavior**
Supported header w/o precondition option i.e.

Supported: 100rel, timer, path, replaces

**Package version or git hash**
commit 1010c6c55c35b9df738c67bc80cb353c873dab76

**Comment by andywolk** [comment]
Fixed by https://github.com/signalwire/freeswitch/pull/956
