### ISSUE TITLE
Whether Freeswitch supports two media description????

### ISSUE THREAD

**Issue by worker24h** [signalwire/freeswitch#906]
Hi， boy， I need you help.
-------------------------------------------------------------------------
I use MediaSoup as webRTC.
I send a Sip INVITE Message to FreeSwitch by MediaSoup. 
For example：
====================SDP Message======================= 

v=0
o=- 1599999 1599999 IN IP4 172.110.110.110
s=mysession session
c=IN IP4 172.110.110.110
t=0 0
**m=audio 40000 RTP/AVP 100
a=sendonly**
a=ssrc:1111222 cname:buToKXw9QTcWQHBF
a=rtpmap:100 OPUS/48000/2
a=fmtp:100 useinbandfec=1; minptime=10; maxptime=40
**m=audio 40001 RTP/AVP 100
a=recvonly**
a=ssrc:1111222 cname:buToKXw9QTcWQHBF
a=rtpmap:100 OPUS/48000/2
a=fmtp:100 useinbandfec=1; minptime=10; maxptime=40

=========================================== 

port：40000 is used sendonly
port：40001 is used recvonly

**_Can support has two media desc in SDP in FS ???_**

**Comment by mjerris** [comment]
we do not

**Comment by worker24h** [comment]
I hope support it. How to do it? Any suggestions? Thanks

**Comment by worker24h** [comment]
@mjerris  Can you help me?
