### ISSUE TITLE
I hope that FREESWITCH supports two media desc

### ISSUE THREAD

**Issue by worker24h** [signalwire/freeswitch#911]
https://github.com/signalwire/freeswitch/issues/906
=======================================

m=audio 40000 RTP/AVP 100
a=sendonly
m=audio 40001 RTP/AVP 100
a=recvonly

@seven1240 @italorossi @areski @mjerris @jourdant 
Can you help me? How to do it? Any suggestions? Thanks

**Comment by mjerris** [comment]
we do t support this
