### ISSUE TITLE
execute_on_answer or api_on_answer not fired in mod_callcenter

### ISSUE THREAD

**Issue by matteovg7** [signalwire/freeswitch#92]
Hi,
the event execute_on_answer or api_on_answer are not fired using mod_callcenter.
I need to call a script when an agent answer a call in a call center queue.
What can I do?

Thank you!
Matteo

**Comment by stalasaniya** [comment]
Hi,

you need to export in cc_variables. 
<action application="set" data="cc_export_vars=nolocal:execute_on_answer,nolocal:api_on_answer"/>

Try with setting cc_export_vars.

Thank you

**Comment by stalasaniya** [comment]
<action application="set" data="cc_export_vars=nolocal:execute_on_answer,nolocal:api_on_answer"/>

**Comment by italorossi** [comment]
You can set the variables in the agent contact field.

**Comment by matteovg7** [comment]
It works exporting the events in cc_variables.
Thank you for the hint.
