### ISSUE TITLE
fsstretch-archive-keyring.gpg certificat expired

### ISSUE THREAD

**Issue by BinaryNumber** [signalwire/freeswitch#923]
**Describe the bug**
https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.gpg certificat has expired.

**To Reproduce**
When I look at the certificat validity:
- Not before
19/07/2020 at 06:58:08 (Central European Summer Time)
- Not after
17/10/2020 at 06:58:08 (Central European Summer Time)

**Expected behavior**
The certificat is valid.

**Comment by andywolk** [comment]
Should be fine now.
