### ISSUE TITLE
value of CSeq in Notify request bigger than 2^31-1

### ISSUE THREAD

**Issue by lqlucky** [signalwire/freeswitch#929]
NOTIFY sip:1007@192.168.2.32:5060;transport=UDP SIP/2.0
Via: SIP/2.0/UDP 192.168.2.41;rport;branch=z9hG4bKU4X13amj1Sa1F
Max-Forwards: 70
From: <sip:1007@ipp.may.com:5060>;tag=OFTT7Cwg4YCg
To: <sip:1007@ipp.may.com:5060>;tag=090600302d
Call-ID: 0b62caae82002a8c013c455013005d46
**_CSeq: 2554554301 NOTIFY_**
Contact: <sip:1007@192.168.2.41:5060>
User-Agent: FreeSWITCH-mod_sofia/1.5.12b~32bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Event: dialog
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Subscription-State: active;expires=3600
Content-Type: application/dialog-info+xml
Content-Length: 150

**Comment by seven1240** [comment]
from RFC 3261:

```
8.1.1.5 CSeq

   The CSeq header field serves as a way to identify and order
   transactions.  It consists of a sequence number and a method.  The
   method MUST match that of the request.  For non-REGISTER requests
   outside of a dialog, the sequence number value is arbitrary.  The
   sequence number value MUST be expressible as a 32-bit unsigned
   integer and MUST be less than 2**31.
```

**Comment by seven1240** [comment]
You should try the latest master, maybe it's already fixed.

**Comment by seven1240** [comment]
seems it's already fixed https://lists.freeswitch.org/pipermail/freeswitch-users/2014-September/107872.html

**Comment by lqlucky** [comment]
OK, thank for help
