### ISSUE TITLE
Rgarding registration issue

### ISSUE THREAD

**Issue by alaghusun60** [signalwire/freeswitch#933]
When i try to register vitelity voip provider.

I got following error"expire time in 60 by request of proxy sip: sofia_reg. C: 2458 Changing expire time in 60 by request of proxy"

**Comment by alaghusun60** [comment]
When i try to register other sip provider
i got error like
“Failed registration with status Too much hopes(403). failure 43”

**Comment by briankwest** [comment]
Please visit our mailing list, this isn't an issue with FreeSWITCH
