### ISSUE TITLE
sip_renegotiate_codec_on_reinvite

### ISSUE THREAD

**Issue by kgalinurov** [signalwire/freeswitch#937]
Hi I find sip_renegotiate_codec_on_reinvite parametr in confluents but not in code.

**Comment by nttranbao** [comment]
Seems like it is removed...
http://asterisk.voicemeup.com/viewtopic.php?t=32538&sid=48da8459d0d8f494d269af86b423ab2c

**Comment by briankwest** [comment]
No longer exists, what are you trying to solve?

**Comment by yamatoyosuke** [comment]
Hi I'm facing the issue with re-invite where 200-OK return misssing fmtp line, https://github.com/signalwire/freeswitch/issues/2254 

I'm thinking that `sip_renegotiate_codec_on_reinvite` or `renegotiate_codec_on_hold` might help to solve my issue, but these setting had been removed. 

@briankwest do you any advice?
