### ISSUE TITLE
FreeSwitch with MySQL 8+; Primary Key Error

### ISSUE THREAD

**Issue by andrewudxgen** [signalwire/freeswitch#942]
Hello, 

We are using Database(MySQL 8+) in cloud server, when we are using ODBC connector, Freeswitch supported SQL queries are not working, since there are no primary keys in the table structure. cloud database not allowing SQL queries if there are no primary key in the table.

please suggest on the same to fix the issue, and we have already ask cloud database team, they said, strictly, every table must have primary key. otherwise, cluster issue will be raised.

kindly help with the same. thanks

**Comment by andywolk** [comment]
No need to use ODBC. There is native mod_mariadb available. Re-open the issue if there is a problem with it.
