### ISSUE TITLE
freeswitch crash

### ISSUE THREAD

**Issue by glaye** [signalwire/freeswitch#948]
FreeSWITCH version: 1.6.20+git~20180123T214909Z~987c9b9a2a~64bit (git 987c9b9 2018-01-23 21:49:09Z 64bit)

backtrace.log In the attachment

[`backtrace.log](http://47.110.71.172:8089/media/backtrace.log.tar.gz)

OS
CentOS Linux release 7.6.1810 (Core) 
Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by briankwest** [comment]
Please re-test on latest releases, 1.6.20 is not the final 1.6 and has been EOL for over two years now.

**Comment by javierwilson** [comment]
> Please re-test on latest releases, 1.6.20 is not the final 1.6 and has been EOL for over two years now.

Just for my information, what is the final 1.6 if not 1.6.20?
