### ISSUE TITLE
1x1 video layout produces 1x2

### ISSUE THREAD

**Issue by David-dp-** [signalwire/freeswitch#955]
**Describe the bug**
When we configure getUserMedia to send 320x240 (using recent Chrome), and then in our FS 1.10.5 dialplan we forward that as rtmp this way...

    <action application="record_session" data="{modname=mod_av,vw=320,vh=240}rtmp://mydomain.com"/>

...an ffmpeg capture reveals the user video to be only a 160x120 inset (against the left margin and centered vertically). The rest of the frame is black. It seems like a 2-person conference layout (and we are using a conference with a virtual agent with setting 'mintwo'. Our conference profile has:

      <param name="video-mode" value="mux"/>
      <param name="video-layout-name" value="1x1"/>
      <param name="video-canvas-size" value="320x240"/>
      <param name="max-members" value="2"/>

**To Reproduce**
1. Use the example configuration above
2. Arrange to capture and record the rtmp received
2. Dial into conference using verto
3. Note the layout in the recorded rtmp
4. Change video-mode to 'transcode' following https://freeswitch.org/confluence/display/FREESWITCH/mod_conference Note that the 160x120 frame is now shown twice in the middle of the screen (vertically), still not 1x1.

**Expected behavior**
The recorded rtmp should show the verto user fullscreen.

**Package version or git hash**
 - Version 1.10.5

**Comment by David-dp-** [comment]
@seven1240 responded in the users list: "did you happen to set record_concat_video etc ? or maybe try conference record"

Yes, we already use both of those...
```
<action application="set" data="core_video_blank_image=false"/>
<action application="lua" data="${conf_dir}/dialplan/answer_then_ensure_sip_encryption.lua ${extension}"/>
<action application="set" data="record_concat_video=true"/>
<action application="set" data="jitterbuffer_msec=5p:100p"/>
<action application="set" data="RECORD_MIN_SEC=2"/>
<action application="set" data="RECORD_STEREO=true"/>
<action application="set" data="record_sample_rate=44100"/>
<action application="set" data="video_no_video_avatar_png=${conf_dir}/dialplan/YourComputerStoppedSendingUsVideo-PleaseCallBack.png"/>
<condition field="${codeForDesiredExperience}" expression="v-1" require-nested="false" break="never">
    <action application="set" data="maxSecondsToConnectToVA=3"/>
    <action application="log" data="INFO Start streaming to VA"/>
    <action application="curl" data="http://mydomain.com connect-timeout ${maxSecondsToConnectToVA} post"/>
    <action application="record_session" data="{modname=mod_av,vw=320,vh=240}rtmp://mydomain.com"/>
</condition>
<condition break="never">
    <action application="set" data="conference_auto_outcall_skip_member_beep=true"/>
    <action application="set" data="api_hangup_hook=jsrun ${conf_dir}/dialplan/cleanup.js ${idOfClientSession} ${codeForDesiredExperience} ${ipOfVA} ${ipOfRestfuldb}"/>
    <action application="set" data="session_in_hangup_hook=true"/>
    <action application="set" data="conference_auto_record=$${recordings_dir}/${mp4_filename}"/>
    <action application="conference_set_auto_outcall"
            data="['conference_member_flags=endconf,jitterbuffer_msec=5p:100p']sofia/gateway/asterisk/${my_destination}"/>
    <action application="conference" data="${my_destination}@my_conference+flags{endconf|mintwo|join-vid-floor}"/>
</condition>
```
Should we use something different?

**Comment by seven1240** [comment]
it's not a bug! I already told you on the mailing list to turn off the video concat or use conference record

**Comment by David-dp-** [comment]
Thank you for this advice @seven1240 When you asked in the mailing list whether we were using those two settings, it wasn't clear to me whether we should or should not use them.

We commented-out `<action application="set" data="record_concat_video=true"/>` and verified that our rtmp outbound stream now has the one user fullscreen.

There is no documentation about `record_concat_video` on FS confluence nor by Googling, so this issue may be a valuable reference to others.

**Comment by seven1240** [comment]
confluence is a community effort, anyone is welcome to create an account
and help to make it better.

**Comment by KamleshMedankar** [comment]
hi,
I am using linphone for video conferencing using freeswitch. when more then two members are joining only layout is visible not video is present what might be the issue below is logs of freeswitch pls let me know were i am going wrong.
https://pastebin.com/wjm69Bt8
