### ISSUE TITLE
SIP issue on  chrome 87

### ISSUE THREAD

**Issue by VietTranPG** [signalwire/freeswitch#958]
When I use chrome 87, after client join room, server emit BYE event.

Reason: Q.850;cause=27;text="DESTINATION_OUT_OF_ORDER"

**Comment by BigLoveT-ara** [comment]
I also encountered the same problem，but my problem occurred in other situations  that when I send the INVITED 

there have some error in logfile 
`2020-11-26 16:27:35.620257 [ERR] switch_rtp.c:2946 audio Handshake failure 1`

PS：my cert is generated by myself using OPENSSL not from CA

**Comment by italorossi** [comment]
It's not a bug. You'll need to upgrade your OpenSSL to support TLS 1.2, probably OpenSSL 1.0.2t or newer, after that recompile FreeSWITCH, remove the old generated dtls-srtp.pem and start again. A new one will be generated and calls will work.

**Comment by VietTranPG** [comment]
I did upgrade SSL but issue still here. :(

![image](https://user-images.githubusercontent.com/23351142/100582003-1e467680-331b-11eb-98bc-b34e51b3922f.png)


aefee982 2020-11-30 07:32:15.353816 [DEBUG] sofia.c:7291 Channel sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us entering state [ready][200]
aefee982 2020-11-30 07:32:18.593809 [ERR] switch_rtp.c:3183 audio Handshake failure 1
aefee982 2020-11-30 07:32:18.593809 [INFO] switch_rtp.c:3184 Changing audio DTLS state from HANDSHAKE to FAIL
aefee982 2020-11-30 07:32:18.613840 [NOTICE] switch_rtp.c:3165 Hangup sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us [CS_EXECUTE] [DESTINATION_OUT_OF_ORDER]
aefee982 2020-11-30 07:32:18.613840 [NOTICE] mod_conference.c:1835 Channel [sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us] has been answered
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_channel.c:3781 (sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us) Callstate Change EARLY -> ACTIVE
aefee982 2020-11-30 07:32:18.613840 [DEBUG] mod_conference.c:1835 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us skip receive message [PROGRESS_EVENT] (channel is hungup already)
2020-11-30 07:32:18.613840 [DEBUG] mod_conference.c:2963 override sound-prefix with: /not/a/real/path
aefee982 2020-11-30 07:32:18.613840 [DEBUG] conference_member.c:1719 Raw Codec Activation Success L16@48000hz 1 channel 20ms
aefee982 2020-11-30 07:32:18.613840 [DEBUG] conference_member.c:1766 Raw Codec Activation Success L16@48000hz 1 channel 20ms
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_codec.c:223 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us Push codec L16:100
2020-11-30 07:32:18.613840 [DEBUG] mod_conference.c:227 Setup timer success interval: 20  samples: 960
aefee982 2020-11-30 07:32:18.613840 [DEBUG] mod_conference.c:2380 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us skip receive message [UNBRIDGE] (channel is hungup already)
aefee982 2020-11-30 07:32:18.613840 [DEBUG] conference_loop.c:1308 Setup timer soft success interval: 20  samples: 960 from codec opus
aefee982 2020-11-30 07:32:18.613840 [INFO] conference_loop.c:1643 Channel leaving conference, cause: DESTINATION_OUT_OF_ORDER
aefee982 2020-11-30 07:32:18.613840 [DEBUG] mod_conference.c:2417 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us skip receive message [TRANSFER] (channel is hungup already)
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_media.c:11859 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us skip receive message [BITRATE_REQ] (channel is hungup already)
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_codec.c:248 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us Restore previous codec opus:116.
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_session.c:2885 sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us skip receive message [PHONE_EVENT] (channel is hungup already)
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_state_machine.c:650 (sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us) State EXECUTE going to sleep
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_state_machine.c:584 (sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us) Running State Change CS_HANGUP (Cur 1 Tot 8)
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_state_machine.c:850 (sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us) Callstate Change ACTIVE -> HANGUP
aefee982 2020-11-30 07:32:18.613840 [DEBUG] switch_core_state_machine.c:852 (sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us) State HANGUP
aefee982 2020-11-30 07:32:18.613840 [DEBUG] mod_sofia.c:449 Channel sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us hanging up, cause: DESTINATION_OUT_OF_ORDER
aefee982 2020-11-30 07:32:18.613840 [DEBUG] mod_sofia.c:502 Sending BYE to sofia/internal/PBMO0EVyngtw@staging-sip.ringr.us
send 602 bytes to wss/[14.177.161.7]:48885 at 07:32:18.618448:
   ------------------------------------------------------------------------
   BYE sip:vbs25hc8@s1olklddi6gd.invalid;transport=ws;ob SIP/2.0
   Via: SIP/2.0/WSS 54.164.201.246:6060;rport;branch=z9hG4bKvS8m0DQm8FSHc
   Max-Forwards: 70
   From: <sip:8504@staging-sip.ringr.us>;tag=XFUySZvKacNcF
   To: <sip:PBMO0EVyngtw@staging-sip.ringr.us>;tag=hlop7q356h
   Call-ID: to9i7msp3ghcdh3ag8v8
   CSeq: 28806977 BYE
   User-Agent: FreeSWITCH-mod_sofia/1.9.0-654-ed4920e~64bit
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY
   Supported: precondition, 100rel, path, replaces
   Reason: Q.850;cause=27;text="DESTINATION_OUT_OF_ORDER"
   Content-Length: 0

**Comment by SimonRain** [comment]
I'm experiencing the same response but we are using a load balancer.

Calls to the main node are working properly but then when a call is sent to different node, we are experiencing this too:

`audio Handshake failure 1`
`Changing audio DTLS state from HANDSHAKE to FAIL`

and it results into this too:

`Reason: Q.850;cause=27;text="DESTINATION_OUT_OF_ORDER"`

**Comment by italorossi** [comment]
Update FreeSWITCH, remove dtls-srtp.pem and restart FreeSWITCH, it should do the job.

**Comment by SimonRain** [comment]
That did it, we are running a load balancer and one of the server had the latest version and I was sure I checked the one that wasn't working but it turned out it was this.

Thank you

**Comment by Marin-Enjoy** [comment]
> I also encountered the same problem，but my problem occurred in other situations that when I send the INVITED
> 
> there have some error in logfile
> `2020-11-26 16:27:35.620257 [ERR] switch_rtp.c:2946 audio Handshake failure 1`
> 
> PS：my cert is generated by myself using OPENSSL not from CA

Have you solved the problem
