### ISSUE TITLE
Build error: network_io/unix/multicast.lo, 'find_if_index' is invalid in C99

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#959]
I am placing this in issues for reference from the Wiki until 1.10.6 goes GA. The build error is in GA 1.10.5, it does not occur in dev 1.10.6. Also in case someone searches for the error here. It may have been fixed in Freeswitch 1.10.6 for some other reason.

A recent clang update via macOS Command Line Tools to version 12 (may also apply to Linux with certain clang), causes the error below during build. Either use CLT V11 for 1.10.5, build 1.10.6 Dev or wait for 1.10.6 GA as a solution. 

**Build Log:**
network_io/unix/multicast.c && touch network_io/unix/multicast.lo
network_io/unix/multicast.c:168:29: error: implicit declaration of function 'find_if_index' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        mip.gsr_interface = find_if_index(iface);
                            ^
1 error generated.
make[2]: *** [network_io/unix/multicast.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [libs/apr/libapr-1.la] Error 2

**Comment by PrateekGoyal18** [comment]
Any update on this bug?

**Comment by MarioG-X** [comment]
As I stated above, this is closed and is not going to be fixed in 1.10.5 since it does not occur in 1.10.6. However, we still can't use FreeSwitch on Big Sur or Catalina due to #961 and #1003.
