### ISSUE TITLE
bad configure apr IPV6 causes mod_event_socket.c:2962 Cannot get information about IP address ::, and CLI lost

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#961]
Updated Feb 15:
This is a known error in APR and has been fixed in the homebrew version. My attempt at a freeswitch patch is below, which was not successful.

Update Jan 17: 
This is an error in APR generation starting with clang V12 which prevents a usable system and the Freeswitch CLI to not work _regardless if IPV6 is available on the system_. See more details posted later on.

Configure contains line:
**checking if APR supports IPv6... no -- no working getaddrinfo**

This causes the following two lines displayed immediately after startup:
**[ERR] mod_event_socket.c:2962 Cannot get information about IP address ::
[NOTICE] switch_loadable_module.c:125 Thread ended for mod_event_socket**

Tested on Mac Mini and iMacs containing only homebrew and FreeSWITCH using _unedited sample default conf_ files, so the problem is not unique to a machine. FS IPV4/6 phones tested fine for years, until clang V12.

Started with clang V12 in macOS 11 Big Sur and macOS 10.15 Catalina, clang V11 on Catalina and Mojave show APR IPv6 support is YES, and no startup problem. This problem was also _found on Centos Linux_ in November:
https://stackoverflow.com/questions/64437650/freeswitch-v1-10-on-centos-7-mod-event-socket-and-fs-cli-error-in-fresh-inst
Unlike them I use both IPV6 and IPV4 and the machine does have both addresses assigned.

I followed their instructions and changed the event_socket.conf as follows:
From:    param name="listen-ip" value=“::”          (Also tried  "::1" but also failed same way)
To:        param name="listen-ip" value="0.0.0.0"
And it started normally and CLI works with 0.0.0.0 but is a major security issue.

I also tried these two:
I turned off IPV6 support via the command line on Big Sur, rebooted and made sure no IPV6, then tested Freeswitch and got the same error.

I changed event_socket.conf unspecified address "::" to other unspecified formats ::/128 and 0:0:0:0:0:0:0:0, no change except those addresses showed in same message.

[06 FreeSWITCH configure.txt.zip](https://github.com/signalwire/freeswitch/files/5616877/06.FreeSWITCH.configure.txt.zip)
[07 FreeSWITCH make.txt.zip](https://github.com/signalwire/freeswitch/files/5616880/07.FreeSWITCH.make.txt.zip)
[11 FreeSwitch run.txt.zip](https://github.com/signalwire/freeswitch/files/5616954/11.FreeSwitch.run.txt.zip)

**Comment by MarioG-X** [comment]
Update 12/16/20: I checked output from lost command for both working and non-working and found both to have the same output. Number and type of IP4 and IP6 identical.

**Comment by mjerris** [comment]
mine is starting fine on latest... what is output of those commands ?  what is different on the machine that doesn't work?

**Comment by MarioG-X** [comment]
To clarify, IPV6 has tested fine with FS for years on this machine with IPV6 phones, until clang V12. It is a Mac mini 2014 strictly for testing, currently with macOS 10.14, 15.15, and 11.1. Here is the current status across the levels.
10.14 with clang 11: Good
10.15 with clang 11: Good
10.15 with clang 12: Bad
11.1 with clang 12: Bad

Freeswitch starts find except for the message above, and CLI will not work
I will send some info directly after todays fixes are incorporated into master.

**Comment by MarioG-X** [comment]
More tests to prove its clang 12:

1. Copied a Mohave that had CLT 11 to a test partition
2. Upgraded that to Big Sur and did not upgrade command line tools, verified clang 11 was still active
3. Start Freeswitch, the error did NOT occur
4. Upgraded homebrew and prerequisites and built FreeSwitch from scratch and the error did NOT occur
5. Trashed /local and rebuilt home-brew and Freeswitch from scratch, cannot proceed because homebrew checks for command line tools 12 and stops.

So if you upgrade to Big Sur but do not scrap /local you may not see the error. You must upgrade to CLT 12 and build /local from scratch.

**Comment by mjerris** [comment]
i dont have access to my desktop at the moment... my laptop is upgraded to big sur and has 12 and I'll re-test on that today...

**Comment by seven1240** [comment]
Just FYI it works fine for me

Apple clang version 12.0.0 (clang-1200.0.32.28)
I don't have v6 since my router doesn't support yet
upgraded from old versions to Big Sur
/usr/local not empty but messed up for a few years including homebrew

**Comment by MarioG-X** [comment]
As I stated above, you must build from scratch. Your /local is probably a mess. Last year, I sent 3 months working on an issue that only showed up if homebrew was built from scratch. If homebrew was updated it never showed up. Upgraded systems are ticking time bombs. When I updated the wiki, I have no idea the state of people systems which is why I test each macOS only built from scratch so people noe what to expect.

**Comment by MarioG-X** [comment]
Additional test: Since the message implies IPV6, I turned off IPV6 support via the command line on Big Sur, rebooted and made sure no IPV6, then tested Freeswitch and got the same error. I have found no way to get past this, and tested on Mac Mini and iMacs using all default conf files.

**Comment by MarioG-X** [comment]
Also tried changing event_socket.conf unspecified address "::" to other unspecified formats  ::/128 and 0:0:0:0:0:0:0:0, no change except those addresses showed in same message.

**Comment by MarioG-X** [comment]
This looks like it could be the problem, in Big Sur and Catalina the FreeSwitch configure output (see first message) contains this line:
**checking if APR supports IPv6... no -- no working getaddrinfo**
in Mojave where this is not a problem APR IPv6 support is YES. Could this be it?

**Comment by MarioG-X** [comment]
Here is the best trace of events I could determine, and my attempt at a patch. Problem is only in Big Sur and Catalina. not Mojave due to CLT differences.

During configure:
1. **freeswitch/libs/apr/configure** is failing to find TCP getaddrinfo and getnameinfo support so it **does not set APR_HAVE_IPV6**. That results in message: 
**checking if APR supports IPv6... no -- no working getaddrinfo**

2. **libs/apr/include/apr_network_io.h does not set APR_INET6** due to APR_HAVE_IPV6 net being set above. This caused build error #1003/#1030 and startup message:
**mod_event_socket.c:2962 Cannot get information about IP address ::**
even though a “Sofia status” shows IPV6 addresses fine if the machine has IPV6 on.

I tried to modify apr configure to force IPV6 on, to no avail. I modified apr_network_io.h to force APR_INET6 on but that did not eliminate the startup error. I then attempted to retrofit the patches from the homebrew apr version which was fixed for this:
apr: configure rollup patch <- Fixes are in here
Homebrew/formula-patches@80312ef

Into these three freeswitch modules:
apr_common.m4.txt
apr_network.m4.txt
configure.ac.txt

But I must be missing something else (I grepped for APR_INET6). I can’t think of anything else to try, I don’t know configure, C, Freeswitch architecture, etc.

**Comment by mjerris** [comment]
https://github.com/signalwire/freeswitch/pull/1096

**Comment by mjerris** [comment]
@MarioG-X can you try https://github.com/signalwire/freeswitch/pull/1096

**Comment by MarioG-X** [comment]
Yowza! Tested on Catalina and Big Sur and no more error message and fs_cli works! Big Thanks!

**Comment by mjerris** [comment]
pull request merged in master now

**Comment by greatitman** [comment]
when switch_rtp_set_local_address calls getaddrinfo , it blocks and doesn't return anythings.  The result of pstack is as follows:

Thread 24 (Thread 0x7f229cd7e700 (LWP 46536)):
#0  0x00007f22f225de1d in recvmsg () from /lib64/libc.so.6
#1  0x00007f22f2283c7d in make_request () from /lib64/libc.so.6
#2  0x00007f22f22841b4 in __check_pf () from /lib64/libc.so.6
#3  0x00007f22f2245ea1 in getaddrinfo () from /lib64/libc.so.6
#4  0x00007f22f5373f96 in call_resolver (sa=0x7f22747520b0, sa@entry=0x7f22601f3828, hostname=0x7f22601f37f0 "121.14.141.17", hostname@entry=0xca0c <Address 0xca0c out of bounds>, family=0, port=port@entry=51724, p=0x7f2260692b58, flags=0) at network_io/unix/sockaddr.c:337
#5  0x00007f22f5374542 in find_addresses (p=<optimized out>, flags=0, port=51724, family=<optimized out>, hostname=0xca0c <Address 0xca0c out of bounds>, sa=0x7f22601f3828) at network_io/unix/sockaddr.c:431
#6  apr_sockaddr_info_get (sa=sa@entry=0x7f22601f3828, hostname=hostname@entry=0xca0c <Address 0xca0c out of bounds>, family=family@entry=0, port=port@entry=51724, flags=flags@entry=0, p=<optimized out>) at network_io/unix/sockaddr.c:568
#7  0x00007f22f50119c8 in switch_sockaddr_info_get (sa=sa@entry=0x7f22601f3828, hostname=hostname@entry=0xca0c <Address 0xca0c out of bounds>, family=family@entry=0, port=port@entry=51724, flags=flags@entry=0, pool=<optimized out>) at src/switch_apr.c:834
#8  0x00007f22f50b9cb9 in switch_rtp_set_local_address (rtp_session=0x7f22601f37f0, host=0xca0c <Address 0xca0c out of bounds>, host@entry=0x7f22601f37f0 "121.14.141.17", port=port@entry=51724, err=0xca0c, err@entry=0x7f229cd7c578) at src/switch_rtp.c:2760
#9  0x00007f22f50bb143 in switch_rtp_new (rx_host=0x7f22601f37f0 "121.14.141.17", rx_port=<optimized out>, tx_host=0x7f2274802440 "221.123.139.199", tx_port=<optimized out>, payload=<optimized out>
