### ISSUE TITLE
Parking a channel that is already parked prevents media playback

### ISSUE THREAD

**Issue by djgroves** [signalwire/freeswitch#962]
From fs_cli, you can control a call (we do this from mod_event_socket, but the behaviour is the same from console):

with an open channel that's in CS_EXECUTE state, we run 
uuid_park <channel> 

the channel moves to CS_PARK state - (this is fine, you can use play to start media playback)

but if you issue another uuid_park whilst it's in the CS_PARK state, then...

At this point, uuid_broadcast or uuid_park return "+OK" on the console (or on the event socket), but has no effect, and in particular, the state of the channel does not change.

This is on freeswitch version 1.10.1

**Comment by djgroves** [comment]
I should add - we're using park_after_bridge channel variable, so we don't necessarily know whether the channel is already parked when sending a park command, and there's no way (AFAIK) to work out whether a call may be parking, other than to track whether the channel it's bridged to has been hung up, which has a possible race condition.

Any assistance or pointers you could provide would be gratefully received. When you park the channel, you get the slightly enigmatic log message "state PARK going to sleep"

**Comment by djgroves** [comment]
No update on this for 2 years. Closing.

**Comment by RobinTsai** [comment]
Any solution?
Found this problem at Version 1.10.7.
