### ISSUE TITLE
CRASH during RE-Activating video Secure RTP

### ISSUE THREAD

**Issue by spacetourist** [signalwire/freeswitch#964]
FreeSWITCH terminates execution and immediately restarted during secure RTP processing, specifically the last message produced is "RE-Activating video Secure RTP". This is not linked to the specific server instance we have seen this on several different installations.

We have not been able to reproduce this scenario at present. The appearance of the log message does not always correlate to a crash however the application has crashed on a number of separate times with this as the last produced message. 

Version: FreeSWITCH (Version 1.10.5 git 1cbd277 2020-09-09 12:25:45Z 64bit) is ready
OS: Debian Buster 4.19.98-1

The installed version was built from PR #825

**Trace logs**

https://pastebin.freeswitch.org/view/9d3f98e1 - moment of crash
https://pastebin.freeswitch.org/view/6d67942c - related channels

**backtrace from core file**

https://pastebin.freeswitch.org/view/adf44d2e

Please let me know if additional details are require, many thanks.

**Comment by dragos-oancea** [comment]
when it crashes does it always happen when calling srtp_protect_rtcp_mki()  ? is the rtp muxed with rtcp for that call scenario (like for webrtc) ? do you ever see this log line: 
'switch_log_printf(SWITCH_CHANNEL_SESSION_LOG(rtp_session->session), SWITCH_LOG_INFO, "Activating %s Secure %s SEND%s\n", rtp_type(rtp_session), idx ? "RTCP" : "RTP", rtp_session>flags[SWITCH_RTP_FLAG_SECURE_SEND_MKI] ? "      (with MKI)" : ""); ' ? with idx == 1 will print "RTCP".

**Comment by spacetourist** [comment]
Plenty of log entries that look similar - are these a match?

https://gist.github.com/spacetourist/838a79a1e6107317338c5133f9842486

**Comment by dragos-oancea** [comment]
do they have the same SDP as the one you shown ? (I've seen meanwhile it's not muxed) . I'm trying to figure out if it's a race condition or it happens everytime with a certain client/Chrome version.

**Comment by spacetourist** [comment]
I've retrieved some other SDP examples at the following link:

https://pastebin.freeswitch.org/view/5ebacca1

All calls pass through a SIP proxy and RTP passes through RTPEngine on its way to FreeSWITCH. The platform applies the same mux flags for each request and are demuxed for delivery. 

Client applications are relatively consistent as a WebRTC softphone based on SIP.js

Please let me know if I can explain further, many thanks for taking a look.

**Comment by spacetourist** [comment]
Just seen another one on a separate server - logs below:

CORE:
https://pastebin.freeswitch.org/view/c5388870

CHANNELS:
https://pastebin.freeswitch.org/view/7d9d2bd0

Appears to represent the same issue

**Comment by spacetourist** [comment]
@dragos-oancea you mentioned that our streams are demuxed - do you believe there are stability concerns related to this approach? Is it that the reassembly/sequencing is somehow more complex in this configuration? 

I could definitely look into changing this configuration if it would make a difference but at this time I simply don't understand the issue - is srtp_protect_rtcp_mki doing something significant?

**Comment by dragos-oancea** [comment]
srtp_protect_rtcp_mki() is run on every rtcp packet -it's doing the SRTP encryption. as for the mux thing not sure it's related with the bug yet - I just believe it's a more common setup for webrtc and it may be a safer code path with the mux. as for the gdb trace it would be more useful with symbols present so we could do "frame 2" and then "info locals" so we'd see what we pass to openssl lib when it crashes. my guess is context is null. 
you could also build FS with ASAN and try to reproduce on a test machine. installing openssl lib with debug symbols would be useful too. 
this is not the kind of bug to be fixed with gdb & logs and glance in the code.  
you need to compare the logs for when it crashes with the ones where it does not crash - see what's different.

**Comment by spacetourist** [comment]
Thank you for the response, I'm not sure reproducing the issue will be possible without more understanding of the cause - these systems are processing hundreds of thousands of calls without issue so running a similar workload on test equipment wouldn't be straightforward. I also lack experience in this kind of low level debugging so I'm not sure I'll be able to progress without first being able to reproduce the crash.

Perhaps the best contribution I can make at this time will be to analyse the calls to see if I can establish a pattern of client/browser versions or presence of certain SDP attributes. This may lead me towards a better understanding of the failure scenario so we can consider setting up a test server with symbols included as suggested. 

From a practical perspective I'd add that we are seeing applications crashes very irregularly and on different servers which handle different users traffic - users hit the same box every time. As such if there was a user who had a "deadly" client/browser combination I would expect to see the same box falling over and regularly as they attempt to use the service.

If I mange to find anything out I'll come back here, thanks again for your time.

**Comment by andywolk** [comment]
Do you have freeswitch debugging symbols installed? @spacetourist 
Please do then repeate gdb stuff.

**Comment by spacetourist** [comment]
I've just seen another instance of the crash and have got symbols installed. Please see the following trace and let me know if it contains all that is required? Notify @andywolk 

https://pastebin.freeswitch.org/view/ab1cb2b4

I can likely export the previous crashes with symbols now if that would be useful?

**Comment by spacetourist** [comment]
Here is the previous trace with symbols:

https://pastebin.freeswitch.org/view/e6b77a2e

Thanks for taking a look

**Comment by spacetourist** [comment]
Hi All,

We're seen another crash - please find the trace below.

https://pastebin.freeswitch.org/view/4abf5f60

Thanks

**Comment by spacetourist** [comment]
Hi All,

We are continuing to run into issues with RTP re-activation crashing our servers. The link below shows a recent call example that crashed the server, in case there is anything useful in there:

https://gist.githubusercontent.com/spacetourist/ccfe23ef6f6e86ed717dbed64c4d5bf4/raw/a83859e7facfa585bcd840cfcdc68ad9bc9287b4/freeswitch.log

Thanks

**Comment by dragos-oancea** [comment]
can you try this fix ? https://github.com/signalwire/freeswitch/pull/1211

**Comment by dragos-oancea** [comment]
are you using mod_conference in your call scenarios ?

**Comment by dragos-oancea** [comment]
it could be a race condition that happens with bridge too. the thread that negotiated the DTLS is not the one that receives RTP and send back RTCP.

**Comment by giggsey** [comment]
Hi, taking over from @spacetourist whilst he's away.

We've finally upgraded a few production servers based on 1.10.5 with our #825 and your #1211 merge requests as the only additions (we kept with the same base to rule out another commit fixing the issue).

We've had two crashes on a single server since the upgrade, details below.

Crash 1:

[Core dump](https://pastebin.freeswitch.org/view/19f84bff) - [Log](https://gist.github.com/giggsey/66b79aab1941abf0baddb976ed7a5a89) -  I don't think this is related to this issue, but there was the log message from #1211 just before the crash.

Crash 2:

[Core dump](https://pastebin.freeswitch.org/view/3affa983) - [Log](https://gist.github.com/giggsey/03178408ea7d8067fbaccf58840c2577)

The warning message from #1211 has appeared twice in our logs since we deployed on Thursday. Once for Crash 1, and once again later that evening (no crash)

**Comment by andywolk** [comment]
@spacetourist Please see if that helps: https://github.com/signalwire/freeswitch/pull/1283

**Comment by andywolk** [comment]
@giggsey

**Comment by giggsey** [comment]
@andywolk Thanks, should #1283 replace #1211?

We haven't had any more crashes since I last commented, and the log message from #1211 has appeared at least daily.

**Comment by andywolk** [comment]
@giggsey yes, do not apply 1211, just use 1283.

**Comment by andywolk** [comment]
@giggsey Please let me know how #1283 went for you

**Comment by andywolk** [comment]
@giggsey Any updates?

**Comment by giggsey** [comment]
@andywolk Sorry, was on leave for a few days last week.

We'll build it and start rolling it out/testing this week.

**Comment by giggsey** [comment]
@andywolk We updated our fleet last week, and will monitor for any crashes.

As @spacetourist mentioned previously, these crashes were happening once every few weeks, so we won't know for a while whether it has had a positive impact.

**Comment by spacetourist** [comment]
I am pleased to report that this has indeed resolved the issue on our network.

Thank you for all your help here @andywolk - very much appreciated!
