### ISSUE TITLE
failed compilation on Fedora 33 64bits

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/freeswitch#978]
**Describe the bug**
sh bootstrap.sh
make results
  CXX      src/switch_cpp.lo
  CXXLD    libfreeswitch.la

*** Warning: Linking the shared library libfreeswitch.la against the
*** static library libs/libvpx/libvpx.a is not portable!
Making all in .
make[2]: Entering directory '/home/src/freeswitch'
  CC       src/freeswitch-switch.o
  CCLD     freeswitch
/usr/bin/ld: ./.libs/libfreeswitch.so: undefined reference to `sys_siglist'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1971: freeswitch] Error 1
make[2]: Leaving directory '/home/src/freeswitch'
make[1]: *** [Makefile:3677: all-recursive] Error 1
make[1]: Leaving directory '/home/src/freeswitch'
make: *** [Makefile:1429: all] Error 
**Expected behavior**

**Package version or git hash**
last git master of 12/09/2020

Thanks

**Comment by ROBERT-MCDOWELL** [comment]
glibc version
glibc-2.32-2.fc33.x86_64

**Comment by daniel-lucio** [comment]
sys_siglist is given by libc*.so, since this is compilation time make sure libc.so exists, you may be missing an RPM that provides it.

**Comment by ROBERT-MCDOWELL** [comment]
libc.so is part of glibc which is one of the necessary library to run linux right?
Fedora 33 has glibc-2.32, and libc.so is in /usr/lib64, maybe to new for FS?

**Comment by ROBERT-MCDOWELL** [comment]
mmhmmm it seems that git pull messed up some files. I cloned it again and compiled fine now. so I close this issue.
