### ISSUE TITLE
Sofia status profile lack WSS-BIND-URL

### ISSUE THREAD

**Issue by ontur00** [signalwire/freeswitch#986]
Debian 10

console write
fs_cli -x 'sofia status profile internal' | grep WSS-BIND-URL
no output

so I go

fs_cli
sofia status profile internal-ipv6 (but why only available is internat-ipv6?)

Question is how open wss and internal-ipv4?

Before working
![image](https://user-images.githubusercontent.com/11216422/102200282-efa4d000-3ec4-11eb-80ed-f71e3440d0b1.png)

**Comment by mjerris** [comment]
feel free to create a pull request to correct this
