### ISSUE TITLE
libpq is installed but make gets: You must install libpq-dev to build mod_pgsql.

### ISSUE THREAD

**Issue by MarioG-X** [signalwire/freeswitch#987]
This is new on Big Sur preventing build of 1.10.6. (1.10.5 does not get that far). home-brew has libpq installed as in previous macOS's. The /usr/local sublibraries contains libpq in opt, bin, lib, share as in previous macOS so nothing looks missing.

However, configure shows something different, although both older and big sur configs show:
checking for PostgreSQL libraries via pkg_config... -L/usr/local/opt/libpq/lib    with no errors, then next line is different:

**Big Sur:** checking for PQgetvalue in -lpq... no
**older systems:** checking for PQgetvalue in -lpq... yes

I have seen old posts with people not finding libpq during build but don't look related. This could be a required change to Freeswitch, or, something else. I have not found anything on the web about this. I have attached config and make files.
[06 FreeSWITCH configure.txt](https://github.com/signalwire/freeswitch/files/5697515/06.FreeSWITCH.configure.txt)
[07 FreeSWITCH make.txt](https://github.com/signalwire/freeswitch/files/5697519/07.FreeSWITCH.make.txt)

**Comment by mjerris** [comment]
sounds like the location homebrew puts the libs has changed.  does homeberw have any info when it installs lib?  i have some overrides that add special locations to look that need to be added to

**Comment by mjerris** [comment]
==> libpq
libpq is keg-only, which means it was not symlinked into /usr/local,
because conflicts with postgres formula.

If you need to have libpq first in your PATH run:
  echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.profile

For compilers to find libpq you may need to set:
  export LDFLAGS="-L/usr/local/opt/libpq/lib"
  export CPPFLAGS="-I/usr/local/opt/libpq/include"

For pkg-config to find libpq you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libpq/lib/pkgconfig"

**Comment by MarioG-X** [comment]
I tried all three and exact same results. I also tried all at same time, nogo.

**Comment by mjerris** [comment]
ok this is interesting

Michaels-MacBook-Pro:freeswitch mike$  gcc -o conftest -g -O2   conftest.c -lpq
ld: library not found for -lpq
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Michaels-MacBook-Pro:freeswitch mike$  gcc -o conftest -g -O2   conftest.c  -L/usr/local/opt/libpq/lib -lpq


it's not including the dir in the test check...   looking

**Comment by mjerris** [comment]
https://github.com/signalwire/freeswitch/pull/988

**Comment by MarioG-X** [comment]
Update: I don't know how to tell when dev will be updated so I manually added your changes. It builds to completion now. The only strange things:
Make install did not fully populate conf but I will wait for the dev update to see it it was. fluke.
Freeswitch came up but it still has the issue [https://github.com/signalwire/freeswitch/issues/961]
