### ISSUE TITLE
500 Overlapped Requests on fast Hold/Retrieve

### ISSUE THREAD

**Issue by mahald** [signalwire/freeswitch#999]
![image](https://user-images.githubusercontent.com/6714894/102213693-66e35f80-3ed7-11eb-8ea3-75c0cc11d113.png)

We have a Problem that FreeSwitch sends out a "500 Overlapping Requests" tearing down the call because a second re-INVITE is received before the ACK from the final response of the first re-INVITE Operation is received. 

See the Blue-marked Message on the Screenshot; this is the ACK for the "200 OK SDP" 3 Lines above it. 
If this message arrived two milliseconds earlier (and thus would go two messages up), all would be fine.

Looking at the RFC: https://tools.ietf.org/html/rfc3261#section-14.2
Section 14.2:

```
   A UAS that receives a second INVITE before it sends the final
   response to a first INVITE with a lower CSeq sequence number on the
   the same dialog MUST return a 500 (Server Internal Error) response to the
   second INVITE and MUST include a Retry-After header field with a
   randomly chosen value of between 0 and 10 seconds.
```

It comes down to whether "before it sends the final response" is interpreted as "but not necessarily received the ACK" or not.
And whether we implicitly understand this as that it should be accepted if the condition does not match.

This seems to be the same issues like this one, but there is no ACK logging responsible for it:
https://lists.freeswitch.org/pipermail/freeswitch-users/2014-June/106111.html

Explanation of Call and Screenshot: FreeSwitch is on the right. The Scenario is an inbound call: answer, play, and then a bridge with "bypass_medai_after_bridge=true". Orange is the B-Leg. At 24.510000 a re-Invite (hold) is initiated from the remote Party on the B-Leg. The Problem also occurs if "bypass_media_after_bridge" is disabled.

**Expected behavior**
FreeSwitch should already accept a new re-INVITE as soon as it has sent the final response to a previous re-INVITE, rather than only after it received the ACK to the final response. Then remember that there will be an ACK for it and ignore this ACK.

**Package version or git hash**
 Version 1.10.5 from Packages

As this happens in roughly 3% of the Calls to specific Numbers and seems to be a behavior of the user's equipment, under certain conditions is executing a very fast hold/retrive, we currently cannot reliably reproduce it. We are working on a solution to test it with the Customer, or we will try to set up a SIPP to test it.

**Comment by badcrc** [comment]
Hi @mahald did a newer version of FreeSwitch fixed this? I'm having the same overlapping request problem on some calls.

**Comment by aybhalala** [comment]
Hi @mahald , Was this resolved? If yes, which release / version? Does it require any extra configuration?

**Comment by peiffer1** [comment]
Hi I have the same problem,
We have linked with an SIP operator that send an initial INVITE to freeswitch, 
freeswitch send a 100 trying and a 200OK
The operator send a re INVITE . (before the ACK)
And freeswitch answer by a 500 Overlapping Request.
The operator send the ACK correspondign to the initial INVITE after the re INVITE.

Is it a correct behaviour from freeswitch, in this case I have to discuss with our SIP operator, or is it a issue in freeswitch?
Regards,
Eric Peiffer

<img width="944" alt="Capture d'écran 2024-02-12 144233" src="https://github.com/signalwire/freeswitch/assets/23041477/0570d433-10f9-4689-9510-ff8b189a38e5">
